### ISSUE TITLE
Error while importing WSDL: Cannot find protocol in those namespaces

### ISSUE THREAD

**Issue by fxlepoutre** [a85/POSTMan-Chrome-Extension#10067]
Hello,

I was thrilled to see in release notes 8.4.0 and 8.6.0 that Postman has now a way to import WSDL specifications and convert it to a sample request. This is the only feature that would let me uninstall completely SoapUI and use Postman instead.

However, I have trouble uploading the WSDL specifications given by my SOAP provider.
I always get the error message “Error while importing WSDL: Cannot find protocol in those namespaces”
![image](https://user-images.githubusercontent.com/9206717/123149697-d0818f00-d461-11eb-9c79-684d8734005d.png)

Those WSDL files actually load correctly into SOAPui, too bad they don’t on Postman:
[SAP WSDL Manage Purchase Orders](https://pastebin.com/zNVjTrBK)
[SAP WSDL Manage Sales Orders](https://pastebin.com/TChWA8SF)
[SAP WSDL Manage Bank Advices](https://pastebin.com/TXhZ735d)

Thanks for the help !
 FX

**Comment by VShingala** [comment]
@fxlepoutre We have investigated the files mentioned by you and We are working on a fix for these issues. They should be fixed with upcoming releases (latest with v8.9.0).

**Comment by VShingala** [comment]
@fxlepoutre We have fixed this issue in the latest version of the Postman App and you should be able to import all files successfully. Feel free to re-open this if you have any issues.

**Comment by fxlepoutre** [comment]
> @fxlepoutre We have fixed this issue in the latest version of the Postman App and you should be able to import all files successfully. Feel free to re-open this if you have any issues.

Hi!
Tested successfully, thanks!

**Comment by plasmagoat** [comment]
Hi
I'm running postman v. 8.10.0 and still get this error with my Microsoft dynamics WSDL files.
These also load fine into SOAPUI. 

I am unfortunately not allowed to share the files.

The file has this target namespace: 
`targetNamespace="urn:microsoft-dynamics-schemas/page/casysclientcredparties"`

**Comment by VShingala** [comment]
@ElDuderino420 Can you give a small example, if you can replicate it which fails during importing. It would really help in debugging the issue further.

**Comment by plasmagoat** [comment]
@VShingala here, hope this helps :) 
[test.wsdl.txt](https://github.com/postmanlabs/postman-app-support/files/6952801/test.wsdl.txt)

**Comment by VShingala** [comment]
@ElDuderino420 Thanks, shared file really helped in determining issue is present. We'll reopen this issue and update this thread with future updates.

**Comment by massimoforni-turboden** [comment]
Hello,

I have the same issue with SAP SuccessFactors WSDL: https://api12preview.sapsf.eu/sfapi/v1/soap?wsdl

**Comment by ethcservaes** [comment]
Hello, 

I have the same issue with the following WSDL
- From Sage => CAdx.txt
[CAdx.txt](https://github.com/postmanlabs/postman-app-support/files/7204404/CAdx.txt)
- VIES Eu Vat vérification : https://ec.europa.eu/taxation_customs/vies/checkVatTestService.wsdl

Thanks in advance if you can resolve theses issues !

**Comment by VShingala** [comment]
@massimoforni-turboden  @ethcservaes Thanks for reporting the issue. We are working on the fix and will share future updates soon.

**Comment by akshaydeo** [comment]
@ElDuderino420 @massimoforni-turboden @ethcservaes @VShingala seems to have fixed the issue in the corresponding importer. So you should be able to use this in the latest Postman app.

Closing this issue for now, but feel free to re-open it if this fix is not working as intended for you 🙂
