### ISSUE TITLE
Import SOAP wsdl missing authentication header

### ISSUE THREAD

**Issue by vromaniello** [a85/POSTMan-Chrome-Extension#10466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Importing a file does not insert the soap header authentication ut only soad envelope and body.

The body should contain also the soap header about authentication or not?
If yes the correct body should be the following:

```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Header>
        <Authentication xmlns="http://betflag.it/">
            <Username>XXX</Username>
            <Password>XXX</Password>
        </Authentication>
    </soap:Header>
    <soap:Body>
        ...
    </soap:Body>
</soap:Envelope>
```

If not how can I set the header authentication easily for all my soap imported call?

### Steps To Reproduce

1. Import wsdl with authentication tag header
2. Check imported SOAP call and his xml body
3. Missing <soap:Header> in xml body

```
<soap:Header>
        <Authentication xmlns="http://betflag.it/">
            <Username>XXX</Username>
            <Password>XXX</Password>
        </Authentication>
</soap:Header>
```

### Environment Information

```markdown
- Operating System: all
- Platform Type: all
- Postman Version: 9.2.0
```

**Comment by aman-v-singh** [comment]
It is not reproducible, The issue was potentially fixed with newer versions.

**Comment by jhermsen** [comment]
The issue still exists.
I created a simple WSDL file: [AppWSDL.txt](https://github.com/user-attachments/files/17644532/AppWSDL.txt)
![image](https://github.com/user-attachments/assets/78ee6b06-eb5a-4307-b5b6-9b6ef43c0711)
As you can see there is a soap:header mentioned, but the resulting collection method does not contain this.
![image](https://github.com/user-attachments/assets/71efca08-c1b5-41e2-a8c0-ed684a34375e)

If I try using the tool SoapUI I get this XML based on WSDL:
```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:app="http://localhost/App.asmx">
   <soapenv:Header>
      <app:AuthHeader CultureName="?">
         <!--Optional:-->
         <app:UserName>?</app:UserName>
         <!--Optional:-->
         <app:Password>?</app:Password>
      </app:AuthHeader>
   </soapenv:Header>
   <soapenv:Body>
      <app:ChangePassword>
         <!--Optional:-->
         <app:userName>?</app:userName>
         <!--Optional:-->
         <app:password>?</app:password>
         <!--Optional:-->
         <app:oldPassword>?</app:oldPassword>
      </app:ChangePassword>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by jhermsen** [comment]
> It is not reproducible, The issue was potentially fixed with newer versions.

Can you reopen the issue as it still exists?
