### ISSUE TITLE
Apple M1 Chip builds are not working - Dropdown Menus, buttons, sidebars are not actionable

### ISSUE THREAD

**Issue by idevchandra** [a85/POSTMan-Chrome-Extension#10460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Most of the sidebar items, dropdown menus, API Request items in Collections, are not actionable.

### Steps To Reproduce

1. Download M1 (arm64) app, v9.1.5 from Postman website or https://dl.pstmn.io/download/version/9.1.5/osx_arm64
2. Extract `.app` from downloaded `.zip` file.
3. Move it to /Applications
4. Open the Postman app. 
5. Perform the actions explained in the image link provided in the `Screenshots or Videos` section.

### Screenshots or Videos

Screenshot with explanation is here -> https://imgur.com/a/w6nvB16

### Environment Information

```markdown
- Operating System: macOS Monterey 12.0.1 (21A559)
- Platform Type: Apple M1 (arm64), M1 Pro and M1 Max
- Postman Version: 9.1.5
```

**Comment by twitharshil** [comment]
@idevchandra Thanks for reporting the issue !! 
Could you share the application logs with us at `help@postman.com` by following the steps mentioned in https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs
This will help us triage the issue further. Do mention the GitHub issue number in the subject

**Comment by idevchandra** [comment]
Sent email to `help@postman.com`

**Comment by idevchandra** [comment]
Sent Loom recording to Postman support team.

**Comment by twitharshil** [comment]
@idevchandra Thanks for sharing the logs & screen recording with the team. We are suspecting that there is something wrong happening with the application builds on the newer apple hardware machines (M1 pro & M1 max). 
Would like to collect some more information that can help us understand the issue better 
1.  Could you try downloading the [Intel builds](https://dl.pstmn.io/download/latest/osx_64) for the postman application & give it a try? What happens when you try to launch the postman application & do the exact same steps? Does the issue still persist? 
2. Electron is the underlying platform framework for the Postman application, we are suspecting if something is wrong with the electron itself on this newer hardware, do you face the same problem with other electron-based applications as well like Signal, Skype, WhatsApp, Slack, VS Code, etc? 
3. We are actively working on upgrading our platform layer, could you try out this [custom build](https://drive.google.com/drive/folders/1_ILnBmA4tdJVq0Z6JYpqCmsBeMGabVZP?usp=sharing) of the PostmanCanary application and share thoughts on whether the issue still persists or not?

**Comment by idevchandra** [comment]
Because of Electron, Node and postman are not working, I returned my M1 device. Can't collect the logs. :/

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jviotti** [comment]
@idevchandra So no arm64 Electron.js app worked for you? Node.js didn't run either?

**Comment by idevchandra** [comment]
Electron.js apps like VS Code, Insomnia, WhatsApp, Figma, Teams worked.

Microsoft Teams, Postman were not working.

Node.js was working. But I had issues with other brew modules. Also, nvm was erroring out.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Baril27** [comment]
I had the same issue with 9.2.0 on an Apple M1 Pro but is working now on 9.3.0.

**Comment by kpuscas** [comment]
Still having the issue with the latest 9.3.1. I'm not having any issues with Slack or VS Code so not sure if it is an underlying Electron issue. I setup this 14" M1max from a 16" Intel Time Machine back up if that tells you anything helpful.

---- 

Ok just tried that PostmanCanary build and it seems to be working as expected

**Comment by ccheatham** [comment]
Ok just tried that PostmanCanary build and it seems to be working as expected

**Comment by jviotti** [comment]
I'm closing this ticket as we believe it is fixed in the latest Postman versions. Please re-open if this is not the case!

**Comment by kevinbull** [comment]
I am still seeing this issue, just downloaded the Apple Silicon version this morning
![image](https://user-images.githubusercontent.com/6344178/150141435-1c5c67b9-0a4b-475e-be23-3f9d9949c6d2.png)

**Comment by kpuscas** [comment]
Same here. Just tried again and same issue

**Comment by jviotti** [comment]
Thanks for confirming! Re-opening the ticket so we can keep looking at this. @kpuscas Are you also running on an M1 Max?

**Comment by kpuscas** [comment]
Yes I'm running a 14in MBP with the M1Max. Note that Postman Canary that I
have works just fine

[image: image.png]

**Comment by ccheatham** [comment]
Same issue: https://d.pr/i/Pq9tjU <https://d.pr/i/Pq9tjU>

**Comment by MihaiSprinceana** [comment]
Same issue on my side as well, but if I logout with the option to delete the local data and login again, then it's working. It could be that the migration using the intel arch local data to arm arch it's not working.

**Comment by twitharshil** [comment]
Hey @kpuscas, @ccheatham, @MihaiSprinceana 
Could you try Postman v9.9.x and let us know whether the issue is fixed or not? We have done some improvements which should address this particular issue. Let me know, how it goes! You can move your existing application to Postman v9.9.x+ via in app-update or directly download it from the [website](https://www.postman.com/downloads/)

<img width="781" alt="Screenshot 2022-01-20 at 6 54 17 PM" src="https://user-images.githubusercontent.com/25850676/150347198-fdd1ee86-96f1-46e4-8fb5-af44c9c90060.png">

**Comment by ccheatham** [comment]
I’m already using 9.9.3.  No dice.

**Comment by kpuscas** [comment]
Same here. On 9.9.3

[image: image.png]

**Comment by mitchhf** [comment]
Seems like I have a similar issue.  I added another bug here: 
https://github.com/postmanlabs/postman-app-support/issues/10966
since it's not identical.

**Comment by jviotti** [comment]
@mitchhf Do you get the same issue with other Electron-based applications like VS Code, Skype, WhatsApp, etc?

**Comment by zzaacchh** [comment]
I was having the same issue on a new M2, on Postman v9.25.2.  Every collection I attempted to access would refuse to open, with no apparent error or console log messages.

I signed out, then signed by in, and everything works now.

**Comment by kmayura1** [comment]
yes re signing in the app, opens workspace tabs.

**Comment by v1r4m** [comment]
I had the very same issue on Postman `v11.16.1`, M1 Macbook Pro 14 with `Sonoma 14.6.1` even in 2024,
which solved beautifully with @zzaacchh 's solution.

**Comment by MC-sanderv** [comment]
Retested on Apple Silicon (M1) with current Postman (v11.70.5): unable to reproduce the UI unresponsiveness.
Also cleared Application Support data, used Intel chip build followed by Apple chip build, still not reproducible. 

Based on earlier reports that “logout + delete local data” resolves the issue, the probable cause was corrupted/legacy local data from older v9 arm64 builds.
Since current versions start cleanly and the problem no longer reproduces, I’m closing this as resolved/obsolete.


 If anyone can reproduce on the latest build, please open a new ticket with version, macOS build, and logs.
