### ISSUE TITLE
Cookies from browser doesn't sync anymore?

### ISSUE THREAD

**Issue by shinebayar-g** [a85/POSTMan-Chrome-Extension#10550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

**Postman Interceptor** extension allows us to sync browser cookies to Postman app right? This was working fine some time ago.
Recently I upgraded my OS to Windows 11 and installed fresh Postman app. Right now browser cookies are not synced to Postman app, even though interceptor status is green and says connected. However cookies are captured only after **Start Capturing Via Interceptor**. Previously Cookies were syncing automatically without this step.

Is this new update behaviour or a legitimate bug?

### Steps To Reproduce

1. Open Postman
2. Open Chrome
3. Install **Postman Interceptor** extension
4. Wait for extension goes green status and connected.
5. Go to Cookies tab of the extension and enable Capture cookies.
6. Add domains to the Add domains input.
7. Go to Postman, select Cookies menu on any of the request window.
8. _Cookies are not there..._

### Environment Information

```markdown
- Operating System: Windows 11
- Platform Type: Native App win32 10.0.22000
- Postman Version: 9.8.2
```

### Additional Context?

Aight it doesn't even work after Start Capture.

**Comment by soltykszymon** [comment]
Same issue, 9.7.1 was fine
upgrade to 9.8 - not syncing

**Comment by Nxys** [comment]
same issue

**Comment by abhijitkane** [comment]
@shinebayar-g @soltykszymon @Nxys We're working on this, and will update this thread once the fix is out.

**Comment by near1024** [comment]
+1

**Comment by shashankawasthi88** [comment]
Hi @shinebayar-g @soltykszymon @Nxys @near1024 we have fixed the issue in version 9.8.3. You can sync the cookies from the browser to Postman by going to 'Capture requests and cookies' (bottom right corner) > Interceptor > Sync cookies. Let us know if this satisfies your usecase.

https://user-images.githubusercontent.com/71059054/148943571-f1a36def-6e45-41dc-b81f-37ae02e570a5.mov

**Comment by SebastianJust** [comment]
I've recently updated postman to the newest version, and now I got the exact same issue. 

I've tried capturing the cookies throughout the "capture request" method, but it still doesn't work. 

Anybody got the same issue?

**Comment by postman-staff** [comment]
Hi SebastianJust,

As you are unable to use Interceptor after recently updating your Postman Desktop App to the newest version, please check if all the dependencies are installed properly.

If the options above didn’t help, follow the steps below to remove all the Interceptor dependencies and retry the installation.

- Open Postman and head to **View** > **Developer** > **Show DevTools (Current View)**
- Enter _pm.interceptorInstaller.reset()_ to remove all present Interceptor dependencies.
- Restart Postman and Chrome and try out the installation steps again.

If you're still experiencing issues after trying the options above, our engineering team have requested that you submit a support request with the following information so that we can investigate further:


- Provide the Interceptor bridge logs, which are located in the following location:
  - macOS: $HOME/.postman/InterceptorBridge
  - Linux: $HOME/.postman/InterceptorBridge
  - Windows: %USERPROFILE%/.postman/InterceptorBridge

- Attach a screenshot showing the interceptor connection status

- Confirm your Desktop App version (**Gear icon** > **Settings** > **About**) and the Interceptor version.

- Share your OS and version details.

- Generate a HAR file:
https://support.postman.com/hc/en-us/articles/360038234154-Exporting-HAR-files-  (Make sure the recording consists of you attempting to use the interceptor this is so that the HAR file generated provides some insight on this issue)

- Provide a screen recording of what you are experiencing when you try to capture cookies.  We find loom.com helpful for this.


via @loutsiros | Postman Support

**Comment by postman-staff** [comment]
Hi SebastianJust,

I have also included a related knowledge link below for your reference to help troubleshoot this issue

I’m having trouble with the Interceptor
https://support.postman.com/hc/en-us/articles/360025849993-I-m-having-trouble-with-the-Interceptor-

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by SebastianJust** [comment]
Hi,
Thank you. I'll try the things out and return, if I still have the issue.

**Comment by SebastianJust** [comment]
Hi, 
It still doesn't work :( 

I've uploaded a zip file with the provided information.

[postman_troubleshooting.zip](https://github.com/postmanlabs/postman-app-support/files/9969112/postman_troubleshooting.zip)

**Comment by SebastianJust** [comment]
Hi, 
I fully remove postman from HREG, removed all files from postman (https://community.postman.com/t/how-to-completely-remove-postman-and-data/4115). Then I removed the interceptor.
Finally I reinstalled postman and the interceptor.

And it seems to work now :) 


**How to remove postman**:
Delete folders:
C:\Users\<user>\AppData\Local\Postman and
C:\Users\<user>\AppData\Roaming\Postman

**Comment by matthew8sweeney** [comment]
> Hi, I fully remove postman from HREG, removed all files from postman ([community.postman.com/t/how-to-completely-remove-postman-and-data/4115](https://community.postman.com/t/how-to-completely-remove-postman-and-data/4115)). Then I removed the interceptor. Finally I reinstalled postman and the interceptor.
> 
> And it seems to work now :)
> 
> **How to remove postman**: Delete folders: C:\Users<user>\AppData\Local\Postman and C:\Users<user>\AppData\Roaming\Postman

I've been having the same problem for a little while in Postman v11.35.2, and this fixed it for me too.
