### ISSUE TITLE
Websocket connection error from desktop app

### ISSUE THREAD

**Issue by idan** [a85/POSTMan-Chrome-Extension#10660]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Sync will not successfully connect.
No amount of signing out and signing back in repairs it.
I'm seeing some mobx errors so this might be some state management bug.
There are similar issues but users there report findings in their developer logs (I don't see any suspicious log lines) or they fix it by signing out and back in (which hasn't worked for me)

Looking at the web inspector, there's clearly something going on. See screenshot.

### Steps To Reproduce

1. Open Postman
2. Be authed
3. See one of my workspaces
4. Try to open it
5. See the red cloud icon
6. Click "retry connection" and it seems to do nothing.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/22723/153809690-51f71c2f-1e6a-4e43-884e-159b63738128.png)

![image](https://user-images.githubusercontent.com/22723/153808941-77365372-45f1-4812-9ba6-d73d97708374.png)

![image](https://user-images.githubusercontent.com/22723/153808898-11e0fb49-b103-4f25-8ec5-d33f304356b0.png)

### Environment Information

```markdown
- Operating System: Windows 11
- Platform Type: Desktop app
- Postman Version: 9.13.1
```

### Additional Context?

- Manually added postman.exe to firewall allowlist
- Disabled "Use system proxy" setting per https://github.com/postmanlabs/postman-app-support/issues/9481

**Comment by numaanashraf** [comment]
@idan We had a [system outage earlier today](https://status.postman.com/incidents/bm5gvvvp5y12) that might have caused this. The issue has been resolved. Could you confirm whether everything is working at your end?

**Comment by idan** [comment]
@numaanashraf still broken, behavior unchanged. I tried signing out and signing back in again. Still getting the same console errors when I try to reestablish the connection.

**Comment by numaanashraf** [comment]
Thanks @idan. Are you using Postman within any networks with proxies or gateways that might block Postman's connection to our servers?

**Comment by idan** [comment]
No, I'm using it from a home network with a router that I control. It does
not have any unusual rules, and other apps (including ones I develop) which
communicate using websockets don't seem to be impacted. I do have a VPN
configured for work, but it is turned off when using Postman.

**Comment by inihility** [comment]
I'm also having this issue since yesterday. Home network.

v9.13.2

edit: reinstalling it doesn't make the error go away.

added console logs
![postman_error_log](https://user-images.githubusercontent.com/1271331/154061356-744afcaa-142a-48e4-9c3e-4b2d558e8f41.png)

Also seeing this:
Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID

**Comment by y-reddy** [comment]
Facing same issue. Errors in the console are similar to what @inihility had put here.
v9.13.2 - Mac OS

**Comment by inihility** [comment]
> Facing same issue. Errors in the console are similar to what @inihility had put here. v9.13.2 - Mac OS

I tested on my Mac as well and experience the same problem. Any updates on this issue? I can use the web version of Postman just fine but can't ping my local environment which is where I develop in.

**Comment by numaanashraf** [comment]
@inihility @y-reddy Could you send the app logs to help@postman.com? Steps to collect logs are detailed [here](https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs).

**Comment by inihility** [comment]
> @inihility @y-reddy Could you send the app logs to [help@postman.com](mailto:help@postman.com)? Steps to collect logs are detailed [here](https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs).

edit: sent log files to [help@postman.com](mailto:help@postman.com)

**Comment by crafton** [comment]
I'm having the same issue; Windows 11, Postman v9.14.6. Tried uninstalling and re-installing, signing out and back in again; made no difference.

**Comment by y-reddy** [comment]
Apparently i have turned off sync on old version of postman. Now there is no option toggle sync. Which is why my postman was not syncing.
[help@postman.com](mailto:help@postman.com) took a minute to fix it post consent.

**Comment by crafton** [comment]
@y-reddy thanks for the tip. I've sent my logs to help@postman.com, hopefully they can resolve.

**Comment by crafton** [comment]
Looks like the sync issue was my issue as well. Postman support has resolved it.

**Comment by inihility** [comment]
For anyone else experiencing this issue, I've sent my logs to support and they told me they are still investigating it.
