### ISSUE TITLE
Can't import a .proto file if a message's field is called `constructor`

### ISSUE THREAD

**Issue by darko-da** [a85/POSTMan-Chrome-Extension#11102]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When importing a `.proto` file in which there is a message definition containing a field with the name `constructor`, the import fails with the error message 

> duplicate name 'constructor' in Type ...

This issue also persists if I instead create a Protobuf API definition within postman instead of importing a `.proto` message. I am able to create the Protobuf API, but when I try to select it when putting together a gRPC Request, the same error as above appears.

### Steps To Reproduce

1. Import a .proto file
2. Select a .proto file with a message definition that has `constructor` as a field name. See here a minimal example (also attached)
```
syntax = "proto3";

package import_test;

message Foo {
    string bar = 1;
    string constructor = 2;
}
```
3. Click Next
4. You will receive an error message saying 
> `duplicate name 'constructor' in Type Foo`.

If you comment out the definition of the constructor field, everything works as expected.

[import_test.zip](https://github.com/postmanlabs/postman-app-support/files/9147228/import_test.zip)

### Operating System

Windows

### Postman Version

9.25.1

### Postman Platform

Postman App

**Comment by codenirvana** [comment]
@darko-da Thanks for reporting this bug.

We've pushed a fix for this in v9.29. Can you please update your app and confirm if that fixes your issue?

**Comment by darko-da** [comment]
@codenirvana Thank you very much for this fix.
I confirm that I now can import the `.proto` files and call the API.

However, when I try to use Server Reflection, I still get the same error, i.e., `duplicate name 'constructor' in Type ...`.

Do you want me to add a new bug report for this?

**Comment by codenirvana** [comment]
Thanks for the confirmation, @darko-da!

Yes, I am aware of this issue in Server Reflection.
We've identified the root cause in our proto parsing package and trying to push our changes to the upstream to fix for all the dependent packages (including the one used for server reflection).

Can you please file a new bug report for this?
We are updating our Server Reflection implementation soon; we'll address this during that.

**Comment by darko-da** [comment]
@codenirvana 
Thanks for the info. Ok, I'll file a new bug report.
