### ISSUE TITLE
Close Button disappears when window width < 1080px

### ISSUE THREAD

**Issue by PaulFarry** [a85/POSTMan-Chrome-Extension#11113]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When the window width is reduced (screen resize, docking etc), then the close button disappears if the width becomes less than 1080px. 

Certain items like Invite, Search Postman start to disappear under certain sizes, but the close button really should be available all the time.

### Steps To Reproduce

1. Open postman
2. Resize the window using the right hand side resize OS window resizer
3. When you get to around 1080px width, the close button disappears

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/81415/180627821-dc6395bc-8c36-4601-b734-6806900fd7c3.png)

### Operating System

Windows

### Postman Version

9.25.1

### Postman Platform

Postman App

**Comment by diptarag** [comment]
@PaulFarry 
Can you please confirm if the close button is accessible when you scroll?

**Comment by PaulFarry** [comment]
No only when you resize the window. I've cropped the image vertically as there is only scrollbars on the right, but the close box isn't part of the scrolling.

**Comment by VaishnaviChallaPostman** [comment]
@PaulFarry  Closing this as this issue is being tracked here: https://github.com/postmanlabs/postman-app-support/issues/11104 
Please subscribe to that GH thread to avoid missing any updates.
Thanks!

**Comment by diptarag** [comment]
@PaulFarry 
Just to confirm the issue - when the close button is clipped, there's no horizontal scroll in the window?

Also, can you please reset the zoom level and check?
![ResetZoom](https://user-images.githubusercontent.com/2277198/180719712-e496a723-6fee-4035-89d4-9508be77eefd.png)

**Comment by EnsignPayton** [comment]
Window when docked to one side of the screen at 1920x1080:

![image](https://user-images.githubusercontent.com/18620874/180823082-c1a05a11-e7d0-4d05-b30c-b6044cee9378.png)

The min/max/close buttons are entirely clipped. There is a (very small and hard to miss) horizontal scrollbar at the bottom that can be used to bring them back into view, but this should not be necessary

**Comment by PaulFarry** [comment]
ok, now that it's been pointed out, yes, there is a scroll bar at the bottom of the screen. but I've never seen that before going through this, I would never have seen it without @EnsignPayton comment above. You don't look for scrollbars to display standard UI widgets. 

If the Cog, Bell, Manage Account and Upgrade buttons were to disappear before making standard UI widgets disappear that would be a lot easier to navigate

**Comment by diptarag** [comment]
Thank you for the feedback. We are tracking this internally and should be fixed in a future version. We will post an update as soon as it's fixed.

**Comment by Blurazzle** [comment]
What is the status? I have this issue still on version 9.31.0.

Not every developer has a super large display. I encounter this issue when splitting the screen, e.g. on the left half of the screen postman on the other half of the screen a browser window.

**Comment by EnsignPayton** [comment]
Still a problem on 10.0.8. Still very annoying. I can "fix" it by zooming out then increasing the font size, but considering this is literally the only application I use that has this problem, I'm pretty disappointed. Rider, Visual Studio, VS Code, Teams, Discord, and Spotify all draw their own window borders, and none of them have this problem.

**Comment by Archimedyz** [comment]
Just noticed this issue today. Still happening on Windows, Postman v10.5.2.

**Comment by adrydale** [comment]
This is still an issue today, Postman v10.12.0.

**Comment by diptarag** [comment]
The issue should be fixed in v10.14

**Comment by PaulFarry** [comment]
![image](https://github.com/postmanlabs/postman-app-support/assets/81415/c86708b8-80d8-428e-ac3d-74ec435db0d5)

It would seem that you can now make the window smaller, but the close button still disappears once you get below certain thresholds. (<760px)

If the same process of shrinking a window is performed in a windows explorer window, then ALL other widgets disappear leaving room for min, max and Close

**Comment by adrydale** [comment]
I agree, this issue still exists. Running v10.14.2 and the close/max/min buttons still disappear around 745px.

**Comment by PaulFarry** [comment]
@diptarag Does a new issue need to be raised or can this one be reopened?

**Comment by diptarag** [comment]
Reopening the issue

Sharing our future plans on this track -
As part of the continuous improvements, we are making sure the window controls won't be disappeared till 640px. This improvement will be shipped as part of v10.15.

We have done some extensive UX research to come up with the minimum value - 640px. We believe good UX is ensured till that width. But most of Postman's features are not best utilized below the threshold. In a future iteration, we will enforce a rule to prevent resizing the Postman window below 640px

**Comment by MC-sanderv** [comment]
Closing this issue due to being stale.
This was originally reported on an older Postman version around window size and the close/min/max buttons disappearing

Since then there have been updates to how window controls are handled at small widths ( minimum width protections)but this specific report hasnt had recent activity

If you are still able to reproduce this on the latest Postman build please reopen the issue with updated details and steps to reproduce
