### ISSUE TITLE
Query Params Value Field Truncates Without Indication

### ISSUE THREAD

**Issue by atkinsmedley** [a85/POSTMan-Chrome-Extension#11314]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using the desktop application interface, I have noticed that long query parameter values are truncated (starting at the 68th character) and there is no indication that they are truncated, like an ellipsis or anything. If they happen to truncate at the end of a logical word, you may not be aware that more values are affecting your HTTP request. 

What's more, there is still room in that field of the UI for the value to be displayed instead of being truncated. The user must click on the field to see the full value (annoying) despite there being room. 

### Steps To Reproduce

1. Open a new request tab
2. Select the Params tab
3. Add a parameter key
4. Start typing a long parameter value at least 68 characters long.
5. Click away from the Value field
6. Notice that all characters after the 67th character are not displayed, even though they are present in the field, and even if the field has more white space to show characters.

### Screenshots or Videos

The first screenshot shows the unused white space circled in orange that could be occupied by the truncated value.
![Screenshot 2022-09-30 092042](https://user-images.githubusercontent.com/89545870/193303771-e6d32210-7dbd-4d1d-b96e-4f5c3e751007.png)

The second screenshot shows the truncated part of the value squared off in red.
![Screenshot 2022-09-30 092013](https://user-images.githubusercontent.com/89545870/193303826-bed7ce3a-2ada-4945-ae15-809ac186d65f.png)

### Operating System

Windows

### Postman Version

9.31.0

### Postman Platform

Postman App

**Comment by DominicSaladin** [comment]
Please fix this, it is really annoying 😅

**Comment by lawschlosser** [comment]
Wow, makes postman somewhat unusable as a daily tool (I keep forgetting that the displayed values are not correct!).

One thing I discovered while attempting to document this issue is that I could "correct" the bug if I made the width of the Postman application/window half the width of my screen size (or smaller).  If I did this, the trailing ellipsis **...** would consistently display properly (so that I would know that the value was truncated).  

In my case, I adjusted the width of the application window to about 1280 pixels (since my display is 2560 pixels).  

### Half width (1280 pixels)
![image](https://user-images.githubusercontent.com/10409070/230497018-f6a0bc08-d77d-45f9-bda7-6ebb5e284522.png)
The value is truncated to `45-`, but DOES display a trailing ellipsis, yay!
&nbsp;&nbsp; ![image](https://user-images.githubusercontent.com/10409070/230497278-0b7d8bf7-db45-4553-a17f-78895fa62c17.png)

### Full width (**2560** pixels)
When the window is expanded beyond 1280 pixels, the ellipsis was not displayed.
![image](https://user-images.githubusercontent.com/10409070/230495753-c030bc29-b0e8-42af-98ae-d0bfd950cac4.png)
The value is truncated to `55-`, but no trailing ellipsis :disappointed: 
&nbsp;&nbsp;![image](https://user-images.githubusercontent.com/10409070/230496287-72c9c62d-3688-4d20-b0d5-791cd91dac67.png)

### Other Notes ###
- Expanding the width of the **value** column (thereby reducing the width of the neighboring **Key** and **Description** columns) appears to have no bearing/impact on the behavior.
- What makes this a notably naughty/frustrating bug is that I imagine many users encounter it when they *want* to see *more* of the query parameter (because the value is so long). So they expand the window and column widths to provide plenty of real estate. Little do they know that all of that nice open space may or may not be populated with their values.  yikes!

### Version/Platform 
`$ uname --kernel-name --kernel-release --kernel-version --operating-system --hardware-platform`
```
Linux 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 GNU/Linux
```
`$ snap list`
```
Name               Version                     Rev    Tracking       Publisher     Notes
bare               1.0                         5      latest/stable  canonical✓    base
core               16-2.58.3                   14946  latest/stable  canonical✓    core
core18             20230320                    2721   latest/stable  canonical✓    base
gnome-3-28-1804    3.28.0-19-g98f9e67.98f9e67  194    latest/stable  canonical✓    -
gtk-common-themes  0.1-81-g442e511             1535   latest/stable  canonical✓    -
postman            10.12.0                     199    v10/stable     postman-inc✓  -
```
`$ cat /etc/os-release`
```
NAME="Linux Mint"
VERSION="20.3 (Una)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.3"
VERSION_ID="20.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=una
UBUNTU_CODENAME=focal
```

**Comment by DominicSaladin** [comment]
6 Months and no answer from Postman... I like that

**Comment by giridharvc7** [comment]
We've now fixed this with v10.13. Please give this a try and let us know what you think.

**Comment by atkinsmedley** [comment]
I just updated to v10.13 and tried it, and it's still an issue.

Before clicking in the field:
![image](https://user-images.githubusercontent.com/89545870/232973401-9b039cf8-e1a4-41d4-a33f-b818de13387a.png)

After clicking in the field:
![image](https://user-images.githubusercontent.com/89545870/232973590-f8e64878-b9ce-4436-9840-44afafd3d2e1.png)

The same screen region is highlighted in each screenshot, showing the text that was hidden and then revealed after click. No ellipsis.

My screen ratio is 2560 x 1440.

Please take another look.

**Comment by lawschlosser** [comment]
@giridharvc7  Thanks for looking into this.  Unfortunately, I'm still seeing the issue ( v10.14.7 via snap)

**Comment by atkinsmedley** [comment]
@giridharvc7 Why is this issue still marked closed? As of the most recent release, this is still an issue. Please fix. It's a rather frustrating bug.

**Comment by giridharvc7** [comment]
Reopening this, we will look into this and get back

**Comment by atkinsmedley** [comment]
Thanks! It's much appreciated!

**Comment by sandeep-singh-pstmn** [comment]
It's happening only after a particular screen resolution for a quick fix

- You can zoom in until you see the truncation of the string
- Reduce the width of the value column until you see the truncation of the string

will raise a proper fix for this soon , we are tracking this on high priority
