### ISSUE TITLE
Loosing Collections

### ISSUE THREAD

**Issue by KotieSmit** [a85/POSTMan-Chrome-Extension#1143]
Version 3.0.0.5 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

Earlier I have noticed that some of my collections disappeared. (Sync was turned on)
In this case entire collections and some requests inside some folders disappeared.

Today (with sync disabled), all but one collection (the only one that was expanded) out of about 20 disappeared.  
Luckily I had an export to recover from.

Unfortunately I can not reproduce it.

**Comment by johnnavarra** [comment]
This happens to me as well.
https://github.com/a85/POSTMan-Chrome-Extension/issues/1131

**Comment by abhijitkane** [comment]
@KotieSmit After you disabled sync, did the collections disappear after you restarted the app?

**Comment by johnnavarra** [comment]
Nope. I've had sync disabled so I haven't lost data

**Comment by johnnavarra** [comment]
well... it seems sync was re-enabled... but not by my choice. I had 66 requests in my collections. after sync it removed 16 of them.

sigh. This is very frustrating. I've disabled sync again and created a data dump.

**Comment by johnnavarra** [comment]
sigh. it overwrote all my environment settings. this is extremely frustrating.

**Comment by bjwyse** [comment]
I am randomly losing requests from my collections also.
Seems to be most recently added requests may disappear after closing and re-opening Postman.

**Comment by abhijitkane** [comment]
@bjwyse 
Can you send us an email at help@getpostman.com

**Comment by anroots** [comment]
This concerns me, too. 

Chrome 43 / Postman 3.0.1 / Ubuntu Linux 14.10

I use Postman in two computers, with Sync on. This morning, I lost my carefully configured API folder for no apparent reason.

I do not know exactly what steps cause this, I'll just turn sync off and make some hard-copy export backups of my collection.

**Comment by abhijitkane** [comment]
@anroots Can you send us an email at help@getpostman.com with your Postman username?

**Comment by anroots** [comment]
Logging out and back in again (as suggested by @abhijitkane) helped - my collections were correctly synced.

**Comment by sobtiankit** [comment]
Just an addition, we also have a "force sync" option, that should resolve any issues without the need to log out and back in. You can find it in Settings > Sync > Force Sync

**Comment by halhenke** [comment]
I've had saved queries revert my changes minutes after i've saved them - i dont really trust Sync at the moment & so its disabled.

**Comment by j-ledoux** [comment]
Same here, I've lost twice all the requests that were stored in folders. I guess there are a couple of issues with collections / folder sync. 
I did force resync of my collections this morning, it duplicates all my requests outside of their folders. I'm normally having 47 requests in this collection, requests count does work properly either because if I copy the collections with its duplicates, count of the copy version is 90... Date of the copy is also weird, we're not at 1st january 1:00 am...
<img width="312" alt="screen shot 2015-08-20 at 10 45 21" src="https://cloud.githubusercontent.com/assets/2115259/9379462/b317647e-4729-11e5-8a72-8cbb7734a3e5.png">
I think, I'm going to deactivate sync as well, since I've lost a lot of time to reorganizing, reodering all my requests twice, I keep local backups anyway.

**Comment by KotieSmit** [comment]
My team has since started using the Team licence, but is now quite useless since no progress is made on this issue.

Today I've lost post data for my  POST calls.  After restoring from a exported file, it lost all my headers for all my api calls setup in postman.

The final nail in the coffin was when I logged back in and all my work was duplicated.

Get your act together.  I paid for my licence, and so has my team/company.

Looking other alternatives for the meantime.

**Comment by a85** [comment]
@KotieSmit Sorry about this. This is an old issue that's been fixed in previous versions. 

Duplication seems to be as you re-imported data back which will have different identifiers. 

We can help you out at help@getpostman.com.

**Comment by KotieSmit** [comment]
Hi Thank you for fast response.

I realise that duplication could be because of that,  but we still have the issue of loosing post data.
I have since lost headers as well.  I'm trying to restore from different backup exports I have.

**Comment by a85** [comment]
@KotieSmit If you were on Sync, we'll help you restore it. @sobtiankit Can you follow up?

**Comment by sobtiankit** [comment]
@KotieSmit if you can email help@getpostman.com from your registered email id.. we will help you recover your data

**Comment by KotieSmit** [comment]
Email send.

Thank you

**Comment by KotieSmit** [comment]
@sobtiankit 
Email send.

Thank you
