### ISSUE TITLE
gRPC server reflection error - no such type

### ISSUE THREAD

**Issue by nomad-software** [a85/POSTMan-Chrome-Extension#11625]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm trying to use server reflection but it always errors saying that it can't find a type.

It seems like a regression of this; https://github.com/postmanlabs/postman-app-support/issues/10815

Rolling back to postman  10.1.2   185  v10/stable fixes the issue, so it looks like a definite regression.

### Steps To Reproduce

* Create a new gRPC request
* Point to a server supporting reflection
* Trying using server reflection

### Operating System

Ubuntu

### Postman Version

postman  10.7.0   186  v10/stable

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by appurva21** [comment]
@nomad-software Thanks for writing in! 

I am not able to reproduce this issue. Can you share a scaled-down version of your Protobuf that we can use?

**Comment by nomad-software** [comment]
Hi, unfortunately the protobuf files are closed source. Do you know where the logs are located?

**Comment by appurva21** [comment]
@nomad-software You can find the logs using [this](https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app).

To help us investigate it further:
1. Can you share the screenshot/video recording of the error that you are facing?
2. Do you still get the error if you [import](https://learning.postman.com/docs/sending-requests/grpc/using-service-definition/#importing-a-proto-file) the Protobuf instead of using server reflection?

**Comment by nomad-software** [comment]
![image](https://user-images.githubusercontent.com/1413497/213675376-8fd8d84e-a020-4bc9-b4c3-bfeb1e485908.png)

**Comment by nomad-software** [comment]
I don't get an error if I import the proto files instead of using reflection.

**Comment by aguydane** [comment]
We also started suffering this issue when we upgraded to the latest Postman version
<img width="1484" alt="Screen Shot 2023-01-20 at 10 37 47" src="https://user-images.githubusercontent.com/72758450/213782381-092be2ce-331a-4d25-a0d7-44781ca4569a.png">

**Comment by codenirvana** [comment]
@dane-skipper, Can you share the scaled-down proto files that we can use to reproduce this issue?

**Comment by codenirvana** [comment]
@dane-skipper @nomad-software This could be because of our recent performance improvements in server reflection.
I went through the changes, and based on the error details (shared above), I tried a few proto files, which could result in this, but I cannot reproduce this issue locally.

Can you share the scaled-down proto files or how the given type is used/nested will help to fast-track the fix.

**Comment by marcustut** [comment]
![image](https://user-images.githubusercontent.com/59773847/214840320-a13579ed-8866-4124-baaf-2146b386777b.png)

Started to have this issue as well, which on previous version it works without problems.

**Comment by krugi** [comment]
Experiencing this as well. Works perfectly fine with `grpcurl`
<img width="504" alt="Screenshot 2023-01-31 at 23 38 25" src="https://user-images.githubusercontent.com/15140079/215889526-4915670c-7d88-4525-b9a2-b87e0cc24c9e.png">

**Comment by chadxzs** [comment]
also having this issue. A colleague that uses Postman v9 says he does not experience this issue accessing the same API w/ reflection.

**Comment by codenirvana** [comment]
@chadxzs @krugi @marcustut, Can you share the scaled-down proto files that we can use to reproduce this issue?

**Comment by chadxzs** [comment]
@codenirvana I submitted a support ticket regarding this, but scaling ours down is a ton of work as this is a large service.

**Comment by aoudiamoncef** [comment]
Hello, 

I having this issue, please see https://github.com/hyperium/tonic/issues/1299

**Comment by aoudiamoncef** [comment]
Hi @codenirvana 

It was tricky to reproduce, the issue begun from having 3 rpc methods...

More detail in this project https://github.com/aoudiamoncef/postman_issue_11625

**Comment by codenirvana** [comment]
@aoudiamoncef 🙌🏻

I can reproduce this issue locally. Thanks for the help!

**Comment by codenirvana** [comment]
It took a while, but this is finally fixed in the latest version of the Postman app (v10.12).

@aoudiamoncef @chadxzs, thanks again for helping us reproduce the issue and identifying the root cause!

**Comment by swiftace** [comment]
Still broken, I'm running v10.12.4 and I get this, @codenirvana

<img width="495" alt="Screenshot 2023-03-21 at 11 20 00" src="https://user-images.githubusercontent.com/195566/226591458-7e6988cd-aad7-4453-b4cd-5fc58488dc8e.png">

**Comment by codenirvana** [comment]
@swiftace from the error message, it looks like server reflection is not enabled/implemented by the server.
Can you confirm?

**Comment by swiftace** [comment]
You are right, thanks :-)

**Comment by bu4ak** [comment]
Same issue
postman v 10.15.0

![image](https://github.com/postmanlabs/postman-app-support/assets/17143820/9567f52d-9c23-4282-9f70-17ee1b80a6ad)


But if I use a proto file import, everything works correctly. Codogeneration also works correctly.
