### ISSUE TITLE
Collection runner Error when json variable is null

### ISSUE THREAD

**Issue by astinnos** [a85/POSTMan-Chrome-Extension#1167]
When i set a property of the body json being used with a POST request using a JSON data file to null, the test runner hangs.

**Body**

``` javascript
{
    "testfield": "{{testfield}}"   
}
```

The first case works but the runner then freezes when the case with the null field is meet.

**Json Data File**

``` javascript
{
        "test_id": 1,
        "test": "InValid Request- Empty Field Test",
        "testfield": "",
        "status_code": 400,
        "error_code": "abc1231",
        "error_message": "Test field is null or empty"
    },
{
        "test_id": 2,
        "test": "InValid Request- Null FieldTest",
        "testfield": null,
        "status_code": 400,
        "error_code": "abc1232",
        "error_message": "Test field is null or empty"
    }
```

Setting the field to null using the editor works fine

``` javascript
{
    "testfield": null   
}
```

**Comment by abhijitkane** [comment]
Thanks for reporting this. We'll fix this in the next release.

**Comment by abhijitkane** [comment]
@ksmithmonex Can you confirm this fixed in v3.0.4?

**Comment by astinnos** [comment]
The runner no longer hangs, however it is still not behaving as expected when using null values. The  property being set to null is set with a string value of "null"

```
"testfield": null
```

becomes

```
"testfield": "null"
```

**Comment by abhijitkane** [comment]
All values in the data files are stringified when they're replaced in the request.
If you don't want a value to be replaced, you'll have to remove it from the data file.

Note that `data.key` will be `null`, not `"null"` in the pre-request and test script sandbox.

**Comment by astinnos** [comment]
Removing the value from the test file does not work either. The property is set to the string value of the placeholder.

In the previous example the "testfield" property value becomes "{{testfield}}"  if i leave the property out of the json object in my test file

**Comment by abhijitkane** [comment]
@ksmithmonex In the latest version of the app, `testfield` will be a blank string if it's specified as null in the CSV/JSON file.

**Comment by duyanhnp** [comment]
Hi @abhijitkane,

I'm still getting this error. I specified a variable as null in CSV file but this variable is returned as variable name with its curly braces.

![image](https://cloud.githubusercontent.com/assets/10646367/23605276/8f6c40e0-028e-11e7-9bc8-73ad27ae4f53.png)

![image](https://cloud.githubusercontent.com/assets/10646367/23605329/d23eb7fe-028e-11e7-991a-b31ad298ad6f.png)

**Comment by punchdrunkdetective** [comment]
This is an old post, but I think Im seeing this same issue in version 5.5.0. If I put nothing in the csv file for a var, I get the stringified var name. If I put null in the csv file, I get "null" for the var. 

My postman script has some like this in it's post body:
"var": "{{var}}"
