### ISSUE TITLE
Cannot see 'running dot' in flows

### ISSUE THREAD

**Issue by JakubTomczynski** [a85/POSTMan-Chrome-Extension#12021]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Cannot see the 'running dot' which indicate the place that the flow is in.

### Steps To Reproduce

1.Go into the flow tab
2.Create a flow with send requests
3.Run flow

### Screenshots or Videos

![Postman flows](https://github.com/postmanlabs/postman-app-support/assets/123468855/4f832cf2-d965-4a9e-8c3e-3f36b03cdaa7)

### Operating System

Windows

### Postman Version

10.14.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by shamasis** [comment]
This is odd. @chrisjpatty can you check?

**Comment by chrisjpatty** [comment]
@JakubTomczynski Thanks for reporting! I'm able to reproduce the issue on my end as well, will have a fix shortly.

**Comment by chrisjpatty** [comment]
<img width="574" alt="Screenshot 2023-06-22 at 3 51 00 PM" src="https://github.com/postmanlabs/postman-app-support/assets/14916515/cc2d67b5-ebba-4a6f-a9d6-16d0b432b8b2">

Thanks again for the report, this should be fixed now. If you're using Postman on the web just refresh your browser tab, or update your desktop app.

**Comment by JakubTomczynski** [comment]
@chrisjpatty Hello, seems like the issuee still occurs on my end. I have updated version to : v10.15.4. 2 gifs below, one my own collection and one fork 
![MY own](https://github.com/postmanlabs/postman-app-support/assets/123468855/8e2c5101-c62b-4aca-91eb-5304a3fe5291)
![Fork](https://github.com/postmanlabs/postman-app-support/assets/123468855/36c88cb4-8606-46d0-b702-acfe37748f13)

**Comment by chrisjpatty** [comment]
@JakubTomczynski Thanks for the follow-up, just so I'm clear, is the issue in the second gif that the success check isn't displaying on the For block, or something else? On the first gif I'm not seeing the issue so I'm guessing there's something I'm misunderstanding about what you're reporting.
