### ISSUE TITLE
Performance testing - POST request with file in form-data sent incorrectly 

### ISSUE THREAD

**Issue by furiousdog** [a85/POSTMan-Chrome-Extension#12059]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello! I am very happy that Postman got instrument for performance testing and want to say thank you all for that! I hope it gets better and more powerful and becomes the industry standard.

But now I have a problem with the next request:
```
curl --location 'https://***/style/upload/64772475f280c96543493a40' \
--header 'accept: */*' \
--header 'Authorization: Bearer ***' \
--header 'Cookie: JSESSIONID=70091AFE073C7CD54BCEFF4226B9CC21' \
--form 'file=@"pseudoimage.jpg"'
```
When I send it via Functional runner it works well. When I try to sent the same request via Performance runner I get an error from my server `Content type '' not supported`.

Unfortunately, the requests from the Performance runner don't appear in the Postman console, so I can't figure out what the difference is between them.

I tried to sniff traffic via tcpdump on my server and got different results.
**Successful request:**
```
POST /style/upload/64772475f280c96543493a40 HTTP/1.1
Host: ***
X-Real-IP: ***
X-Forwarded-For: ***
X-Forwarded-Proto: https
Content-Length: 224
accept: */*
Authorization: Bearer ***
User-Agent: PostmanRuntime/7.32.2
Postman-Token: 8c08fbce-f088-4c22-ab48-615f59e72f1b
Accept-Encoding: gzip, deflate, br
Content-Type: multipart/form-data; boundary=--------------------------669828117041241416719545
Cookie: JSESSIONID=4686C09CFAABE9E86A2231C5C9CA2BEB
----------------------------669828117041241416719545
Content-Disposition: form-data; name="file"; filename="pseudoimage.jpg"
Content-Type: image/jpeg
pseudoimage
----------------------------669828117041241416719545--
```

**Unsuccessful request:**
```
.b..S...POST /style/upload/64774d891595e66fddaa84a4 HTTP/1.1
Host: ***
X-Real-IP: ***
X-Forwarded-For: ***
X-Forwarded-Proto: https
Content-Length: 0
accept: */*
Authorization: Bearer ***
User-Agent: PostmanRuntime/7.32.2
Cache-Control: no-cache
Postman-Token: a541c53d-31ac-4b3d-b1a2-57b41794516c
Accept-Encoding: gzip, deflate, br
Cookie: JSESSIONID=730AF396A79B0BDE57020DEF1751E4A2
```

As you can see, the unsuccessful one has no Content-Type and Boundary block.

### Steps To Reproduce

1. Create a POST request with file in form-data.
2. Save it to collection.
3. Run saved request via Performance runner.

### Operating System

macOS

### Postman Version

Version 10.13.8-canary01

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by malvikach** [comment]
@furiousdog Thanks for reporting this! We will look into this and update you about the same.

**Comment by shreyas-panduranga** [comment]
This issue should be fixed in the latest version of the canary and in the latest released mainline app.

@malvikach This has been verified on the production app.

**Comment by ssskhan** [comment]
Hi. When will it be resolved ? Still getting this issue, I am using the latest version.

**Comment by postfrzero** [comment]
@ssskhan This issue has been addressed for a while. Could you open a new ticket with additional details so we can better understand what's going wrong?

**Comment by ssskhan** [comment]
@postfrzero  Just to clarify, the issue and approach to reproduce is exactly the same.

1) add a post request with an image file in form data
2) do performance testing on it and it won't send the image file with the request, but works fine in functional test. 

Do you still want me to open a new issue ?
