### ISSUE TITLE
GraphQL Variables Commenting

### ISSUE THREAD

**Issue by matt2102** [a85/POSTMan-Chrome-Extension#12097]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When writing GraphQL queries and mutation, if you have commented out variables the lists will be incorrectly parsed.

### Steps To Reproduce

Make a GraphQL request with a list parameter e.g. $listIds: [String!], create a variables for that in the variables section.  Make another variables and comment that out.

so the final request would resemble something like: 

{
    // "commentId": "123456"
    "listIds": [],
}

### Operating System

Windows

### Postman Version

Version 10.14.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by timhall** [comment]
Hi! Thanks for raising this issue, it has been resolved and will be included in the next release

**Comment by timhall** [comment]
This has been implemented in the September Postman release, thanks again for raising this issue

**Comment by sgarg7** [comment]
I believe this is still broken in Postman or did not work. If I comment a line in graphql variables in a POST request where body is of type GraphQL, postman sends the variables with the commented line
