### ISSUE TITLE
Collection becomes readonly in the Find & Replace and can't be changed

### ISSUE THREAD

**Issue by foman** [a85/POSTMan-Chrome-Extension#12144]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

As you can see in the find replace, the collection becomes readonly, it can not be modified.

### Steps To Reproduce

1. I create a new collection and add a test request, 
2. in Find & Replace, find the some text and try to replace it
Result: It can not replace it, the collection is readonly.

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/505913/aece6128-66dd-466b-bfd7-4de3ebd78f04)

### Operating System

macos

### Postman Version

10.15.4

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by giridharvc7** [comment]
@foman thank you for reporting. We will keep you posted once a fix for this is raised.

**Comment by dev-sharma-08** [comment]
@foman,
As I can see on the screenshot you provided, you are able to click on the checkbox, and the `Replace in 1 selected` button is enabled. If you click on that button, the text should be get replaced with `myUrl`, regardless of that lock icon showing in find and replace tab.
Let us know if the functionality if working for you. Meanwhile we are fixing the lock icon bug.

**Comment by kaa-intive** [comment]
It's not only about the icon. After pressing Select all and [Replace in selected] loader appears, but nothing is replaced. There is no error or message shown.

**Comment by kaa-intive** [comment]
I've noticed this issue 2 weeks ago using v10.15.1, MacOS 13.2.1 
Updated Postman to 10.15.5 and it still there.

**Comment by foman** [comment]
No, After clicking replace, nothing was changed...

**Comment by kcatvu** [comment]
Fixed in July 2023 (v10.16)
![image](https://github.com/postmanlabs/postman-app-support/assets/144733778/96f98bda-e134-4f55-af06-485ae296b36b)

**Comment by apoorvgupta03** [comment]
Hey all, we are closing this ticket for now as we've pushed a change for this since (v10.16), please feel free to open this if issue still persists

**Comment by Spoondogg** [comment]
Still seeing this on v10.24.15 on Windows.  I don't see the `lock` icon, but any attempts to replace strings in a url don't take effect.

**Comment by RexpecT** [comment]
I had to search everywhere, after that I could successfully replaced the content in the Scripts section.
Narrowing down the search to one collection, then replace the content did not work.
My collections are not readonly or locked.

Version: 11.7.0
OS platform: win32 10.0.22621

**Comment by hasher4ever** [comment]
Issue persists. 

**Find and replace not working.**

Steps to reproduce:

1. Open Find and replace
2. Input search text into FIND text box
3. Click Find button
4. Fill in REPLACE WITH text box with new text
5. Check Select all checkbox
6. Click Replace in X selected
7. (Wait for loader)
8. Click Find button again

**AR: No replacements have been made
ER: All found text should be replaced**

_Environment:_
Postman for Windows
Version 11.19.0
UI version 11.19.0-ui-241023-0433
Architecture x64
OS platform win32 10.0.22631

**Comment by upatidar7** [comment]
+1 still now working on version  v11.23.3 macOs

**Comment by arabczuk-allegro** [comment]
+1 still not working on MacOS
Postman Version 11.33.5 UI Version: 11.33.5-ui-250220-2335 Desktop Platform Version: 11.33.4 (11.33.4)

**Comment by saheli80** [comment]
Still not working for me . After pressing Replace in selected, loader appears, but nothing is replaced. There is no error either.

Postman version:v11.34.4 
windows 10 enterprise

**Comment by joostholslag** [comment]
still not working for me either. I do noticed that the issue presents for collections that are forked from another teams postman collection and for collections backed up to github. But not for a new collection that's not a fork or backed up to GitHub.
workspace with all three collection types: https://www.postman.com/joostholslagteam/workspace/openehr-rest-workspace

**Comment by dcdraper** [comment]
This is still not working with version 11.46.5 and I cannot reopen the issue (no permission I guess)

**Comment by cybern1nja8** [comment]
This is still not working with version Postman 11.46.2. (Windows)

**Comment by dcdraper** [comment]
Since this issue cannot be reopened, I created a new ticket: https://github.com/postmanlabs/postman-app-support/issues/13604
