### ISSUE TITLE
Postman extension not loading data.

### ISSUE THREAD

**Issue by oluwatobiiloba** [a85/POSTMan-Chrome-Extension#12270]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman not loading my collections or data despite successfully logging in.

<img width="341" alt="Screenshot 2023-08-27 at 16 12 44" src="https://github.com/postmanlabs/postman-app-support/assets/74077388/c6ce3b84-e3a0-4287-9cd1-8eda927834f7">

### Steps To Reproduce

-Open collection

### Operating System

macOS

### Postman Version

0.6.1

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by WayneRockett** [comment]
I get the same issue on a PC, and cannot seem to find a way of importing/adding an existing collection.

**Comment by pankajk07** [comment]
@oluwatobiiloba @WayneRockett Can you please update to the latest extension and check if the issue is still reproducible?

If the issue persists please share the logs with us. You can access logs from here

<img width="476" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/44100113/bc1efb44-eea3-4880-9965-acc009e4304b">

**Comment by PSAGChristian** [comment]
With the currently available version 0.7.0 I still have the same issue.

```
(2023-09-12T05:46:34.919Z) [info] [extension] Extension activation started: 1694497594917
(2023-09-12T05:46:34.978Z) [info] [extension] Extension activation completed: 1694497594978
(2023-09-12T05:46:34.978Z) [info] [extension] Extension activation took 61ms
(2023-09-12T05:46:41.712Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2023-09-12T05:46:41.712Z) [info] [extension:htmlProvider] get sidebar HTML
(2023-09-12T05:46:41.716Z) [info] [extension:workspaceContext] Found the record in the cache
(2023-09-12T05:47:43.295Z) [info] [extension:secretManager] Removing the account data
(2023-09-12T05:47:43.315Z) [info] [extension:globalStateManager] clearing storage
(2023-09-12T05:47:43.326Z) [info] [extension:sidebar:manager] setting the view to login app
(2023-09-12T05:47:43.326Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"login"}
(2023-09-12T05:47:49.079Z) [info] [extension:sidebar:manager] set login state to busy
(2023-09-12T05:47:49.079Z) [info] [extension:auth] Starting the login flow
(2023-09-12T05:48:06.607Z) [info] [extension:auth] Handing the URL redirect to VSCode
(2023-09-12T05:48:06.607Z) [info] [extension:auth:client] finalising the auth handover
(2023-09-12T05:48:07.229Z) [info] [extension:auth] The sign in flow has finished successfully
(2023-09-12T05:48:07.849Z) [info] [extension:sidebar:manager] setting the view to sidebar app
(2023-09-12T05:48:07.849Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2023-09-12T05:48:07.849Z) [info] [extension:htmlProvider] get sidebar HTML
(2023-09-12T05:48:07.867Z) [info] [extension:workspaceContext:networkClient] fetch recent workspaces: {"baseUrl":"https://bifrost-extension-https-global.gw.postman.com/ws/proxy"}
(2023-09-12T06:01:01.453Z) [error] [extension:sidebar:manager:history-sidebar] Error: Failed to get history items: {"stack":"\n    in Nt\n    in div\n    in styled.div\n    in a\n    in k\n    in Lt\n    in Suspense\n    in Ke\n    in Suspense\n    in div\n    in styled.div\n    in div\n    in styled.div\n    in nav\n    in styled.nav\n    in k\n    in fr\n    in st\n    in lt\n    in kt\n    in _t\n    in Pt\n    in w\n    in Xe\n    in le\n    in ee\n    in ne\n    in ft\n    in c\n    in a\n    in k\n    in StrictMode","appId":"history-sidebar","errorElementId":"history-sidebar"}
```

Operating System
Win11

Postman Version
0.7.0

Postman Platform
VSCode 1.82.0

User Account Type
Signed In User

**Comment by oluwatobiiloba** [comment]
`(2023-09-20T14:56:17.007Z) [info] [extension] Extension activation started: 1695221776945
(2023-09-20T14:56:20.729Z) [info] [extension] Extension activation completed: 1695221780729
(2023-09-20T14:56:20.729Z) [info] [extension] Extension activation took 3784ms
(2023-09-20T15:33:59.385Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2023-09-20T15:33:59.414Z) [info] [extension:htmlProvider] get sidebar HTML
(2023-09-20T15:34:01.344Z) [info] [extension:workspaceContext] Found the record in the cache
(2023-09-20T15:34:11.408Z) [info] [extension:htmlProvider] getting console panel HTML
(2023-09-20T15:34:14.428Z) [info] [extension:Console:provider] Message from Console: {"type":"SEND_ANALYTICS","payload":{"action":"init","category":"console","label":"","value":1}}
(2023-09-20T15:34:14.440Z) [info] [extension:Console:provider] Message from Console: {"type":"promise-message","payload":{"uid":"878248af-6e12-4215-b5cf-5f86e6f00eb1","originalMessage":{"type":"SESSION_STORAGE","payload":{"method":"getItem","storageType":"KV","key":"23034417:4436403:Console:default-timeline"}}}}
(2023-09-20T15:34:14.444Z) [info] [extension:Console:provider] Send message to webview: {"type":"promise-message-878248af-6e12-4215-b5cf-5f86e6f00eb1"}
(2023-09-20T15:34:19.070Z) [info] [extension:secretManager] Removing the account data
(2023-09-20T15:34:19.071Z) [info] [extension:Console:provider] Send message to webview: {"type":"CLEAR_CONSOLE","payload":{}}
(2023-09-20T15:34:19.106Z) [info] [extension:Console:provider] Message from Console: {"type":"promise-message","payload":{"uid":"927bbe59-5626-4d8f-b437-55d9c652315d","originalMessage":{"type":"SESSION_STORAGE","payload":{"method":"setItem","storageType":"KV","key":"23034417:4436403:Console:default-timeline","value":[]}}}}
(2023-09-20T15:34:19.112Z) [info] [extension:Console:provider] Send message to webview: {"type":"STORAGE_UPDATE","payload":{"key":"23034417:4436403:Console:default-timeline","value":[],"storageType":"KV"}}
(2023-09-20T15:34:19.113Z) [info] [extension:Console:provider] Send message to webview: {"type":"promise-message-927bbe59-5626-4d8f-b437-55d9c652315d","payload":true}
(2023-09-20T15:34:19.167Z) [info] [extension:globalStateManager] clearing storage
(2023-09-20T15:34:19.174Z) [info] [extension:sidebar:manager] setting the view to login app
(2023-09-20T15:34:19.174Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"login"}
(2023-09-20T15:34:21.166Z) [info] [extension:sidebar:manager] set login state to busy
(2023-09-20T15:34:21.187Z) [info] [extension:auth] Starting the login flow
(2023-09-20T15:35:06.171Z) [info] [extension:auth] Handing the URL redirect to VSCode
(2023-09-20T15:35:06.177Z) [info] [extension:auth:client] finalising the auth handover
(2023-09-20T15:35:08.195Z) [info] [extension:auth] The sign in flow has finished successfully
(2023-09-20T15:35:09.443Z) [info] [extension:sidebar:manager] setting the view to sidebar app
(2023-09-20T15:35:09.443Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2023-09-20T15:35:09.443Z) [info] [extension:htmlProvider] get sidebar HTML
(2023-09-20T15:35:09.450Z) [info] [extension:workspaceContext:networkClient] fetch recent workspaces: {"baseUrl":"https://bifrost-extension-https-global.gw.postman.com/ws/proxy"}
(2023-09-20T15:35:22.469Z) [error] [extension:sidebar:manager:history-sidebar] Error: Failed to get history items: {"stack":"\n    in Nt\n    in div\n    in styled.div\n    in a\n    in k\n    in Lt\n    in Suspense\n    in Ke\n    in Suspense\n    in div\n    in styled.div\n    in div\n    in styled.div\n    in nav\n    in styled.nav\n    in k\n    in fr\n    in st\n    in lt\n    in kt\n    in _t\n    in Pt\n    in w\n    in Xe\n    in le\n    in ee\n    in ne\n    in ft\n    in c\n    in a\n    in k\n    in StrictMode","appId":"history-sidebar","errorElementId":"history-sidebar"}
(2023-09-20T15:39:11.109Z) [info] [extension] Extension activation started: 1695224351104
(2023-09-20T15:39:12.731Z) [info] [extension] Extension activation completed: 1695224352730
(2023-09-20T15:39:12.731Z) [info] [extension] Extension activation took 1626ms
(2023-09-20T15:39:15.251Z) [info] [extension:htmlProvider] getting console panel HTML
(2023-09-20T15:39:23.913Z) [info] [extension:Console:provider] Message from Console: {"type":"SEND_ANALYTICS","payload":{"action":"init","category":"console","label":"","value":1}}
(2023-09-20T15:39:24.462Z) [info] [extension:Console:provider] Message from Console: {"type":"promise-message","payload":{"uid":"a43ca384-2cfe-4d13-9585-1f55fae545eb","originalMessage":{"type":"SESSION_STORAGE","payload":{"method":"getItem","storageType":"KV","key":"23034417:4436403:Console:default-timeline"}}}}
(2023-09-20T15:39:24.463Z) [info] [extension:Console:provider] Send message to webview: {"type":"promise-message-a43ca384-2cfe-4d13-9585-1f55fae545eb"}
(2023-09-20T15:44:26.896Z) [info] [extension] Extension activation started: 1695224666884
(2023-09-20T15:44:27.142Z) [info] [extension] Extension activation completed: 1695224667142
(2023-09-20T15:44:27.142Z) [info] [extension] Extension activation took 258ms
(2023-09-20T15:45:01.862Z) [info] [extension] Extension activation started: 1695224701852
(2023-09-20T15:45:02.375Z) [info] [extension] Extension activation completed: 1695224702375
(2023-09-20T15:45:02.375Z) [info] [extension] Extension activation took 523ms
(2023-09-20T16:04:43.316Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2023-09-20T16:04:43.320Z) [info] [extension:htmlProvider] get sidebar HTML
(2023-09-20T16:04:43.365Z) [info] [extension:workspaceContext] Found the record in the cache
(2023-09-20T16:04:46.622Z) [info] [extension:secretManager] Removing the account data
(2023-09-20T16:04:46.665Z) [info] [extension:globalStateManager] clearing storage
(2023-09-20T16:04:46.668Z) [info] [extension:sidebar:manager] setting the view to login app
(2023-09-20T16:04:46.668Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"login"}
(2023-09-20T16:04:48.893Z) [info] [extension:sidebar:manager] set login state to busy
(2023-09-20T16:04:48.897Z) [info] [extension:auth] Starting the login flow
(2023-09-20T16:05:14.662Z) [info] [extension:auth] Handing the URL redirect to VSCode
(2023-09-20T16:05:14.668Z) [info] [extension:auth:client] finalising the auth handover
(2023-09-20T16:05:16.280Z) [info] [extension:auth] The sign in flow has finished successfully
(2023-09-20T16:05:17.279Z) [info] [extension:sidebar:manager] setting the view to sidebar app
(2023-09-20T16:05:17.279Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2023-09-20T16:05:17.279Z) [info] [extension:htmlProvider] get sidebar HTML
(2023-09-20T16:05:17.292Z) [info] [extension:workspaceContext:networkClient] fetch recent workspaces: {"baseUrl":"https://bifrost-extension-https-global.gw.postman.com/ws/proxy"}
`

**Comment by oluwatobiiloba** [comment]
@pankajk07 
```
(2023-09-20T14:56:17.007Z) [info] [extension] Extension activation started: 1695221776945
(2023-09-20T14:56:20.729Z) [info] [extension] Extension activation completed: 1695221780729
(2023-09-20T14:56:20.729Z) [info] [extension] Extension activation took 3784ms
(2023-09-20T15:33:59.385Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2023-09-20T15:33:59.414Z) [info] [extension:htmlProvider] get sidebar HTML
(2023-09-20T15:34:01.344Z) [info] [extension:workspaceContext] Found the record in the cache
(2023-09-20T15:34:11.408Z) [info] [extension:htmlProvider] getting console panel HTML
(2023-09-20T15:34:14.428Z) [info] [extension:Console:provider] Message from Console: {"type":"SEND_ANALYTICS","payload":{"action":"init","category":"console","label":"","value":1}}
(2023-09-20T15:34:14.440Z) [info] [extension:Console:provider] Message from Console: {"type":"promise-message","payload":{"uid":"878248af-6e12-4215-b5cf-5f86e6f00eb1","originalMessage":{"type":"SESSION_STORAGE","payload":{"method":"getItem","storageType":"KV","key":"23034417:4436403:Console:default-timeline"}}}}
(2023-09-20T15:34:14.444Z) [info] [extension:Console:provider] Send message to webview: {"type":"promise-message-878248af-6e12-4215-b5cf-5f86e6f00eb1"}
(2023-09-20T15:34:19.070Z) [info] [extension:secretManager] Removing the account data
(2023-09-20T15:34:19.071Z) [info] [extension:Console:provider] Send message to webview: {"type":"CLEAR_CONSOLE","payload":{}}
(2023-09-20T15:34:19.106Z) [info] [extension:Console:provider] Message from Console: {"type":"promise-message","payload":{"uid":"927bbe59-5626-4d8f-b437-55d9c652315d","originalMessage":{"type":"SESSION_STORAGE","payload":{"method":"setItem","storageType":"KV","key":"23034417:4436403:Console:default-timeline","value":[]}}}}
(2023-09-20T15:34:19.112Z) [info] [extension:Console:provider] Send message to webview: {"type":"STORAGE_UPDATE","payload":{"key":"23034417:4436403:Console:default-timeline","value":[],"storageType":"KV"}}
(2023-09-20T15:34:19.113Z) [info] [extension:Console:provider] Send message to webview: {"type":"promise-message-927bbe59-5626-4d8f-b437-55d9c652315d","payload":true}
(2023-09-20T15:34:19.167Z) [info] [extension:globalStateManager] clearing storage
(2023-09-20T15:34:19.174Z) [info] [extension:sidebar:manager] setting the view to login app
(2023-09-20T15:34:19.174Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"login"}
(2023-09-20T15:34:21.166Z) [info] [extension:sidebar:manager] set login state to busy
(2023-09-20T15:34:21.187Z) [info] [extension:auth] Starting the login flow
(2023-09-20T15:35:06.171Z) [info] [extension:auth] Handing the URL redirect to VSCode
(2023-09-20T15:35:06.177Z) [info] [extension:auth:client] finalising the auth handover
(2023-09-20T15:35:08.195Z) [info] [extension:auth] The sign in flow has finished successfully
(2023-09-20T15:35:09.443Z) [info] [extension:sidebar:manager] setting the view to sidebar app
(2023-09-20T15:35:09.443Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2023-09-20T15:35:09.443Z) [info] [extension:htmlProvider] get sidebar HTML
(2023-09-20T15:35:09.450Z) [info] [extension:workspaceContext:networkClient] fetch recent workspaces: {"baseUrl":"https://bifrost-extension-https-global.gw.postman.com/ws/proxy"}
(2023-09-20T15:35:22.469Z) [error] [extension:sidebar:manager:history-sidebar] Error: Failed to get history items: {"stack":"\n    in Nt\n    in div\n    in styled.div\n    in a\n    in k\n    in Lt\n    in Suspense\n    in Ke\n    in Suspense\n    in div\n    in styled.div\n    in div\n    in styled.div\n    in nav\n    in styled.nav\n    in k\n    in fr\n    in st\n    in lt\n    in kt\n    in _t\n    in Pt\n    in w\n    in Xe\n    in le\n    in ee\n    in ne\n    in ft\n    in c\n    in a\n    in k\n    in StrictMode","appId":"history-sidebar","errorElementId":"history-sidebar"}
(2023-09-20T15:39:11.109Z) [info] [extension] Extension activation started: 1695224351104
(2023-09-20T15:39:12.731Z) [info] [extension] Extension activation completed: 1695224352730
(2023-09-20T15:39:12.731Z) [info] [extension] Extension activation took 1626ms
(2023-09-20T15:39:15.251Z) [info] [extension:htmlProvider] getting console panel HTML
(2023-09-20T15:39:23.913Z) [info] [extension:Console:provider] Message from Console: {"type":"SEND_ANALYTICS","payload":{"action":"init","category":"console","label":"","value":1}}
(2023-09-20T15:39:24.462Z) [info] [extension:Console:provider] Message from Console: {"type":"promise-message","payload":{"uid":"a43ca384-2cfe-4d13-9585-1f55fae545eb","originalMessage":{"type":"SESSION_STORAGE","payload":{"method":"getItem","storageType":"KV","key":"23034417:4436403:Console:default-timeline"}}}}
(2023-09-20T15:39:24.463Z) [info] [extension:Console:provider] Send message to webview: {"type":"promise-message-a43ca384-2cfe-4d13-9585-1f55fae545eb"}
(2023-09-20T15:44:26.896Z) [info] [extension] Extension activation started: 1695224666884
(2023-09-20T15:44:27.142Z) [info] [extension] Extension activation completed: 1695224667142
(2023-09-20T15:44:27.142Z) [info] [extension] Extension activation took 258ms
(2023-09-20T15:45:01.862Z) [info] [extension] Extension activation started: 1695224701852
(2023-09-20T15:45:02.375Z) [info] [extension] Extension activation completed: 1695224702375
(2023-09-20T15:45:02.375Z) [info] [extension] Extension activation took 523ms
(2023-09-20T16:04:43.316Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2023-09-20T16:04:43.320Z) [info] [extension:htmlProvider] get sidebar HTML
(2023-09-20T16:04:43.365Z) [info] [extension:workspaceContext] Found the record in the cache
(2023-09-20T16:04:46.622Z) [info] [extension:secretManager] Removing the account data
(2023-09-20T16:04:46.665Z) [info] [extension:globalStateManager] clearing storage
(2023-09-20T16:04:46.668Z) [info] [extension:sidebar:manager] setting the view to login app
(2023-09-20T16:04:46.668Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"login"}
(2023-09-20T16:04:48.893Z) [info] [extension:sidebar:manager] set login state to busy
(2023-09-20T16:04:48.897Z) [info] [extension:auth] Starting the login flow
(2023-09-20T16:05:14.662Z) [info] [extension:auth] Handing the URL redirect to VSCode
(2023-09-20T16:05:14.668Z) [info] [extension:auth:client] finalising the auth handover
(2023-09-20T16:05:16.280Z) [info] [extension:auth] The sign in flow has finished successfully
(2023-09-20T16:05:17.279Z) [info] [extension:sidebar:manager] setting the view to sidebar app
(2023-09-20T16:05:17.279Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2023-09-20T16:05:17.279Z) [info] [extension:htmlProvider] get sidebar HTML
(2023-09-20T16:05:17.292Z) [info] [extension:workspaceContext:networkClient] fetch recent workspaces: {"baseUrl":"https://bifrost-extension-https-global.gw.postman.com/ws/proxy"}

```

**Comment by oluwatobiiloba** [comment]
https://github.com/postmanlabs/postman-app-support/assets/74077388/b44b38b0-3e32-4220-8190-88a60452f1bf

@pankajk07

**Comment by whittenc** [comment]
I am seeing the same issue, any resolution?

**Comment by gcasella** [comment]
I have the same issue. I am behind a corporate proxy.

**Comment by oluwatobiiloba** [comment]
@pankajk07 , this has been resolved on my end. Thank you

**Comment by oluwatobiiloba** [comment]
@whittenc , have you tried updating to the most recent version?

**Comment by whittenc** [comment]
I have tried using 0.18.0 and it is still not working, I am behind a corporate proxy as well.

From the log:
(2024-01-19T14:17:55.006Z) [info] [extension:htmlProvider] get sidebar HTML
(2024-01-19T14:17:55.012Z) [info] [extension:workspaceContext:networkClient] fetch recent workspaces: {"baseUrl":"https://bifrost-extension-https-global.gw.postman.com/ws/proxy"}
