### ISSUE TITLE
Postbot clobbered all my tests!

### ISSUE THREAD

**Issue by ChrisMiami** [a85/POSTMan-Chrome-Extension#12410]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I had maybe 6 tests created against a request and decided to add a specific new one.  I asked Postbot to create it for me. It did, but it REPLACED all my current tests!  I cannot find a way to get them back (Ctrl-Z was ineffective).  I asked Postbot to "restore previous tests" but nope, that just generated random repetitions of the test it clobbered mine with.  Ugh.  What a hassle.

### Steps To Reproduce

1. open a request with existing tests
2. put the cursor where you want the new test to appear
3. open postbot's input 
4. paste from another app and hit enter
5. notice that HTML formatting was sent
6. stop postbot
7. paste and match format (this is a ridiculous place to have to do this, this input should only accept plain text)
8. re-send the request
9. when it's done, notice that it wiped out all the existing tests.

### Operating System

macOS

### Postman Version

10.18.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by abhijitkane** [comment]
Thanks for reporting this @ChrisMiami. We'll look into the formatting issue right away.

For the issue of the tests being replaced, can you email us at help@postman.com from your registered email? That'll help us track what may have gone wrong with your query. A screenshot of what the pasted HTML formatting looked like will help too.

**Comment by kylerRenneker** [comment]
@ChrisMiami Apologies on the delayed response! We have been working diligently on improving Postbot and it's capabilities. 

We implemented a fix that should allow you to use CMD/CTRL + Z  within the test script editor to undo any changes that Postbot made that your are not satisfied with. 

Please update your Postman app to the latest app version and try again. 

Also, please continue to reach out with any/all feedback. We are constantly adding new features to Postbot and addressing any bugs.

**Comment by pbalsara-wk** [comment]
Came here to say that this issue is still happening and CTRL + Z does not work. I have to close the Request and opt to Not Save so I can get back the original tests I've created. Too scared to use Postbot if it's going to wipe my existing post-scripts.

**Comment by abhijitkane** [comment]
@pbalsara-wk That's odd - can you describe the steps that led to this situation? What specific test are you asking Postbot to generate? Feel free to share a screen recording with us at help@postman.com too.

**Comment by pbalsara-wk** [comment]
@abhijitkane it happens inconsistently in version 11.0.7

Here is my initial script:
![postman_script](https://github.com/postmanlabs/postman-app-support/assets/169838617/eb3eb694-1e14-4240-aa56-3fde6f8c08b0)
My initial prompt: "create test cases to check if environment variable called environment contains a certain value"
![postman_script2](https://github.com/postmanlabs/postman-app-support/assets/169838617/ef85f297-0590-437d-93e1-e8022ab5cb4f)
2nd prompt: "Update test case to check for qa" This is where my original script gets wiped. CTRL + Z does not let me get the scripts back. I have to close the Request I'm working on and click Don't Save and start over. For this particular request, since it's not that complex I'm not too worried. But for more complex scripting, I can't use this feature because I fear I'll lose all my other work. 
![postman_script3](https://github.com/postmanlabs/postman-app-support/assets/169838617/fdf71cfd-2041-4f97-aff9-d159e569b8f6)
