### ISSUE TITLE
Failed to run performance test

### ISSUE THREAD

**Issue by thachun** [a85/POSTMan-Chrome-Extension#12608]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am trying to run the performance test on a collection but unfortunately I got an error saying:
_"Failed to start run
 Postman encountered an error due to which the run could not be started. Please try again."_
![image](https://github.com/postmanlabs/postman-app-support/assets/4361026/1d5d6456-dd55-4f9e-8c6e-bc7483d663b5)

Is there any version working that I could downgrade?

Thanks!

### Steps To Reproduce

1. Just run a performance test on a collection and see a popup error message at the right corner.

### Operating System

Windows

### Postman Version

10.22.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ilies-t** [comment]
I have the same problem in `10.22.9` version

**Comment by mateussaggin** [comment]
Same problem here in `10.22.9`.

Edit: The problem is happening only if there is folders inside the collection.

**Comment by sweco-dkuntg** [comment]
> Same problem here in `10.22.9`.
> 
> Edit: The problem is happening only if there is folders inside the collection.

Thank you so much. I got it working 💯.

**Comment by nikithaachhini23** [comment]
Hi @thachun 

Could you please provide information on whether you're running performance run on a folder directly (or) on a collection with folders?

Screen recording of the flow would be much appreciated.

**Comment by atehvg** [comment]
Same thing is happening when I run a folder inside a collection. Running the collection with folders doesn't have issues. Running Version 10.22.9.

Edit: added version number

**Comment by thachun** [comment]
> Hi @thachun
> 
> Could you please provide information on whether you're running performance run on a folder directly (or) on a collection with folders?
> 
> Screen recording of the flow would be much appreciated.

I did not see any folder in my collection. I just create a new collection again and it works :-). Something wrong with the old collection that honestly, I have no idea.

**Comment by gintsgints** [comment]
<img width="1287" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/1847580/9905cd5a-62fe-4e42-8ee7-72926aed5d89">

**Comment by nikithaachhini23** [comment]
@thachun Thank you for providing the screenshot. Running folders inside a collection (or) running a collection as a whole with requests and folders will work. Let me know if you're facing any issues there.

As @atehvg informed running a performance run directly on a folder is an issue which we're currently looking into and will have it fixed in the upcoming release.

**Comment by habibsc** [comment]
I'm having this same issue if I try to run the Performance test from a Folder inside a Collection. Running the Performance test directly from a Collection, with requests not inside a Folder, worked a expected.
Still using Postman `10.22.6` here.

**Comment by gintsgints** [comment]
For me works whole collection even it has tests within folders.

**Comment by cpinkerton-kpler** [comment]
Same issue on `v10.22` - trying to run a Performance test on a sub-folder of a Collection. Running the Functional test works on the same folder. Running the Performance test on a whole Collections works

**Comment by nikithaachhini23** [comment]
Hey @thachun @atehvg Could you try updating the app to the latest version and check? (latest version should be 10.24.0). It works even on 10.23.0

Running performance test directly on folders with in collection should work now.

**Comment by SavioHolanda** [comment]
Estou na versão v10.24.11 e está ocorrendo o mesmo problema.

Solução que fiz: Criei uma nova coleção e coloquei as requisições para essa nova coleção e com voltou a funcionar.

**Comment by nikithaachhini23** [comment]
@SavioHolanda Are you saying that on v10.24.11 running a performance test directly on folders is not working?
I verified that it works. Could you please share a recording?

**Comment by hfcipriano** [comment]
I prefer the old postman... This new one should renamed to _bugman_

**Comment by Linghucong1999** [comment]
![image](https://github.com/postmanlabs/postman-app-support/assets/94914428/f2d1f011-6e8f-4fb5-8ac4-07bc06d4c049)
这个就很操蛋

**Comment by albaraX** [comment]
I have same problem. An earlier advices doesn't work. Postman v. 11.0.11. Testing collection aren't contain any folder and I create a new collection in current version of Postman. I've tried run testing with 1 VU (2 mins). Anyway got error "Failed to start run". 

> ![image](https://private-user-images.githubusercontent.com/94914428/328782866-f2d1f011-6e8f-4fb5-8ac4-07bc06d4c049.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDU5NDEsIm5iZiI6MTcxNTI0NTY0MSwicGF0aCI6Ii85NDkxNDQyOC8zMjg3ODI4NjYtZjJkMWYwMTEtNmU4Zi00ZmI1LThhYzQtMDdiYzA2ZDRjMDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA5MDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MjkyOTRiYjQxMTFhYzQ1ZGJhMTAwYmJlZDc1OWI2OTJlNDgwZjk5MWRkY2I2MDViNzdiNDExOWEyNGIzMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GOTaqHAQibjrlcEwhztuNd-FRlVg3CfNCPg3x9q8wfs) 这个就很操蛋

**Comment by s93rum06** [comment]
<pre>
[18176][1715471123192][main][info]["Booting Postman 11.0.12, win32-10.0.19045 on x64"]
[18176][1715471123194][main][info]["EventBus~initialize - Success"]
[18176][1715471123196][main][info]["Proxy configuration has not been setup"]
[18176][1715471123196][main][info]["CloudProxyManager~init - Success"]
[18176][1715471123215][main][info]["performShellDataMigration: Migration has already been done. Bailing out"]
[18176][1715471123216][main][info]["UpdateHandler~init - Success"]
[18176][1715471123218][main][info]["LeaderSelection: Initialized successfully"]
[18176][1715471123218][main][info]["VersionDependencyService: Initialized successfully"]
[18176][1715471123240][main][info]["GPU detected VID 4318 DID 7944 ACTIVE false"]
[18176][1715471123240][main][info]["GPU detected VID 5140 DID 140 ACTIVE false"]
[18176][1715471123243][main][info]["newAccountRegionPreferenceService~getPreferenceWithFallback - Preference not found in storage."]
[18176][1715471123244][main][info]["newAccountRegionPreferenceService~getToggleMenuTemplate - Using preference:","useUSRegion"]
[18176][1715471123256][main][info]["shellController~init: Success"]
[18176][1715471123267][main][info]["shellMeta~init: Success"]
[18176][1715471123267][main][info]["partitionMigrationService: State of V7 partition:"]
[18176][1715471123268][main][info]["partitionMigrationService: V7 partitions",[]]
[18176][1715471123268][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no partition with scratchpad namespace"]
[18176][1715471123268][main][info]["partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no transit partition which could have been used for scratchpad"]
[18176][1715471123268][main][info]["partitionMigrationService~init: Success"]
[18176][1715471123283][main][info]["partitionMigrationService~runV8PartitionsIntegrity: Two way migration~ removing the following partitions from v8",[]]
[18176][1715471123288][main][info]["userPartitionService~getRecentV8UserPartition: recent v8 user context partition ","8120dbe8-f271-4a9d-9519-8394b751ab87"]
[18176][1715471123288][main][info]["userPartitionService~_rectifyTheActivePartitionOfApplication: Setting the active partition to ","8120dbe8-f271-4a9d-9519-8394b751ab87"]
[18176][1715471123296][main][info]["userPartitionService~init: Success"]
[18176][1715471123311][main][info]["userPartitionService: State of v8 partition system:"]
[18176][1715471123314][main][info]["shell~init~getPartitionToLoad: loading active partition"]
[18176][1715471123316][main][info]["userPartitionService: List of partitions:",[{"partitionId":"8120dbe8-f271-4a9d-9519-8394b751ab87","namespace":"users","userId":"34858560","teamId":"0","lastUpdated":"2024-05-11T23:35:52.352Z"},{"partitionId":"3162e21b-a368-44b2-a4cb-8e30a5eef382","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]]
[18176][1715471123316][main][info]["userPartitionService: users global meta:",{}]
[18176][1715471123320][main][info]["Main:windowManager~newRequesterWindow: Fetch and update runtime config: us"]
[18176][1715471124618][main][info]["RuntimeIPCAgent~started: Success"]
[18176][1715471125740][main][info]["Main~getRemoteInitPath:: "]
[18176][1715471126240][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[18176][1715471126255][main][info]["windowManager: First requester booted successfully."]
[18176][1715471126255][main][info]["windowManager~restoreWindows: Restoring requester windows"]
[18176][1715471126255][main][info]["Main~AppEvents - Received booted event for process requester.Version 11.0.12 UI Version: 11.0.12-ui-240509-0541 Desktop Platform Version: 11.0.12"]
[18176][1715471126361][main][info]["Main~getRemoteInitPath:: "]
[18176][1715471126595][main][info]["Main~getPlatformLaunchPerfMetrics"]
[18176][1715471127716][main][info]["Main - model-events~user - (user, bootstrapUser) received"]
[18176][1715471127716][main][info]["model-events~user - bootstrapUser received"]
[18176][1715471127730][main][info]["INTERCEPTOR CONNECTIVITY: Attempting to start websocket server on port 15611"]
[18176][1715471162394][main][info]["ExecutionProcess ~ First boot"]
[18176][1715471162805][main][info]["ExecutionSystem execution ~ ipc connection successfully established"]
[18176][1715471162805][main][info]["[ExecutionProcessLauncher] Spawned the execution process, pid: ",12984]
[18176][1715471162817][main][info]["ExecutionSystem execution ~ ipc connection successfully established"]
[18176][1715471165490][main][error]["ExecutionProcess ~ Boot error",{"name":"Error","message":"Unhandled error. ({\n  subsystem: 'system.startup',\n  error: {\n    message: \"Cannot destructure property 'memory' of '(intermediate value)' as it is undefined.\",\n    stack: \"TypeError: Cannot destructure property 'memory' of '(intermediate value)' as it is undefined.\\n\" +\n      '    at ExecutionEngine._getNumberOfPossibleGroups (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\ScenarioManager\\\\ExecutionEngine\\\\Engine.js:127:13)\\n' +\n      '    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\\n' +\n      '    at async ExecutionEngine.setup (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\ScenarioManager\\\\ExecutionEngine\\\\Engine.js:154:49)\\n' +\n      '    at async onStartup (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\ScenarioManager\\\\index.js:38:5)\\n' +\n      '    at async startup (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\lib\\\\system\\\\_life-cycle.js:30:5)\\n' +\n      '    at async C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\lib\\\\system\\\\_life-cycle.js:219:7\\n' +\n      '    at async C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\preload\\\\desktop\\\\node-process\\\\IPC.js:1:2486'\n  },\n  source: 'ExecutionSystem:LifeCycle',\n  message: 'Error in starting up the ExecutionSystem',\n  severity: undefined,\n  timestamp: '2024-05-11T23:46:05.497Z'\n})","stack":"Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({\n  subsystem: 'system.startup',\n  error: {\n    message: \"Cannot destructure property 'memory' of '(intermediate value)' as it is undefined.\",\n    stack: \"TypeError: Cannot destructure property 'memory' of '(intermediate value)' as it is undefined.\\n\" +\n      '    at ExecutionEngine._getNumberOfPossibleGroups (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\ScenarioManager\\\\ExecutionEngine\\\\Engine.js:127:13)\\n' +\n      '    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\\n' +\n      '    at async ExecutionEngine.setup (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\ScenarioManager\\\\ExecutionEngine\\\\Engine.js:154:49)\\n' +\n      '    at async onStartup (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\ScenarioManager\\\\index.js:38:5)\\n' +\n      '    at async startup (C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\lib\\\\system\\\\_life-cycle.js:30:5)\\n' +\n      '    at async C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\services\\\\automation-testing\\\\lib\\\\system\\\\_life-cycle.js:219:7\\n' +\n      '    at async C:\\\\Users\\\\jerry\\\\AppData\\\\Local\\\\Postman\\\\app-11.0.12\\\\resources\\\\app.asar\\\\preload\\\\desktop\\\\node-process\\\\IPC.js:1:2486'\n  },\n  source: 'ExecutionSystem:LifeCycle',\n  message: 'Error in starting up the ExecutionSystem',\n  severity: undefined,\n  timestamp: '2024-05-11T23:46:05.497Z'\n})\n    at new NodeError (node:internal/errors:372:5)\n    at EventEmitter.emit (node:events:516:17)\n    at sendEvent (C:\\Users\\jerry\\AppData\\Local\\Postman\\app-11.0.12\\resources\\app.asar\\services\\automation-testing\\lib\\communication.js:19:19)\n    at broadcastError (C:\\Users\\jerry\\AppData\\Local\\Postman\\app-11.0.12\\resources\\app.asar\\services\\automation-testing\\lib\\communication.js:164:3)\n    at C:\\Users\\jerry\\AppData\\Local\\Postman\\app-11.0.12\\resources\\app.asar\\services\\automation-testing\\lib\\system\\_life-cycle.js:221:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async C:\\Users\\jerry\\AppData\\Local\\Postman\\app-11.0.12\\resources\\app.asar\\preload\\desktop\\node-process\\IPC.js:1:2486"}]
[18176][1715471183990][main][info]["ExecutionProcess ~ Already booted"]
[18176][1715471202169][main][info]["ExecutionProcess ~ Already booted"]
[18176][1715471578625][main][info]["WindowManager~closeHandler - Closed Window (id: 1 )"]
[18176][1715471578649][main][info]["Quitting app"]
[18176][1715471578649][main][info]["ExecutionProcessLauncher ~ No actively running power-save-blocker"]
[18176][1715471578653][main][info]["ExecutionSystem execution ~ ipc connection closed."]
</pre>

**Comment by Linghucong1999** [comment]
> I have same problem. An earlier advices doesn't work. Postman v. 11.0.11. Testing collection aren't contain any folder and I create a new collection in current version of Postman. I've tried run testing with 1 VU (2 mins). Anyway got error "Failed to start run".我有同样的问题。先前的建议不起作用。邮差 v. 11.0.11。测试集合不包含任何文件夹，我在当前版本的 Postman 中创建一个新集合。我尝试过使用 1 VU（2 分钟）运行测试。无论如何，出现错误“无法开始运行”。
> 
> > ![image](https://private-user-images.githubusercontent.com/94914428/328782866-f2d1f011-6e8f-4fb5-8ac4-07bc06d4c049.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDU5NDEsIm5iZiI6MTcxNTI0NTY0MSwicGF0aCI6Ii85NDkxNDQyOC8zMjg3ODI4NjYtZjJkMWYwMTEtNmU4Zi00ZmI1LThhYzQtMDdiYzA2ZDRjMDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA5MDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MjkyOTRiYjQxMTFhYzQ1ZGJhMTAwYmJlZDc1OWI2OTJlNDgwZjk5MWRkY2I2MDViNzdiNDExOWEyNGIzMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GOTaqHAQibjrlcEwhztuNd-FRlVg3CfNCPg3x9q8wfs) 这个就很操蛋

The same version worked before, but suddenly it stopped working for a while. I opened the console and no error was reported.

**Comment by Linghucong1999** [comment]
> I have same problem. An earlier advices doesn't work. Postman v. 11.0.11. Testing collection aren't contain any folder and I create a new collection in current version of Postman. I've tried run testing with 1 VU (2 mins). Anyway got error "Failed to start run".
> 
> > ![image](https://private-user-images.githubusercontent.com/94914428/328782866-f2d1f011-6e8f-4fb5-8ac4-07bc06d4c049.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDU5NDEsIm5iZiI6MTcxNTI0NTY0MSwicGF0aCI6Ii85NDkxNDQyOC8zMjg3ODI4NjYtZjJkMWYwMTEtNmU4Zi00ZmI1LThhYzQtMDdiYzA2ZDRjMDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA5MDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MjkyOTRiYjQxMTFhYzQ1ZGJhMTAwYmJlZDc1OWI2OTJlNDgwZjk5MWRkY2I2MDViNzdiNDExOWEyNGIzMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GOTaqHAQibjrlcEwhztuNd-FRlVg3CfNCPg3x9q8wfs) 这个就很操蛋

The same version worked before, but suddenly it stopped working for a while. I opened the console and no error was reported.

**Comment by albaraX** [comment]
Maybe if you use all your runner's limits (25/25) then you can't start a performance test? I have 40/25 runs

**Comment by Linghucong1999** [comment]
> Maybe if you use all your runner's limits (25/25) then you can't start a performance test? I have 40/25 runs

i use 1/1 run,is still the case

**Comment by arr19422** [comment]
Same here, Postman just does not initiate a performing test, wichever the VU, Duration or Load profile. It just does not work.

**Comment by nikithaachhini23** [comment]
Apologies for the delay in responding back. We're looking into this [issue](https://github.com/postmanlabs/postman-app-support/issues/12608#issuecomment-2106063461). 

Are all of you running the performance run on windows machine using the latest version?

**Comment by s93rum06** [comment]
3 days ago, Yes. not today  v11.1.
<pre>
[18176][1715471123192][main][info]["Booting Postman 11.0.12, win32-10.0.19045 on x64"]
[18176][1715471123194][main][info]["EventBus~initialize - Success"]
</pre>

> Apologies for the delay in responding back. We're looking into this [issue](https://github.com/postmanlabs/postman-app-support/issues/12608#issuecomment-2106063461).
> 
> Are all of you running the performance run on windows machine using the latest version?

**Comment by Linghucong1999** [comment]
> Apologies for the delay in responding back. We're looking into this [issue](https://github.com/postmanlabs/postman-app-support/issues/12608#issuecomment-2106063461).
> 
> Are all of you running the performance run on windows machine using the latest version?

yap
![image](https://github.com/postmanlabs/postman-app-support/assets/94914428/c1e3490c-4933-4a64-b055-88418c430a1e)

**Comment by deibyd** [comment]
I am experiencing exactly the same issue. When I try to perform a load test, it returns an error.

![image](https://github.com/postmanlabs/postman-app-support/assets/10169167/99c50941-6277-4732-9705-07d04090dd5a)

![image](https://github.com/postmanlabs/postman-app-support/assets/10169167/6ec8f5b3-bb1d-4b2a-8871-4f6c6f4b73a3)

Please help me to be able to perform these load tests. Could it be a subscription issue where I need to pay?

**Comment by nikithaachhini23** [comment]
@deibyd Its not a subscription issue. Seems like a windows specific issue which the team will be looking into. We'll ensure to fix this issue soon. Could you please provide the logs if possible?

**Comment by nikithaachhini23** [comment]
@s93rum06 Could you please zip the entire `logs` folder and send it?

**Comment by deibyd** [comment]
> @deibyd Its not a subscription issue. Seems like a windows specific issue which the team will be looking into. We'll ensure to fix this issue soon. Could you please provide the logs if possible?
[postman-logs.zip](https://github.com/postmanlabs/postman-app-support/files/15404604/postman-logs.zip)

**Comment by tagtag21** [comment]
@deibyd hi . I have a similar problem, did you manage to figure it out?

**Comment by VlogP** [comment]
@deibyd Hi, same issue.

**Comment by deibyd** [comment]
No, I haven't fixed it yet; it still occurs. I have passed the log to @nikithaachhini23. Maybe he can tell us the status and what he has discovered. Thank you very much in advance, nikithaachhini23. We remain attentive to anything else you need. I think it would be a good idea for others to also attach their logs.

**Comment by albaraX** [comment]
Can't attach a hole logs for some reason, but here is a part of them:

```
[3376][1714656247782][execution-node-process][error][["Error while getting available memory",{"code":1,"killed":false,"signal":null,"cmd":"systeminfo | find \"Available Physical Memory\""}]]
[3376][1714656247783][execution-node-process][error]["Failed to get platform specs",{"code":1,"killed":false,"signal":null,"cmd":"systeminfo | find \"Available Physical Memory\"","name":"Error","message":"Command failed: systeminfo | find \"Available Physical Memory\"\n","stack":"Error: Command failed: systeminfo | find \"Available Physical Memory\"\n\n at ChildProcess.exithandler (node:child_process:407:12)\n at ChildProcess.emit (node:events:527:28)\n at maybeClose (node:internal/child_process:1092:16)\n at ChildProcess._handle.onexit (node:internal/child_process:302:5)"}]
[3376][1714656247784][execution-node-process][error][{"subsystem":"system.startup","error":{"message":"Cannot destructure property 'memory' of '(intermediate value)' as it is undefined.","stack":"TypeError: Cannot destructure property 'memory' of '(intermediate value)' as it is undefined.\n at ExecutionEngine._getNumberOfPossibleGroups
```

`[20112][1716816819308][main][error]["ExecutionProcess ~ Boot error",{"name":"Error","message":"Unhandled error. ({\n subsystem: 'system.startup',\n error: {\n message: \"Cannot destructure property 'memory' of '(intermediate value)' as it is undefined.\",\n stack: \"TypeError: Cannot destructure property 'memory' of '(intermediate value)' as it is undefined.\\n\" +\n ' at ExecutionEngine._getNumberOfPossibleGroups`

**Comment by tagtag21** [comment]
My logs with the problem
[logs.zip](https://github.com/postmanlabs/postman-app-support/files/15495276/logs.zip)

**Comment by nikithaachhini23** [comment]
Thanks a lot guys for your inputs and efforts in providing us logs. Appreciate your patience with us.

So far my analysis:
1. While using the postman app on a different language say Japanese via app general settings. Running a performance test on windows machine might not be working. Are you guys using the app in a different language?
2. Based on the logs, there's an issue while retrieving available memory from the user's windows machine to run a performance test. We have got all the logs data we need. Thanks again!

We're definitely considering this as a priority issue and will be looking into it soon. Rest assured we'll fix it as soon as we can and update you.

**Comment by VictorStala** [comment]
Hello, I've ran into the problem described above aswell. These are the commands mentioned for testing on the ticket #12852 so here are the results, hope this helps!
![mem-test](https://github.com/postmanlabs/postman-app-support/assets/166688761/23891d4d-f6bf-42fa-a634-4cbde5614379)

**Comment by albaraX** [comment]
> Hello, I've ran into the problem described above aswell. These are the commands mentioned for testing on the ticket #12852 so here are the results, hope this helps! ![mem-test](https://private-user-images.githubusercontent.com/166688761/335488575-23891d4d-f6bf-42fa-a634-4cbde5614379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDI0MDAsIm5iZiI6MTcxNzE0MjEwMCwicGF0aCI6Ii8xNjY2ODg3NjEvMzM1NDg4NTc1LTIzODkxZDRkLWY2YmYtNDJmYS1hNjM0LTRjYmRlNTYxNDM3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNzU1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDk5OTc5ODg2NzU3OTRhOGFmYmI4MGVjYmI2OTBmYTk4MzBmNjI2OGUyNmU5ZTVjZGIwNTc4YTk4NTBlYWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iiUoMDWVdd0RtowY0fuj6Y0ctJjSwqMarWtv6oHiFJU)

Right now run those commands and got same response, but I have a bit more free memory

**Comment by tagtag21** [comment]
Hello!
My results
![Screenshot_5](https://github.com/postmanlabs/postman-app-support/assets/4338963/94c7933a-4e49-4c81-8e8a-5e6794f12099)
![Screenshot_4](https://github.com/postmanlabs/postman-app-support/assets/4338963/0869851c-675b-49a8-863e-2ed25eb10064)

**Comment by NazeehAlhosary** [comment]
@deibyd  Hi, I have the latest version (v11.1.14), and I still have the same issue.

**Comment by johseffer** [comment]
same here

![image](https://github.com/postmanlabs/postman-app-support/assets/25435217/0b9c2662-5948-436a-9f3b-0e542667e33a)

![image](https://github.com/postmanlabs/postman-app-support/assets/25435217/23d83620-1bff-43c0-8fc4-a78be635eb08)

**Comment by postfrzero** [comment]
Hey folks, we've identified an issue which could be leading to these errors and we're working on rolling out a Canary app build which could resolve this while the changes are integrated into the mainline app. Either @nikithaachhini23 or I will post an update here as soon as we have something tangible.

**Comment by Thairam** [comment]
same here.

**Comment by manuelmilian** [comment]
same here, Postman v11.2.0 on Windows 11

**Comment by tagtag21** [comment]
@postfrzero 
Hello!

Please write when the fix is ​​planned?

**Comment by issamansur** [comment]
I wanted to start test today, but had same issue.
Version: 11.2.12 (latest)
I have no folders in collection

P.S.: interesting, that at start I had this error
![image](https://github.com/postmanlabs/postman-app-support/assets/77580844/bee7b67c-47b3-4342-bdf1-f514559220e0)
After reloading page of runner had this:
![image](https://github.com/postmanlabs/postman-app-support/assets/77580844/f8a5cdbd-c094-4d0a-91ec-5218e0bad3c5)

**Comment by qa-oks** [comment]
The same issue, version 11.2.12.
Is there any information about the fixing? Seems like the problem is kind of critical for a lot of people here

**Comment by filippoitaliano** [comment]
I have the same issue. I think it's also worth mentioning I experience this same behavior on Windows 11 and also on the latest macOS, both with the latest version of Postman. Right now I'm using version 10.24.2 to be able to run Performance tests.

**Comment by seifeddine55** [comment]
Our team have the same error using 11.12.1 but for 10.24.25  it's working. Any thought about this kind of behavior

**Comment by issamansur** [comment]
Guys, please, can you send link/site , where I can download stable version of postman with working performance test  (10.24.2-10.24.25)?

**Comment by filippoitaliano** [comment]
@issamansur Postman portable from Portapps is the one i'm using. It bundles version 10.24. Don't take this as a recommendation. Please do your research on https://github.com/portapps reliability 🙏.

**Comment by issamansur** [comment]
> @issamansur Postman portable from Portapps is the one i'm using. It bundles version 10.24. Don't take this as a recommendation. Please do your research on https://github.com/portapps reliability 🙏.

Thank you so much!

**Comment by nikithaachhini23** [comment]
Hey folks, we've fixed the issue and as promised rolled out a canary build. Please download the app as per your platform choice and let us know.

~~ ~~Here's the link - [https://www.postman.com/downloads/canary/](https://www.postman.com/downloads/canary/) 
On scrolling down in this page, you'll find canary builds for different OS platforms.~~ ~~

Thanks for your patience. We'll rollout this fix as part of **v11.3** in our mainline app.

**Update:** v11.3 is out and instead of using canary link please use [https://www.postman.com/downloads/](https://www.postman.com/downloads/)

**Comment by seifeddine55** [comment]
@nikithaachhini23 ,still having the same error using postman 


![Screenshot_20240624_112134_Teams.jpg](https://github.com/postmanlabs/postman-app-support/assets/26234442/9d451c27-c699-4f27-b29f-0b9d8101a6d8)




![Screenshot_20240624_112832_Teams.jpg](https://github.com/postmanlabs/postman-app-support/assets/26234442/08f84e7a-240e-4bd9-b122-5ca683b32dc8)

**Comment by nikithaachhini23** [comment]
@seifeddine55 Could you please share the recording? Also, can you run below two commands individually in your cmd prompt and share the screenshot?

`powershell -Command "(Get-CimInstance -ClassName Win32_OperatingSystem).FreePhysicalMemory"`

`powershell -Command "(Get-WmiObject -Class Win32_OperatingSystem).FreePhysicalMemory"`

If you're trying to open a previous run which failed to start - that run report would continue to show that way as it failed previously and is an expected behaviour.

**Comment by seifeddine55** [comment]
@nikithaachhini23  ![image](https://github.com/postmanlabs/postman-app-support/assets/26234442/b03dbd2c-6827-469a-a0c9-28fab2562f92)

![GIF 24-06-2024 12-22-12](https://github.com/postmanlabs/postman-app-support/assets/26234442/cc9df5a2-88cb-42eb-b448-acad321896e7)

**Comment by nikithaachhini23** [comment]
@seifeddine55 Isn't the retry working? Could you please provide the **application** logs? You can refer this [link](https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app#h_01G396RG1PATWM520KV442RCSJ) to provide the zipped logs. Please delete the existing logs first -> relaunch the app -> trigger the performance test -> zip the logs and send us

Thanks!

**Comment by seifeddine55** [comment]
hi @nikithaachhini23 , i'm having a fragment of the graph when the tests are running , Any thoughts 

![Capture d’écran 2024-06-25 102516](https://github.com/postmanlabs/postman-app-support/assets/26234442/c9439545-6c91-40ba-b0ca-ec1943bb8b3b)

**Comment by postfrzero** [comment]
Hey @seifeddine55, it looks like this could be a different issue. Would you mind getting in touch with us at help@postman.com? This will allow us to get application logs and other specific information which can help us zero in on what's going on without worrying about anything in the log contents becoming public, etc.

**Comment by ilyassCH** [comment]
Hi All,

I need to perform the performance testing, but I have the same error : 
![image](https://github.com/postmanlabs/postman-app-support/assets/43208092/b73b7b84-be5c-4070-863a-5636b628dea3)

Here is my Postman version:
![image](https://github.com/postmanlabs/postman-app-support/assets/43208092/c86e8d1e-389c-494a-b92f-7589c4682190)

Here is the result of executing the two commands : 
![image](https://github.com/postmanlabs/postman-app-support/assets/43208092/caf9b08d-48b6-4f35-92ca-667a363f4721)

Feel free to ask any other needed information.

Thanks,

Ilyass

**Comment by issamansur** [comment]
@ilyassCH, try use this https://www.postman.com/downloads/canary/

**Comment by ilyassCH** [comment]
Hi @issamansur thank you for your suggestion, but I still have the same error : 
![image](https://github.com/postmanlabs/postman-app-support/assets/43208092/6fc00821-63e9-4783-8380-99d495af7795)

Postman canary version:
![image](https://github.com/postmanlabs/postman-app-support/assets/43208092/f965b271-9791-4b58-8552-2938c279bc75)


When I am allowed to run the performance test, I see this screen a few seconds after clicking the **run** button:

![image](https://github.com/postmanlabs/postman-app-support/assets/43208092/fdae6341-3afe-4751-8da9-c5536568adca)



Thanks,

**Comment by issamansur** [comment]
Interesting, last version canary works for me, but it doesn't work for u. So.. wait for answer from developers :(

**Comment by ilyassCH** [comment]
Hi @nikithaachhini23 , Hi @postfrzero , 

I'm still experiencing issues running the performance test and encountering the same error messages:

- "Something went wrong while setting up your system for performance testing"
- "Failed to start run"

Could you please assist me with this? May I share my Postman logs with you for further investigation?

Thank you,

Ilyass

**Comment by nikithaachhini23** [comment]
@ilyassCH Apologies for the delay in responding. This seems like a cache issue. Could you please provide us the application logs as described [here](https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app#h_01G396RG1PATWM520KV442RCSJ) (or) get in touch with us at [help@postman.com](mailto:help@postman.com)?

**Comment by ilyassCH** [comment]
Hi @nikithaachhini23 Thank you for your response,

Here is the zipped Postman logs.

Thank you,

Ilyass

[Uploading logs.zip…]()

**Comment by nikithaachhini23** [comment]
@ilyassCH The link you've provided doesn't have logs. It references to the current support thread. Could you please cross check and send?

**Comment by ilyassCH** [comment]
> @ilyassCH The link you've provided doesn't have logs. It references to the current support thread. Could you please cross check and send?

Sorry, here is the well uploaded postman logs : 

[postman_logs.zip](https://github.com/user-attachments/files/16015566/postman_logs.zip)

**Comment by nikithaachhini23** [comment]
Hi @ilyassCH  The logs you've provided point to our mainline prod app `v11.2` and this issue would exist as the fix will go as part of `v11.3`. We validated that the issue you're facing on canary is because of cache.

I'd request you to follow the below steps:
1. Force quit all open instances of the Postman Desktop app.
2. Uninstall the postman canary app you have on your machine.
3. Open File explorer on windows and paste below ones in the path field:
     
     `C:\Users\<user>\AppData\Local\PostmanCanary`
      `C:\Users\<user>\AppData\Roaming\PostmanCanary`
      
      By providing your username in `<user>`, you'll find the canary folders in the above 2 paths. Delete these folders to get rid of any local data ([ref](https://support.postman.com/hc/en-us/articles/4410785125271-How-to-remove-local-data))
 4. Do a fresh install of canary using [https://www.postman.com/downloads/canary/](https://www.postman.com/downloads/canary/)
 5. Try running a performance test and verify if issue is fixed
 
 
In case, you encounter any issue with the above steps please reach out to us via [help@postman.com](mailto:help@postman.com) we'll assist you further.

**Comment by ilyassCH** [comment]
Hello @nikithaachhini23 ,

Thank you very much for your help, it works great for me.  

I am looking forward to v11.3!

Best regards,  
Ilyass

**Comment by topWang1888** [comment]
> Hi @ilyassCH The logs you've provided point to our mainline prod app `v11.2` and this issue would exist as the fix will go as part of `v11.3`. We validated that the issue you're facing on canary is because of cache.
> 
> I'd request you to follow the below steps:
> 
> 1. Force quit all open instances of the Postman Desktop app.
> 2. Uninstall the postman canary app you have on your machine.
> 3. Open File explorer on windows and paste below ones in the path field:
>    `C:\Users\<user>\AppData\Local\PostmanCanary`
>    `C:\Users\<user>\AppData\Roaming\PostmanCanary`
>    By providing your username in `<user>`, you'll find the canary folders in the above 2 paths. Delete these folders to get rid of any local data ([ref](https://support.postman.com/hc/en-us/articles/4410785125271-How-to-remove-local-data))
> 4. Do a fresh install of canary using https://www.postman.com/downloads/canary/
> 5. Try running a performance test and verify if issue is fixed
> 
> In case, you encounter any issue with the above steps please reach out to us via [help@postman.com](mailto:help@postman.com) we'll assist you further.

This works for me. Thanks

**Comment by teamolhuang** [comment]
Having this issue on 11.2, I poked around and found a 11.3.0 in appdata local. I started postman through that and it says it updated to 11.3.0, and the error went away for me.

**Comment by nikithaachhini23** [comment]
Hello folks, issue is fixed in v11.3 and is available on [https://www.postman.com/downloads/](https://www.postman.com/downloads/) to download as per your platform choice. Updated the previous canary link with this one.

**Comment by postfrzero** [comment]
Thanks for your patience here folks! I'm closing this issue now, though of course we'll keep an eye out for comments.

**Comment by almmechanics** [comment]
Still occurs in 11.15.0 :(

**Comment by TscharnigAndreas** [comment]
I still receive the very same error on 11.51.0

![Image](https://github.com/user-attachments/assets/a64fe657-67ec-41ff-9423-fc6f0ba36230)
