### ISSUE TITLE
localhost not being resolved [VSCode Extension]

### ISSUE THREAD

**Issue by mark-hingston** [a85/POSTMan-Chrome-Extension#12939]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When sending a request to an application server running on `localhost` the response pane shows the following error:

![image](https://github.com/postmanlabs/postman-app-support/assets/97893030/5e0725de-6eba-46d9-9f30-45db8380d577)

If I change the host name to the loopback address `127.0.0.1` the request succeeds.

### Steps To Reproduce

As above

### Operating System

Windows

### Postman Version

1.0.3

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
@mark-hingston Thanks for reporting this issue. We are looking into this, in the meantime you can unblock yourself by replacing `localhost` with `127.0.0.1`. 

For example, you can change the URL from `localhost:8080` to `127.0.0.1:8080` and send the request.

**Comment by pankajk07** [comment]
@mark-hingston We have identified the issue and will be fixed in the upcoming release of the extension.

**Comment by MrItzreal** [comment]
> @mark-hingston Thanks for reporting this issue. We are looking into this, in the meantime you can unblock yourself by replacing `localhost` with `127.0.0.1`.
> 
> For example, you can change the URL from `localhost:8080` to `127.0.0.1:8080` and send the request.



I can attest that as of 6/17/2024 EST, changing 'localhost' to '127.0.0.1' works.

**Comment by HamzaH30** [comment]
> > @mark-hingston Thanks for reporting this issue. We are looking into this, in the meantime you can unblock yourself by replacing `localhost` with `127.0.0.1`.
> > For example, you can change the URL from `localhost:8080` to `127.0.0.1:8080` and send the request.
> 
> I can attest that as of 6/17/2024 EST, changing 'localhost' to '127.0.0.1' works.

Thank you!

**Comment by nmsteve** [comment]
Facing same Issues. Great to hear it will be fixed on next release!

**Comment by aa2kb** [comment]
facing the same issue

**Comment by voho** [comment]
the same issue here

**Comment by yunsteel** [comment]
> > @mark-hingston Thanks for reporting this issue. We are looking into this, in the meantime you can unblock yourself by replacing `localhost` with `127.0.0.1`.
> > For example, you can change the URL from `localhost:8080` to `127.0.0.1:8080` and send the request.
> 
> I can attest that as of 6/17/2024 EST, changing 'localhost' to '127.0.0.1' works.

Thank you! It works well

**Comment by Wagkart** [comment]
Facing same issue - changing to http://127.0.0.1:8000/ did  work for me as well

**Comment by temorgan** [comment]
I've tried the http://127.0.0.1 method (my localhost port is http://localhost:7071). But it is unsuccessful. My function_app.py code was working successfully before and now all I receive is the invalid ip address message. Most frustrating.

**Comment by indraneel-postman** [comment]
The localhost resolution issue is fixed in the latest release - Postman Extension v1.1.0. Please update your extension to the latest version to use localhost APIs without any hindrance.

**Comment by moh682** [comment]
This also happens when using Graphql with Postman App.

**Comment by temorgan** [comment]
Hi all, unfortunately I'm still encountering the 'invalid ip' persistent issue with my Postman setup when testing an Azure Function app. I'm on a Windows 10 OS with Postman Version: v7.32.1and running locally with the function endpoint at http://127.0.0.1:7071/normalize_excel_data The environment variables are set correctly (verified via command prompt) but even with changing the Postman request URL to http://127.0.0.1:7071/normalize_excel_data and setting the Content-Type header to application/json as well as adjusting tests to expect a 200 status code, JSON content type, and valid JSON response, I'm receiving a response status code as 400 as well as a Content-Type mismatch (application/json vs. expected text/xml). The Schema validation errors indicating null where an object is expected. I'm new to VS Code and have a basic understanding of Python but this is new and was never an issue. I had this running seamlessly before but now I'm stuck with this blasted invalid IP address.
