### ISSUE TITLE
Postman UI showing 'secret not supported for domain error' when base URL is coming from a variable

### ISSUE THREAD

**Issue by stephen84s** [a85/POSTMan-Chrome-Extension#13028]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We have a couple of values coming from the postman vault and they have been restricted to specific domains.
Because the Base URL changes between environments it is coming from a variable in the environment.

What we observed was in this scenario, if we try to use the secret from the vault (which restricted to certain domains only), the UI will show an error that the secret is not available for that domain.
However note the request goes through fine when we click the "send" button.

### Steps To Reproduce

1. Create a new secret in postman vault `google-query` with any value, restricted to `https://www.google.com` domain
2. Next create a environment `test`
3. In test environment add a variable `google-url` with value `https://www.google.com/ 
4. Now create a collection with url: {{google-url}} and Query Param: `q` with value `{{vault:google-query}}`
5. Observe the `{{vault:google-query}}` is highlighted red and we get an error stating "secret is not supported on domain of this request"
6. If you hit the send button now, the request goes through fine.
7. If you replace the variable `{{google-url}} with the actual value `https://www.google.com` the UI error will go away.

### Screenshots or Videos

Vault Contents:
![image](https://github.com/user-attachments/assets/709b3e6d-ac71-4703-9e2e-0dfbf791cd3e)

Request with UI Error:
![image](https://github.com/user-attachments/assets/d7e75a5a-7a91-4cfd-a76b-399cc2866596)

### Operating System

macOS

### Postman Version

11.4.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by VShingala** [comment]
@stephen84s We've fixed this issue with Postman App v11.5 which is now available to download. Could you update your app and try this again?

In the case mentioned by you, we will now show an hover tooltip which asks you to add value for your vault secret. Once you also add the correct query, the error should be resolved. Feel free to add more questions if you have any here.

![image](https://github.com/user-attachments/assets/01b63b3d-3587-4e5d-b2a3-69ad28c63f0f)

Below is the screenshot once we have added a value for vault secret.

![image](https://github.com/user-attachments/assets/e1ff1a09-42c0-4abf-ba89-f578d7d97638)

**Comment by stephen84s** [comment]
@VShingala Upgraded to 11.5.1 and the problem still exists, I think you missed the second part of step 1, to add "https://www.google.com" to the allowed domains list of the vault secret.

![image](https://github.com/user-attachments/assets/48c05ee4-f412-4a8f-991c-916e89c7bfbb)

![image](https://github.com/user-attachments/assets/2457e504-9873-4131-a3e9-5d43fbebdba8)

**Comment by VShingala** [comment]
@stephen84s Yeah, you're correct. I missed out on adding the proper domain for the vault secret. We're working on the fix for this particular issue which should be available by end of next week with. We'll add update here once the fix is available.

**Comment by VShingala** [comment]
@stephen84s This issue is now fixed with latest Postman App v11.6. We were able to verify it working with steps mentioned by you. Sharing the screenshot of same below.

![image](https://github.com/user-attachments/assets/ee2d33d8-555f-43a2-ac9a-cd0e7dd6d006)

![image](https://github.com/user-attachments/assets/a61d3e7b-ff19-46d9-8d3f-1b6693e89340)

We're closing this issue for now but feel free to re-open it if you face any further problems with the fix.
