### ISSUE TITLE
Meaningless moving cursor at the end of the URL 

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#13232]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The cursor jumps at the end of the request URL.

### Step 1
This is the URL I have 
![image](https://github.com/user-attachments/assets/d3012a4b-a429-4176-92c6-963d3bfed49d)

### Step 2
Selecting the text
![image](https://github.com/user-attachments/assets/82674179-aa7c-4ffc-9a60-f0347143ad1c)

### Step 3
 Starting to type (I want to replace the selected text). Suddenly the cursor jumps to the end after first character. It is very annoying.
![image](https://github.com/user-attachments/assets/07729432-135d-4afc-a254-525fe9dc9110)

Please do not move the cursor at the end of the line. It should stay within the selected block. It should behave like any other text editors behave.

### Operating System

Windows

### Postman Version

newest

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by giridharvc7** [comment]
Thank you for reporting this, i'm able to reproduce this issue, but albiet inconsistently. We'll have a look into this

https://github.com/user-attachments/assets/8ac5058f-c438-42a5-ac27-4fe2633bcd90

**Comment by jonathanhaviv** [comment]
Hi @martinformi we have released a fix for this issue. I'm going to close this for now, but if you're still facing this problem feel free to reopen the issue.

**Comment by MasonMarinko** [comment]
Is this fix live? If so, this is still an ongoing issue.

**`To Reproduce`**

- Click in middle of request URL
- Submit request
- Start typing
- After you type 1 character, cursor jumps to end of URL.

**GIF**

![Image](https://github.com/user-attachments/assets/95fc34b5-0e3c-4a65-bb37-6bdc9b7bcb1d)

**Comment by jonathanhaviv** [comment]
@MasonMarinko, thanks for sharing. It looks like a similar issue, but with a different cause. We will dig into this more and let you know once we have fully fixed it.

**Comment by timhall** [comment]
Hi @MasonMarinko I've been taking a look at this and I'm having trouble reproducing the issue. Couple of questions:

1. How are you submitting the request? (i.e. clicking Send, <kbd>Cmd+Enter</kbd> / <kbd>Ctrl+Enter</kbd>)
2. OS / Postman version / Web or Desktop

**Comment by MasonMarinko** [comment]
Ok @timhall @jonathanhaviv got some more information, sorry I didn't include it last time.

Replicate: Looks like it's not on initial send, 

- Click inside the request URL, then ENTER, JUST enter, not `Cmd+Enter` / `Ctrl+Enter`
- When request is complete, type and after one character, it will jump to end.

**OS Name**: Microsoft Windows 11 Enterprise, 
**OS Version**: 10.0.22631 Build 22631
**Postman Version**: 

![Image](https://github.com/user-attachments/assets/0ed7be93-c72d-43d8-8166-1d6d9c108df5)

I'm using Desktop app

**Comment by Juliusvm** [comment]
Also having this issue, it is very frustrating. Mac OS

<img width="285" alt="Image" src="https://github.com/user-attachments/assets/dee6d8b6-92a6-41d1-8788-0460e97d8232" />

**Comment by chrisjshields** [comment]
Possibly one of the most frustrating UI bugs I've seen. Windows:
![Image](https://github.com/user-attachments/assets/2651b5ee-8af0-44cb-8989-cb6d91f80675)

**Comment by timhall** [comment]
Hi @MasonMarinko (and others) thanks for the details, I'm able to reproduce it and I'm working on a fix now. Will update this thread when it is released.

**Comment by alnotas** [comment]
My God, how difficult is to fix this issue. Every couple of days a new update is downloaded and yet, this issue remains. It's totally frustrating and counter-productive.

**Comment by MasonMarinko** [comment]
@timhall any eta on when this will be fixed?

**Comment by timhall** [comment]
@martinformi and others: sorry for this annoying issue! It has been fixed in Postman v11.44.4 (released May 8th). Please give it a try and let us know if you run into anything else.

**Comment by MasonMarinko** [comment]
@timhall This issue is not fixed, Here is my version, still happening...

![Image](https://github.com/user-attachments/assets/63e3d3ea-bd33-4b09-ab20-6594c704bc0a)

![Image](https://github.com/user-attachments/assets/7bd8ad9a-c867-4807-80eb-9f339fff54a1)

**Comment by timhall** [comment]
Sorry about that, looks like the behavior is still occurring on Windows. I'll keep debugging it.

**Comment by MasonMarinko** [comment]
@timhall do we have ETA this time? Last one took a few weeks, is this going to be similar time frame?

**Comment by timhall** [comment]
@MasonMarinko, the follow-up fix was released in 11.46.6 earlier today. Please update and give it a try when you can, thanks!

**Comment by MasonMarinko** [comment]
@timhall seems to be working as expected now, thank you!

**Comment by DSchau** [comment]
Thanks for the persistence @MasonMarinko :) Let us know how else we can keep improving Postman for you!

(and of course, nice work @timhall on the non-trivial fix and quicker fix the second time!)

Also if you'd like to chat about how we can improve Postman for you, feel free to book a time here: https://app.reclaim.ai/m/dschau/quick-meeting
