### ISSUE TITLE
Recursive variable resolution not working

### ISSUE THREAD

**Issue by Larsekk** [a85/POSTMan-Chrome-Extension#1341]
Following scenario seems to be a bug:

*\* Env. variable *\* 
aaa = aaa123
ccc = {{ddd}}

*\* Global variable **
ddd = ddd123

*\* Request **
Build: {{aaa}} {{ccc}}
Resolved: aaa123 {{ddd}}

Until 3.0.5 or 3.0.4 the recursive resolution worked fine.

**Comment by thirtified** [comment]
Same here, and still broken in 3.0.7 :(.

**Comment by dprice** [comment]
Also seeing it in 3.0.7. Recursive variables are the basis of all my URLs so this is a huge blocker for me.

**Comment by abhijitkane** [comment]
Was able to reproduce this, but it was fixed when I restarted my app. Will add a force-fix for this and investigate how it happened.

@dprice @thirtified Can you try restarting Postman and trying?

**Comment by thirtified** [comment]
@abhijitkane Thanks, but restarting doesn't change anything for me. I even updated from 3.0.6 to 3.0.7 at some point, no change.

**Comment by dprice** [comment]
@abhijitkane Restarted and still not working here either with version:
Version 3.0.7 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by Larsekk** [comment]
Also tried to restart and reinstall the application. Problem still exists.

OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by josephnoall** [comment]
I have got the same problem.  I've noticed that most (but not quite all) of the time if I click on the "Open a new postman window" icon then the problem will not exhibit itself in the new window (it still does in the old window).  I use a lot of variable values that expire every 40 minutes, so starting over with a new window and re-opening all my tabs each time is getting a little tedious.  Is there any way to revert to 3.0.4?

Here is my version information:

Version 3.0.6 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
@josephnoall No, but we'll be pushing a fix for this tomorrow.

**Comment by abhijitkane** [comment]
@josephnoall @Larsekk Can you confirm this fixed in v3.0.8? (chrome:/extensions, enable 'Developer Mode', Update extensions now)

**Comment by thirtified** [comment]
@abhijitkane YES, confirmed: nested variable expansion works again in 3.0.8. Awesome, thanks for the fix!

Version 3.0.8 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by Larsekk** [comment]
@abhijitkane : I can confirm that the issues is solved too! Thank you for the fix.

Version 3.0.8 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by dprice** [comment]
@abhijitkane - also confirmed that 3.0.8 is working. Many thanks!

**Comment by josephnoall** [comment]
Confirmed that this is fixed in 3.0.8, thanks!
