### ISSUE TITLE
[Help]Upload file via Post man 

### ISSUE THREAD

**Issue by mit4ever** [a85/POSTMan-Chrome-Extension#1441]
Hi,
I upload file via Postman is not working but Advanced Rest Client is working, please help me.
Thanks

**Comment by abhijitkane** [comment]
@tuyenlq What's the exact problem you're facing? You can check http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ and http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ to check if Postman is throwing any errors and the exact request/response payloads.

**Comment by mit4ever** [comment]
@abhijitkane 

I cant upload file via post man :(,so i do wrong ?

Request header: 
![capture1](https://cloud.githubusercontent.com/assets/10045154/9937724/1e50f6f6-5d8c-11e5-82ca-e595d8bdf7e9.PNG)

Request Payload: 
![capture2](https://cloud.githubusercontent.com/assets/10045154/9937732/29c64bf8-5d8c-11e5-8b0e-6053575c2d22.PNG)

Respone: 
![capture3](https://cloud.githubusercontent.com/assets/10045154/9937739/32cd2f64-5d8c-11e5-88f0-7a4da07a84cc.PNG)

Postman: 
![capturepostman](https://cloud.githubusercontent.com/assets/10045154/9937709/07bcc8c0-5d8c-11e5-9efb-75a97e88ae4a.PNG)

Thanks

**Comment by abhijitkane** [comment]
Try changing `files[]` to `files`. If that doesn't help, can you post the screenshot from advanced rest client?

**Comment by mit4ever** [comment]
![2015-09-18_9-52-16](https://cloud.githubusercontent.com/assets/10045154/9951114/83829ace-5dec-11e5-8b3f-4c83b9ecef9d.png)
It working. I suggest in postman cannot get path image

**Comment by mit4ever** [comment]
Hi,

Why closed topic ? i try upload file on postman  but it not working

**Comment by abhijitkane** [comment]
The file name in Advanced Rest Client is fileUpload, but `files[]`/`files` in Postman. Can you change it to `fileUpload` in Postman as well?
If not, you can select the 'binary' mode in Postman instead of 'form-data' and try uploading the file there.

**Comment by kellyjandrews** [comment]
@abhijitkane 
I'm also having some difficulty with the file upload for `multipart/form-data` field type.

I did notice something in the `curl` however, that may be causing the problem. 

With Postman, the `curl` call uses this `-F "file1=filename.jpg"`.
In my terminal however, I have to use `-F "file1=@filename.jpg"`.

I tested with Advanced Rest Client, and was able to upload there as well.  I don't think the file select is appropriately attaching the file to the request. Hope that helps.

**Comment by a85** [comment]
@abhijitkane I believe we have pushed a bug fix for that yesterday?

**Comment by abhijitkane** [comment]
@kellyjandrews What version of Postman are you using? Also, if the Interceptor is on, can you try turning  it off?

**Comment by kellyjandrews** [comment]
3.0.21 - Interceptor is not on.

**Comment by abhijitkane** [comment]
Can you update to 3.0.22 (chrome:/extensions > Enable developer mode > Update extensions now) and check?
Try uploading a small text file via the form-data section via a POST request to http://dump.getpostman.com/post.

**Comment by kellyjandrews** [comment]
Still omitted the `@` in the `-F` flag. I attempted to use your route, but not sure what the form field should be called. I tried `file`.

**Comment by abhijitkane** [comment]
The http://dump.getpostman.com/post endpoint should echo the contents of the file you're sending.
Are you unable to reproduce this? If not, can you check the console for any errors? (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/)

Screenshot - 
![screen shot 2015-10-07 at 18 16 40](https://cloud.githubusercontent.com/assets/681190/10337776/a1db65c2-6d1f-11e5-966f-0db3f0288fae.png)

**Comment by kellyjandrews** [comment]
```
<html>
    <head>
        <title>Internal Server Error</title>
    </head>
    <body>
        <h1>Internal Server Error</h1>
    </body>
</html>
```

**Comment by abhijitkane** [comment]
Even with a simple text file?

**Comment by kellyjandrews** [comment]
`test.txt` with the text "test" in it, yes.

**Comment by kellyjandrews** [comment]
the curl still shows this - 

```
curl -X POST -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW" -H "Cache-Control: no-cache" -H "Postman-Token: abcb6497-b225-c592-01be-e9ff460ca188" -F "file=test.txt" 'http://dump.getpostman.com/post'
```

 `-F "file=test.txt"` should be `-F "file=@test.txt"`

**Comment by abhijitkane** [comment]
The curl command is not what Postman actually sends. That's generated for convenience.

What if you change the URL to `httpbin.org/post`?

**Comment by kellyjandrews** [comment]
If the cUrl command is generated for convenience, it would be more convenient if it were accurate :) 

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
111
```

**Comment by abhijitkane** [comment]
Of course - we'll include that in the next release. For now, you can choose Shell > cURL in the preview window to get the correct cURL output.
We'll look into the file upload issue and get back to you.

**Comment by kellyjandrews** [comment]
you know what - that makes more sense - I didn't realize there was a shell -> curl - that looks appropriate - when tested in terminal - that works fine

```
{
  "args": {},
  "data": "",
  "files": {
    "file": "testing\n"
  },
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Cache-Control": "no-cache",
    "Content-Length": "194",
    "Content-Type": "multipart/form-data; boundary=---011000010111000001101001; boundary=------------------------a31d9bbb3c265a14",
    "Host": "httpbin.org",
    "Postman-Token": "fcd35ead-41e4-c204-87d8-a430d1ff22bd",
    "User-Agent": "curl/7.37.1"
  },
  "json": null,
  "origin": "68.58.82.213",
  "url": "http://httpbin.org/post"
}
```

**Comment by arawind** [comment]
Facing the same issue - Postman 3.0.22 (Packaged) with Interceptor 0.2.13

Interceptor's request: 

```
curl 'http://dump.getpostman.com/post' -H 'Origin: chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryjm9OsGs3uzVVdoIT' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Cookie: km_ai=hb9iwazFI3WzkVlvNCCiDgDxxH4%3D; _ga=GA1.2.1540532211.1444282899; kvcd=1444283323195; km_vs=1; km_lv=1444283323; km_uq=; mp_88b82fb04df34ce696ed11f104901795_mixpanel=%7B%22distinct_id%22%3A%20%2215045f8206b50-0623da2ee-34627807-fa000-15045f8206c61%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%2C%22%24search_engine%22%3A%20%22google%22%7D' -H 'Connection: keep-alive' -H 'X-FirePHP-Version: 0.0.6' -H 'DNT: 1' -H 'Postman-Token: 55114064-1a5f-6089-f81f-31e0f2831402' --data-binary $'------WebKitFormBoundaryjm9OsGs3uzVVdoIT--\r\n' --compressed
```

Postman's Response for above:

```
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "en-US,en;q=0.8",
    "Cache-Control": "no-cache",
    "Connection": "close",
    "Content-Length": "44",
    "Content-Type": "multipart/form-data; boundary=----WebKitFormBoundaryjm9OsGs3uzVVdoIT",
    "Cookie": "km_ai=hb9iwazFI3WzkVlvNCCiDgDxxH4%3D; _ga=GA1.2.1540532211.1444282899; kvcd=1444283323195; km_vs=1; km_lv=1444283323; km_uq=; mp_88b82fb04df34ce696ed11f104901795_mixpanel=%7B%22distinct_id%22%3A%20%2215045f8206b50-0623da2ee-34627807-fa000-15045f8206c61%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%2C%22%24search_engine%22%3A%20%22google%22%7D",
    "Dnt": "1",
    "Host": "127.0.0.1:8000",
    "Origin": "chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo",
    "Postman-Token": "55114064-1a5f-6089-f81f-31e0f2831402",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36",
    "X-Firephp-Version": "0.0.6"
  },
  "json": null,
  "origin": "127.0.0.1",
  "url": "http://127.0.0.1:8000/post"
}
```

Works from DHC:

```
{
  "args": {}, 
  "data": "", 
  "files": {
    "abcd": "test\n"
  }, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Accept-Language": "en-US,en;q=0.8", 
    "Connection": "close", 
    "Content-Length": "201", 
    "Content-Type": "multipart/form-data; boundary=----WebKitFormBoundarysSTdzdLs9E6oVCz0", 
    "Cookie": "km_ai=hb9iwazFI3WzkVlvNCCiDgDxxH4%3D; _ga=GA1.2.1540532211.1444282899; kvcd=1444283323195; km_vs=1; km_lv=1444283323; km_uq=; mp_88b82fb04df34ce696ed11f104901795_mixpanel=%7B%22distinct_id%22%3A%20%2215045f8206b50-0623da2ee-34627807-fa000-15045f8206c61%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%2C%22%24search_engine%22%3A%20%22google%22%7D", 
    "Dnt": "1", 
    "Host": "127.0.0.1:8000", 
    "Origin": "chrome-extension://aejoelaoggembcahagimdiliamlcdmfm", 
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36", 
    "X-Firephp-Version": "0.0.6"
  }, 
  "json": null, 
  "origin": "127.0.0.1", 
  "url": "http://127.0.0.1:8000/post"
}
```

**Comment by abhijitkane** [comment]
@arawind There's an issue with file uploads through the Interceptor which we'll be fixing soon.

**Comment by jemshit** [comment]
I was getting error as well. I was overwriting field `Content_Type` in Header like this: `Content-Type: multipart/form-data`. Then i removed it from Header and i think Postman auto created content type, so it started to work.

**Comment by sunshineo** [comment]
+1 I cannot believe this does not work. I have a simple curl for upload files which works, but I just cannot do the same in Postman.

**Comment by sankety** [comment]
Facing the same issue in which I am able to upload file using CURL but not through postman.

**Comment by mrbarletta** [comment]
Solved doing what @jemshit said

**Comment by tamjd1** [comment]
Solved doing what @jemshit said as well.

**Comment by marky04** [comment]
Solved doing what @jemshit said

**Comment by reduxdj** [comment]
The problem for me is the UI file needs to be removed, and replaced, or it stops working.

**Comment by xeviscc** [comment]
Still having the same problem!

Check the screenshoots, in the Headers in the bottom says it sent Content-Type "text/xml"
Headers:
![image](https://cloud.githubusercontent.com/assets/10829055/19974550/1f4e989a-a1e9-11e6-96b5-2b9d71d31424.png)
Body:
![image](https://cloud.githubusercontent.com/assets/10829055/19974560/2972d606-a1e9-11e6-9832-20102c6f60fc.png)

**Comment by sdnts** [comment]
@xeviscc The headers your screenshots show are actually the response headers. Is your file not being sent at all?

**Comment by xeviscc** [comment]
You are right, I did not notice it at the moment I posted the screenshoots.
And you are right also about the file. It is notsent at all, I check the code  (ie: cur) and it is not referenced.

**Comment by jamesdixon** [comment]
@jemshit's fix worked for me. cheers!

**Comment by shivamjain03** [comment]
It does not work for me with any of the above mentioned solutions.
I do not have any interceptor in my code. Find attached screenshots.
The request do not work with postman client but works fine with Advance Rest Client(chrome extension)

Seems like Advance rest client tool automatically adds the necessary details with the request while postman doesn't.  
The details in ARC are :
accept: application/json
content-type: multipart/form-data; boundary=----WebKitFormBoundaryLH8o2JqfnQGkh9xq
authorization: ASI_CLIENT client_id=481ddeb7 client_secret=732359d3acfb476964f58e1b4e8ee54f
content-length: 63485
------WebKitFormBoundaryLH8o2JqfnQGkh9xq
Content-Disposition: form-data; name="fileUpload"; filename="example.pdf"
Content-Type: application/pdf

I also tried the same request with CURL tool but gives the same error.
Please let me know in case you have any solution for this. Thanks in advance 

![multipart2](https://cloud.githubusercontent.com/assets/24459407/21017843/b9be7748-bd90-11e6-9361-fb23e9afe198.png)
![multipart1](https://cloud.githubusercontent.com/assets/24459407/21017853/c2834d22-bd90-11e6-89a5-0f1ffaf7872e.png)

**Comment by drorlupu** [comment]
This seems to be broken in Postman 4.9.0 and fixed in 4.9.2

**Comment by stevemcmillen** [comment]
Yup. I'm on postman 4.9.3 and its been a few weeks since I used this API but now seems that Content-Length is not added to the request.  Specifically if Body is "binary" then POSTMan not adding Content-Length as it should.  

Note: As workaround, get the curl command from postman and where it has -d '', change to -d '@<path to your file>'

**Comment by stevemcmillen** [comment]
I'm running Version 4.10.2 and its still not working.  It does work in the Chrome POSTMan App but since Chrome app is being deprecated I hope this bug can be fixed soon. This is a blocking issue for uploading files thru our APIs since we have a few that just use binary data method.

I'll log a more specific bug here: https://github.com/postmanlabs/postman-app-support/issues/2756

**Comment by ghost** [comment]
how to send jwt token and file from postman

**Comment by tmack8001** [comment]
I also am having issues getting a "binary" body via file selection working with my API backend

**Comment by shivamjain03** [comment]
You can easily upload a binary file in postman using following steps:
- Content-type should be multipart-formdata in Headers
- In body 'form-data' option should be remain as default.
- Choose 'File' option instead of 'text' from dropdown at the right side.
- Type 'File' in text box where placeholder is 'key'.
- choose your binary file to be uploaded by clicking choose files button.
- Click on send button you are in.  
Let me know in case any one still face any issue.
![postman](https://cloud.githubusercontent.com/assets/24459407/24358581/3a52416c-131f-11e7-97af-f5341209e9a9.png)

**Comment by stevemcmillen** [comment]
This would not work for our chunked upload API since it requires passing data as binary in body and thus I need to use the "binary" method for POST.

**Comment by a85** [comment]
@stevemcmillen Closing this for now but will be tracking this one that you posted. https://github.com/postmanlabs/postman-app-support/issues/2756

**Comment by OfficialKeen** [comment]
can you help me please? when i want to upload a file using postman,there are no respond from postman
![postman1](https://cloud.githubusercontent.com/assets/20989101/25564778/abfdcae0-2de4-11e7-9017-ab620e63c5f4.png)
![postman2](https://cloud.githubusercontent.com/assets/20989101/25564781/b69bc948-2de4-11e7-9e8c-9b9c24163683.png)

**Comment by Abhijitpandia** [comment]
how can i post XML data to spark server through postman

**Comment by sandeepstw** [comment]
i just wanted to upload image
i follow all above steps..but not working..
what logic should be there in controller and model for image collection

**Comment by lemonysoft** [comment]
@stw-services me too...

**Comment by sdnts** [comment]
@stw-services @lemonsoftltd The image upload logic you're talking about would need to go in your server, so I'm afraid I won't be able to help there.

@OfficialKeen Looks like a response was received, but it isn't what you expect, can you check your server to make sure everything is in place there?

**Comment by sanojqa** [comment]
I need to pass request as json format with file and need to upload file using Postman. The file is in my local system. We can pass it as form-data but how can we mention the file path in json format?

**Comment by thg303** [comment]
@sanojqa json does not support binary format data (like binary files). you have 2 options:
1- change the request type to "multipart/form-data"
2- convert file to base64 and send it in a field, caution: it can increase the size of transmission up to 30%.

**Comment by Athu5477** [comment]
@**thg303**   does we can apply request as json file to upload file in jmeter?

Can u pls help me to resolve issue mentioned below.
I  have to perform file upload with parameters in jmeter ,using patch method.But i am unable to do fileupload with patch method.Its not working for jmeter. I have send data in parameters table and put file in file upload table. After that i am getting the response as below

{"status":"FAILURE","errors":[{"message":{"loan_app_uuid":["This field is required."],"document_type":["This field is required."],"borrower_uuid":["This field is required."],"document_file":["No file was submitted."],"document_category":["This field is required."]},"error_code":"INVALID_INPUT","http_code":400}],"results":""}

Data is not accepting from parameters table. But when i am keeping this data in body data,i cant put file need to upload in file upload table. I just put data in body as json format.After that data is accepting. But file is not accepting.Getting error as below.

{"status":"FAILURE","errors":[{"message":{"document_file":["The submitted data was not a file. Check the encoding type on the form."]},"error_code":"INVALID_INPUT","http_code":400}],"results":""}

Here only the issue is file should send in file format. Please help me to resolve this issue.

My body data is as follows.

{
"loan_app_uuid": "a1727dba1e5544c9a16274d351ca6ef6",
"borrower_uuid": "5a8e6fc0c3884434a7d483adafe7cd65",
"document_category":"10",
"document_type":"1011",
"source_name":"1st Source Bank",
"primary_account_number":"4444",
"statement_date":"2/4/2018",
"document_file":""Application/pdf"
}

**Comment by thg303** [comment]
welcome to github @Athu5477 
fyi, this is not how github works, we discuss issues about this repository (postman) not Jmeter or anything else. Jmeter has it's own documentation and issue tracker (see [jemeter.apache.org](http://jmeter.apache.org)). 
you may ask this question in [stackoverflow.com](http://stackoverflow.com) or [jmeter's mailing list](https://jmeter.apache.org/mail.html). 
Good luck.

**Comment by manreet185** [comment]
Hi all, I am able to upload a file. However, it shows me the wrong name in my portal. 
For eg: I am uploading a file(test.txt) to portal. It says 200ok in response. When i see on my portal, it shows default.txt. However, it works perfectly fine using curl. Can anyone please explain how to populate correct name using postman.
Although , "Name" key is added in header with correct name of the file.

**Comment by todinesh13** [comment]
jh
