### ISSUE TITLE
Raw body JSON number 25.00 renders as JSON number 25 in Pretty view

### ISSUE THREAD

**Issue by tlovett-rmn** [a85/POSTMan-Chrome-Extension#1465]
Decimal numbers are rendering differently in the Raw view of the response body than they are in the Pretty view. I kept trying to figure out why my `BigDecimal`s we're serializing as I expected until I realized it was Postman changing the scale. I would expect to see the same number formatting in each view.

Raw (and Preview) Body view:

```
{
  "foo" : 25.00
}
```

Pretty Body view:

``` json
{
  "foo": 25
}
```

My installation:

```
Version 3.0.17 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64
```

**Comment by tlovett-rmn** [comment]
Looks like it may be the case that there is no difference between 25 and 25.00 by the JSON spec. So this may be a nice-to-have rather than a bug.

**Comment by zikolach** [comment]
I noticed even more strange behaviour. Float numbers are rendered as objects in Pretty mode. E.g. `"latitude":48.20838051106268` is rendered as
```
"latitude": {
        "s": 1,
        "e": 1,
        "c": [
          4,
          8,
          2,
          0,
          8,
          3,
          8,
          0,
          5,
          1,
          1,
          0,
          6,
          2,
          6,
          8
        ]
      }
```

**Comment by loesak** [comment]
+1. we're seen the same issue as @zikolach has reported

**Comment by jamesaspence** [comment]
I hate to do the dreaded +1 here but, since this hasn't been updated in a very long time, I feel the need to. I would expect that postman's pretty view would send the exact same format through as the raw JSON, and this completely surprised me when I noticed this behavior.

I would argue that, despite JSON not seeing a difference between 1.5 and 1.50, for example, postman should nonetheless retain exact format across both tabs. Maybe that's a very difficult technical task, I'm not sure, but regardless I think it's more important than just nice-to-have. For now I'll be using the raw view.

**Comment by luke-hill** [comment]
As a +1 also, I'll just add I spent a good hour diagnosing what was the problem. Until I found a few of these links. This affects numbers both big and small - But for some reason doesn't seem to affect integers, just floats

**Comment by codenirvana** [comment]
This is fixed in our Canary channel: https://www.getpostman.com/downloads/canary

**Comment by kamalaknn** [comment]
This should be fixed in the latest version of Postman App. Please update your app and give it a try.

**Comment by jorgelaranjo** [comment]
Still present on v10.14.3
Raw show the same as `Pretty` thus of no use.

### CURL result
```
        "a": 12345678.91,
        "b": 123.45,
        "c": 1234567,
        "d": 123456789.45,
        "e": 123456.78,
        "f": 0
```

### Postman
```
        "a": 1.234567891E7,
        "b": 123.45,
        "c": 1234567.0,
        "d": 1.2345678945E8,
        "e": 123456.78,
        "f": 0.0
```
