### ISSUE TITLE
no window at all. only taskbar icon.

### ISSUE THREAD

**Issue by JohnTube** [a85/POSTMan-Chrome-Extension#1508]
v3.0.24 on chrome 45.0.2454.101m suddenly stopped displaying PostMan window, only taskbar icon is visible. 
Windows 7 sp1 64bits. 

Any idea how to fix this? as chrome restart, system restart and postman app re-install did not fix it.

**Comment by abhijitkane** [comment]
We haven't had this reported before. Were you able to run the earlier version of Postman?
Try going to https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en and clicking "Launch App"

**Comment by JohnTube** [comment]
Unfortunately nothing happens except icon showing up in taskbar.
Same thing when I want to start it from Chrome App Launcher or chrome://apps/ tab

I hope this helps from chrome://indexeddb-internals/
![image](https://cloud.githubusercontent.com/assets/1917890/10520727/ac673a3a-7363-11e5-9655-9e06155479fc.png)
It does not disappear even after extension removal.
"Loading..." text does not disappear.
"Force close" does nothing also.

**Comment by abhijitkane** [comment]
Do you see any other instances of Postman listed in chrome:/extensions?

You can try removing the app from chrome:/extensions, removing the folders listed in your screenshot, and then reinstalling the app.

**Comment by JohnTube** [comment]
Fixed after deleting that folder and re-installing the extension.
Thanks for your help
I hope I could provide any details to help you find what's caused this.

**Comment by abhijitkane** [comment]
Sure. We'll try installing Postman on a similar setup and see if we can reproduce the issue.
Chrome does behave erratically from time-to-time, though :)

**Comment by banderson501** [comment]
I am having this same problem right now. I will try the steps listed above but there is a likely a bug in Postman. I just moved from using two monitors to one so it probably thinks I still have a second monitor and is displaying it where it was. A close and restart of the app did not fix it.

**Comment by JohnTube** [comment]
The number of monitors was not the cause of the bug in my case. But I remember I thought about using Windows UI tools like Spy++, Inspect, etc. to check if the window is present but displayed "out of screen borders".

**Comment by abhijitkane** [comment]
@banderson501 What version of Postman are you using?

**Comment by JohnTube** [comment]
Version 3.1.1 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by mbirtwistle** [comment]
On Windows 10, hold down SHIFT and right-click the task bar icon. A Maximise option then appears which allows you to restore the UI

**Comment by shobhitvaish** [comment]
@mbirtwistle You are genius!

**Comment by gauravsars** [comment]
@mbirtwistle thank you

**Comment by ziplarson** [comment]
GENIUS : On Windows 10, hold down SHIFT and right-click the task bar icon. A Maximise option then appears which allows you to restore the UI.:)

**Comment by noman404** [comment]
@mbirtwistle thanks for the tips :)

**Comment by letaoana** [comment]
Thanks @mbirtwistle

**Comment by onurarpapay** [comment]
@mbirtwistle I was sure that there was a shortcut to bring up the oldstyle "window menu". Thank you @mbirtwistle
