### ISSUE TITLE
Collection Runner hangs

### ISSUE THREAD

**Issue by StevenBlair123** [a85/POSTMan-Chrome-Extension#1549]
Version 3.1.3
Confirmed this did not work on 3.1.2 but as soon as we upgraded to 3.1.3 we hit this problem
1. Click Runner
2. Choose a Collection
3. Press Start Test Run
4. Spinning icon keeps running and no test results are returned.

We have confirmed the collection works when we run each one individually.
If we add a breakpoint to the server, we can see if it being fired when we run Collection Runner.

**Comment by a85** [comment]
@StevenBlair123 Just confirmed this. We'll push a fix asap.

**Comment by abhijitkane** [comment]
@StevenBlair123 We've pushed a fix for this in v3.1.4 of the app. You can upgrade by going to chrome:/extensions, enabling 'Developer Mode', and clicking 'Update extensions now'.

**Comment by StevenBlair123** [comment]
Updated to 3.1.4 but still appear to have the same problem.
Tried it on two different PC's.

**Comment by abhijitkane** [comment]
@StevenBlair123 Can you check the console of the collection runner for any errors when you start the run? (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/)

**Comment by StevenBlair123** [comment]
OK, I think I see the problem.

Here is the console output:

Object {collection_id: "66372e70-b03f-01d8-0b4d-e998f26bac3d", folder_id: 0, target_type: "collection", environment_id: "0", delay: 0â€¦}
[]
POST http://%7B%7Burl%7D%7D/api/producthierarchies net::ERR_NAME_NOT_RESOLVED

The URL is being fed from a environment variable, so in POSTMAN, it looks like this:

{{url}}/api/producthierarchies

If I run the POST outside the Collection Runner, it works.
Also, if I remove the variable, and put the URL in, the Collction Runner appears to work.

**Comment by abhijitkane** [comment]
Are you selecting the environment in the collection runner's 'Environment' dropdown?

**Comment by StevenBlair123** [comment]
omg no.
I didn't realise there was a separate environment setting in the Collection Runner.
Looks to be working now, thanks.
