### ISSUE TITLE
Right-click on items in Collection?

### ISSUE THREAD

**Issue by z3ntu** [a85/POSTMan-Chrome-Extension#1582]
It would be great if you could right-click on an item in the "Collections" view to bring up the context menu. The triple-points button on the right side can disappear if the name is too long. Basically it is still there but it does not get shown.

**Comment by cebor** [comment]
:+1:

**Comment by aditikul** [comment]
We've fixed the bug which made the triple points button disappear if the request name was long. Are you still facing this issue? Please let me know which version you are using. The context menu appearing on right click is a good idea, we will take this into consideration for future updates. Thanks!

**Comment by z3ntu** [comment]
@aditikul I have just tested it, right click is still not working, but the triple dots don't disappear when there is a long name. Closed as there isn't really a need for right-click anymore?

**Comment by aditikul** [comment]
@z3ntu Good to know that the bug with long names is fixed for you, thanks. We can keep this open for now as there are other use cases for a right click context menu. We can take it up on a long term basis though as a feature request. Thanks!

**Comment by vegetableman** [comment]
@z3ntu Assuming you are using the native app, could you update to the latest version which supports right click context menu. Let me know if that doesn't solve your use-case.
