### ISSUE TITLE
Team collection owner name is not updated with profile change

### ISSUE THREAD

**Issue by Gutbuster** [a85/POSTMan-Chrome-Extension#1666]
When sharing a collection with your team, a change in users name is not reflected in the listing. I encountered this after changing my own user name, but the old one still appears in the shared collections. 

This occurs even with completely new collections that have been created after the profile was changed.

**Comment by abhijitkane** [comment]
@Gutbuster We've updated the names for all users. Future changes in the user's name should reflect in the shared collections. Can you confirm the fix?

**Comment by Gutbuster** [comment]
The username has been changed to the users actual name. Which is also fine in my books. But out of curiosity, was there some technical issue why the "Username" field was not utilized? Or simply a design choice?
- Verified the updated name is shown on shared collections. 
- Attempted changing the actual name in profile, and verified that this is reflected in the shared collections.

I consider this issue fixed.

**Comment by abhijitkane** [comment]
Not using the username was a design choice. Usernames are unique, and you cannot change your username to anything you like. The 'name' field in the profile is something that has no restrictions.

**Comment by Gutbuster** [comment]
After the postman was updated, the issue has re-appeared. The old user name is once again shown as the owner of a collection.

**Comment by abhijitkane** [comment]
@Gutbuster That was a regression in the app. Should be fixed now.

**Comment by Gutbuster** [comment]
@abhijitkane Issue still persists. Verified with version 4.2.1.
