### ISSUE TITLE
POSTMAN does GET request when POST is selected

### ISSUE THREAD

**Issue by riscie** [a85/POSTMan-Chrome-Extension#1687]
Hi there

I think there is an issue with POSTMAN sending a GET request when POST is selected in a specific case. Here is how to reproduce. 
- We use a simple simple http server. I wrote mine in go (golang). See here https://play.golang.org/p/EGLcSTjLa9 
- I register only one route to the server which is `/test/` notice the trailing slash!
- When I now do a **POST** request with POSTMAN to `/test` (notice: no trailing slash!) my webserver tells me, that there was a request and the method which was used is **GET**.
- If I do a **POST** request to `/test/` (with the trailing slash) everything works as expected.

In my opinion, sending requests to /test should not hit the server at all, because this URL is not registered. Also when I do the same with curl (`curl -X POST http://localhost:8080/test`) my server does not answer at all, which is what I would suspect. 

Is there a specific reason to this behaviour?

Thank you 
Ris

**Comment by abhijitkane** [comment]
This might be due to the fact that the first endpoint is returning a 301/302 response code. Chrome's API then makes a GET call to the new location. (This process is not visible to Postman)

To confirm, you can enable DevTools (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/), and head to the Network tab. Check the 'Preserve Log' option, and send your request. If you see two requests  (one to `/test`, one to `/test/`), that probably means that the server is returning a redirect.

**Comment by riscie** [comment]
You are right. I just tested it. I get a `301 Moved Permanently` first, then the 200 from `/test/` . This is from my server, right? So probably a non-issue. Was just confusing to me.
You say this process is not visible to Postman which means, there is no way to make this more transparent in the app, right?

**Comment by abhijitkane** [comment]
No, but there's a way to block the second request from being sent. You'll need to install Postman Interceptor - https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en, uncheck the 'Automatically follow redirects' setting in Postman, and toggle the Interceptor on in Postman (satellite icon in the top bar)

**Comment by ghost** [comment]
duplicates #1490

**Comment by judgej** [comment]
Just had this, scratching my head for ages. Turned out the URL I was using was [inadvertently] `http` and the server was redirecting to `https`. Postman was not making this redirect even slightly transparent.

**Comment by mrenoe** [comment]
@judgej this comment just resolved hours of debugging. Thanks for posting this and yes please Postman make this slightly more obvious.

**Comment by VonTalavang** [comment]
posts stills as gets

**Comment by judgej** [comment]
I'm using the console window a lot more these days to see what is happening on the wire (or close to the wire). That highlights redirects a lot more obviously.

**Comment by suntrop** [comment]
I have got the problem. I can't do a POST request. There is no https, trailing slash or other redirect happening. Postman ist the only app with a problem. I testes in Do Http and PhpStorm and both work fine.

**Comment by sanekyy** [comment]
same problem

**Comment by w5m** [comment]
Removing a trailing slash from my Postman test URL resolved it for me.

**Comment by Adriano-luis** [comment]
@w5m Thanks man. Removing a trailing slash from my Postman test URL resolved it for me too.

**Comment by lucian-grey** [comment]
@judgej still relevant today and saved me hours of head scratching. For others facing same issue, open up the console and check if you see any Get requests being made to the same url but with **https://**example.com/example. If so, just make sure to add https:// infront of your api url link when you're posting it

**Comment by evgenipetrov9** [comment]
Had the same issue today, not sure why this is closed

**Comment by lucian-grey** [comment]
Hey,

Make sure its https:// instead of http or it will revert to get automatically. Hope this helps!

Thank you, Lucas

**Comment by hamzanaveed7861** [comment]
It might be you are ignoring https://. Adding https:// resolved this issue for me.

**Comment by glendza** [comment]
still happens

**Comment by bladefistx2** [comment]
Still an issue! 
when switching to GET/PATCH/DELETE etc. I can see the "--request GET" being added to the curl on the side bar, but when I choose POST it disappears completely.

setting https:// did NOT solve it.
removing/adding trailing slash did NOT solve it 

anyway these are not solutions and postman should fix this error popping up every other version...!
a reinstall of postman was the only thing that worked for me. EDIT - the issue is back!

**Comment by AnasSiddiqui18** [comment]
> Just had this, scratching my head for ages. Turned out the URL I was using was [inadvertently] `http` and the server was redirecting to `https`. Postman was not making this redirect even slightly transparent.

Thank you very much you saved my day. I just deployed my traditional nodejs server on railway deployment, and when i am testing the endpoints so when performing **POST** because i am not adding the https protocol the **POST** request is treated as **GET**.

**Comment by bladefistx2** [comment]
another solution is to select wget instead of curl. enjoy

**Comment by raunaksinghjolly** [comment]
Still facing this issue..., none of the above solutions working.

**Comment by daniel-myparcel** [comment]
> Just had this, scratching my head for ages. Turned out the URL I was using was [inadvertently] `http` and the server was redirecting to `https`. Postman was not making this redirect even slightly transparent.

Dude you are a legend!!! thank you

**Comment by VesperQuartz** [comment]
It's not postman fault
