### ISSUE TITLE
Postman is double encoding query parameters using OAuth 1.0

### ISSUE THREAD

**Issue by evanpurkhiser** [a85/POSTMan-Chrome-Extension#1869]
As far as I can tell, postman is _not_ decoding parameters before normalizing them when it follows the [3.4.1.3.2.  Parameters Normalization](https://tools.ietf.org/html/rfc5849#section-3.4.1.3.2) step of OAuth. This causes the parameters to be encoded _twice_.

The spec does specifically state that the query parameters should be decoded before they are passed along to be normalized: [3.4.1.3.1.  Parameter Sources](https://tools.ietf.org/html/rfc5849#section-3.4.1.3.1).

> The query component of the HTTP request URI as defined by
> [RFC3986], Section 3.4.  The query component is parsed into a list
> of name/value pairs by treating it as an
> "application/x-www-form-urlencoded" string, separating the names
> and values and decoding them as defined by
> [W3C.REC-html40-19980424], Section 17.13.4.

So any URL that has percent encoded values inside the query parameters will fail to generate a correct signature.

**Comment by abhijitkane** [comment]
@EvanPurkhiser Thanks for reporting this. We'll investigate and try to push a fix ASAP.

**Comment by abhijitkane** [comment]
@EvanPurkhiser We'll be pushing a fix in the next release.

**Comment by evanpurkhiser** [comment]
Thank you @abhijitkane

**Comment by abhijitkane** [comment]
@EvanPurkhiser can you confirm this fixed in the latest version?

**Comment by evanpurkhiser** [comment]
Will confirm this coming week. Thank you @abhijitkane !

**Comment by weiwanning** [comment]
This bug is still happening to me, I am on 4.10.5 the mac app.
Appear to work when I url decode once.

**Comment by onacit** [comment]
Am I O.K. to see this in July-2024?

**Comment by MrShemek** [comment]
Same for me (Oauth 2), I'm using 12.9.7 version:

```
Version 12.9.7
UI Version: 12.9.7-ui-260508-0231
Desktop Platform Version: 12.9.7 (12.9.7)
```

i.e. for scopes, `accounts:read companies:read` is turned into `scope=accounts%253Aread%2520companies%253Aread`. Same issue with `redirect_uri`. Can this be checked and addressed? 🙏🏼 

----

**Update: it was an issue on Cloudfront side on my end, no fix for Postman needed. Sorry for the trouble!**
