### ISSUE TITLE
Postman Echo - Delete Cookies Tests Fail

### ISSUE THREAD

**Issue by jfeltis** [a85/POSTMan-Chrome-Extension#2191]
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Both
3. OS details: OS X 10.11.6
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Not sure
6. Expected behaviour: Tests pass
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
8. Screenshots (if applicable)

1. Run Postman Echo > Cookies > Set Cookies
2. Run Postman Echo > Cookies > Delete Cookies
3. View Tests on Response

The tests exists as follows:

```
tests["Body contains cookie foo1"] = ('foo1' in responseJSON.cookies);
tests["Body does not contain cookie foo2"] = !('foo2' in responseJSON.cookies);
```

However, they should read as:

```
tests["Body does not contain cookie foo1"] = !('foo1' in responseJSON.cookies);
tests["Body contains cookie foo2"] = ('foo2' in responseJSON.cookies);
```

...because the API call is to `.../cookies/delete?foo1`.

The existing tests would pass if the call was to `.../cookies/delete?foo2`.

**Comment by shamasis** [comment]
Fixed. :-) Thanks for reporting.

**Comment by Yardglass** [comment]
This is still not quite right. The tests pass now, but the names are wrong:

    tests["Body contains cookie foo2"] = !('foo2' in responseJSON.cookies);
    tests["Body does not contain cookie foo2"] = !('foo1' in responseJSON.cookies);

Should be:

    tests["Body does not contain cookie foo1"] = !('foo1' in responseJSON.cookies);
    tests["Body does not contain cookie foo2"] = !('foo2' in responseJSON.cookies);
