### ISSUE TITLE
Mac app v4.5 get file dialog to save response body instead of displaying in Body tab when response Content-Type=*/*

### ISSUE THREAD

**Issue by stormposse** [a85/POSTMan-Chrome-Extension#2221]
1. Postman Version: 4.5.0
2. App (Chrome app or Mac app): Mac
3. OS details: Yosemeite 10.10.5
4. Is the Interceptor on and enabled in the app: n
5. Did you encounter this recently, or has this bug always been there: just now after 4.5.0 install
6. Expected behaviour: expect to see response body in Body tab of response section, not a download dialog
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   requester.js:461 Resource interpreted as Document but transferred with MIME type _/_: "data:_/_;base64, PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxiaWxsaW5nLWRldGFpbHMtcmVmPjM5YmE5NDBmLTRmMDEtNDhjYy1hZDIxLTFlMzBlN2RjOTA2NDwvYmlsbGluZy1kZXRhaWxzLXJlZj4=".insertChildAt @ requester.js:461processUpdates @ requester.js:525dangerouslyProcessChildrenUpdates @ requester.js:2251processQueue @ requester.js:13981updateChildren @ requester.js:14155_updateDOMChildren @ requester.js:11525updateComponent @ requester.js:11354receiveComponent @ requester.js:11299receiveComponent @ requester.js:5568_updateRenderedComponent @ requester.js:7542_performComponentUpdate @ requester.js:7524updateComponent @ requester.js:7453performUpdateIfNecessary @ requester.js:7401performUpdateIfNecessary @ requester.js:5583runBatchedUpdates @ requester.js:6163perform @ requester.js:6620perform @ requester.js:6620perform @ requester.js:6120flushBatchedUpdates @ requester.js:6181closeAll @ requester.js:6686perform @ requester.js:6633batchedUpdates @ requester.js:10644enqueueUpdate @ requester.js:6210enqueueUpdate @ requester.js:5796enqueueSetState @ requester.js:5962ReactComponent.setState @ requester.js:15789handleModelChange @ requester.js:192946triggerEvents @ requester.js:45976triggerApi @ requester.js:45961eventsApi @ requester.js:45760Events.trigger @ requester.js:45951set @ requester.js:46121test @ requester.js:238598apply @ /Applications/Postman.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:54(anonymous function) @ /Applications/Postman.app/Contents/Resources/electron.asar/renderer/api/remote.js:243emitThree @ events.js:116emit @ events.js:194
8. Screenshots (if applicable)

SEEMS to happen when you do a POST request that returns a response with Content-Type=*/* header. Does not happen when the response Content-Type is, say, application/xml or application/json.

I can't see an option to turn this behaviour off.

**Comment by danielmcq** [comment]
I am having the same issue.
1. Postman Version: 4.5.0
2. App (Chrome app or Mac app): Mac
3. OS details: El Capitan 10.11.6
4. Is the Interceptor on and enabled in the app: ?
5. Did you encounter this recently, or has this bug always been there: After upgrading to 4.5.0
6. Expected behavior: Expect to see response body in Body tab of response section, not a download dialog

One thing that is different for me than what @stormposse reports is my content type is `application/jwt`. Also, I have a test script which saves the response body to an environment variable. This still seems to work even when canceling the save dialog.

**Comment by shamasis** [comment]
This should be resolved now. Closing. Please reopen if otherwise.

**Comment by danielmcq** [comment]
I'm still getting the same problem in 4.6.1 for the Mac app. Will this fix appear in an upcoming version?

**Comment by shamasis** [comment]
What's your content type?

**Comment by danielmcq** [comment]
application/jwt

**Comment by shamasis** [comment]
@numaanashraf 👆🏼

**Comment by cobear25** [comment]
Please re-open this, it's super annoying.

**Comment by sdnts** [comment]
@danielmcq @stormposse Can you guys try updating to the latest version (4.7.2) and confirm if the problem is resolved?

**Comment by danielmcq** [comment]
For me, Postman 4.7.2, Mac, when POSTing and the response's Content-Type is "application/jwt", or "application/jwt; charset=utf-8", it correctly outputs the response in the Body tab, instead of prompting to save a file. This is what I desired. Thanks!

By the way, is there any way this can be configurable? Either by choosing which Content-Types are treated as files, or by disabling the file save prompt all together?

**Comment by sdnts** [comment]
@danielmcq As of now, no. But that's a good idea, I'll look around to check if this is possible!
