### ISSUE TITLE
Mac Postman App v4.7.0 Using loopback adapter instead of proper IP address. 

### ISSUE THREAD

**Issue by nbcarey** [a85/POSTMan-Chrome-Extension#2314]
**Problem:** The Mac Postman App v4.7.0 appears to be trying to connect to the loopback adapter (127.0.0.1) for all URLs. Hitting the same url with `curl(1)` or in a web browser succeeds normally. Note that the Mac Postman App was working fine prior to upgrading to 4.7.0.

These environment variables are set:

```
http_proxy=http://webproxysea.nordstrom.net:8181
https_proxy=http://webproxysea.nordstrom.net:8181
no_proxy=local,localhost,127.0.0.1,nordstrom.net,dev.nordstrom.com,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
```
1. Postman Version: 4.7.0
2. App (Chrome app or Mac app): Mac
3. OS details: OS X v10.11.5 (El Capitan)
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Just today. Immediately after upgrading to v4.7.0 of the Mac Postman App
6. Expected behaviour:
   
   ```
   * Hitting a DNS name should resolve to the correct IP address.
   * Hitting an IP address directly should ... hit that IP address
   ```
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   
   ```
    ================================================================
        o
      (/) P O S T M A N
      ^
   
      Go to View -> Show Postman Console to check your script logs. 
   
   ================================================================
   🌏 sync service connectivity initiated
   socket replaying queued commands
   🌏 connected to sync service.
   🐶 watchdog checking connection health
   🐶 watchdog checking connection health
   ```
8. Screenshots (if applicable)

![image](https://cloud.githubusercontent.com/assets/6518145/18292712/88556e1e-7443-11e6-8d1c-1c4a90fdf4a7.png)

![image](https://cloud.githubusercontent.com/assets/6518145/18292553/b912bec2-7442-11e6-8a4e-3d0aeff4850f.png)

- Upgrade your Mac Postman App to 4.7.0
- Attempt to `GET` the domain name `github.com`
- Note the error
- Open the Postman console and note the more detailed error message:
  
  Error: connect ECONNREFUSED 127.0.0.1:80
- Open a terminal window and run the command `dig github.com` to resolve Github's IP address: `192.30.253.112`
- Repeat the above steps, replacing `github.com` with its IP address.
- Note that the error is the same: it is still trying to connect to the loopback adapter at 127.0.0.1

**Comment by v0ltair3** [comment]
+1

I'm facing the exact same problem... any workaround available ??? Shall I downgrade ?

**Comment by SamvelRaja** [comment]
@nbcarey  @v0ltair3  Thanks for taking this to our notice. There is bug related to the proxy protocol handling which is causing the issue.
Appending the protocol manually to the proxy server host should ideally solve this issue.

![proy_issue_resolution](https://cloud.githubusercontent.com/assets/5114052/18312532/db8343b0-7527-11e6-8cd5-825d0179d6f0.gif)

**Comment by turchinc** [comment]
I am seeing a similar issue but AFAIK am not using a proxy. My problem is with localhost and with the new Windows App v.4.7.0.  (downloaded from https://dl.pstmn.io/download/latest/win?arch=64) is not working.

Windows App:
![image](https://cloud.githubusercontent.com/assets/645266/18391148/4d1e6ece-76ad-11e6-8b5d-088bc6f21f2e.png)
Chrome Extension:
![image](https://cloud.githubusercontent.com/assets/645266/18391174/652dd8a6-76ad-11e6-9bf1-1df0a420bb99.png)

Interestingly, the HTTPS endpoint for the same localhost address is working fine in the Windows App:
![image](https://cloud.githubusercontent.com/assets/645266/18391254/a67dbf42-76ad-11e6-8155-c426793f96e6.png)

**Comment by joelaw1** [comment]
I have the same problem as the OP but I cannot apply the referenced fix due to auto proxy configuration and corporate pac file policies.

**Comment by nbcarey** [comment]
Same here. Our proxy configuration is...interesting. Or something :)

**Comment by joelaw1** [comment]
The v4.7.1 update resolved this issue on my workstation.   Thanks!

**Comment by nbcarey** [comment]
v4.7.1 seems to have fixed  my problem as well. Thanks!

**Comment by SamvelRaja** [comment]
@turchinc @v0ltair3  The issue has been fixed in the `4.7.1` kindly check from your end.

**Comment by turchinc** [comment]
I can confirm this. Thanks.

**Comment by shankie-codes** [comment]
Humm. I'm on 4.8 and am still having this problem – and am not using a proxy. I am however using DNSMasq for local development. Anyone else had a similar problem?
