### ISSUE TITLE
Postman opens off screen(s) when display monitors are changed

### ISSUE THREAD

**Issue by schellem** [a85/POSTMan-Chrome-Extension#2833]
V4.10.3 running on win 8.1, I opened Postman this morning and the app was not visible but has tray icon, tried again and get another tray icon. Can't switch to them, I opened my docked laptop to see if it was showing up on that screen and it's not.

**I actually can't use Postman now as I can't get to it**. I'm guessing the last time I opened POSTMAN was at home with laptop not docked and using a different monitor configuration.

At the office I use a dock with 2 monitors and laptop closed at home I run with laptop screen and a single HDMI connected monitor.

**Comment by schellem** [comment]
Finally figured out how to get it back onscreen. Hover over the Postman tray icon, right click the running instance and select Move, then use arrow keys to try and find it.

**Comment by sdnts** [comment]
@schellem We'll definitely look into this, thanks for letting us know!

**Comment by hnoe-c7ks7s** [comment]
The suggested fix didn't work for me (Windows 10) when Postman is pinned to the taskbar, so I can't select 'move'. Right click only shows 'unpin from task bar' or 'close window'. I had to unpin it to see the running session before I could recenter it to my screen. I was using a single monitor hooked up to a Dell docking station and now I'm just using the laptop screen (and checked that I was only projecting to the laptop)

**Comment by mvaneijk** [comment]
I also ran into this issue on Windows 10 after unplugging my second monitor from my laptop.

@hnoe-c7ks7s  A workaround is to click the running instance in the taskbar. Press [Alt]+[Space], [M] and use the arrow keys to get it back into your main window.

**Comment by slowwit** [comment]
Hello,
This has also occurred on my system Windows 7 Service pack 1 64bit. 
 I enjoy the product.  Thank you
If I was a better program I would help, but at least I can offer praise.
Postman
Version 5.0.2
win / x86-64
Chrome 59.0.3071.115

**Comment by PaulRobson85** [comment]
Just had this issue also after unplugging my laptop from a dock with dual monitors in Windows 10 64 bit. Postman was not open at the time, but I assume saved its position from the last time I was using it. 

Strangely the windows snap shortcuts did not work (winkey + -->) 

Work around "Press [Alt]+[Space], [M] and use the arrow keys to get it back into your main window." did the job for me.

After the work around, windows snap shortcuts went back to working as per normal.

**Comment by schellem** [comment]
Just learned the same issue occurs with the Console Window. I went to use it today and nothing happened after diffing around a bit I realized it's open but not where I can see it.

**Comment by rotherfuchs** [comment]
Same issue on Mac OSX Sierra.

**Comment by sdnts** [comment]
For the moment, if you guys see this, you can reset the app's window settings manually. To do this, you'll need to delete the `requester.json` file from the app's data directory, this is located:

on macOS: ~/Library/Application\ Support/Postman
on Windows: C:\Users\<your_user_id>\AppData\Roaming\Postman
on Linux: ~/.config/Postman

For the runner & console, the files are called `runner.json` and `console.json` respectively. Deleting these will reset window placement preferences

We'll take this up soon so the manual step isn't needed.

**Comment by slowwit** [comment]
Thanks Sinha!
FYI no one should be confused but just in case , an update....

_on Windows: C:\Users\your_user_id\AppData\Roaming\Postman_

**Comment by stdunbar** [comment]
Problem still exists in 5.3.2 on Windows 10.

**Comment by rodrigodata** [comment]
> stdunbar commented 2 days ago
> Problem still exists in 5.3.2 on Windows 10.

+1

**Comment by landonvg** [comment]
Same problem in Window 7 with v5.3.2.

**Comment by WinBlue** [comment]
Problem exists with v5.3.2 on Windows 10.

**Comment by centur** [comment]
5.4.1 on windows 10 - still exists =( Also subscribing to the thread to see when it's resolved.

Alt+Space, then M and arrows help, though. Thanks for the hint @PaulRobson85 , was missing that feature after Win8 menus changed.

**Comment by dayan2** [comment]
Just hold your moves in the Postman tab in the taskbar, when small pop-up appears, right click on it and Maximize it. This works for windows 10.

**Comment by sethb43** [comment]
Its late but...
@hnoe-c7ks7s, you have to hover over the postman icon on the task bar until the preview window comes up then right click on the preview window.  The alt+control+m solution that PaulRobson85 gave is a keyboard shortcut that does the same thing.

Still exists on v5.5.0 + windows 10 for me

**Comment by samuel-ye** [comment]
encounter the postman window missing problem in Mac, where width and height are strangely set to 0 in requester.json. after modify them manually to normal size, the window is back.

**Comment by kbalint** [comment]
happening with v5.5.2, on Remote Desktop too (remote machine has 2 monitors, RD has one window)

**Comment by gabrielamboss** [comment]
Happens to me whenever I closed it on my top monitor. y coordinate on requester.json would appear as -1173, which was too high for postman to be dragged back down. Modifying the value temporarily solved the issue, until I moved the window and closed it again.

In the end I edited the y coordinate to a reasonable value and set the file to be read-only. This workaround worked.

**Comment by pmmcmullen** [comment]
I just had this issue with my laptop. I typically use a second monitor while at work but I came home to work on it again and it opened off screen. The Shift + Right Click -> Move option worked when I hit the arrow keys.

**Comment by sdnts** [comment]
This is now fixed in our internal builds. We'll be rolling out the update soon :)

**Comment by FabiusChiang** [comment]
so frustrated under win10; thanks to he solution "Alt+Space then M"!

**Comment by kobidadon1** [comment]
must be a pain to debug this lol, unplugging the monitor every time

**Comment by jdege** [comment]
I'm still seeing this in 6.0.7.

**Comment by joseanand** [comment]
Same issue happened for me and I tried to click shift button then minimize and then tried to maximize the same.  This worked for me.

**Comment by Gavin-McFall** [comment]
This issue happens to me all the time on macOS Sierra 10.12.6

**Comment by dheerajopensource** [comment]
its a real nightmare...switching to advance rest...bye bye Postman

**Comment by govindrai** [comment]
Happening on MacOS Sierra 10.13.4 (17E199). Not working even after deleting requester.json.

**Comment by dsimoes** [comment]
Happening to me(Windows 10 1734). Updated to latest version. Nothing I do brings back the Postman screen! help anyone?!

**Comment by govindrai** [comment]
Just open up a new window. Then switch to the other hidden window, close it using cmd/ctrl w. Now just use the new window.

Thank you,
Govind Rai

**Comment by thecuriousdev** [comment]
Looking into this issue, I am able to reproduce this in windows but not in MacOS. @govindrai @Gavin-McFall since you are mac users can you please help me with these questions,
1. Can you confirm whether you are using a multi monitor setup?
2. Can you provide steps to reproduce this issue?

**Comment by thecuriousdev** [comment]
@dsimoes can you help me with these things,
1. Are you using a multi monitor setup?
2. If so you put the postman window in a non main screen? and its `position x` was `0` or the window was maximized?

**Comment by dsimoes** [comment]
@thecuriousdev 

I do use sec. monitor @office (right side).
I was latter at home and got the off-screen issue. I plugged in my sec. monitor @home (Top side, not right) to try to recover the window but no luck.

Eventually what I did to fix it was:
1) Rename the Postman dir on appdata
2) Started up Postman to re-generate my settings
3) Restored my original appdata Postman dir, but used the "window" and "requester.json" files from the working dir.

Now it's working ok. I don't remember the position x before I replaced the files.

When I have a bit more time I can try to replicate this behavior.

thanks.

**Comment by thecuriousdev** [comment]
@dsimoes thanks for the help :) do you remember whether Postman was maximized (or it was in the left most corner of the screen) in your office monitor?

**Comment by dsimoes** [comment]
@thecuriousdev Maximized.

**Comment by kobidadon1** [comment]
Hi Guys,

I noticed this issue also happens to me with the YouTube independent window, so maybe it could be a chrome thing?
It's not happening anymore with postman but with the youtube, it's every time I log in&out of my user.
3 screens setup.

**Comment by govindrai** [comment]
Yes; I had a multi monitor setup. Unfortunately; I don’t know how to reproduce. It has only happened to me once so far.

Thank you,
Govind Rai

**Comment by centur** [comment]
@govindrai I found that it happens with some other electron apps quite often in the scenario when one has different monitors setup and custom arrangements in office and at home (typical with laptop users):
E.g my work setup was like this:
![image](https://user-images.githubusercontent.com/720822/42978498-79dd9276-8c10-11e8-95f1-d32c20b31e1f.png)
Where 
- solid line - laptop with 4k screen
- dotted lines - 2x 1080p dell monitors, one of them is vertical.

while at home I have simpler setup:
![image](https://user-images.githubusercontent.com/720822/42978533-b8e7164a-8c10-11e8-8d23-5cae6fd78c0b.png)
Where 
- solid line - same laptop with 4k screen
- dotted line - 1x acer monitor with resolution >1080p


Windows 10 can play quite nicely with different monitors and different scales per monitor, but apps that remember their position often go haywire when you close app on one setup when it's on external monitor with scaling 200% and try to reopen it on another setup where monitor has different scale settings and orientation\coordinates.

Is it possible to make a setting which will disable window location being saved and will open postman app on main screen, maximized?  I think this would mitigate the magnitude of this problem.

**Comment by thecuriousdev** [comment]
Really appreciates your help and feedbacks :) We made a fix for this in our internal builds which prevent this from happening. Will make it available to everyone soon, I'll keep you posted here. Stay tuned!

**Comment by vladovarga** [comment]
v6.2.3 + win 10 stil hapening

**Comment by andyjjones1** [comment]
Still happening for me.  Windows 10.
Postman for Chrome, Version 5.5.3, win / x86-64, Chrome 68.0.3440.106.

It could only be solved by pressing [Alt+Space] and then *clicking* maximize by hand instead of pressing any keys.  My postman came back after that.

**Comment by m3dbedb** [comment]
Same happens on win 7 sp1 32 bit. <del>On version  6.2.3 I didn't notice the bug</del>, but found it on 6.2.4 with single monitor configuration. Window manipulation have no effect. In my case halps closing and opening the app again, all data is stored.
The bug found in 6.2.5. Screen goes black as far as I select another tab and press "Send". Fastest way to reproduse: launch Developer tools (current view).
Number of monitors and windows desktop scale (100 and 125) doesn't matter.
Currently I have to use chrome version 5.5.3 <del>and portable one.</del> Portable 6.1.4-6.2.4 have the same issue
<details>
  <summary>Click to view picture</summary>
  Picture in the middle of...
    ---
  ![post](https://user-images.githubusercontent.com/25632818/44655577-5c4ae680-a9fe-11e8-823e-4e257203d618.jpg)
  ---
  ...a collapsible block
</details>

**Comment by hi2uday** [comment]
Close the postman and remove requester.json file under - C:\Users\your_user_id\AppData\Roaming\Postman should resolve the problem in windows 10.

**Comment by m3dbedb** [comment]
Win 7 32 6.5.2 still the same issue, RDP, intel video on host PC, radeon on terminal. Looks like it happens depend on amount of opened collections or there are some collections that works good and other that cause the bug. Note that I launch the app this way: C:\Users\gagarin\AppData\Local\Postman\app-6.5.2\Postman.exe --disable-gpu and POSTMAN_DISABLE_GPU parameter is set "true".
**UPDATE**
Same bug in Postman 6.7.1 for windows 32

**Comment by m3dbedb** [comment]
The issue still present in postman 7.0.6 under windows 7 32

**Comment by Jiasm** [comment]
> For the moment, if you guys see this, you can reset the app's window settings manually. To do this, you'll need to delete the `requester.json` file from the app's data directory, this is located:
> 
> on macOS: ~/Library/Application\ Support/Postman
> on Windows: C:\Users<your_user_id>\AppData\Roaming\Postman
> on Linux: ~/.config/Postman
> 
> For the runner & console, the files are called `runner.json` and `console.json` respectively. Deleting these will reset window placement preferences
> 
> We'll take this up soon so the manual step isn't needed.

In fact, you also need to delete the `window` file in the same directory.

**Comment by ankurdengla** [comment]
@schellem @hnoe-c7ks7s @mvaneijk @PaulRobson85 @slowwit @gabrielamboss @dsimoes @pmmcmullen94 @andyjjones1 

We were able to reproduce the issue in the following case (on Windows only) -
- Open Postman on external monitor (unmaximized).
- Minimize the app.
- Unplug the external monitor.
- Restore the app from the taskbar. It opened off-screen.

This case has been fixed in the latest version (Postman 7.0.9). Please verify this. Also, if you are still facing the issue on 7.0.9, can you please share the exact steps for reproducing this issue?

**Comment by dsimoes** [comment]
@ankurdengla1996 

Reproduction confirmed.
Upgraded to 7.0.9. Fix confirmed.

Thanks!

**Comment by m3dbedb** [comment]
I have the issue under windows 7 32 bit in ponstman 7.0.9

**Comment by ankurdengla** [comment]
Hey @m3dbedb, Can you please describe your exact issue and give us the steps for reproducing it?

**Comment by m3dbedb** [comment]
I have windows 7 32 bit, video card is intel hd graphics 2000. I have an issue with latest postman **7.0.9**. I open postman and open several tests (usually 10-20  jumps) from my collection, after that postman window became black. Running postman with key _C:\Users\user\AppData\Local\Postman\app-7.0.9\Postman.exe --disable-gpu_ and setting system parameter **POSTMAN_DISABLE_GPU** to **true** doesn't help.

**Comment by numaanashraf** [comment]
@m3dbedb Are you facing any issues with Postman windows opening off-screen when multiple monitors are used?

**Comment by numaanashraf** [comment]
We have addressed all known and reproducible issues on thread and are closing this particular issue for now. Do let us know if you are still facing issues with Postman's window positioning when working with multiple monitor.

**Comment by GiorgioAresu** [comment]
Happened to me on OS X 10.14.6 with Postman v7.3.4. Had to use it fullscreen to be able to see the window. Now that I found this thread I solved this way:
- close postman
- delete the requester.json
- open postman (issue remains)
- from the menu, File->New Postman Window (this one shows)
- from the menu, Window->Postman (you should see two, click the one without a checkmark)
- from the menu, File->Close Window

Now you should be back to only one, visible, window

**Comment by zax761** [comment]
This has been here for so long and it's so annoying. Could you try to fix this?

**Comment by magnusfoldager** [comment]
Just encountered this issue as well. 
Solved by navigating to `~/Library/Application\ Support/Postman` and deleting `window` (renaming it first to be safe)

**Comment by BryceMindLab** [comment]
> Just encountered this issue as well.
> Solved by navigating to `~/Library/Application\ Support/Postman` and deleting `window` (renaming it first to be safe)

Thanks @magnusfoldager, this fixed the problem for me on **OSX v10.14.6, Postman v7.6.0**

**Comment by lostdev** [comment]
It happened to me today as well. I had to use the workarounds proposed above, but this happens all the time when I remote into my computer, which converts my 3 screens into one.

**Comment by jbgrunewald** [comment]
I just experienced this today. Mac OS Catalina 10.15.1, Postman Version 7.13.0

**Comment by al265** [comment]
Just encountered this problem when I added two more monitors. I'm running Windows 10, Postman v7.14.0.

**Comment by asbarron** [comment]
On Mac OS I ran into this issue and had to remove the file `window` from` ~/Library/Application\ Support/Postman` to resolve.

**Comment by lilstar132** [comment]
Still happening on Windows 10 Pro 1809 with two monitors one over the other.
Managed to solve the issue by using Right Click>Move>Arrow Keys.
Postman v7.19.1

**Comment by alivcor** [comment]
On Windows, **delete** the following file : `C:\Users\<username>\AppData\Roaming\Postman\window`

**Comment by vreemt** [comment]
I got it back by hovering over the icon in the taskbar, right clicking on the preview and then using `Move` with arrow keys. 

My config means using Windows/Alt key combinations won't work, as I'm using the app in a Remote Desktop session and those keys are sent to the local system.

I managed to misplace the window by dragging it up. I'd already lost the menu bar, and the next time I started the app it was off screen altogether. (The off screening can also have been caused by my multiple monitor set up, though I'd already moved half the app off the usable desktop area before then). In my case, I knew the window was somewhere above the top, so I just moved it down until it appeared. The `Move` option disappears when the window is Maximised, so you may need to `Restore` first.

I'm using an old version: Win 10, Postman for Chrome, Version 5.5.5, win / x86-64, Chrome 81.0.4044.138

**Comment by arlemi** [comment]
@vreemt We're tracking issues related to the Chrome app there https://github.com/postmanlabs/postman-chrome-extension-legacy but are not actively maintaining it, you should use the Windows app instead https://www.postman.com/downloads/.

**Comment by conterio** [comment]
i'm having this issue.  disconnected my laptop from my duel monitors and postman is out of screen, I even reset.  I hope I don't have to connect to my doc again just to get postman app front and center.  the window + left or right keys are not moving the application

**Comment by arlemi** [comment]
@conterio Can you try the recommendations here to move the window back to the main screen? https://www.howtogeek.com/howto/windows/bring-misplaced-off-screen-windows-back-to-your-desktop-keyboard-trick/

**Comment by lalitver10** [comment]
> Win 7 32 6.5.2 still the same issue, RDP, intel video on host PC, radeon on terminal. Looks like it happens depend on amount of opened collections or there are some collections that works good and other that cause the bug. Note that I launch the app this way: C:\Users\gagarin\AppData\Local\Postman\app-6.5.2\Postman.exe --disable-gpu and POSTMAN_DISABLE_GPU parameter is set "true".
> **UPDATE**
> Same bug in Postman 6.7.1 for windows 32

**Comment by alikrc** [comment]
same here, why this bug closed?

**Comment by ibajrami** [comment]
Still happening in November 2021. Opened Postman on my second monitor at work and was unable to get it back on my screen when I got back home, I solved it by plugging a second monitor and move it back to the main screen and then unplug the second monitor.

**Comment by cooperthompson** [comment]
I've been able to work around this by deleting the "window" file from C:\Users\%USERNAME%\AppData\Roaming\Postman, then restarting Postman.

**Comment by howdagee** [comment]
I was facing this issue this morning as well. I was able to right click the preview and used the arrow keys to get it back in place.

Once Postman came into view I saw an update page indicating that Postman has been updated to 9.4.0.  Looks like it is either happening on the latest version or was stuck from previous version and I assume it only updated when I tried to close Postman in an attempt to get Postman on the main screen.

Windows 10 64bit Thinkpad
2 external monitors connected via USB C port to hub.

**Comment by RaisinTen** [comment]
Hey folks, could y'all please test out the latest Postman version (v9.16.x) and let us know if this is still an outstanding issue?

**Comment by dsanders11** [comment]
This should be fixed from Postman version v9.16.0 and onwards, so we're going to go ahead and close this issue. Please comment (and feel free to ping me) if you're still seeing this, with a description of your setup. Thanks!

**Comment by gwsampso** [comment]
Cant move in Postman v9.18.1

**Comment by ozzybasch** [comment]
@dsanders11 @sdnts @schellem Currently, it's happening in my system. The Postman is already up-to-date. I'm using the latest Windows 11 updates. Tried to fix it as mentioned above _(by deleting the window file from AppData)_ but didn't work. I think this issue should be open, as it affects my work and productivity. 
Can you please help me on this for the permanent solution?  Thank you all.

**Comment by wurayan** [comment]
This just happened to me, I have two monitors and didn't change any configuration, I literally just opened a chrome window to search for something and when I came back to postman it was "outside" of my visible screen.
None of the above solutions did anything for me.
If I press F11, I can use Postman in full screen, but I really prefer not to use it that way.
