### ISSUE TITLE
Cookies aren't persisted

### ISSUE THREAD

**Issue by decadence** [a85/POSTMan-Chrome-Extension#2913]
I have problems with cookies.
I make request to PHP site (Laravel 5.4) and can see 2 cookies in Response section, but they don't appear in Manage Cookies window and therefore Postman doesn't send them in next request.
Interesting thing is that site on Laravel 5.2 works ok.

Version/App Information:
 1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Windows Native App
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: I don't know because today is first day of using Postman
 6. Expected behaviour: I expect that cookies are saved between requests.
 7. Console logs
 8. Screenshots (if applicable)
![screenshot_2](https://cloud.githubusercontent.com/assets/1434668/24760126/5ca4f010-1af0-11e7-9b9e-90994ec7f9b0.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/1434668/24760125/5c982434-1af0-11e7-93f5-405b7e055d8a.png)

Steps to reproduce the problem: this site is local so I don't know how you can reproduce it.

**Comment by sijones-uk** [comment]
I'm having the same problem (also using Laravel 5.4). Cookies are missing from the Manage Cookies window. I had to revert back to an earlier version of Postman where this is working.

**Comment by decadence** [comment]
@sijones-uk glad to hear I'm not the only one with this case and this is real bug and isn't my mistake.

**Comment by kamalaknn** [comment]
Hey, we are trying to reproduce this issue. Could you attach a screenshot of the Postman Console, so we can have a look at the `set-cookie` headers to investigate better?

**Comment by decadence** [comment]
@kamalaknn
You can confirm this bug with request to https://laracasts.com/ (I think it's using latest Laravel version).
It sends 3 cookies but only one present in Manage Cookies.

**Comment by decadence** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/1434668/24793836/2f2d1116-1b8c-11e7-8605-e2f89ceb6e73.png)
Maybe problem with cookie length because it has very long value.
I can't even see all set-cookie string.

**Comment by kamalaknn** [comment]
@Decadence Thanks for the link. We could see the behaviour. 

We will work on a fix for this. I will update this thread once we have it.

**Comment by decadence** [comment]
@kamalaknn thanks!

**Comment by sijones-uk** [comment]
@kamalaknn Was this issue fixed in the 4.10.6 release to fix #2885, or is this a separate. as-yet-unfixed issue?

**Comment by kamalaknn** [comment]
@sijones-uk this appears to be a different. The fix for #2885 makes sure cookies set for wildcard subdomains are listed properly by Postman. If that is your use case, then 4.10.6 will have everything you need.

We will get a fix for this issue out soon.

**Comment by sijones-uk** [comment]
@kamalaknn has this issue been fixed now?

**Comment by kamalaknn** [comment]
Hey, @sijones-uk we just pushed a few cookie related fixes in `5.1.2` version of the app. Could you update your app to the latest version and let us know if it still exists?

**Comment by sijones-uk** [comment]
Do you mean 5.0.2? That's the version I get when I download it from your website.

**Comment by kamalaknn** [comment]
@sijones-uk 5.1.2 is our latest version.

Could you try now? The newer versions take some time to propagate through our caches.

**Comment by decadence** [comment]
@kamalaknn I tried 5.1.2 version and seems like issue is resolved. I was able to login on Laravel 5.4 site using Postman. You can close this if there are no other problems.

**Comment by kamalaknn** [comment]
@decadence That's great.

@sijones-uk I'm marking this issue as resolved. Feel free to revive this thread if you are still seeing this.

**Comment by marcelomelodf** [comment]
Still seeing this in Postman v5.5.0. Both in Windows and MacOS. Can not set a Cookie value, only the default value is persisted.
