### ISSUE TITLE
Response body preview doesn't update on subsequent requests w/o response body

### ISSUE THREAD

**Issue by qmcree** [a85/POSTMan-Chrome-Extension#2950]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Mac
 3. OS details: Mac OS 10.12.3
 4. Is the Interceptor on and enabled in the app: N/A
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: Response body in preview tab should be blank on subsequent requests when the response body is empty.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): None
 8. Screenshots (if applicable) 

1. Select "Body" > "Preview" tab in response section.
2. Make a request that responds with status "417 Unprocessible Entity" and a JSON response body.
3. In the same request, make a request that responds with status "200 OK" and an empty response body. Notice how the response body from the first request is still shown.

**Comment by poisa** [comment]
I just came here to report this but you already beat me to it. Started happening with the latest version.

**Comment by wilsonandcompany** [comment]
Infrequently, I am able to repro even if subsequent response has a body. OSX 10.9.5, Postman 4.10.7 native app.

**Comment by qmcree** [comment]
@wilsonandcompany I can confirm this as well. When it occurs, the only way to see the correct data in the "Preview" tab is to click another tab like "Raw" and then click "Preview" again.

**Comment by kamalaknn** [comment]
Hi, 

We can confirm that this is a bug in the latest version. We will roll out a fix for this in the next version.

Until then changing the response body type once will make sure that the response body is updated.

This shouldn't be happening though and will be fixed as soon as possible.

I will update here once the fix is out.

**Comment by numaanashraf** [comment]
@qmcree @wilsonandcompany @poisa This is fixed in v.4.11.0.

**Comment by wilsonandcompany** [comment]
@numaanashraf Thanks

**Comment by qmcree** [comment]
Thanks @numaanashraf and @kamalaknn!

**Comment by timworx** [comment]
There may have been a regression. 
Version 6.4.4 (6.4.4) on High Sierra seems to exhibit this.

1. Make a request that returns an HTML page (in this case it a 404 Django debug error page)
2. Subsequent request succeeds with a 201 and no response.
3. Preview still has the HTML page (causing me to think that I haven't fixed my routes).

**Comment by kamalaknn** [comment]
Hey,

We were able to reproduce this. We will push out a fix for this in the next release.

**Comment by timworx** [comment]
> Hey,
> 
> We were able to reproduce this. We will push out a fix for this in the next release.

Jeez @kamalaknn , that was quick! 💥

**Comment by kamalaknn** [comment]
Hey @timworx 

We've pushed the fix for this on our [Canary channel](https://www.getpostman.com/canary). The fix has also been pushed to the stable channel. We will open the rollout over the coming week.

**Comment by kamalaknn** [comment]
This fix has been rolled out to the stable channel. Please update and let us know if you continue to face this.

**Comment by imranhassangithub** [comment]
I am using v6.7.1. #5400 still not reflecting any change for 204 response

**Comment by sujayvenaik** [comment]
@imranhassangithub 
I tried replicating this by spinning up a local server that returns 204 response but could not replicate.

Can you send a screen recording of the scenario where you encountered this so we could debug this?
Or a public API where we can reproduce this?

**Comment by ereztdev** [comment]
@kamalaknn this issue should be re-opened.
This is still happening in your latest version which installs the desktop version (0.2.2) that uses the browser.

**Comment by ereztdev** [comment]
This morning, the response is changing on subsequent trials + JSON is now being folded, thanks.
