### ISSUE TITLE
Feature Request: Add ability to document a raw body request

### ISSUE THREAD

**Issue by CosmicBara** [a85/POSTMan-Chrome-Extension#3117]
I noticed that the latest version of the Postman app for Windows includes support for documenting the request parameters, headers, and the body. However, it seems only the form-data and x-www-form-urlencoded types are supported for documentation. Is it in the pipeline to support documenting of the raw request body? I know JSON does not support comments by default, but if you guys provided some way to provide documentation so we can explain what each parameter in the JSON object represents, that would be super useful.

**Comment by a85** [comment]
@GunslingerBara You can use the request body markdown to do this. We support tables too so you can document JSON structures. I'd love to hear suggestions on how to document JSON objects. :)

**Comment by CosmicBara** [comment]
@a85 What exactly do you mean by "request body markdown"? Is there a page in the Postman documentation that details this, or an example you can share?

**Comment by sdnts** [comment]
Hi @GunslingerBara You should be able to document Raw bodies in the Request's description. We'll look into supporting docs for raw body as well.

**Comment by a85** [comment]
@GunslingerBara Have a look at our docs: https:https://www.getpostman.com/docs/postman/api_documentation/how_to_document_using_markdown

**Comment by govindrai** [comment]
@madebysid Shouldn't this be open? I know we can use the description section and markdown for documenting raw body, but it's cumbersome and I know it would make the documenter that much powerful.

**Comment by govindrai** [comment]
@a85 one idea is to simply mirror what you have for form-data and x-www-form-urlencoded in addition to being able to type out raw bodies. It would be even better if you could determine from the JSON or XML structures nested fields and autopopulate the key column. That would be ideal.

**Comment by a85** [comment]
@govindrai We have a new data editor in works that will allow for this but we might have some work to do on the data structure. I'll reopen this.

**Comment by aichholzer** [comment]
While you can add descriptions to `form-data` parameters, there is no way to do the same for `JSON` request bodies. Also, the markdown editor seems like a hack around this. Parameter or body descriptions should be consistent and handled by Postman in a similar way.

Any further progress with this?

**Comment by Sutty100** [comment]
+1 on an update!

This is a blocker for us using postman pro as we can not document our API's request/response JSON models to the same level that we can with swagger

**Comment by lukaswelte** [comment]
+1 
I would love to have the ability to document JSON APIs using Postman. In order to do that I need to make explicit how the schema for my request and my response looks like (what fields are required, which are optional and what are potential values like e.g. the values of the enum).

Would be awesome to be able to define a schema (name & describe required fields) for request JSON data as well as the response.
This schema could then even be integrated with the tests to check this same schema there.

Would be great to resolve that blocker which keeps us away from integrating Postman into the process in our company.

**Comment by reid3290** [comment]
+1 Not able to comment on raw json request is really not a good idea.

**Comment by Sridatta19** [comment]
+1 Hope this feature arrives soon

**Comment by eranhazout** [comment]
+6 (we are a team ;) Required fields should be very useful

**Comment by pmilanez** [comment]
+2 👍 this will be a game changer

**Comment by steeveroucaute** [comment]
+1 not being able to comment and properly document a JSON payload is a blocker for me. Swagger has data models which is way more useful to document complex objects.

**Comment by markus-ethur** [comment]
+1  Agree totaly, we should have some kind of comments

**Comment by kausality** [comment]
+1

This is one of the reasons I had to rescind our published API docs from Postman back to Swagger.

**Comment by eiyiaioyou** [comment]
+1

**Comment by CosmicBara** [comment]
It will soon be a year since I made this suggestion, and I haven't seen any feedback on potentially implementing this feature. Throughout this past year, I've received emails consistently from people +1 or showing their support. Can Postman devs please provide an official response as to whether or not they will implement this request?

**Comment by djly** [comment]
+1, as we use json body for all our requests, I might have to start looking for another solution. Was really hoping postman would support this.

**Comment by kheengz** [comment]
Wish this Feature Request: **Add ability to define required/optional fields/headers and field types** will be added soon

**Comment by armyofda12mnkeys** [comment]
I agree, would be great to allow comments (even if you had to 'opt into' this feature [via a checkbox in the Request Area] on the specific Request that would be fine).

Sometimes I want comments to describe that param,
or to suggest alternate values to copy/paste to test,
or maybe quickly comment out a param or a group of params when testing our web services.

@a85 saw you self-assigned to this yourself. Does that mean its officially being looked at to implement ?
Do you think it will be coded so you can use regular single-line comment // and block-style /* */ coding comments within the JSON Body?

**Comment by bt-dd** [comment]
+1 As others have brought up, this would be an extremely useful feature, hopefully it will eventually be added to Postman!

**Comment by fireice009** [comment]
+1. Especially now support for publishing documents. We use it for API document.

**Comment by bj97301** [comment]
help yo

**Comment by Sirsksk** [comment]
Hi!
I'm trying to document a raw-XML body... I don't know if there is a solution for that.. yet just asking :)

**Comment by mehdichati** [comment]
+1 , for this feature , for any assumed professional API (required/ optional) input field is mandatory.

thanks for your help.

**Comment by AxonDivisionDev** [comment]
This should be a huge priority, ability to visual showcase the validity of a field quickly is incredibly important. The entire logic of a program can be shifted based on whether an attribute exists or not.

**Comment by eriadam** [comment]
@a85 @vkaegis Any update from you guys would be much appreciated.

**Comment by mikecousins** [comment]
Any idea if this will be improved shortly? Our company is about to make our purchasing decision and this will weigh heavily on it. Thanks.

**Comment by vkaegis** [comment]
No ETA on this yet. This is a huge priority for us as well, but we have some prerequisites to be taken care of.

**Comment by abes-dabir** [comment]
+1

**Comment by ray-kay** [comment]
+1 @a85 any update/timeline on this? I am new to global IT consultant company (16k employees) and I would like to establish Postman as dev. documentation tool #1 but not to being able to document individual fields in a JSON BODY request/response like to you can in swagger is big blocker.

thanks

**Comment by mcelhennyi** [comment]
+1 this is needed big time!

**Comment by kevinohara80** [comment]
FWIW, this is preventing our team from moving to Postman Pro and we're looking at Swagger Hub instead. We'd much rather use Postman!!! 

😔

**Comment by adrianovcar** [comment]
+1

**Comment by w3b5urf3r** [comment]
+1. I don't see why this is not happening yet!! first post on 6 Jun 2017 !

**Comment by Almesia** [comment]
+1

**Comment by Hrafnkellos** [comment]
+1

**Comment by jordanebelanger** [comment]
Make it happen already, it's not an hard feature to add and would make documenting using postman requests ACTUALLY possible :)

**Comment by rorykoehler** [comment]
+1 Not having this feature makes Postman practically unusable

**Comment by AxonDivisionDev** [comment]
Working with JSON:API and a dev team where we really need this feature. Our workaround is to leave raw attributes empty if nullable types, obviously not ideal nor is it explicit 👎

**Comment by valentim-guilherme** [comment]
+1 waiting for this feature for years!

**Comment by dchurchland** [comment]
+1 Documenting JSON body is the difference between my team using or not using Postman.  Here am I hoping we get to use it...

**Comment by bheddens** [comment]
Would love to see the ability to document JSON body raw, otherwise, documentation looks clunky in the description.

**Comment by loris** [comment]
+1 this is currently blocking our enterprise from moving their api documentations to Postman

**Comment by aaronn** [comment]
+1– was choosing between Postman and Swagger and was kind of shocked this wasn't supported. We need the ability to document what kinds of fields are going to be required or optional, and stuffing them into `form-data` doesn't feel like a good way to do this.

**Comment by abhisekp** [comment]
The editor may use [JSON5](https://json5.org/) to support comments in the json. :rocket:

**EDIT**: I tried to use code markdown in request description.

### In Postman (while editing)
**Code Highlighting**
![Code Highlighting](http://pix.toile-libre.org/upload/original/1556628926.png)

### In Postman (in view mode)
**No Code Highlight**
![No Code Highlight](http://pix.toile-libre.org/upload/original/1556628993.png)

### In Postman Documention online
**No Code Highlight**
![No Code Highlight](http://pix.toile-libre.org/upload/original/1556629093.png)

**Comment by lukaswelte** [comment]
That is nice :) 
But sadly not comparable to schema which contains information like type and if optional or not (and can be read by a machine instead of a human reading the comments)

**Comment by loris** [comment]
I also think that JSON comments is not the best solution.
Would be better to have a real JSON editor like Postman have for simple key/value dictionnary (headers, parameters, etc) but with added support for nesting and complex values.
Have a look at the plist editor from XCode :

![Screenshot 2019-04-30 at 17 39 14](https://user-images.githubusercontent.com/8362/56974436-22bf1200-6b6f-11e9-86c8-a9c8ddb18765.png)

**Comment by mikecousins** [comment]
Is that for the request or the response or both? Also, I'm going to have to agree with the others that having a couple actual columns (type, optional, comment, etc) would be great.

**Comment by loris** [comment]
@mikecousins for the request, to be able to describe the JSON payload: description, default value, required or not etc
And have these information displayed in the API documentation of course

**Comment by mikecousins** [comment]
We need the response documented similarly as well or this is still useless.

**Comment by bj97301** [comment]
@vkaegis Any update on this?  The without this the docs are near useless.  With this, the docs will be very useful.

**Comment by a85** [comment]
Thank you for your feedback everyone. I’d love to hear some ideas on how to solve for response bodies of all kinds and not just JSON. We see APIs that return XML/plaintext/JSON along with different data models being used to build those data models. If everybody just used JSON then the world would be a simpler place and we could launch this feature asap.

**Comment by mikecousins** [comment]
JSON seems like what 95% of APIs use these days isn't it?

**Comment by a85** [comment]
Our most popular blog post is for SOAP APIs. And well GraphQL APIs are different still.

**Comment by mikecousins** [comment]
SOAP makes me sad.

**Comment by bj97301** [comment]
@a85 Start with the most popular one(json) and try not get overwhelmed by shittiness of soap and xml.  Not sure what the best solution is but a quick one would be to right click the field and be able to add a comment/description.  Or maybe support json5 with comments.  🤷🏿‍♂️

**Comment by RomuloVHSYS** [comment]
> That is nice :)
> But sadly not comparable to schema which contains information like type and if optional or not (and can be read by a machine instead of a human reading the comments)

@lukaswelte I agree with that, so i'm watching this issue #2847 too, both looks like different issues that can be solved with the same feature.

**Comment by RomuloVHSYS** [comment]
Recently i'm seeing how are the struct of the collections(the .json files), and i found the property `"disabled": true`, my first try to use optional parameters was disabling the parameters, so they don't get appended on the URL, but appear on private doc, but when published they don't appear anymore, so why not use the same `disable` property to show 'not required' parameters on the doc?
 
That way the doc is going to work like on the private version, it's not the perfect solution, but can suit the needs of many users here.

**Comment by a85** [comment]
Everyone, this is part of a much larger initiative but we are introducing the ability to define APIs in Postman using schemas. You will be able to document schemas for both requests and responses using whatever format you typically use. Postman will then take this as another input in generating docs, building mocks, or adding tests. It looks like this: 

<img width="1552" alt="Screenshot 2019-04-30 14 02 13" src="https://user-images.githubusercontent.com/653409/56995066-8d635400-6b55-11e9-9720-0888d91e4e82.png">

Along with this, we will be introducing "annotations" for collections as well as schemas soon so you will be able to annotate parts of your request/responses.

We'd love your feedback!

**Comment by RomuloVHSYS** [comment]
Awesome! But i got a question:

> Along with this, we will be introducing "annotations" for collections as well as schemas soon so you will be able to annotate parts of your request/responses.

@a85 , with "annotations" will we be able to set optative/required parameters?

**Comment by loris** [comment]
@a85 awesome, great direction you are taking here. Do you have any approximate release date to communicate on this feature already?

**Comment by a85** [comment]
@RomuloVHSYS Annotations, Schemas, and Required/Optional parameters are independent features.

@loris Thank you! This will start rolling out in May.

**Comment by aaronn** [comment]
@a85 is there any way to join the API tab beta?

**Comment by jsavagecommercialpeople** [comment]
Do you know when the Schema functionality will be released as I just upgraded and I can't see it? This will be really useful for us right now so want to understand when we will be able to do it.

**Comment by a85** [comment]
The feature is rolling out in production now in 7.1. Integration of schemas with generated docs is not done yet but we are working on it.

**Comment by RomuloVHSYS** [comment]
@a85 There is a documentation for how to use this new feature?

**Comment by a85** [comment]
Yes. Still early and we'll be refining it but you can find docs here: https://learning.getpostman.com/docs/postman/design_and_develop_apis/introduction_to_apis/

**Comment by RomuloVHSYS** [comment]
After exploring this new feature a while, i think it don't fits on what this issue requests, that is show raw body on the [postman documentation](https://learning.getpostman.com/docs/postman/api_documentation/intro_to_api_documentation/) properly documented.
If the idea is use the schemas for generating docs(what is working well), so docs should accept all properties that this schemas are using, like `type` `format` `required` and others

Even so, it's a really great addition to the postman, and i think that it's the right way

**Comment by OpeOnikute** [comment]
+1

**Comment by RomuloVHSYS** [comment]
Ayn news? 

My enterprise is about to release some new products and will only purchase the postman enterprise if the documentation can show the request properties without append then to the url, it's so simple..

Required/Optional it's just a way to do that

**Comment by tony-tao-accolade** [comment]
Would like this feature as well.

**Comment by kirill-kostenetskyi** [comment]
@a85 Do you have any new estimations when this will roll up? 
Thanks

**Comment by OMA2k** [comment]
I can't believe this issue was raised more than 2 years ago, and still nothing has been done about it. It's as simple as adding the contents of the "Params" tab under the "Body" tab even when the "raw" radio button is selected, so the parameters of the raw request can be manually documented under the "raw" code textbox so they appear in the documentation. It's really easy to implement that. Why hasn't that been done in 2 years?

**Comment by abhisekp** [comment]
@OMA2K it is easier to document a JSON body using JSON schema.
There are various JSON schema converters available such as https://jsonschema.net/

**Comment by OMA2k** [comment]
@abhisekp : Thanks for your answer. Where can this resulting schema be added in Postman as documentation for a request?

**Comment by abhisekp** [comment]
@OMA2k The API tab in v7 helps

**Comment by OMA2k** [comment]
@abhisekp : But the API tab means building a new completely separate project from a regular collection, doesn't it? Isn't there any other way?

**Comment by danioso** [comment]
Any solution for documenting the raw bodies?

**Comment by jitDotBlake** [comment]
Any updates?

Suggestion: provide a comment box per JSON key (like form-data, path variables, etc.) 

Schemas are cool, but I don't believe it's what this request is about - people at #3358 would appreciate raw JSON body commenting too.

**Comment by DoveAz** [comment]
+10086

**Comment by kingwill101** [comment]
any updates?

**Comment by eyalgrossdev** [comment]
I too would like to know of any updates on this? Thinking of switching from SwaggerHub but this is a bit of a deal breaker. 😞

**Comment by rgr** [comment]
any updates ?

**Comment by sheerlox** [comment]
Just wait for it.
https://github.com/postmanlabs/postman-app-support/projects/40#card-33062537

**Comment by SyDan** [comment]
+1
Its a really crucial feature in documentation

**Comment by JayChandler** [comment]
+1

In many API documentations, a link to an external API documentation is included in the description just to describe the response and request body properly. That can't be the way to go for a tool like Postman,. Postman should be the one and only place to do all those things.

The solution is quite simple

- Provide a JSON Schema per collection ( Can be taken from OpenAPI import too )
- Allow markdown in description properties
- Allow the possibility to set request body and response body schema type per request
- Include description for request and response body in documentation
- Include schema in documentation

Tbh it would allready help if it would render it like swagger

![swagger1](https://user-images.githubusercontent.com/6359575/80345817-09c46c00-886a-11ea-8cfa-f9d8479782aa.PNG)

![swagger2](https://user-images.githubusercontent.com/6359575/80345820-0af59900-886a-11ea-9041-1b4399378fa5.PNG)

**Comment by kengleong** [comment]
+1

**Comment by shahidcodes** [comment]
+1

**Comment by JoeAlamo** [comment]
This would be really useful to have as part of the Postman **collection**.

I personally don't use Postman's API feature, because converting my OpenAPI schema into Postman API via Postman really garbled and messed up my OpenAPI Schema.

I had a far better experience using apimatic.io to convert my OpenAPI schema into a Postman collection, and then use the docs for the Postman collection.

If we were able to add extra information to the request body object in the JSON collection, which also got rendered by the docs, that would be fantastic!

**Comment by eyalgrossdev** [comment]
Any update on this?

**Comment by cheneyweb** [comment]
+1

**Comment by stcalica** [comment]
Another user is requesting this feature

**Comment by Borduhh** [comment]
Let me preface my answer with if this isn't allowed than please delete my comment.

Like many others on this thread I LOVE Postman and have been using it for a while for documenting APIs. So naturally when we started building a new JSON REST API, I recommended we use Postman to keep our API well documented. After building/documents for about 50 routes while growing a team, we've noticed some problems. The largest is that we aren't able to properly document the request body so when a new team member comes online, it's not easy to tell what parameters are required, what their type is, etc.

In a perfect world we would be able to document the following on each body parameter:

- A descriptive name
- A brief description of that parameter
- Whether that parameter is requried/optional
- An example value for that parameter
- The parameters type (i.e., string, number, object, array)

While we could just have everyone work off of an OA3 JSON spec doc, that creates another thing our interns/new employees have to learn when coming on. We'd rather a simple UI they can use to create routes at warp speed. Then as a team becomes more experienced, they would be able to export a spec doc or API documentation right from the tool.

### Proposed solution:
Postman already has the simple UI in their tool for `form-data`:
![Screen Shot 2021-03-20 at 4 54 53 AM](https://user-images.githubusercontent.com/4759596/111864640-a1c2bc80-8938-11eb-9b9f-82ff486b0e67.png)

It wouldn't be that hard to mimic this UI to add a JSON tab with the above fields at all. The only inherit issue that might arise is nested attributes (i.e, `someAttribute.child.child.child.name`). This could be solved by creating simple reusable object models like in many other tools that users could include.


### Fix for now (edit this if it's not allowed)
It pains me to actually say this, but we had to make the move to (Stoplight)[https://stoplight.io/] for now since it seems like they have all these features built in (I am not an employee or affiliate for Stoplight, just a developer that wants a tool to work).

![Screen Shot 2021-03-20 at 5 05 09 AM](https://user-images.githubusercontent.com/4759596/111864872-ed299a80-8939-11eb-8a1a-ff09f35596f3.png)

![Screen Shot 2021-03-20 at 5 05 27 AM](https://user-images.githubusercontent.com/4759596/111864873-ee5ac780-8939-11eb-9f44-541743aabee6.png)

Honestly though, I love Postman's UI so much more. PLEASE MAKE THIS HAPPEN POSTMAN so we can come back!!!

**Comment by sheerlox** [comment]
It really saddens me to see that such a mandatory feature requested by so many developers in the Postman community gets so little priority.
It will soon be 4 years since it has been requested, the solution seems pretty straightforward to implement now that every detail has been discussed here by motivated community members.
This leaves me with a bitter impression of little interest for what the community needs. Please make a move on this.

**Comment by jgarciasm** [comment]
We need that functionality in our company too. Please, don´t make us to migrate to another tool. We love Postman, but this is a crucial requirement for us.

**Comment by ckang777** [comment]
I recently had to create an external API doc and it was not fun trying to do this with markdown. Would be great if we can document JSON request/response payload as many have suggested above. Thanks!

**Comment by LucasAmoedo** [comment]
As many others have said, the absence of this functionality is the reason our company will be switching over to another tool. It is a shame, because we all like Postman better, but we are using markdown tables at this moment, which is becoming increasingly cumbersome.

**Comment by OMA2k** [comment]
Can an actual Postman developer respond to this almost 2 year old issue?

>

**Comment by therockstorm** [comment]
I've been using [oas-markdown](https://github.com/therockstorm/oas-markdown) to accomplish this. It's a CLI that takes in a resolved OpenAPI schema and outputs a schema with all request body params documented, [here's an example](https://docs.vertexvis.com/#a8f05429-036c-45b8-89ef-6bd3aa14a7fe).

<img width="805" alt="Screen Shot 2021-05-24 at 08 06 19" src="https://user-images.githubusercontent.com/1085683/119359510-f3543400-bc66-11eb-9ee7-dd4f634607b2.png">

**Comment by rymnc** [comment]
+1

**Comment by kwolfy** [comment]
+1

**Comment by Altair-Bueno** [comment]
> Manage all of your organization's APIs in Postman, with the industry's most complete API development environment.

Yet this has been open **4 years**... Definitely using another tool for my next API

**Comment by OMA2k** [comment]
> > Manage all of your organization's APIs in Postman, with the industry's most complete API development environment.
> 
> Yet this has been open **4 years**... Definitely using another tool for my next API

Suggestions for an alternative tool to Postman?

**Comment by Altair-Bueno** [comment]
> > > Manage all of your organization's APIs in Postman, with the industry's most complete API development environment.
> 
> > 
> 
> > Yet this has been open **4 years**... Definitely using another tool for my next API
> 
> 
> 
> Suggestions for an alternative tool to Postman?

From what i have seen there is a plugin for vscode that works like postman called Thunder Client. Also yesterday i found these guys https://swagger.io/tools/. I haven't tried it yet but looks promising

**Comment by govindrai** [comment]
I think the reason these guys have lagged on this is because documenting APIs has already been solved with OpenAPI. You guys should document the api using OAS (open api specification). There’s also alternatives like RAML but I suggest using OAS3.0. Postman supports importing those OAS files. 

See https://blog.postman.com/openapi-specification-postman-how-to/


You can add/update the spec within postman which is very convenient and even keep the spec up to date:

https://learning.postman.com/docs/designing-and-developing-your-api/defining-an-api/

**Comment by deemeetree** [comment]
@govindrai Not a good reason. As you can see from the issue linked to by @br-tyler-milner Postman does not display schema details in rendered API documentation. So, eventually, one has to use a different tool like swagger or StopLight.Io.

**Comment by charlesreitz** [comment]
+1

**Comment by schonhoff** [comment]
It would be nice to see Postman integrating the API Schema to the documentation site. We are using another tool just for this reason...

**Comment by petkostas** [comment]
This is definitely sad, after so many years since the initial report not having any progress, [as mentioned above](https://github.com/postmanlabs/postman-app-support/issues/3117#issuecomment-803276176) we use stoplight for defining our OpenAPI schemas and then use Postman to create collections, not being able to document request payloads is problematic and is raising questions among our development team (100+ developers) as we recently opted to adopt postman.
Suggesting using external links or manually documenting them, defies the purpose of having OAS support, as we spend most of our design effort on having proper OpenAPI specifications.
Please re-consider the priority of this issue, documenting request payloads is as important as documenting other components of a specification.

**Comment by bj97301** [comment]
> This is definitely sad, after so many years since the initial report not having any progress, [as mentioned above](https://github.com/postmanlabs/postman-app-support/issues/3117#issuecomment-803276176) we use stoplight for defining our OpenAPI schemas and then use Postman to create collections, not being able to document request payloads is problematic and is raising questions among our development team (100+ developers) as we recently opted to adopt postman.
> Suggesting using external links or manually documenting them, defies the purpose of having OAS support, as we spend most of our design effort on having proper OpenAPI specifications.
> Please re-consider the priority of this issue, documenting request payloads is as important as documenting other components of a specification.

Yup…

**Comment by brandonkirsch** [comment]
Postman prices are going up and this 5 year issue is not resolved.  Our team is making plans to drop this package because we pay good money only to be endlessly ignored.

**Comment by lougeo** [comment]
This is a requirement for the company I work for as well. OAS supports this syntax so it should be an easy lift to get something other than just raw json as the request parameter documentation. It would be great if we could get the data that we're already supplying Postman with formatted a little cleaner.

**Comment by akshaydeo** [comment]
Hi everyone, thank you for your patience. We have released support for Open API 3.0 schema documentation support in March 2022. You can learn more about [here](https://blog.postman.com/open-api-3-0-documentation/).

Let us know your feedback 🙇‍♂️

**Comment by lougeo** [comment]
This does not solve the issue. When the request parameters are query string parameters they are labelled nicely with all of the supporting information that can be provided in the OAS specification (type, and !description). However when the request parameters are body parameters, they are just formatted as a json blob. They need to be formatted the same as the query string parameters - with a description.

**Comment by petkostas** [comment]
@akshaydeo No it is not, the request body documentation is still not rendered in the collection documentation.
This is the request body under the `APIs` section of Postman (which is the expected result)
![body_schema](https://user-images.githubusercontent.com/3758537/169879109-1b9a6f58-6652-40e4-a2d8-4fed07818284.png)

And this is the request body under the `Collections` section of Postman (which is not what is expected)
![body_collection](https://user-images.githubusercontent.com/3758537/169879193-0522c34a-3438-4c59-b3f4-7dee97e82435.png)

**Comment by schonhoff** [comment]
Yep, it is still not possible to show the api documentation to a client without sharing the api. I would love to get the api documentation to the client through the collection documentation. Maybe with an extra site or something but the current state isn't even the feature that is requested here.

**Comment by jimmyn** [comment]
I have the same issue, the rendered documentation shows the raw body of the request and not the property list with the description

Generated postman documentation:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/5391775/201078978-ac6e6890-00a3-4f50-94da-1dec28cdb0c8.png">

API definition:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/5391775/201079181-67078729-bdca-45a8-ad93-d58fcf3ff096.png">

Until this is fixed, we are using a custom website to generate documentation from openapi schema

**Comment by ashutosh-betaflux** [comment]
Sad to see, @postman-support  team has not prioritise this most needed feature. 😔

**Comment by PwrSrg** [comment]
I seriously can't believe this **_STILL_** hasn't been fixed almost **6 YEARS later**.

BUT I am glad I came back here and read about **[Stoplight.io](https://stoplight.io)**! 🤩

So **thank you** Postman!  If it weren't for your incompetence, I would never have discovered your **competitor**.

Goodbye Postman... 🚀

**Comment by shashankawasthi88** [comment]
Hi All,

We're actively working on this issue and would like to understand your workflow better to design the right solution. If you want to discuss this, please drop me a note at [shashank.awasthi@postman.com](mailto:shashank.awasthi@postman.com) or set up a call with me using [this link](https://calendly.com/shashank-awasthi/typed-information-in-collections).
@PwrSrg @jimmyn @schonhoff @petkostas

**Comment by Altair-Bueno** [comment]
Switched to OpenAPI long time ago. Not using Postman anymore.

**Comment by petkostas** [comment]
Same here; additionally, since I switched companies some time ago, your recent (not so recent) [announcement](https://blog.postman.com/announcing-new-lightweight-postman-api-client/) completely blocked postman usage within the org.

**Comment by shashankawasthi88** [comment]
Hi All,

We are happy to launch [Types in Collections](https://community.postman.com/t/the-postman-drop-design-sync-and-manage-apis-without-the-switching-tax/78684#p-129904-create-error-free-api-experiences-with-type-validation-3) for all users. This gives you the ability to document raw JSON requests in Postman. Feel free to reach out to us for any feedback.

Cheers!
