### ISSUE TITLE
Runner appending = to variables in query params Mac App

### ISSUE THREAD

**Issue by martincalvert** [a85/POSTMan-Chrome-Extension#3181]
## App Details:

```
Postman for Mac
Version 5.0.0
OS X 10.12.5  / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: **I just started using the mac app but it appears to be there in 4.11.1 and 5.0.0**
 2. Expected behaviour: **When adding query parameters from a data file in the runner it should just add the exact string without any mutations/additions.**
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

```
https://image.com/api/v1/images/$$_image.png?cache=38b0c951-ea33-4753-9227-b0277cd6d57f&height=120width=160=
```

 4. Screenshots (if applicable): Not sure if they are needed.

#### Explanation

Main issue it seems on the mac app whenever you have a data value populated after a `?` in the url it appends a `=` to the end of the url. It does not happen in the chrome app. This doesn't happen in the builder but only happens in the runner. The variable does not need to be from a data file but can be an environment variable also. Example below of builder and data file.

```
https://image.com/api/v1/images/{{path}}?cache={{uuid}}&{{params}}
```
```
https://image.com/api/v1/images/$$_image.png?cache=38b0c951-ea33-4753-9227-b0277cd6d57f&height=120width=160=
```
should be
```
https://image.com/api/v1/images/$$_image.png?cache=38b0c951-ea33-4753-9227-b0277cd6d57f&height=120width=160
```
 **json data file**
```js
[{'path':'$$_image.png','params':'height=120width=160'}]
```

**Comment by prashantagarwal** [comment]
@martincalvert Thanks for reporting this. We are looking into this issue.

**Comment by czardoz** [comment]
@martincalvert the value of your `params` variable is `height=120width=160`. Are you sure it should not be `height=120&width=160`? (Note the `&` between `120` & `width`). This could be why Postman is adding an extra `=` at the end.

**Comment by willybill** [comment]
This is also happening in Windows Runner and Newman 3.6.1.  In case it helps, I've attached a zipped collection named 'Test' that has 2 flavors of the GET test from Postman Echo collection. The 1st test passes the parameter as a string. The 2nd test passes the parameter using a global var and shows the trailing = when run from Runner or Newman.

Below are snippets from Newman in Jenkins console. Notice the trailing = in Request URL of 2nd test.
newman --version
3.6.1

→ GET Request - works
GET https://echo.getpostman.com/get?test=123 [200 OK, 742B, 538ms]

→ GET Request - global var adds trailing = to Request URL in Runner & Newman
GET https://echo.getpostman.com/get?test=123= [200 OK, 715B, 107ms]

[Test.zip](https://github.com/postmanlabs/postman-app-support/files/1088976/Test.zip)

**Comment by willybill** [comment]
I forgot to mention I am seeing this when running the collection using newman 3.6.1 in Jenkins. Below are snippets from newman in Jenkins console.  Notice the trailing = in Request URL of 2nd test.
+ newman --version
3.6.1
→ GET Request - works
  GET https://echo.getpostman.com/get?test=123 [200 OK, 742B, 538ms]
  ✓  Body contains headers
  ✓  Body contains args
  ✓  Body contains url
  ✓  Args key contains argument passed as url parameter

→ GET Request - global var adds trailing = to Request URL in Runner
  GET https://echo.getpostman.com/get?test=123= [200 OK, 715B, 107ms]
  ✓  Body contains headers
  ✓  Body contains args
  ✓  Body contains url
  ✓  Args key contains argument passed as url parameter

**Comment by martincalvert** [comment]
@czardoz that was a typo on my part. I tested it with and without the `&` in between params and it still is appending the `=`. I also removed the `?` and the `=` was not appended. So Postman is definitely doing something with variables that come after a `?`

**Comment by willybill** [comment]
Is there an ETA on fixing this?  It's blocking our ability to transition to latest version of newman.

**Comment by marcpeters2** [comment]
We are also seeing this issue, using the Postman Mac app version 5.0.0.  A typical request in our collection has a URL defined as follows:

`{{host}}/resource?{{clientType}}`

The *clientType* environment variable is set to `clientType=INTERNAL`.

When running the collection using the Collection Runner, the generated URL appears as follows:

`localhost:8088/resource?clientType=INTERNAL=`   (note the extra = at the end)

**Comment by martincalvert** [comment]
No clue if this is helpful but I have rolled all the way back to newman@2.1.2 and still see the issue.

**Comment by willybill** [comment]
Can we get an ETA on when this will be fixed?  It's a serious bug that has blocked us from moving forward with the newman upgrade and I'm getting pressure to look for another test application if things like this can't be fixed in a reasonable time.

**Comment by sdnts** [comment]
We've isolated the problem and a fix will be out with the next release. Thanks for your patience.

**Comment by willybill** [comment]
What is the release date of the 5.2 milestone?  And, is this going to be fixed in both postman & newman when the fix is released?

**Comment by sdnts** [comment]
@willybill This is caused because we do not have a type system in the Postman App yet. All variables are treated as strings right now.
Essentially, leaving a variable undefined is the same as it having a value of an empty string. 

Let's assume you have a URL like: `domain.com/a`. The reason this issue arises is because the app treats the variable `a` as having an empty variable, so the URL is translated to `domain.com/a=''` (excluding the quotes, of course). This is why you see the appended `=` sign.

Working around this issue will only break other flows. We intend to fix this by having a proper type system in the data editor, so this will be addressed in later versions, not 5.2, as solving the problem correctly is important. 

This is definitely a problem that's on our radar, and we will get to it shortly. We appreciate your patience.

**Comment by kunagpal** [comment]
This has been fixed in the latest version of the app (v5.3.0), do go ahead and check it out 😄

**Comment by willybill** [comment]
Thank you!
    On Wednesday, October 11, 2017, 4:00:40 AM EDT, Kunal Nagpal <notifications@github.com> wrote:  
 
 
This has been fixed in the latest version of the app (v5.3.0), do go ahead and check it out 😄

**Comment by martincalvert** [comment]
I am still seeing it with newman 3.8.3 and OSX app 5.3.0

Request looks like `{{proto}}://{{envhost}}/api/v1/{{path}}?{{params}}&cache={{$guid}}` and params is still getting a `=` at the end.

**Comment by nithyamuth** [comment]
Any idea when this will be fixed? I am using 5.3.2 in the windows desktop app and still have runner appending = to the get request.

**Comment by abcondas** [comment]
I too am using v5.3.2 in Ubuntu and am seeing the issue.  Thanks for the great product!  Any ETA on this fix?  :-)

**Comment by willybill** [comment]
This serious bug, which causes a breakage when using newman, is 7 months old. If you have no intention of fixing it can you simply say so and we'll start moving to another testing app.

**Comment by willybill** [comment]
It just got worse as we are seeing this problem inside Postman now, in v5.5.0.

**Comment by harryi3t** [comment]
@willybill We have found the root cause and have fixed it.
With the next version of Postman, this should work fine.

**Comment by harryi3t** [comment]
Related issue: https://github.com/postmanlabs/postman-app-support/issues/3991

**Comment by jwadhams** [comment]
This issue appears to be resolved (for my use case) in 5.6.0, if you're willing to use the "Canary" until 5.6.0 ships for real. https://www.getpostman.com/canary

**Comment by willybill** [comment]
Has this been fixed in v6.0.9?

**Comment by harryi3t** [comment]
@willybill Yes. Could you confirm this for us?

**Comment by willybill** [comment]
No it still doesn't work.  I upgraded to Postman 6.0.9 and exported my collection as a 2.1 collection. I upgraded newman to 3.9.3.  When I run the collection, I STILL get the trailing = sign as shown below which causes my service to throw a 500.  As a developer I try to give others the benefit of the doubt, but somebody really blew it with this bug, not that introducing it was so bad because bugs are introduced all the time.  It's the fact that it hasn't been fixed in 9 months that is driving us to find another testing solution.  You had such a great product - what happened!

POST <MY-URL>?srcAppFeatureId=UserGuide&products=Amazon= [500 Internal Server Error, 1012B, 251ms]

**Comment by a85** [comment]
@willybill This is not exactly a bug but rather how a particular string can be interpreted on the server side. If there is a parameter whether there is an = sign or not should be immaterial. 

We will add controls in the UI (whether there is a null value or an empty value) but to me this feels like a stupidly coded server and the way it is parsing responses. I don't see any logical reason why there should be a 500 error just because there is an '=' sign. We can't test for every bit of extreme incompetence with the way services are coded.

**Comment by harryi3t** [comment]
@willybill We have fixed the issue in the App. Earlier, while sending the request from App it was appending `=` at the end.

I am closing this issue since the issue reported by the OP @martincalvert is fixed.
For the issue that you are facing I have opened a separate issue here https://github.com/postmanlabs/postman-app-support/issues/4298

Also, until we fix this bug you can use a temporary workaround. Just replace globally all `"value": ""` to `"value": null`
Maybe you can use a simple sed command
```
sed -i  's/"value": ""/"value": null/g' YOUR_COLLECTION.postman_collection.json
```
