### ISSUE TITLE
URL truncated after `#`

### ISSUE THREAD

**Issue by catogtp** [a85/POSTMan-Chrome-Extension#3208]
## App Details:
Postman for Chrome
Version 5.0.1
win / x86-64
Chrome 58.0.3029.110

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Just recently
 2. Expected behaviour: Full text input instead of truncated values

Start a new builder tab.
Select the parameters button.
enter a key name.
enter a value and at some point type ##.

**Comment by sdnts** [comment]
@catogtp I was able to reproduce this, and we will get on a fix.
Out of curiosity though, why are you trying to have a `#` in a URL parameter's value? I ask because a `#` has special meaning for URLs.

**Comment by catogtp** [comment]
We are passing over a hash in the post data for data validation. Unfortunately I didn't compute or pick the method so I am left with what I have been provided by my customer.

**Comment by AndrewPirkola** [comment]
I have the same issue. We need to use a vendor API to trigger sending an e-mail, and one of the parameters is the e-mail subject. The problem is that the subject must include the pattern ##{id}## for it to get properly handled. 

Why that's a URL parameter rather than being something in the body of a post message is something I'll forever not understand, but it's what I have.

**Comment by a85** [comment]
@madebysid Is this fixed now?

**Comment by catogtp** [comment]
@a85 As of 3 minutes ago using build 5.5.0 updated today, the problem still exists.

**Comment by numaanashraf** [comment]
@catogtp `#` has special meaning in URLs and the url fragment after the hash is not sent to the server. At the moment, we do not auto-encode these special characters and are compliant with the WHATWG URL spec. As a workaround, you can select the value you need to send, right click and select encodeURIComponent. This will encode the `#` and will be sent to the server.
