### ISSUE TITLE
Postman very slow to return from endpoint calls and global variable updates

### ISSUE THREAD

**Issue by zeleznickm** [a85/POSTMan-Chrome-Extension#3216]
## App Details:

Postman for Windows
Version 5.0.0
win32 6.1.7601 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:  Postman has been very slow to respond to calls to endpoint apis, used to be very responsive
 2. Expected behaviour: calling an endpoint api, or updating a global parameter should not hang for a while.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by prashantagarwal** [comment]
@zeleznickm Thanks for reporting this. We are actively working on improving Postman performance.
We will be making some releases around this soon.

**Comment by zeleznickm** [comment]
Did notice this error in the dev tools console, maybe unrelated

file:///C:/Users/zeleznickm/AppData/Local/Postman/app-5.0.0/resources/app.asar/html/mode-auto.js  ERR_FILE_NOT_FOUND

**Comment by zeleznickm** [comment]
Saw this on another call

disconnected from sync service, possibly a network outage
scheduled reconnection attempt #1 after 7611ms
watchdog checking connection health
reconnecting to sync service #(1/8)
reconnecting to sync service after being offline for 7.983 seconds
connected to sync service
Error fetching team notifications  (a stack trace  of calls to various sails.io.js stuff)
force disconnect from sync service
disconnected from sync service, possibly a network outage
connected to sync service
socket replaying queued commands

**Comment by gregeisips** [comment]
+1
I have the same problem. please help. We are on the paid version now and it is almost unusable

**Comment by numaanashraf** [comment]
@gregeisips @zeleznickm Hi, we had made some core changes to the internals of the app in Postman 6. Could you verify whether you are still facing sluggish performance in Postman v6.1.4?

**Comment by MeaningOfLights** [comment]
I have the same problem and I am on the latest version v6.2.2. 
The GPU flag did nothing, what worked was deleting the  C:\Users\<userId>\AppData\Roaming\Postman. Take a back up as it will lose your settings.

**Comment by jzabroski** [comment]
Postman Desktop UI, on latest version (v6.5.3), turns completely blank after taking a long time to display a response:

![image](https://user-images.githubusercontent.com/447485/49399928-adaaf600-f710-11e8-984c-2a98ab7e1768.png)

You can see I am on the latest version with this screenshot:

![image](https://user-images.githubusercontent.com/447485/49399981-d6cb8680-f710-11e8-96c4-9d7d36b4989c.png)

**Comment by jzabroski** [comment]
Here is a simple repro of the crashing issue.  Create an endpoint that generates periods using Enumerable.Range in c# and increments each period by one minute.  At one year of one minutely periods, Postman crashes.  Attached is a half year, which works "ok" but is still ridiculously slow for what it's trying to accomplish.

[halfyearresponse.txt](https://github.com/postmanlabs/postman-app-support/files/2641274/halfyearresponse.txt)

**Comment by jzabroski** [comment]
For what it is worth, Swagger UI built with Swashbuckle.AspNetCore has the same issues.  When debugging in Chrome with Developer Tools and "out of memory crash prevention" enabled, I can see that my Swagger UI is choking inside of immutable.js Facebook library.  I have no idea if Postman uses immutable.js or what version of immutable.js my Swagger UI is using.

**Comment by jzabroski** [comment]
Here is a quick C# repro for ASP.NET MVC Core:

```csharp
var months = 12;
var daysPerMonth = 30;
var minutesPerHour = 60;
var hoursPerDay = 24;
var totalMinutes = months * daysPerMonth * minutesPerHour * hoursPerDay;

Ok(
	Enumerable.Range(0, totalMinutes)
		.Select(i =>
			new
			{
				StartDate = new DateTimeOffset(2017, 1, 1, 0, 0, 0, TimeSpan.Zero).AddMinutes(i),
				EndDate = new DateTimeOffset(2017, 1, 1, 0, 0, 0, TimeSpan.Zero).AddMinutes(i + 1)
			})
);
```

**Comment by jzabroski** [comment]
Is anyone looking at this issue?

**Comment by jzabroski** [comment]
@numaanashraf What more do you need to know that I have not given in my simple repro?

**Comment by jzabroski** [comment]
@numaanashraf What do you need to know?

**Comment by kamalaknn** [comment]
@jzabroski I think the issue you have been experiencing is related to large responses slowing down Postman. We are tracking it as part of https://github.com/postmanlabs/postman-app-support/issues/4751

@zeleznickm @MeaningOfLights We pushed some improvements to the request handling and environment update infrastructure couple of versions ago. Could you give the latest version a try and let us know if you're still facing any issues?

**Comment by kamalaknn** [comment]
Closing this issue due to lack of inactivity related to the original issue reported.

We have pushed many improvements to variable updates flows since Postman v6. Please update to the latest version and let us know if you are still facing this issues on the latest version.

**Comment by rick-hayek** [comment]
It still happens on v7.0.7. 
I'm requesting a very simple web api which returns very light json data. In chrome, it finishes around 300ms, but in Postman, it takes 1.5s to complete the request. kinda insane.

![image](https://user-images.githubusercontent.com/17425089/56019554-8c4dbc80-5d37-11e9-9590-c03ff6daf1d0.png)

**Comment by vikiCoder** [comment]
We've added a tooltip in response time showing detailed timing information after the request is sent. Please update to the latest version(v7.0.9) and you will be able to see what is taking more time in request sending. Below is a screenshot just as an example of this feature.

![image](https://user-images.githubusercontent.com/16588032/56636209-af586480-6685-11e9-85cb-aae07f9fa2ec.png)

**Comment by Turkish** [comment]
I have requests taking more than 4 seconds with POSTMAN that are taking less than a second with chrome
![image](https://user-images.githubusercontent.com/2260546/65757562-4fbc2480-e10f-11e9-9a7a-f4dfacd1f5e3.png)

The tooltip shows POSTMAN is struggling with the DNS Lookup
Same query with chrome:
![image](https://user-images.githubusercontent.com/2260546/65757700-96118380-e10f-11e9-8df9-7640a17a6da7.png)

I relied on POSTMAN to communicate to third parties about the response time of their API, now I look stupid...

**Comment by d0x7** [comment]
> I relied on POSTMAN to communicate to third parties about the response time of their API, now I look stupid...

Same issue over here. The request itself is quite fast. 

Apparently the issue is, well, looking the DNS up, but I don't really get why. Using 127.0.0.1 it's super fast (around 6ms for the whole request, DNS is cached that way), but for `localhost` looking up the DNS takes, as you can see, around 500ms. 

![image](https://user-images.githubusercontent.com/17951467/67861854-503a4780-fb21-11e9-819b-24bf7f9f2fc6.png)

**Comment by andredsp** [comment]
I had a similar issue in macOS with local DNS lookup taking ~10 seconds. The issue can be solved by adding the following to /etc/hosts (assuming hostname is macbook):

```
127.0.0.1   macbook
::1         macbook
```

This returns the time to something more suitable (< 1 second)

Source: https://stackoverflow.com/questions/33289695/inetaddress-getlocalhost-slow-to-run-30-seconds/33289897#33289897

**Comment by d0x7** [comment]
> I had a similar issue in macOS with local DNS lookup taking ~10 seconds. The issue can be solved by adding the following to /etc/hosts (assuming hostname is macbook):
> 
> ```
> 127.0.0.1   macbook
> ::1         macbook
> ```
> 
> This returns the time to something more suitable (< 1 second)
> 
> Source: https://stackoverflow.com/questions/33289695/inetaddress-getlocalhost-slow-to-run-30-seconds/33289897#33289897

While this is a workaround, it's not a fix. It's also working if you're just using `127.0.0.1` without adding something to the hosts file, but yeah, not a fix. Postman team should fix this as this is IMO a major issue.

**Comment by ghost** [comment]
I had this same issue. I was using the setup below in my hosts file among other domain names. 
This added extra 5sec for DNS lookup in postman for the API

127.0.0.1       domain.local
127.0.0.1       api.domain.local 

I fixed it by moving api.domain.local to the top of the list & it work(DNS lookup time down to 1.3ms)

**Comment by seantsb** [comment]
I think running into the same issue; taking 30s for "transfer start"

<img width="392" alt="Screen Shot 2021-05-19 at 18 04 31" src="https://user-images.githubusercontent.com/2584573/118890443-aa9a2500-b8cc-11eb-8c76-cd73ed1a3678.png">

**Comment by swedkg** [comment]
The issue is still here (Version 8.12.5)
I'm using cUrl to repeat the same request 10 times, time_starttransfer is approximately 11 seconds.
Postman reports it to be 35s

![image](https://user-images.githubusercontent.com/9026763/157448120-2c4f6b66-0e74-43ab-8339-df0e0e5323fa.png)
![image](https://user-images.githubusercontent.com/9026763/157448209-fba71c3f-9fe4-43c4-b314-2c24d6d4505a.png)

**Comment by Turkish** [comment]
@swedkg  postman is dying , a lot of folks are using insomnia now instead, the major reason is their new agent, they stopped being a desktop app and now they have an agent running in the background and you have to use their browser app. I have been using postman for very long, and relied on it, but their last version (agent + browser) is much worse than  a simple desktop app, it's sad to see it like this

**Comment by numaanashraf** [comment]
@Turkish Postman for Web (+ agent) is an additional option that's available for you. Postman for Desktop is fully supported and all the latest features of Postman is and will continue to be available on both platforms.

https://www.postman.com/downloads/

**Comment by quentinlamamy** [comment]
Same issue, postman took 5s on a endpoint, my browser 5ms. Its just 19o data.

If we can trust anyore postman to check all our endpoint and performance, it's the end....
