### ISSUE TITLE
certificate load error: ENOENT: no such file or directory, open ''

### ISSUE THREAD

**Issue by rubenski** [a85/POSTMan-Chrome-Extension#3251]
Hi, I have added certificates to Postman 5.0.2 in order access some endpoints at my company. Whenever I fire a request Postman reports a certificate load error in the console. It says it can't find the file or directory. I checked my file system. It should be accessible to Postman. I provided complete control over my certificate folder to "Everyone" in Windows. The exact same setup works on my old machine with Postman 4.10.7. I used the certificates from that machine, so the problem should not be in the actual certificates.  

The error message and the part - open '' - specifically seems to suggest Postman is trying to open an empty path...

My cert settings:

![certs](https://user-images.githubusercontent.com/1971606/27985300-d64f2ec6-63e8-11e7-86de-edfc09b39b8f.png)

(Cert names contain only letters and underscores. No special characters)

## App Details:
Postman for Windows
Version 5.0.2
win32 10.0.14393 / x64
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Recently encountered problem with certificates not being loaded/found
 2. Expected behaviour: finds certificates and sends them
 3. Console logs:

certificate load error: ENOENT: no such file or directory, open ''
----------------------------------------------------------------------
POST
https://subdomain.example.com/my/url
01:28:35.287
Error: SSL Error: **UNABLE_TO_VERIFY_LEAF_SIGNATURE**
Proxy:
proxy:"http://localhost:22222"
tunnel:true
Request Headers:
cache-control:"no-cache"
Postman-Token:"a6ab6ab1-9351-4352-b9ed-f72389920e56"
Upgrade-Insecure-Requests:"1"
Origin:"https://subdomain.example.com"
Host:"subdomain.example.com"

4. Reproduce:

Open Postman 5.02 for Windows
Add a certificate and fire request while checking console

**Comment by sdnts** [comment]
Hi @rubenski I see you haven't specified a KEY file with your certs, can you supply Postman the key file used to generate your CRT as well and retry?

**Comment by krdeepak** [comment]
How can we add certificate with only .crt file available and not the key file. For normal ssl handshake, only crt file is needed.

**Comment by kamalaknn** [comment]
It looks like we are canceling out both certificate files if there was an error with one file. We'll take a look at this again.

Thanks for reporting this.

**Comment by dmytrocx75** [comment]
@kamalaknn I got the same problem `"certificate load error: ENOENT: no such file or directory, open ''` 
 trying to send a request with SSL certificate verification ON and .crt file added.
Could you advise me any workaround until it's fixed or tell when it will be fixed?

**Comment by dhruv-niki** [comment]
Has this been fixed for Postman v5.5.0 ?

**Comment by lems111** [comment]
In which release, should we expect the fix for this one? I have a customer that requires mutual authentication with only crt file. I have to switch to SOAP UI for now

**Comment by danimr** [comment]
Same problem over here. Running post in admin mode does not fix the problem.

A wordarroud would be highly appreciated.

**Comment by sscheitle** [comment]
I'm on version 6 and having the same problem. Any fixes?

**Comment by tahirm** [comment]
Getting the same error on latest Version 6.1.3 as well. This makes Postman unusable when certificate is required for authentication.

Its been almost one year since this issue, what is the expected timeline here?

**Comment by c-olaand** [comment]
Same issue for me :-(

**Comment by snips11** [comment]
And for me!

**Comment by jajimene** [comment]
Same here :(

**Comment by pshoultz** [comment]
same problem

**Comment by andrergomes** [comment]
Any idea?

**Comment by ghost** [comment]
I am also facing this issue

**Comment by guy-klebanov** [comment]
same issue, any update ?

**Comment by kamalaknn** [comment]
This has been fixed in the library we use for sending requests - `postman-runtime`. We'll push the fix on our stable channels soon.

**Comment by guy-klebanov** [comment]
can u pls share an assessment when it will be released (i.e. soon means ?) ?

**Comment by harryi3t** [comment]
@rubenski 
This is fixed in the latest version of Postman 6.3.0 🎉 
![no-key-file-does-not-crash-the-request-sending-flow](https://user-images.githubusercontent.com/5207331/45155453-ab5ffb00-b1f8-11e8-8449-c00a2b4667f4.png)

**Comment by barbareek** [comment]
This is not fixed , i am still getting "certificate "key" load error: ENOENT: no such file or directory, open "

**Comment by barbareek** [comment]
<img width="604" alt="screen shot 2018-09-22 at 12 42 39 pm" src="https://user-images.githubusercontent.com/5753015/45914640-62997a80-be65-11e8-824a-3e1cf0bb9090.png">

**Comment by adeniltonbs** [comment]
same here

**Comment by dacloutier** [comment]
I'm having the same issue in 6.4.2

**Comment by Lavanya1689** [comment]
Same issue in 6.5.2

**Comment by harryi3t** [comment]
@adeniltonbs @dacloutier @Lavanya1689 @barbareek 
The error that you see in the Postman Console is actually just a warning. Earlier Postman would not even send the request and error out if one of CRT file or Key file was missing. We fixed it by removing the restriction. Now, if only one file is used, we log the warning and continue sending the request.

If this is not working out for you as expected, could you help us out by providing some endpoints against which we can test this? A real-world API or even a sample server will work too.

**Comment by Lavanya1689** [comment]
I am seeing the below error

`HTTP Basic: Access denied.`

I added my crt file in the Certificates

**Comment by shamasis** [comment]
> I am seeing the below error
> 
> `HTTP Basic: Access denied.`
> 
> I added my crt file in the Certificates


This might not be related to the actual certificate issue.
