### ISSUE TITLE
Exported Run Results JSON file contains wrong results.totalRequestTime : concatenated string instead of sum

### ISSUE THREAD

**Issue by megadix** [a85/POSTMan-Chrome-Extension#3275]
## App Details:

```
Postman for Windows
Version 5.0.2
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:  
This is the first time I've used this feature
 2. Expected behaviour:  
`results.totalRequestTime` in exported JSON file should be a number (perhaps long?) with the sum of the elapsed request times
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):  
*not applicable*
 4. Screenshots (if applicable)  
*not applicable*

## Steps to reproduce the problem

1. Create a collection with at least 2 requests
2. Run the collection
3. Click on **Export Results**

Now look at the exported JSON file:
- inside `results` each entry is an object with a `times` array
- `times` array contains the elapsed time, in milliseconds, of the request
- if you look at `totalRequestTime` you can see that is just a **concatenation** of the string representation of `results.times`

E.g. if times is:
```json
"times": [
	"507",
	"3269",
	"2353"
]
```

then `totalRequestTime` will be:
```json
"totalRequestTime": "50732692353"
```

**Comment by kamalaknn** [comment]
@megadix Thanks for reporting this. This should have been handled properly.

We'll update the thread once this is fixed.

**Comment by a85** [comment]
@madebysid Is this fixed now?

**Comment by megadix** [comment]
Just tested on new version *5.5.0*, it seems that bug is still there.

**Comment by megadix** [comment]
Small update:
The bug is visible only when `Iterations` is > 1, so it is not a problem with "one-shot" tests.
Sample code for calculating the total times:
```js
const times = ["522", "514", null, undefined];
const total = times.reduce(
  (sum, value) => {return sum + (value ? Number(value) : 0)},
  0
);
```

**Comment by tmulry** [comment]
This is still an issue for me in 5.5.0 (as it was in 5.3.2 ).  All the times in the runner report are showing and concatenating as strings instead of numbers.

**Comment by adequatica** [comment]
Still a problem (6.0.10).

**Comment by sivcan** [comment]
Hi all,
We regret the inconvenience caused. 
This has been fixed on our end and I'll update this thread once the change is reflected in an upcoming release.

**Comment by sivcan** [comment]
@megadix and others, this has been fixed in the latest release i.e **v6.1.2** 
Kindly update to the same.
