### ISSUE TITLE
Postman Console rendering disabled headers

### ISSUE THREAD

**Issue by loraxipam** [a85/POSTMan-Chrome-Extension#3302]
## App Details:
```
Postman for Windows
Version 5.1.1
win32 6.1.7601 / x64
```

## Issue Report:
 1. Recently seen. (Broken by 5.1.1?)
 2. Expected behaviour: using a different Accept encoding, the Console would show the correct type sent in the request.
 3. Console log shows "Request Headers: Accept: "application/xml" even when "application/json" was requested.
 4. Screenshots
![image](https://user-images.githubusercontent.com/17756560/28533874-b2368184-706c-11e7-8a11-fe09bc020cc0.png)

![image](https://user-images.githubusercontent.com/17756560/28532848-0e0671e4-7069-11e7-91f5-4721ccae5175.png)

![image](https://user-images.githubusercontent.com/17756560/28532914-4a8f9dd4-7069-11e7-923b-6cec9c4c742b.png)

## Description
- Two Accept headers are defined in my GET call but only one of which is checked as "Active".
- The first Accept header is application/json and the second is application/xml
- When the JSON header is chosen, the data returned is JSON and the content-type matches but the console shows that it asked for XML.
- When the XML header is chosen, XML is returned and the console shows it asked for XML.

**Comment by kamalaknn** [comment]
Hey @loraxipam 

Thanks for reporting this. I was able to reproduce this. 

There is something wrong with how the Request Headers are listed on the console. It appears that it only shows the last value of a header. Also, this would only affect the console and does not affect the behavior of the request.

We'll work on a fix. I'll update this thread once a fix for this is pushed.

**Comment by loraxipam** [comment]
I wonder if this is limited to Accept or it if is any time there are multiple entries in the possible Header array.

**Comment by kamalaknn** [comment]
@loraxipam Yup, this is not specific to `Accept` header. Any header with duplicate values would go through this flow.

**Comment by JamesMGreene** [comment]
I've noticed this, too, even if there is only one disabled `Accept` header.  The Console will initially show that disabled header's value (e.g. `text/csv`) but then seems to update to the correct one (e.g. `*/*`, in my case) after receiving the response.

**Comment by connorsadlervelo** [comment]
This really should be fixed IMHO.
I found it very confusing just now. I had a header unticked and it still showed it in the Postman console. I don't think it's being sent to the backend across the wire but who knows?
Basic errors like this make Postman feel quite unreliable.
Then it becomes worse when you see that this was reported over a year ago.
Rant over! Please fix

**Comment by erichurkman** [comment]
Just hit this too. If the console isn't an accurate representation of what's actually being sent, what use is it? Being able to see the raw request being sent should be a basic thing.

**Comment by sebadiaz-arg** [comment]
Hi, in the initial post I see it is reported for Postman running in Windows. In MacOS I've same problem, Versión 6.4.4. It could be great if you can solve it. Thanks!

**Comment by dhineshwiz** [comment]
This is fixed in the latest version.

**Comment by mikem** [comment]
> This is fixed in the latest version.

Which version is that? I just tried 6.7.1 and the issue still persists.

In fact, repeating the steps in the initial report, I see two `Accept` headers.

**Comment by dhineshwiz** [comment]
hey @mikem, i just verified in v6.7.1, a request with two `Accept` headers and one disabled, the postman console doesn't render the disabled headers

<img width="1042" alt="screenshot 2019-01-14 at 1 49 35 pm" src="https://user-images.githubusercontent.com/10631268/51102036-56b23980-1803-11e9-880e-03edfcd51a58.png">

**Comment by Miq3l** [comment]
Hi @dhineshwiz ,
I'm just now experiencing the same issue. I'm using v6.7.1 in Windows .
All the best,
Miquel

**Comment by mikem** [comment]
@dhineshwiz I forgot to specify that I'm looking at the Raw version of the request in the console, not the pretty version as in your screenshots. Here's what I see:

<img width="763" alt="screen shot 2019-01-14 at 21 16 42" src="https://user-images.githubusercontent.com/62569/51115058-19b96780-1842-11e9-996f-a97ed15f6ad9.png">

<img width="777" alt="screen shot 2019-01-14 at 21 17 19" src="https://user-images.githubusercontent.com/62569/51115067-22aa3900-1842-11e9-8a5a-6064c14e0bf0.png">

**Comment by numaanashraf** [comment]
This is addressed in Postman v7.0

**Comment by moravcik** [comment]
I am experiencing the same issue, Postman version 7.2.2 (Linux)

**Comment by ankurdengla** [comment]
Hey @moravcik ! We are unable to reproduce the issue on Postman 7.2.2 at our end. Could you please share the steps to reproduce the issue along with relevant screenshots (if possible) ?

**Comment by moravcik** [comment]
Hi @ankurdengla1996 - I planned to document how to reproduce this problem but I found it was entirely my bug - my problem. 
Few months ago I tried to add some headers to the request conditionally in the pre-request script, but at that time it didn't work. I forgot to remove my pre-request script and now I have installed the latest version of Postman and the pre-request script started to work, always re-adding the same header I was trying to turn on or off. Well, it's not a bug, it's a feature :) 
Well done, guys, and sorry for my trivial "bug" reporting.

**Comment by codenirvana** [comment]
@moravcik Yes, We added support for request mutation via pre-request script in v7.0.9, [More Info](https://github.com/postmanlabs/postman-app-support/issues/4631#issuecomment-477766260).

I understand the source of confusion, categorizing system and programmatically added headers is definitely on our list and will be fixed with #6396.

Thanks for your feedback!
