### ISSUE TITLE
Make Manage Environments window movable & resizable

### ISSUE THREAD

**Issue by abhidp** [a85/POSTMan-Chrome-Extension#3493]
## App Details:

```
Postman for Mac
Version 5.2.0 (5.2.0)
OS X 10.12.6 (16G29) / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always been there
 2. Expected behaviour: Users should be able to drag and move the MANAGE ENVIRONMENTS window to any part of the screen. As of now the Manage Environments panel sits right at the centre of the screen and cannot be moved to any other position. This hides essential information behind the Mng Env window. For example - In the GIF below, I want to validate whether the token in my Environment Variables is picked up correctly from the JSON response body. But I cant, because my response body is hidden behind the Mng Env window and I can't move it out of the way to compare the Key-Value pair details with my response body details.
![manageevironmentwindownotmovable](https://user-images.githubusercontent.com/30851622/30088710-600f40d4-92eb-11e7-9d7d-29634c06fa75.gif)

 4. Screenshots (if applicable) - Attached

**Comment by sdnts** [comment]
Hi @abhimassive! Thanks for the suggestion! We will take a look at this. I'm guessing being able to move all modals around is what you're looking for, correct?

**Comment by abhidp** [comment]
Absolutely correct @madebysid

**Comment by a1dutch** [comment]
Would love a resizable environment window to see all my variables

**Comment by tparikka** [comment]
I also need this feature; almost all of my variable names don't fit in the columns at default size. The window should be resizeable and the column widths also resizeable.

**Comment by deanblackborough** [comment]
I'm fighting against the tiny window at the moment, please make the window re-sizeable.

**Comment by ghost** [comment]
How is this still a thing?

**Comment by arlemi** [comment]
@elias-putz-kiwigrid and everyone in this thread, it won't be a thing pretty soon! We're moving environments to their own tab. This experience is already available on [Postman for the Web](https://go.postman.co/build) (and you can see a live demo of it here: https://youtu.be/1n6g4fbaIxA?t=892) and will make into the app in the coming months. 🙂

**Comment by giridharvc7** [comment]
This is now fixed in app v8.0, let know what you think @elias-putz-kiwigrid @deanblackborough @abhidp @a1dutch @tparikka

**Comment by a1dutch** [comment]
@giridharvc7, The modal quickview is still not resizable, only when you click `edit` and it opens in a tab is the whole window resizable.

**Comment by giridharvc7** [comment]
Yes. We don't intend to make the modal resizable for now. All editing of environment will happen in the environment's window. But, does this solve your problem though?

**Comment by a1dutch** [comment]
for me its not possible to view large variables without clicking the `edit` button. e.g. like bearer tokens.

it might be easier to do away with the quick look and just open the tab instead
