### ISSUE TITLE
Variables in token name not working

### ISSUE THREAD

**Issue by DavydeVries** [a85/POSTMan-Chrome-Extension#3525]
## App Details:
```
Postman for Mac
Version 5.2.0
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: recently, but I think it's always been there.
 2. Expected behaviour: replaces variables in token name
 3. Console logs: doesn't apply
 4. Screenshots (if applicable): see below

## Steps:
1. Manage environments, add a environment
2. Add some variables
3. Request a OAuth2 access token, uses environment variables in the `token name` field
3. Resulted in a access token name with your variables. (see screenshot)

![schermafbeelding 2017-09-14 om 08 51 18](https://user-images.githubusercontent.com/7860305/30415915-7adde024-992a-11e7-816b-2b076ee5e8be.png)

**Comment by kamalaknn** [comment]
@DavydeVries thanks for sending your feedback. We are working on improvements to the OAuth token generation flows. 

We are planning on adding more information to the token outside of the token name like the timestamp and provider by default. Would that help? Is there something you would want from the environment?

**Comment by prashantagarwal** [comment]
@DavydeVries This should be fixed in latest Postman app versions. Feel free to reopen this issue if it does not solves your issue.

**Comment by DavydeVries** [comment]
What is the latest app version? Because I'm running on:
Postman for Mac
Version 5.3.2
OS X 17.2.0 / x64

And this is still happening:
![schermafbeelding 2017-11-03 om 09 40 13](https://user-images.githubusercontent.com/7860305/32365722-4625c2de-c07b-11e7-95ba-7a68c2094278.png)

**Comment by kamalaknn** [comment]
@DavydeVries We haven't enabled variables in `Token Name` yet. We will be adding a few improvements to the OAuth 2.0 flow in the near term that would make it easy for you to identify tokens without adding timestamp to token names.

**Comment by hIUG** [comment]
Will this be resolved? I'm also trying to set a dynamic name on the token depending on an environment variable ({{name}})

**Comment by DavydeVries** [comment]
Still waiting for this... Token age would also be a great feature!

**Comment by leonardstronkhorst** [comment]
Can you also enable variables for `Auth URL`, `Access Token URL`, and `Client ID` (basically all fields of the `Get new access token form`)?

**Comment by slowblow** [comment]
It is necessary we are able to identify a token through variables in function of environment selected. When will it be enabled variables in Token Name?

**Comment by DavydeVries** [comment]
> It is necessary we are able to identify a token through variables in function of environment selected. When will it be enabled variables in Token Name?

I guess never, because this issue is over a year old now. And they give evasive answers soo...

**Comment by vikiCoder** [comment]
This issue is fixed in the latest version of Postman App (v7.6.0). Now variables in the token name are replaced with their value while generating new tokens.

**Comment by nagireddy51** [comment]
> This issue is fixed in the latest version of Postman App (v7.6.0). Now variables in the token name are replaced with their value while generating new tokens.

I don't think that this issue is fixed. I see the same issue with v7.27.0.
