### ISSUE TITLE
Install does not create shortcut in start menu or on desktop.

### ISSUE THREAD

**Issue by amosbaker** [a85/POSTMan-Chrome-Extension#3871]
## App Details:

```
Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: N/A, just switched from chrome extension recently.
 2. Expected behaviour: When installing I would expect basic options like 'Create shortcut on Desktop' or 'Install Directory'. Some of us don't use our C drive in windows. Also finding the executable after installation is not really documented and therefore needlessly tedious.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 4. Screenshots (if applicable)

Steps to reproduce the problem:
Install using provided binary on Windows 7.

**Comment by prashantagarwal** [comment]
@amosbaker Thanks for reporting this issue. We will investigate this and keep you updated about it.

**Comment by SamvelRaja** [comment]
@amosbaker we fixed this issue, we recommend you to update to the latest version of the app and check the same.
Closing this now, feel free to re-open if you face this again.

**Comment by fayazmd** [comment]
![image](https://user-images.githubusercontent.com/37344807/40765649-bf84e468-64ca-11e8-9873-89812cea604e.png)


Issue still persists..  Also, I am trying to change the icon manually by right clicking on the shortcut but then, while saving I am seeing an error The folder "C:\Users\Admin\AppData\Local\Postman\app-6.0.10" specified in the Start In box is not valid. Make sure that the folder exists and that the path is correct.

**Comment by Andriy1024** [comment]
I had same issue.
I fixed this when started setup as administrator. Hope it will help you too.
