### ISSUE TITLE
Postman Native App listed as "Electron" in Windows Task Manager

### ISSUE THREAD

**Issue by kbuzby** [a85/POSTMan-Chrome-Extension#3879]
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Encountered Today
 2. Expected behaviour: Application labeled as Postman
 4. Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/2800467/33403696-01b14d6a-d527-11e7-8e82-392a327813c2.png)

The Postman application in windows is listed as Electron in windows task manager, with postman as a process under it - this seems like it should be listed as "Postman".

**Comment by thecuriousdev** [comment]
Thanks for letting us know about this issue. the issue is fixed now, will be released soon!

**Comment by kbuzby** [comment]
Verified it was fixed. Thanks!

**Comment by kurtteal** [comment]
I just noticed this today. It seems it's still happening :(

![image](https://user-images.githubusercontent.com/4903281/36947456-e1125a80-1fc3-11e8-81d4-ca7078d76936.png)
![image](https://user-images.githubusercontent.com/4903281/36947464-036eeecc-1fc4-11e8-9765-7aecfda8ceef.png)

**Comment by thecuriousdev** [comment]
@kurtteal you are using an older version of Postman, please try updating to the latest version.

**Comment by kurtteal** [comment]
I see :) 
I did update it to the latest version though. As you can see in the picture above, the app was telling me it was in the latest version (at v5.6.1). Maybe there's a latest version check bug in there? I have now reinstalled it to get the _real_ latest version (v6.0.8) and now I can confirm the bug is fixed :)
