### ISSUE TITLE
Postman window is hidden and cannot be resized by any means

### ISSUE THREAD

**Issue by gl2007** [a85/POSTMan-Chrome-Extension#3953]
## App Details:

```
Postman for Windows
Version "Postman-win64-5.3.2"
OS Windows 10 Enterprise
```

## Issue Report:
1. Postman was started in my office where I have an extra monitor. Postman was maximized.
2. Come home and try to open Postman.
3. Postman window does not show up but is probably hidden since it was maximized. No way to resize the window or to see if. Tried window scaling options in Postman.exe properties to no avail.

Tried to see in regedt32 to see if any state can be reset. Could not find one. Does it remember its state in some file?

**Comment by gl2007** [comment]
Found a workaround! 
1. Hover the mouse over the taskbar icon, until windows shows the "window preview".
2. R-click on the "preview" window.
3. You can now use the maximize option to resize Postman to the current screen sizes.

In my case, the Postman was showing the "Update" popup as well. Wonder, if that is the cause of this behavior or is unrelated.

**Comment by sdnts** [comment]
Hi @ghanashyaml This is a known issue, and has since been fixed in our Canary version. The fix will land on our stable channel in coming releases. You can follow #2992 for updates :)

**Comment by jibolso** [comment]
> Hi @ghanashyaml This is a known issue, and has since been fixed in our Canary version. The fix will land on our stable channel in coming releases. You can follow #2992 for updates :)

Just a kind note, it's 2019 and this issue from 2017 still happens. The fix was to over the mouse over the task bar icon and right click on the preview window and then select the maximize option just like @ghanashyaml said.

**Comment by chris-burkhardt** [comment]
This might help some Mac users that have reached this page while looking for a solution. 

I had this same issue on my MacBook Pro (not Windows). The window just disappeared completely when I minimized it and I could not locate the window to open it again. The way I got it back was by doing the following:

1. Left click the Postman icon so you see the Postman toolbar at the top of your screen
![Screen Shot 2020-01-13 at 10 44 36 AM](https://user-images.githubusercontent.com/31424007/72229416-bfd4b480-35f1-11ea-938d-728ce919f86f.png)

2. Click View -> Toggle Full Screen (the app window should appear in full screen mode)
![Screen Shot 2020-01-13 at 10 45 32 AM](https://user-images.githubusercontent.com/31424007/72229428-d844cf00-35f1-11ea-8714-349000c9da8a.png)

3. Click the Open New icon (square box with + sign) and select Postman Window (a new (2nd), normal size window will appear that can be resized)
![Screen Shot 2020-01-13 at 10 46 20 AM](https://user-images.githubusercontent.com/31424007/72229448-06c2aa00-35f2-11ea-987c-242ac785366e.png)

4. Right click the Postman Icon from your dock and you should see 2 Postman windows
<img width="171" alt="Screen Shot 2020-01-13 at 10 48 08 AM" src="https://user-images.githubusercontent.com/31424007/72229474-44273780-35f2-11ea-925f-d57ddebc4b4d.png">

5. Click the Postman window that cannot be resized (it should show up full screen) and then close the window by clicking the red X icon.
![Screen Shot 2020-01-13 at 10 47 42 AM](https://user-images.githubusercontent.com/31424007/72229491-6de05e80-35f2-11ea-9840-6722d47543cc.png)

Now you will have a working window that is resizable and movable. The broken window is closed and the issue does not persist.

The steps above are assuming you are able to Toggle Full Screen and see the window that cannot be found anywhere else to be resized.  

I hope this helps someone.

**Comment by 19Sean96** [comment]
> > Hi @ghanashyaml This is a known issue, and has since been fixed in our Canary version. The fix will land on our stable channel in coming releases. You can follow #2992 for updates :)
> 
> Just a kind note, it's 2019 and this issue from 2017 still happens. The fix was to over the mouse over the task bar icon and right click on the preview window and then select the maximize option just like @ghanashyaml said.

Haha wow, such a simple fix, but still kinda annoying since I just re-installed. Seems like this issue still exists 2020, just an FYI to the devs

**Comment by mohsen-sabbaghi** [comment]
> ## App Details:
> ```
> Postman for Windows
> Version "Postman-win64-5.3.2"
> OS Windows 10 Enterprise
> ```
> 
> ## Issue Report:
> 1. Postman was started in my office where I have an extra monitor. Postman was maximized.
> 2. Come home and try to open Postman.
> 3. Postman window does not show up but is probably hidden since it was maximized. No way to resize the window or to see if. Tried window scaling options in Postman.exe properties to no avail.
> 
> Tried to see in regedt32 to see if any state can be reset. Could not find one. Does it remember its state in some file?

**simply press F11 to get rid of full-screen mode!**

**Comment by kendarkfire** [comment]
it still happens in my windows 10 OS, mouse over the task icon and right click on the preview, the "Maximize‘’ option is grayed out, now I cannot move it or resize the window
![image](https://user-images.githubusercontent.com/7509145/124200379-0a6a1b00-da8a-11eb-9e85-26a7546190c3.png)

**Comment by sanketbhangale43** [comment]
Please try this
1. Right-click on the taskbar 
2. Choose the option "Show windows side by side"

Now you should be able to see the postman window on the screen

Thanks

**Comment by deepak-mane** [comment]
@sanketbhangale43 : Thanks your resolution helped. Right-click on the taskbar Choose the option "Show windows side by side"

**Comment by razinsyakib** [comment]
> This might help some Mac users that have reached this page while looking for a solution.
> 
> I had this same issue on my MacBook Pro (not Windows). The window just disappeared completely when I minimized it and I could not locate the window to open it again. The way I got it back was by doing the following:
> 
> 1. Left click the Postman icon so you see the Postman toolbar at the top of your screen
>    ![Screen Shot 2020-01-13 at 10 44 36 AM](https://user-images.githubusercontent.com/31424007/72229416-bfd4b480-35f1-11ea-938d-728ce919f86f.png)
> 2. Click View -> Toggle Full Screen (the app window should appear in full screen mode)
>    ![Screen Shot 2020-01-13 at 10 45 32 AM](https://user-images.githubusercontent.com/31424007/72229428-d844cf00-35f1-11ea-8714-349000c9da8a.png)
> 3. Click the Open New icon (square box with + sign) and select Postman Window (a new (2nd), normal size window will appear that can be resized)
>    ![Screen Shot 2020-01-13 at 10 46 20 AM](https://user-images.githubusercontent.com/31424007/72229448-06c2aa00-35f2-11ea-987c-242ac785366e.png)
> 4. Right click the Postman Icon from your dock and you should see 2 Postman windows
> 
> <img alt="Screen Shot 2020-01-13 at 10 48 08 AM" width="171" src="https://user-images.githubusercontent.com/31424007/72229474-44273780-35f2-11ea-925f-d57ddebc4b4d.png">
> 
> 5. Click the Postman window that cannot be resized (it should show up full screen) and then close the window by clicking the red X icon.
>    ![Screen Shot 2020-01-13 at 10 47 42 AM](https://user-images.githubusercontent.com/31424007/72229491-6de05e80-35f2-11ea-9840-6722d47543cc.png)
> 
> Now you will have a working window that is resizable and movable. The broken window is closed and the issue does not persist.
> 
> The steps above are assuming you are able to Toggle Full Screen and see the window that cannot be found anywhere else to be resized.
> 
> I hope this helps someone.

Thank you sir, I still don't know what the benefit of this useless button to hide the window button :)
