### ISSUE TITLE
Cannot connect to Postman account since v5.6.0-canary01

### ISSUE THREAD

**Issue by chhahira** [a85/POSTMan-Chrome-Extension#3962]
I am not able to connect to my postman account after i updated my postman canary app.

**Comment by numaanashraf** [comment]
@chhahira Thanks for reporting this. Could you share a screenshot or steps to replicate the issue you faced?

**Comment by chhahira** [comment]
![2017-12-15_092945](https://user-images.githubusercontent.com/16698798/34017610-88c35ff0-e17a-11e7-9593-e9409e2b2063.png)

@numaanashraf Thanks for your reply.
I believe I started seeing the issue after i updated my postman canary app. Not able to login to my account since the update.
It says connecting and then goes offline after some time.
Surprisingly I am not able to connect to my account using postman chrome extension or the postman app. Not sure if this has anything to do with the update or just some problem with my postman account.

**Comment by chhahira** [comment]
@thecuriousdev @numaanashraf  the issue still remains....i have tried reinstalling postman, but no luck...still cannot connect to my postman account. Appreciate if you could take a look please. Thanks!

**Comment by imindrajit** [comment]
I too am facing the same issue. I have attached screenshots for reference.

Screenshot when trying to login via google account

<img width="1280" alt="screen shot 2017-12-17 at 11 15 10 pm" src="https://user-images.githubusercontent.com/3801358/34082225-5e00d0a6-e380-11e7-93e1-f469e5d037a8.png">

Next screen

<img width="1280" alt="screen shot 2017-12-17 at 11 15 16 pm" src="https://user-images.githubusercontent.com/3801358/34082231-718672fc-e380-11e7-92b5-77bd841e78a0.png">

**Comment by ssevern1** [comment]
Did you ever resolve this?  I'm seeing the same.

**Comment by imindrajit** [comment]
Remove ~/Library/Applications \Support/Postman directory and try to login again. The issue should be resolved.

**Comment by chhahira** [comment]
@imindrajit how can i remove the directory you mentioned. I could not find it in my system. I have the latest postman installed. APologies if this is a silly question. I am still not able to login to my postman account.

**Comment by MatthewRalston** [comment]
Hi, this is still an issue facing lots of users.

**Comment by safeer-ahmed** [comment]
So any workaround to get in Postman windows app?

**Comment by thecuriousdev** [comment]
@safeer-ahmed @MatthewRalston @chhahira @ssevern1 @imindrajit anyone still facing this issue?

**Comment by MatthewRalston** [comment]
As in the comments above **yes this is still an issue facing lots of users**

**Comment by safeer-ahmed** [comment]
It worked fine.

**Comment by chhahira** [comment]
any udpates please? how can i resolve this. Its really annoying that i cannot login to my postman.

**Comment by thecuriousdev** [comment]
Can you try updating the app to the latest version (6.1.2+), We've made a fix for this. Please let us know if you are still facing this issue.

**Comment by thecuriousdev** [comment]
Closing this issue for now, feel free to reopen if are facing any issues.
