### ISSUE TITLE
Collection Runner Hangs

### ISSUE THREAD

**Issue by mccannt** [a85/POSTMan-Chrome-Extension#4019]
## App Details:

```
Postman for Mac
Version 5.5.0 (5.5.0)
OS X 10.12.6 (16G29)
```

## Issue Report:
 1. Intermittently when stopping a run in the collection runner, it will hang the runner and gives the message "Stopping ...". This appears to stop the actual execution of the run, however the collection runner window does not reset and needs to be closed and reopened to continue. 
 2. Expected behaviour: I would expect the collection runner window to stop the run and reset consistently. 
 3. Console logs:
```
NOTE: Adding request 307de6b8-0dd8-a213-ad2d-b84da69a631f to force fetch
runner.js:203908 Error sanitizing order for collection:  TypeError: Cannot read property 'push' of undefined
    at child.addRemoteRequestsToFetch (runner.js:228991)
    at child.sanitizeOrder (runner.js:203904)
    at runner.js:203702
    at child._processRequests (runner.js:203808)
    at runner.js:203682
    at IDBRequest.cursorRequest.onsuccess (runner.js:234548)
sanitizeOrder @ runner.js:203908
runner.js:228988 NOTE: Adding request 925966bd-f2da-24ef-e3f9-a154352a6d01 to force fetch
runner.js:203908 Error sanitizing order for collection:  TypeError: Cannot read property 'push' of undefined
    at child.addRemoteRequestsToFetch (runner.js:228991)
    at child.sanitizeOrder (runner.js:203904)
    at runner.js:203702
    at child._processRequests (runner.js:203808)
    at runner.js:203682
    at IDBRequest.cursorRequest.onsuccess (runner.js:234548)
sanitizeOrder @ runner.js:203908
runner.js:247091 Errors were encountered running your collection: Object
```
 
4. Screenshots (if applicable):
![screenshot at jan 03 09-05-19](https://user-images.githubusercontent.com/14275144/34521730-afaa8b8a-f065-11e7-8743-7373907f79be.png)

**Comment by prashantagarwal** [comment]
@mccannt Thanks for reporting this. Does this happen for all your collections or just a particular one.

**Comment by mccannt** [comment]
@prashantagarwal Where its intermittent I cant say I see it on all of my collections, but I can say I have seen it happen on more than one.

**Comment by d-shenoy** [comment]
I am seeing the same thing. Mysteriously started happening with version 5.5.0 on mac exactly as described by others. If I look at the dev console, there isnt an API which is hanging waiting for a response. I am running it using the Collection Runner UI

**Comment by enguyen** [comment]
Exact same error, here, on same version of Postman and OSX. I see the error in the console immediately when I open Postman. The Collection runner shows a message in the UI when I try to run it: 

![image](https://user-images.githubusercontent.com/107458/35241978-2257bd5e-ff6d-11e7-8a6a-8726c38ba72d.png)

No new console messages are printed with this message, though.

UPDATE: Logging out, deleting all local state, and reinstalling Postman resulted in the same errors :/

**Comment by sivcan** [comment]
A new version of Postman i.e Postman 6 is out and I'd request you all to kindly update to the same.
Let us know if you are still facing this issue of Collection Runner Hanging and I'll reopen this issue.

**Comment by mccannt** [comment]
@sivcan I have been using the latest version of Postman (6.0.10) for a few weeks now and I am still seeing this happen often. 

Let me know if there is something I can gather to help with this.

**Comment by mccannt** [comment]
@sivcan @prashantagarwal  

So this is happening to a co-worker of mine now as well. 
I had him grab the Dev Console logs when this happened.
He is running on OSX as well using v6.1.3 of the Postman App.

Can we have this re-opened please?

`runner.js:9796 Errors were encountered running your collection: 
Object
message
:
"Cannot read property 'toString' of undefined"
name
:
"TypeError"
stack
:
"TypeError: Cannot read property 'toString' of undefined↵    at PostmanVariable.toString (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/collection/variable.js:108:34)↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/superstring/index.js:221:53↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/superstring/index.js:47:23↵    at String.replace (<anonymous>)↵    at SuperString.replace (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/superstring/index.js:45:34)↵    at Substitutor.parse (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/superstring/index.js:132:27)↵    at Function.replaceSubstitutions (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/collection/property.js:222:69)↵    at Function.<anonymous> (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/collection/property.js:253:25)↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/collection/property.js:247:40↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/node_modules/lodash/lodash.js:4944:15↵    at baseForOwn (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/node_modules/lodash/lodash.js:3001:24)↵    at Function.forOwn (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/node_modules/lodash/lodash.js:13002:24)↵    at Function.<anonymous> (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/collection/property.js:246:19)↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/collection/property.js:247:40↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/node_modules/lodash/lodash.js:4944:15↵    at baseForOwn (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/node_modules/lodash/lodash.js:3001:24)↵    at Function.forOwn (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/node_modules/lodash/lodash.js:13002:24)↵    at Function.<anonymous> (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/collection/property.js:246:19)↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/collection/property.js:247:40↵    at /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/node_modules/lodash/lodash.js:4944:15↵    at baseForOwn (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/node_modules/lodash/lodash.js:3001:24)↵    at Function.forOwn (/Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/node_modules/postman-collection/node_modules/lodash/lodash.js:13002:24)"
__proto__
:
Object
onEndRun	@	runner.js:9796`

**Comment by sivcan** [comment]
@mccannt I can see there are errors with the variables being used - `PostmanVariable.toString`

Are you able to run the same requests in the main request builder and not the collection runner?

Are there any errors there?

**Comment by mccannt** [comment]
@sivcan We can run these same requests in the Builder with no issues other than failed tests in some cases, but that is to be expected as we are testing 😄 
Outside of that no one has noticed any errors or odd behaviour with the app when using the builder. 

Only in the runner.

**Comment by sivcan** [comment]
@mccannt The fix has landed in the latest canary build: https://www.getpostman.com/canary
You can try it out.

**Comment by sivcan** [comment]
@mccannt As per the logs it looks like a similar issue that we've fixed in our recent release.

Can you [download the v6.2.2](https://www.getpostman.com/apps) and test it out if it fixes it for you?

**Comment by mccannt** [comment]
@sivcan So far so good. I have not run into this issue again in the latest release and I have not heard anything back from my teams about this being an issue still. 

Will let you know if this does return.

Thx.

**Comment by sivcan** [comment]
@mccannt That's great!
Let me know if this comes up again.

Closing this issue.

**Comment by Kevdog777** [comment]
Hi @sivcan,

I am getting this issue again in the latest version:

![image](https://user-images.githubusercontent.com/38526279/76082572-9efe5f00-5fa3-11ea-8606-9d873bfa0d1e.png)

I am running this on Windows 10.

I am afraid, I can't show my code due to company policy.

**Comment by mccannt** [comment]
@Kevdog777 Can you give us any more details on this?
Do you have any console errors or anything to help us?

Thx
