### ISSUE TITLE
401 unauthorized error for NTLM auth while running collection

### ISSUE THREAD

**Issue by apoorvaagrawal86** [a85/POSTMan-Chrome-Extension#4092]
## App Details:

```
Postman for Windows
Version 5.5.0
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Encountered this issue for the first time
 2. Expected behaviour: Running test collection with several GET and POST requests, gives 401 unauthorized error on certain iterations of the collection. Ideally, it should give 200 OK status since it executed correctly when executed individually.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): NA
 4. Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/34733289/35262334-3a6e1820-003a-11e8-8943-09e9a3132a7f.png)

Steps to Reproduce -

1. Create a collection with a GET and POST request.
2. The test scripts include validating a data value in an object using .csv data file. 
    pm.test("CheckProductName", function() {
    var jsonData = pm.response.json();
    pm.expect(jsonData.productList[data.pId].name).to.eql(data.productName);
    });
3. pId and productName are assigned values in a .csv data file.
4. Run the collection runner for 6 iterations (data file has 6 iterations to be validated).
5. On running the collection runner, the GET call starts from the 3rd iteration giving 401 unauthorized error. and the POST request call give the same error from the 5th iteration.

**Comment by sdnts** [comment]
@apoorvaagrawal86 This sounds like an issue with your CSV file. Does your CSV file have enough data for all 6 iterations?
Can you keep the Postman Console (Cmd/Ctrl+Alt+C) open during the run and verify if the calls outgoing are correct?
If they are, it would point to an issue with your server. Let me know if they're not.

**Comment by apoorvaagrawal86** [comment]
Hello Sid,

Thanks for the reply. I verified the csv file and it has complete data for all the 6 iterations. 

Please find the snapshot for 2 GET calls in the postman console. One returns 200 status whereas the other returns 401 status.
I am a novice in evaluating the api's, hence please let me know what all parameters should I look to identify the correctness of an api.

![image](https://user-images.githubusercontent.com/34733289/35551675-34e1a120-05b6-11e8-9d2e-f34e778768e7.png)

PS - I have hidden the URLs for copyright purpose.

csv file snapshot - 

![image](https://user-images.githubusercontent.com/34733289/35551731-7624dc88-05b6-11e8-80cc-45072a259f71.png)

**Comment by rustoleum76** [comment]
I encounter this same issue using NTLM and a Collection Runner.  I have documented the issue I encountered in the community forums, but seems to be the same issue.  I can see Status 200 for the first couple iterations, and then 401 for each thereafter.  I can run the tests individually, and I also found that if I run 2 iterations of the Collection, then 3 iterations, then all 407 I can get the full result set to complete.

https://community.getpostman.com/t/401-unauthorized-on-3rd-and-beyond-request-using-runner-to-iterate-through-csv/718/5

**Comment by rustoleum76** [comment]
has this been verified as a defect, yet?  Should I insert my own Issue report despite my issues appearing to be the same problem as 4092?  Thanks

**Comment by stefring** [comment]
I‘v run into the same issue, when Runner not using the .json  file, the result is fine, but with the data file upload, and there is a 401 error, have no idea how could this be ?? check in console, the head and the body is correct,  don't know why would this happen, has this been verified as a defect, and will it be fixed on the following release?

**Comment by rustoleum76** [comment]
has this been verified as a defect, yet? Should I insert my own Issue report despite my issues appearing to be the same problem as 4092? What can I do to help in the investigation of this?  I'd love to recommend to our management team Pro seats for this tool, but the Runner capability is a key feature that I can't use at the moment.  Thanks!

**Comment by Rob-DeRosia** [comment]
I am experiencing this same issue when using NTLM authentication and multiple iterations in the Runner. Each of my collections has the Authorization request as the first request in the collection. The first two iterations succeed, but the third iteration fails with a 401 Unauthorized and the Runner immediately ends running the tests, as pictured below.

![thirditeration401](https://user-images.githubusercontent.com/1385257/38576743-9c0a3444-3cc4-11e8-8917-a25b80d7bce0.png)

After looking at the Postman Console and reviewing the request headers on the Authorization requests from each iteration, **it appears that the Temporary Authentication headers are not being cleared between each run.**

I am currently on the Windows client, Postman v6.0.10. Please let me know if any additional information is required to troubleshoot this issue.

**Comment by ryanhoward1988** [comment]
Is there any progress on this yet? We are experiencing the same issue and are really keen to find a resolution to this.
If we can do anything to help this investigation then please let me know

**Comment by ragoutje** [comment]
+1 for a solution to this issue.

It always happens on the third and further requests run in the collection runner. When running 3 or more requests from Postman one by one this does not occur.

I found that the 3rd request in the runner receives a different response header:
> www-authenticate:
> 0:"NTLM"
> 1:"Negotiate"

It seems to be related.

Edit:
The 1st and 2nd requests do not receive this response header.

**Comment by andmill** [comment]
+1 seeing the same recently as well whilst using runner.

**Comment by susikka** [comment]
I faced this issue too. A POST request in my collection has a script. This request executed fine when run using the **SEND** button but returned 401 Unauthorized with collection runner. 

I tried removing the script in the POST request and run the collection again. The POST request executed fine(returned 201 Created). Then I re-added the script in the request and executed the collection again and request worked again.

All other requests in the collection(that do not have any script), still return 401 Unauthorized.

These requests use OAuth2.0 for authentication.

**Comment by susikka** [comment]
@madebysid Any progress on this ? Got some really urgent stuff that is stuck because of this issue. Would help if this could be resolved asap.

**Comment by shahidhafiz** [comment]
I found if you don't use inherit from parent for the authorization on each api call you get a 200 OK reliably. NTML Authentication [Beta] feel like its not stable enough.

**Comment by seancummins1** [comment]
I got around this issue by changing my test.
I was getting the issue when I had my test as the below.

**tests["Status code is 200"] = responseCode.code === 200;**

After changing it to the following I stopped getting the error on the 3rd iteration and all now pass.
**tests["Status code is 200"] = responseCode.code === 200 || responseCode.code === 400;**

**Comment by Bakerstreetsoriginal** [comment]
Facing this issue as well currently, oddly though, it's only for the first 5 calls in the runner that use a fresh auth token.

The token is valid, I've double checked it in in the request headers.

**Comment by seancummins1** [comment]
If you save test case then run the test case it should error because of your variables in the body. If you then run the collection it should work for all requests.

**Comment by sivcan** [comment]
@ryanhoward1988 @Bakerstreetsoriginal @seancummins1 
Apologies for the late response.

Can you guys verify if the same is happening for you if you run the collection using [Newman](https://github.com/postmanlabs/newman)?
Let me know, thanks!

**Comment by ryanhoward1988** [comment]
@sivcan Yes the same is happening via newman
The first 2 iterations return HTTP 200 the following iterations all return HTTP 401

**Comment by WillemKeesman** [comment]
Ran into this issue as well. And finally found what caused it.
The bearer token was set automatically as an authorization header in Postman. Newman can not process it for the first POST call and therefore the whole collection will fail.

How i solved it:
manually created a Bearer token in  the authorization header of the 1st Post call.. Note that the token can still be fetched from an environment or global variable. After changing the first header all other calls ran smooth as well.

**Comment by RobbyDeLaet** [comment]
@susikka Any progression on this issue?

I can run a collection with 2 requests with NTLM authentication. When I add a third request, this request will fail with a 401.

In the developers console I see:
 three http calls for the first request
 two http calls for the second request
 one http call for the third request

**Comment by ryanhoward1988** [comment]
Has any else noticed that this issue appears to have gotten worse. I used to see this issue on the third iteration of a collection and then everything after that. I now seem to see it on third request of the first iteration and then everything after that...

i am using v 6.5.2

**Comment by neumann1990** [comment]
@sivcan Pinging again to keep visibility on this issue. I've just run into the same problem myself.

**Comment by thinklarge** [comment]
Just so this gets more awareness I'd say I'm getting this too. 

The temp fix that has worked is @shahidhafiz suggestion to not use Inherit From Parent. 

Another fix that worked for me is, if I have the runner open and I manually fire a single request from the collection (not runner), the whole chain works.  This won't work for Newman.

**Comment by dbasargin** [comment]
+1 Here. 
I too am experiencing this with NTLM Authorization.

While iterating over a JSON file In the collection runner and from the command line, 
after the second iteration all following requests receive a 401 unauthorized.

Postman Version is up to date: v6.7.2

I do notice: If I add NTLM Authentication headers at the Collection level, then Inherit from parent in all requests, all requests fail. If I add NTLM Authentication at the collection level and for every request in the collection, I get this behaviour where all requests in the collection for the first two iterations of my data file succeed and the rest fail.

**Comment by andmill** [comment]
I've given up and moved to a Java framework using apache http client and testNG. Working like a charm, runs from the command line in Jenkins using maven. All open source so no yearly cost to the company from Postman enterprise. More difficult to implement but the benefits far outweigh that. For starters, it works! Also, I can validate csv and xml files easily as well as DB validation.

**Comment by numaanashraf** [comment]
@dbasargin Could you verify whether you are facing the same issue while running the collection via newman? https://github.com/postmanlabs/newman#newman-run-collection-file-source-options

**Comment by dbasargin** [comment]
> @dbasargin Could you verify whether you are facing the same issue while running the collection via newman? https://github.com/postmanlabs/newman#newman-run-collection-file-source-options

Hi Numaan,
I have verified that, yes, I am experiencing this with both newman and the collection runner.

**Comment by susikka** [comment]
@numaanashraf I too tried running my collection with newman. As was the case with the collection runner, with newman too only the first request was successfully executed, all others failed with HTTP 401.

This issue has been lingering for a long time now. Do we have a timeline by when we can expect this issue to be fixed ?

**Comment by andmill** [comment]
@numaanashraf same here. Issues in collection runner and newman. Tried on both windows machines and Linux servers.

**Comment by harryi3t** [comment]
@codenirvana I was able to reproduce this using newman too
Here's a collection which has 1 request with NTLM auth [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/dd639df2a35ee6862740)
```bash
newman run -n 5 https://www.getpostman.com/collections/dd639df2a35ee6862740
```
<img width="572" alt="harryi3t_harendras-macbook-pro____work_postman_postman-app__zsh_" src="https://user-images.githubusercontent.com/5207331/52909571-919b0780-32b0-11e9-8fb4-5f2dec5f99b1.png">

**Comment by codenirvana** [comment]
We've released a fix for this on our Canary (`version: 7.1.0-canary01`) channel https://www.getpostman.com/canary

Please try it out in the Canary version and let us know if you continue to face the issue.
Will update the thread once we release the fix on our stable channel.

**Comment by andmill** [comment]
Hey @codenirvana, what about newman for automated runs?

**Comment by codenirvana** [comment]
@andmill Its fixed in the latest version of Newman as well!

**Comment by thbaid** [comment]
Hi, Please clarify the version of Postman that was fixed to successfully run a collection having multiple API tests without generating 401 token issue error ?  I have latest pm version and still get 401 errors .

You are up to date! Postman v7.0.7 is the latest version.

**Comment by codenirvana** [comment]
@thbaid As mentioned https://github.com/postmanlabs/postman-app-support/issues/4092#issuecomment-477782259 its fixed in Postman Canary https://www.getpostman.com/canary

This will be fixed in the next release of the Postman App.

**Comment by dbasargin** [comment]
I tested this in the latest Canary Version. This is working nicely for me. Thank you for update. Does 7.1 have a target release date?

**Comment by codenirvana** [comment]
This has been fixed in the latest Postman app.

**Comment by anandhakrishnan85** [comment]
This issue still exists in latest version of Postman app (v7.10.0)

**Comment by SKvasnytsia** [comment]
Hi, facing the same issue. Using NTLM Authorisation. When running Postman collection, getting 401 on the third request. Postman Version: 7.22.1

**Comment by coditva** [comment]
> getting 401 on the third request.

@SKvasnytsia your case seem to be similar to #7747. We're tracking this issue. Will update there when we have a fix.
