### ISSUE TITLE
get & put collection API

### ISSUE THREAD

**Issue by galbarm** [a85/POSTMan-Chrome-Extension#4229]
Hello, I'm a pro user, trying to design a workflow for updating collections through the API. 
Specifically, I'm trying to replace the content of collection B with the content of collection A (without creating new collections, to keep the published url the same).

To do this I'm: 
1. performing a get request on collection A. 
2. Copying the body of the result and pasting it as the body of a put request on collection B.

I noticed that I have to change {"collection":{"info":{"_postman_id"}}} field to the id of collection B to make it work, and it makes sense. 
But surprisingly this is not all I had to do: 
I had to remove all fields with "_postman_id" or "id" keys. 
And also had to change a field "description": null, to "description": "", since the server didn't like the appearance of a null value. (although it appeared like that in the response of the get of collection A)

Since I'm writing a procedure to perform these actions automatically, I'd like to follow a guideline and not to "guess" the details. 
But couldn't find any information in the docs.

Thanks for the help.

**Comment by deepakpathania-zz** [comment]
Hey @galbarm, sorry for the delayed response. This has been fixed from our end. 

Now, if you pass any collection body in a create endpoint, we take care of retracting all the ids for you so that you can use the response of `/get/{{colection_id}}` and chain it to a collection create without any additional efforts.

Can you please verify and let me know if it works for you? Thanks.

**Comment by galbarm** [comment]
Still not working for some collections.
I have a collection that I'm performing GET on, then simply copying the response body to a POST collection request, but the response I get from the POST request is 400:

```
{
    "error": {
        "name": "malformedRequestError",
        "message": "Data does not match any schemas from \"oneOf\" at item.0"
    }
}
```

**Comment by deepakpathania-zz** [comment]
Hey @galbarm, do you mind sharing the collection body you're using to make the POST request, feel free to retract the sensitive data.

**Comment by galbarm** [comment]
Here it is:

`{
    "collection": {
        "info": {
            "_postman_id": "2eafddce-9bfb-4383-85de-0bfc5d31b5a3",
            "name": "Photos",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "item": [
            {
                "_postman_id": "62b01cd5-962e-439c-a7ee-76fc14651e8e",
                "name": "Files Operations",
                "description": "",
                "item": [
                    {
                        "_postman_id": "6fe74cd8-d75a-4f5b-a5c4-a1459686f0e7",
                        "name": "Get File Upload URL",
                        "event": [
                            {
                                "listen": "test",
                                "script": {
                                    "id": "34c2c12f-ae8c-4c62-87d2-2dbc75747557",
                                    "type": "text/javascript",
                                    "exec": [
                                        "var jsonData = JSON.parse(responseBody);",
                                        "postman.setEnvironmentVariable(\"uploadUrl\",jsonData.url);"
                                    ]
                                }
                            }
                        ],
                        "request": {
                            "method": "GET",
                            "header": [
                                {
                                    "key": "Authorization",
                                    "value": "Bearer {{accessToken}}"
                                },
                                {
                                    "key": "X-Account-ID",
                                    "value": "{{accountToken}}"
                                }
                            ],
                            "body": {
                                "mode": "raw",
                                "raw": ""
                            },
                            "url": {
                                "raw": "{{protocol}}://{{host}}/api/photos/upload-url?filename={{filename}}",
                                "protocol": "{{protocol}}",
                                "host": [
                                    "{{host}}"
                                ],
                                "path": [
                                    "api",
                                    "photos",
                                    "upload-url"
                                ],
                                "query": [
                                    {
                                        "key": "filename",
                                        "value": "{{filename}}",
                                        "equals": true
                                    }
                                ]
                            },
                            "description": "Returns a new upload url for upload file"
                        },
                        "response": [
                            {
                                "id": "1c2e6c45-ba99-47dc-9cdf-bdfcf30b4663",
                                "name": "Get Image Upload Url",
                                "originalRequest": {
                                    "method": "GET",
                                    "header": [
                                        {
                                            "key": "Authorization",
                                            "value": "Bearer {{accessToken}}",
                                            "disabled": false
                                        },
                                        {
                                            "key": "X-Account-ID",
                                            "value": "{{accountToken}}",
                                            "disabled": false
                                        }
                                    ],
                                    "body": {
                                        "mode": "raw",
                                        "raw": ""
                                    },
                                    "url": {
                                        "raw": "{{protocol}}://{{host}}/api/photos/upload-url?filename={{filename}}",
                                        "protocol": "{{protocol}}",
                                        "host": [
                                            "{{host}}"
                                        ],
                                        "path": [
                                            "api",
                                            "photos",
                                            "upload-url"
                                        ],
                                        "query": [
                                            {
                                                "key": "filename",
                                                "value": "{{filename}}",
                                                "equals": true
                                            }
                                        ]
                                    }
                                },
                                "status": "OK",
                                "code": 200,
                                "_postman_previewlanguage": "json",
                                "header": [
                                    {
                                        "key": "Content-Encoding",
                                        "value": "gzip",
                                        "name": "Content-Encoding",
                                        "description": "The type of encoding used on the data."
                                    },
                                    {
                                        "key": "Content-Length",
                                        "value": "419",
                                        "name": "Content-Length",
                                        "description": "The length of the response body in octets (8-bit bytes)"
                                    },
                                    {
                                        "key": "Content-Type",
                                        "value": "application/json",
                                        "name": "Content-Type",
                                        "description": "The mime type of this content"
                                    },
                                    {
                                        "key": "Date",
                                        "value": "Tue, 03 Jul 2018 04:25:06 GMT",
                                        "name": "Date",
                                        "description": "The date and time that the message was sent"
                                    },
                                    {
                                        "key": "Vary",
                                        "value": "Origin,Accept-Encoding",
                                        "name": "Vary",
                                        "description": "Tells downstream proxies how to match future request headers to decide whether the cached response can be used rather than requesting a fresh one from the origin server."
                                    },
                                    {
                                        "key": "X-Request-ID",
                                        "value": "63a98dd6-bd67-4840-8ce5-fed16308051d",
                                        "name": "X-Request-ID",
                                        "description": "Custom header"
                                    }
                                ],
                                "cookie": [],
                                "responseTime": null,
                                "body": "{\"url\":\"https://xxx\",\"headers\":{\"x-amz-server-side-encryption\":\"AES256\"}}"
                            }
                        ]
                    },
                    {
                        "_postman_id": "fbf733f8-cc32-424a-9122-60acbf3c29d1",
                        "name": "Upload File",
                        "request": {
                            "method": "PUT",
                            "header": [
                                {
                                    "key": "x-amz-server-side-encryption",
                                    "value": "AES256"
                                }
                            ],
                            "body": {
                                "mode": "file",
                                "file": {
                                    "src": null
                                }
                            },
                            "url": {
                                "raw": "{{uploadUrl}}",
                                "host": [
                                    "{{uploadUrl}}"
                                ]
                            },
                            "description": "Upload file request template. 'uploadUrl' variable is set automatically after calling \"Get File Upload URL\""
                        },
                        "response": []
                    },
                    {
                        "_postman_id": "95694f16-b685-4f6f-b592-fb286103aa60",
                        "name": "Get File Download URL",
                        "event": [
                            {
                                "listen": "test",
                                "script": {
                                    "id": "4f345f03-1890-40fb-b6c8-b42ee0c8dc1c",
                                    "type": "text/javascript",
                                    "exec": [
                                        "var jsonData = JSON.parse(responseBody);",
                                        "postman.setEnvironmentVariable(\"downloadUrl\",jsonData.url);"
                                    ]
                                }
                            }
                        ],
                        "request": {
                            "method": "GET",
                            "header": [
                                {
                                    "key": "Authorization",
                                    "value": "Bearer {{accessToken}}"
                                },
                                {
                                    "key": "X-Account-ID",
                                    "value": "{{accountToken}}"
                                }
                            ],
                            "body": {
                                "mode": "raw",
                                "raw": ""
                            },
                            "url": {
                                "raw": "{{protocol}}://{{host}}/api/photos/download-url?fileID={{fileID}}",
                                "protocol": "{{protocol}}",
                                "host": [
                                    "{{host}}"
                                ],
                                "path": [
                                    "api",
                                    "photos",
                                    "download-url"
                                ],
                                "query": [
                                    {
                                        "key": "fileID",
                                        "value": "{{fileID}}",
                                        "equals": true
                                    }
                                ]
                            },
                            "description": "Returns a new download URL by file ID."
                        },
                        "response": []
                    },
                    {
                        "_postman_id": "809d87e0-210c-4db9-b31e-55f327ca377a",
                        "name": "Download File",
                        "request": {
                            "method": "GET",
                            "header": [],
                            "body": {
                                "mode": "file",
                                "file": {
                                    "src": null
                                }
                            },
                            "url": {
                                "raw": "{{downloadUrl}}",
                                "host": [
                                    "{{downloadUrl}}"
                                ]
                            },
                            "description": "Download file request template. 'downloadUrl' variable is set automatically after calling \"Get File Download URL\""
                        },
                        "response": []
                    },
                    {
                        "_postman_id": "51fb3242-26ca-4754-90fe-bb86f94d6a83",
                        "name": "Get  File Delete URL",
                        "event": [
                            {
                                "listen": "test",
                                "script": {
                                    "id": "bca30ef6-3583-49f5-b059-5b0c20c2552b",
                                    "type": "text/javascript",
                                    "exec": [
                                        "var jsonData = JSON.parse(responseBody);",
                                        "postman.setEnvironmentVariable(\"deleteUrl\",jsonData.url);"
                                    ]
                                }
                            }
                        ],
                        "request": {
                            "method": "GET",
                            "header": [
                                {
                                    "key": "Authorization",
                                    "value": "Bearer {{accessToken}}"
                                },
                                {
                                    "key": "X-Account-ID",
                                    "value": "{{accountToken}}"
                                }
                            ],
                            "body": {
                                "mode": "raw",
                                "raw": ""
                            },
                            "url": {
                                "raw": "{{protocol}}://{{host}}/api/photos/delete-url?fileID={{fileID}}",
                                "protocol": "{{protocol}}",
                                "host": [
                                    "{{host}}"
                                ],
                                "path": [
                                    "api",
                                    "photos",
                                    "delete-url"
                                ],
                                "query": [
                                    {
                                        "key": "fileID",
                                        "value": "{{fileID}}",
                                        "equals": true
                                    }
                                ]
                            },
                            "description": "Returns a new delete URL by file ID."
                        },
                        "response": []
                    },
                    {
                        "_postman_id": "3327435b-55de-43f7-9c97-ea6eadd9929b",
                        "name": "Delete File",
                        "event": [
                            {
                                "listen": "test",
                                "script": {
                                    "id": "92030dc1-f5f2-46e0-ab80-89ad936582a4",
                                    "type": "text/javascript",
                                    "exec": [
                                        ""
                                    ]
                                }
                            }
                        ],
                        "request": {
                            "method": "DELETE",
                            "header": [],
                            "body": {
                                "mode": "raw",
                                "raw": ""
                            },
                            "url": {
                                "raw": "{{deleteUrl}}",
                                "host": [
                                    "{{deleteUrl}}"
                                ]
                            },
                            "description": "Delete file request template. deleteUrl variable is set automatically after calling \"Get File Delete URL\""
                        },
                        "response": []
                    }
                ]
            },
            {
                "_postman_id": "f08e460b-16c2-45fc-b889-74e241edefdb",
                "name": "Files Queries",
                "description": "",
                "item": [
                    {
                        "_postman_id": "3735642b-30e4-4ddd-889a-6e3e145d81e8",
                        "name": "Get Files",
                        "event": [
                            {
                                "listen": "test",
                                "script": {
                                    "id": "804cc3c5-8e48-4308-a2a1-006c5a316b4c",
                                    "type": "text/javascript",
                                    "exec": [
                                        "var jsonData = JSON.parse(responseBody);",
                                        "postman.setEnvironmentVariable(\"nextPage\",jsonData.nextPage);"
                                    ]
                                }
                            }
                        ],
                        "request": {
                            "method": "GET",
                            "header": [
                                {
                                    "key": "Authorization",
                                    "value": "Bearer {{accessToken}}"
                                },
                                {
                                    "key": "X-Account-ID",
                                    "value": "{{accountToken}}"
                                }
                            ],
                            "body": {
                                "mode": "raw",
                                "raw": ""
                            },
                            "url": {
                                "raw": "{{protocol}}://{{host}}/api/photos/gallery?pageSize={{pageSize}}",
                                "protocol": "{{protocol}}",
                                "host": [
                                    "{{host}}"
                                ],
                                "path": [
                                    "api",
                                    "photos",
                                    "gallery"
                                ],
                                "query": [
                                    {
                                        "key": "pageSize",
                                        "value": "{{pageSize}}",
                                        "equals": true
                                    }
                                ]
                            },
                            "description": "Returns list of files with the size of `pageSize` query param and nextPage ticket which can be used in \"Get Next Page\" request.\nThis request API will be expand to support a wide range of query criterias."
                        },
                        "response": []
                    },
                    {
                        "_postman_id": "48758ddb-f5c4-45d9-a1cb-5d3cca5537a7",
                        "name": "Get File With Next Page",
                        "event": [
                            {
                                "listen": "test",
                                "script": {
                                    "id": "a65f25a2-841b-44a4-9eda-fab44d3ded2d",
                                    "type": "text/javascript",
                                    "exec": [
                                        "var jsonData = JSON.parse(responseBody);",
                                        "postman.setEnvironmentVariable(\"nextPage\",jsonData.nextPage);"
                                    ]
                                }
                            }
                        ],
                        "request": {
                            "method": "GET",
                            "header": [
                                {
                                    "key": "Authorization",
                                    "value": "Bearer {{accessToken}}"
                                },
                                {
                                    "key": "X-Account-ID",
                                    "value": "{{accountToken}}"
                                }
                            ],
                            "body": {
                                "mode": "raw",
                                "raw": ""
                            },
                            "url": {
                                "raw": "{{protocol}}://{{host}}/api/photos/gallery?nextPage={{nextPage}}",
                                "protocol": "{{protocol}}",
                                "host": [
                                    "{{host}}"
                                ],
                                "path": [
                                    "api",
                                    "photos",
                                    "gallery"
                                ],
                                "query": [
                                    {
                                        "key": "nextPage",
                                        "value": "{{nextPage}}",
                                        "equals": true
                                    }
                                ]
                            },
                            "description": "Returns page of files accroding to `nextPage` value from the previous request."
                        },
                        "response": []
                    },
                    {
                        "_postman_id": "076f4ddd-6f68-430b-bbf7-3da1b9e2d2f6",
                        "name": "Get File",
                        "event": [
                            {
                                "listen": "test",
                                "script": {
                                    "id": "804cc3c5-8e48-4308-a2a1-006c5a316b4c",
                                    "type": "text/javascript",
                                    "exec": [
                                        "var jsonData = JSON.parse(responseBody);",
                                        "postman.setEnvironmentVariable(\"nextPage\",jsonData.nextPage);"
                                    ]
                                }
                            }
                        ],
                        "request": {
                            "method": "GET",
                            "header": [
                                {
                                    "key": "Authorization",
                                    "value": "Bearer {{accessToken}}"
                                },
                                {
                                    "key": "X-Account-ID",
                                    "value": "{{accountToken}}"
                                }
                            ],
                            "body": {
                                "mode": "raw",
                                "raw": ""
                            },
                            "url": {
                                "raw": "{{protocol}}://{{host}}/api/photos/gallery/{{fileID}}/info",
                                "protocol": "{{protocol}}",
                                "host": [
                                    "{{host}}"
                                ],
                                "path": [
                                    "api",
                                    "photos",
                                    "gallery",
                                    "{{fileID}}",
                                    "info"
                                ]
                            },
                            "description": "Returns file full information by file ID."
                        },
                        "response": []
                    }
                ]
            },
            {
                "_postman_id": "38bac095-acda-487b-9415-95d044c93709",
                "name": "Thumbnails",
                "description": "",
                "item": [
                    {
                        "_postman_id": "930c8ea4-0044-4ae2-9dee-e921aa96f329",
                        "name": "Get Thumbnail",
                        "event": [
                            {
                                "listen": "test",
                                "script": {
                                    "id": "6b084a1f-e61b-45f8-b35e-7dcbfb842fa2",
                                    "type": "text/javascript",
                                    "exec": [
                                        "var jsonData = JSON.parse(responseBody);",
                                        "postman.setEnvironmentVariable(\"thumbnailUrl\",jsonData.url);"
                                    ]
                                }
                            }
                        ],
                        "request": {
                            "method": "GET",
                            "header": [
                                {
                                    "key": "Authorization",
                                    "value": "Bearer {{accessToken}}"
                                },
                                {
                                    "key": "X-Account-ID",
                                    "value": "{{accountToken}}"
                                }
                            ],
                            "body": {
                                "mode": "raw",
                                "raw": ""
                            },
                            "url": {
                                "raw": "{{protocol}}://{{host}}/api/photos/thumbnails/{{fileID}}?desired_width={{desired_width}}",
                                "protocol": "{{protocol}}",
                                "host": [
                                    "{{host}}"
                                ],
                                "path": [
                                    "api",
                                    "photos",
                                    "thumbnails",
                                    "{{fileID}}"
                                ],
                                "query": [
                                    {
                                        "key": "desired_width",
                                        "value": "{{desired_width}}",
                                        "equals": true
                                    }
                                ]
                            },
                            "description": "Returns thumbnail download URL by file ID and desired thumbnail width."
                        },
                        "response": []
                    },
                    {
                        "_postman_id": "2838b582-cadf-47c1-9df9-20c96b7aa939",
                        "name": "Download Thumbnail",
                        "request": {
                            "method": "GET",
                            "header": [],
                            "body": {},
                            "url": {
                                "raw": "{{thumbnailUrl}}",
                                "host": [
                                    "{{thumbnailUrl}}"
                                ]
                            },
                            "description": "Download thumbnail request template. 'thumbnailUrl' variable is set automatically after calling \"Get Thumbnail\""
                        },
                        "response": []
                    }
                ]
            }
        ]
    }
}`

**Comment by deepakpathania-zz** [comment]
Hey @galbarm, I was able to reproduce the issue on my end, thanks for sharing the collection. Will push out a fix soon and update here.

**Comment by deepakpathania-zz** [comment]
Hey @galbarm, thank you for your patience. The issue has been fixed from our end, can you please verify and let me know if it works for you now?

**Comment by galbarm** [comment]
seems to be working now

**Comment by zankhanarana9** [comment]
Hi, I am facing a similar issue. I am trying to run a collection that checks the response status and time elapsed for the requests in the data file. I am sending a POST request first and then a GET. I get 404 not found for the GET request. It works fine if all the requests are POST in the data file.

**Comment by deepakpathania-zz** [comment]
Hey @zankhanarana9, do you mind opening a separate issue with more details? Thanks.
