### ISSUE TITLE
resync popups that make no sense

### ISSUE THREAD

**Issue by paulRonanRLS** [a85/POSTMan-Chrome-Extension#4360]
## App Details:

```
Postman for Mac
Version 6.0.10
OS X 16.4.0 / x64
```

## Issue Report:
 Ths issue has begun in the last week or so
A popup appears suggesting that a  resync conflict decision is required (screen shot attached)
 top line of application has SYNCING permanently displayed

![screen shot 2018-03-20 at 15 23 45](https://user-images.githubusercontent.com/18261772/37664567-7a79dd7e-2c53-11e8-9978-52c2e8124723.png)

**Comment by nithyamuth** [comment]
Getting the same issue - resync every now and then.

**Comment by ghelton** [comment]
Also started experiencing this issue repeatedly today. Same version of postman. One thing to note is that in between modal popups the syncing icon never switches back to Synced:
![screen shot 2018-03-20 at 2 58 43 pm](https://user-images.githubusercontent.com/48418/37685089-6abc43a8-2c4f-11e8-9e3e-3f5158f092df.png)

**Comment by ianedmo** [comment]
I'm also getting this issue (same version but for Windows). The 'Resolve Sync Conflicts' popup is appearing multiple times throughout the day and never seems to successfully sync.

**Comment by Simbosan** [comment]
+1 as described above

**Comment by Aaargh20318** [comment]
Same. As far as I know I never even opted-in to syncing and I can't find where I can disable it.

**Comment by joelclouddistrict** [comment]
+1

**Comment by dbethel** [comment]
This is happening every few minutes for me at this point with the same version on my mac. Is crazy that you can't even disable the sync.

**Comment by zoso200** [comment]
Also getting this on Windows v6.0.10 and seeing the Syncing icon stay blue perpetually as noted by GrantCodesCodes

**Comment by Simbosan** [comment]
Still happening.  I was going to try logging out and back in but the scary warning about deleting all my work put me off

**Comment by Simbosan** [comment]
Uninstalling and re-installing didn't fix.  Here's how I got it working (version 6.0.10) .

1) Settings Menu.
2) Select Data tab
3) Export Data.  This dumps ALL settings into JSON
4) Log out and let it delete all data 
5) Log in again.  It will sync old data from the last time you successfully sync'd
5) Then via the Settings > Data tab, Import data.   You will have the option to replace collections that already have been sync'd.   Do whatever is appropriate for you.

This got me syncing again.

**Comment by IrynaRus** [comment]
I have the same issue. 
Unfortunately, I haven't read the last comment earlier, so I tried to log out and in again and lost several days of my work as it appeared not to be synced. So, don't do that.
Now, when I logged in it says "Connecting", but actually can't connect to get what's on the server.
![2018-03-29_14-59-02](https://user-images.githubusercontent.com/37125239/38070190-63fbc1ec-3366-11e8-9b72-6e14e7903440.png)
![2018-03-29_15-30-56](https://user-images.githubusercontent.com/37125239/38070191-642db88c-3366-11e8-85d3-2f969cebaca2.png)
![2018-03-29_15-31-29](https://user-images.githubusercontent.com/37125239/38070192-645d31e8-3366-11e8-90dc-5f83ad6cbfc9.png)

**Comment by shawnsolo** [comment]
Same issue

**Comment by kamalaknn** [comment]
Hi everyone,

Sorry for the delayed response. We've identified the issue with conflicts in history. We'll be pushing the fix out on our Canary channel soon. 

I'll update this thread when the fix is out.

**Comment by crysislinux** [comment]
What's the status now? I think it's a major problem and should be put on top of the priority list. Is the issue a server side problem or client side problem and do we need to update the client to fix it?

**Comment by tarcom** [comment]
This issue is a bit of a pain in the but. Looking forward for a fix, or a way of turning off the sync.

**Comment by NanoPish** [comment]
Major issue

**Comment by IrynaRus** [comment]
Hi guys!
Can you please update what's the status of this problem? My tests haven't been synced since 4th of April  and I see that pop-up with conflicts every 5 minutes or so. It's all just waiting for any trouble or crash to lost all my work. I'm exporting my data every day, but I don't think that this is a good solution.
Waiting for good news.
![image](https://user-images.githubusercontent.com/37125239/39105769-0c9032c8-46fb-11e8-8f9a-a97def05b4d8.png)

**Comment by georgedpeterson** [comment]
Same issue.

**Comment by DedMorozzz** [comment]
each 15 mins I got a message about "sync conflict", how i can disable syncing?

**Comment by crysislinux** [comment]
I logged out and login again, the problems seems gone.

**Comment by zoso200** [comment]
Update: I exported all collections, logged out and logged back in and imported all collections back in. This has fixed the sync issue for me.

**Comment by matthuhman** [comment]
Sync conflicts are now showing up for me every < 5 minutes. How soon can we expect a fix?

**Comment by alexlvcom** [comment]
Same issue for me. Already a month, very annoying. Having it with two different computers and accounts.

**Comment by yura-arab4uk** [comment]
Please fix this bug! It's pretty annoying!

**Comment by kamalaknn** [comment]
Sorry for the delayed response here. We've pushed the fix to our canary channel. You can download the Canary version from https://www.getpostman.com/canary

I understand that you'll not have local changes that weren't synced on the stable app. We will be pushing this fix to the stable channel very soon.

I'll post updates to this thread once the fix is out on stable channel.

Thanks for understanding.

**Comment by cwarren** [comment]
Looking forward to getting this fix on stable

**Comment by Kallaste** [comment]
I am very much looking forward to it too.

**Comment by gui-moreira** [comment]
I am having the same issue

**Comment by alexstulov** [comment]
Would be very nice to have this fix.

**Comment by bobbyyumm** [comment]
I there a way to retrieve lost work, due to sync issue? i have lost 2 + days of work over 122 endpoints... when i login to my account its shows no activity past may 7th...

**Comment by Kallaste** [comment]
I have been using Canary for the past few days and it works perfectly. No sync problems. I just exported my collection data into it and it was just like being in stable (except blue, so that's nice).

**Comment by DedMorozzz** [comment]
can you push fix from Canary into stable version? This problem exists more then 2 monthes

**Comment by panuoksala** [comment]
Same issue here. Pretty much pushes me off from Postman currently.

**Comment by DedMorozzz** [comment]
@panuoksala new version without this problem

**Comment by panuoksala** [comment]
Not for me. Version v6.0.10. Everytime I start-up Postman this pops-up.
![image](https://user-images.githubusercontent.com/15687235/40219041-7c3b303e-5a7c-11e8-8745-edc1a8fb803e.png)

**Comment by sergioverde90** [comment]
Same. v6.0.10 still shows the pop-up every time.

**Comment by sivcan** [comment]
@panuoksala @sergioverde90 - I suggest that you try out the latest canary builds since it contains the fix for the same: https://www.getpostman.com/canary

If you have tried it out on the latest canary build and still the problem persists then let us know.

**Comment by sivcan** [comment]
The new stable version has been released i.e **v6.1.2** and it fixes this issue.
Kindly update to the same.

**Comment by cwarren** [comment]
I would love to update, but the update button just brings up a 404 - https://www.getpostman.com/docs/v6/updating#linux

**Comment by sivcan** [comment]
@cwarren - You can download the apps from here: https://www.getpostman.com/apps
Also, since I can see that you're a linux user - there's an extra addition in the release that it brings auto updates to linux also.

**Comment by AartiTewari** [comment]
@kamalaknn The have upgraded postman to v6.1.3 and started facing syncing issues. The changes made by me yesterday on same version but different instance of postman( using different laptop) are not synced when I opened the postman today on my work laptop (upgraded to same version).
The manual sync option is also disabled.

Please have a look

**Comment by thetreythomas** [comment]
Windows 10 Pro

Postman for Windows
Version 6.1.3
win32 10.0.17134 / x64

Still seeing this issue. I've seen this pop-up now 4 times in the last 5 hours.

**Comment by rstrauss-logyx** [comment]
I am having the same problem on 6.1.3 on a Mac.
Logging out, restarting and logging in stopped the alerts.

**Comment by ianedmo** [comment]
I've been having the same problem on 6.1.3 on Windows. 
Word of warning - I did the same as the comment above but when I've logged back in all my work from yesterday is gone, despite clicking the sync button many times yesterday.

**Comment by zoso200** [comment]
Had a sync issue on one of my environments which I fixed by exporting the environment, re-starting the application and then importing the environment. 

I can only say from my experience but this happened when I was making multiple changes to collections and environments - it seems that sync is just tripping up when too much is going on at once? Had no issues since for the past few weeks prior to yesterday.

**Comment by mpawlow** [comment]
+1 
Experiencing the same problem on the following platform:
-  Postman: v6.1.3 
-  OS Name: Microsoft Windows 10 Enterprise
-  OS Version: 10.0.16299 N/A Build 16299
-  System Type: x64-based PC

**Comment by mmothers** [comment]
This issue occurred for the first time on my PC
- Postman: v6.1.3
- MS Win 10 enterprise / x64
- I updated to 6.1.3 last week.  Nothing changed today other than this error.

I'm getting similar to history but for environment instead.   Whenever I open postman app, I get the sync error.  Clicking sync button does nothing.  Tried syncing w local or server selected. same thing.  I ran a collection test, quit postman, restarted and now seems ok.  Weird.

I'm not using Pro and always wondered what was actually syncing.  From what I understand, the non-Pro accounts would simply save to local PC.  So why even sync for non-Pro?   confused.

**Comment by kamalaknn** [comment]
Hi, 

This issue seems to be diverging a bit now. The original issue where conflict modals showed up for history requests has been fixed and released to the production channel.

I'm closing this issue now for this reason.

We have made a couple of fixes as well to connectivity related parts in both the client and the servers. I would encourage everyone to upgrade your apps to the latest version and give it another try.

If any similar issues arise, please do open a separate issue with steps to reproduce and we will look into it.

**Comment by mpawlow** [comment]
Thanks @kamalaknn 

> We have made a couple of fixes as well to connectivity related parts in both the client and the servers. 

Are the aforementioned fixes / optimizations in **v6.1.4** or another release not yet in the update stream?

Unfortunately, I am still experiencing the divergent **RESOLVE SYNC CONFLICTS** issues with **request** and **environment** _Item Types_ mentioned in https://github.com/postmanlabs/postman-app-support/issues/4360#issuecomment-397837186

**Comment by kamalaknn** [comment]
@mpawlow 

The fixes are pushed in `6.1.4` release of the Postman. If you're still facing issues with syncing could you send an email to `help@getpostman.com` with your user details and steps to reproduce? Would be helpful to look at this with more context from user account information.

**Comment by RicardoGarciaM** [comment]
Still happening for me v6.1.4 (free), the Sync icon is active (blue) even I am in the free version. When go to Settings -> Sync -> Re-sync is greyed out. Maybe is because moved to a new computer?

**Comment by eugenevital** [comment]
I have been having this issue as well. Even when I close the app and open it back up I get this message.
![image](https://user-images.githubusercontent.com/9011160/42226566-416841b8-7ead-11e8-9761-a49cf7554c66.png)

**Comment by mpawlow** [comment]
>  If you're still facing issues with syncing could you send an email to help@getpostman.com with your user details and steps to reproduce?

Thanks @kamalaknn

I was able to work-around the re-sync issues by doing the following:

1. Duplicate conflicted **environment** item type and rename it to something unique
1. Duplicate each conflicted **request** item type and rename it to something unique
1. Delete the old (source) **environment** item type
1. Delete each old (source) **request** item type
1. Go to: `File > Settings > Sync`
1. Click the `Re-sync` button to manually re-sync
   - Sync icon circle successfully turned orange

I haven't received any sync conflicts prompts so far after a couple of days.

**Comment by Sajjon** [comment]
I had sync issues too. Running macOS High Sierra - 10.13.6 (17G65) and Postman 6.3.0/

 I'm part of a team, and it seemed I got into a "bad state". My import ("team collection" -> "share" -> "my workspace") of a team collection was out of sync even though I deleted it and re-imported it (re "shared" it. I think "Share" is a bad name, should be name "import"...).

What fixed it for me was to delete the macOS app and also the `~/Library/Application\ Support/Postman` folder. I am not sure the deletion of `Application\ Support/Postman` was needed, since I didn't try without it.

So easy to follow instructions:
1.  Deleted imported collection from postman (cloud synced...)
2.  `sudo rm -r /Applications/Postman.app && rm -r ~/Library/Application\ Support/Postman`
3.  [Re-install macOS app](https://app.getpostman.com/app/download/osx64?)
4.  Re-imported ("Share") team collection to my workspace
5.  Now it works 🎉

**Comment by ghost** [comment]
> Hi everyone,
> 
> Sorry for the delayed response. We've identified the issue with conflicts in history. We'll be pushing the fix out on our Canary channel soon.
> 
> I'll update this thread when the fix is out.

This has started happening again, since the latest update **Postman v7.2.2**

**Comment by TLKG** [comment]
I'm getting this constant synching/rotating a few days ago, and now it draws 20% of CPU. 
Windows 10, Postman v7.27.1, standalone, no team.

![image](https://user-images.githubusercontent.com/22269729/149041999-d7485cd1-a5b9-49ac-8c71-d014b1df63c5.png)
