### ISSUE TITLE
Runner resets the selected folder after Run

### ISSUE THREAD

**Issue by nickm8** [a85/POSTMan-Chrome-Extension#4368]
## App Details:
```
Postman for Windows
Version 6.0.9
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Recent (Since new workplaces update)
 2. Expected behavior:
Runner uses the same test location when using Retry button
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
No Logs for this function

~~~
## Replications Steps
1. Create a collection with two folders
2. Add a request to the folder
3. Open Runner
4. Select a folder from a collection 
5. Start run
6. Retry the run after it completes
7. Notice the selected folder has reset instead of using the same folder

**Comment by sivcan** [comment]
Hi @nickm8 - Thanks for reporting. We are aware of this issue and are looking into it.
I'll update this thread once we fix this.

**Comment by mattdeluco** [comment]
I've noticed that the pre-request script for the request in the folder I've selected doesn't run when I use "retry" in the runner - would this be related?

**Comment by sivcan** [comment]
@mattdeluco - I tried to reproduce that but it's not happening.
Can you recheck your pre-request script if there's any issue in that ?

**Comment by sivcan** [comment]
@nickm8 This issue has been fixed internally.
I'll update the thread once it is released.

**Comment by sivcan** [comment]
@nickm8 @mattdeluco We have a released a fix for this issue on our canary channel.
Can you guys try it out if it fixes the issue for you?
https://www.getpostman.com/canary

Canary builds can run alongside the main Postman app and won't affect your settings / data.

**Comment by nickm8** [comment]
I tried with the canary version but it still failed to use Data from my datafile after clicking retry.
I will note that the UI for the runner seemed faster compared to the current version.

**Comment by sivcan** [comment]
@nickm8 Retrying one is a separate issue and you can track it here: https://github.com/postmanlabs/postman-app-support/issues/4287

And yes, major performance optimizations have been done with load times of the app. :) 

Closing this issue.
