### ISSUE TITLE
Postman is not syncing

### ISSUE THREAD

**Issue by Garcia107** [a85/POSTMan-Chrome-Extension#4401]
username: juankgarcia1007

Hi there, 

I just bought a new computer so I download the latest postman version available, but for some reason is not syncing my collections :( 
Don't know what to do.

Please help.

**Comment by ansharfirman** [comment]
Me and my friends cannot sync collections, since I update postman application. it's always show connecting, and my Internet is worked perfectly. just cannot sync postman collections on my account

**Comment by alxtr1bal** [comment]
Same Here...

**Comment by sudo-suhas** [comment]
Developer console shows socket related error - `Error: Could not fetch from sync. Socket not connected`.

Detailed log: [postman-sync-err.log](https://github.com/postmanlabs/postman-app-support/files/1858680/postman-sync-err.log)

Edit: I have no proxy configured in my system. Sync was working correctly before I updated to the latest version.

**Comment by CN-Zed** [comment]
same

**Comment by alxtr1bal** [comment]
And re-sync button is greyed out in settings.

**Comment by IrynaRus** [comment]
I think it's related to #4360

**Comment by foxted** [comment]
Same issue here. No particular error in the console, simply warnings. Tried export/import of data and logging out, no success. Did a full uninstall/reinstall, no success there either.

**Comment by ansharfirman** [comment]
now it's worked. I dont do anything.

something did by magic out there.. lol

**Comment by zed76r** [comment]
> now it's worked. I dont do anything.
> something did by magic out there.. lol

but it very slow.

**Comment by kamalaknn** [comment]
We've been seeing some issues with our Sync servers today. We are working on a fix.

It should be back soon.

**Comment by kamalaknn** [comment]
We've pushed a fix to our Sync servers. Things should be back to normal now.

Thanks for understanding.

**Comment by maheeka** [comment]
I was directed to here from https://github.com/postmanlabs/postman-app-support/issues/4360. Can you confirm whether the issue is fixed? I am still coming across continuous sync conflict popups.

**Comment by IrynaRus** [comment]
The same for me @maheeka. I'm still getting that sync conflict pop-up and no changes have been synced to the server today.

**Comment by IrynaRus** [comment]
@kamalaknn Could you please have a look if there are any issues with sync? 
I'm still seeing "Syncing" status and no changes synced to the server. The latest record in Activity section is from 04.04.2016. So it hasn't been syncing for two days. 
![2018-04-06_9-14-38](https://user-images.githubusercontent.com/37125239/38396428-64903ef6-397b-11e8-832b-86c901616182.png)
![2018-04-06_9-16-44](https://user-images.githubusercontent.com/37125239/38396429-64c566a8-397b-11e8-8b78-15d3b664f359.png)

**Comment by maheeka** [comment]
yes @IrynaRus. Mine is last synced on Thu Mar 29 2018, over a week ago. Manual sync is disabled as well.
![image](https://user-images.githubusercontent.com/1029806/38399317-084bf0ce-398d-11e8-9c3a-32dfa3faba2f.png)
@kamalaknn could you please see if the issue still persists.

**Comment by AartiTewari** [comment]
I am facing the same problem after upgrading the postman to version Version 6.1.3. The changes I made on one of the collection yesterday on a different computer have not been synced. Hence when I am trying to access them on my work laptop today- even after trying to sync , nothing is happening.
 
The manual sync option is unavailable as well.

**Comment by AartiTewari** [comment]
The issue has revolved. Although , I don't know how.

**Comment by SeniorSE** [comment]
I just got an update to Postman, and it still doesn't work.  

I just tried starting up Postman and got the Resolve Sync Conflicts window again.

**Comment by davidoskay** [comment]
Same issue on mac os

**Comment by kobi-l** [comment]
I'm seeing this same issue on windows machine. My postman is out of sync and the changes I make do not sync to the cloud. Just like it's been previously mentioned here, the 'Sync' icon is blue and the 'Re-Sync' button in the Settings screen is Disabled. 

What could I do to sync my changes? 

THIS TICKET NEEDS TO BE REOPENED and ISSUE NEEDS TO BE ADDRESSED ASAP. 

![2018-07-12 09_18_50-postmansyncingissue](https://user-images.githubusercontent.com/10341640/42642723-b4a5857e-85b4-11e8-9aa8-2d1b0886cbb3.png)

**Comment by futie** [comment]
Same problem here - appears to sync on Win10, no sync on Mac. Same screen/behaviour as for @kobilabok

**Comment by Undistraction** [comment]
Same issue on OSX. Nothing syncs -  two iMacs & Macbook Pro.

If I hit 'Sync' I just get 'Connecting …'

Can't share or create workspaces.

**Comment by Iliyass** [comment]
Same problem on OS X 10.13.6, Postman Version 6.1.4

**Comment by Undistraction** [comment]
@Iliyass Seems to be an intermittent problem. Some kind of issue with their API. Give it some time and it will probably come back up.

**Comment by kamalaknn** [comment]
We've made a couple of more changes to the way the Postman app syncs with the Postman servers. This allows the app to sync with the servers in more frequent chunks smaller instead of fewer big chunks. We hope this will increase the overall health of servers which in turn will result in fewer disconnections on the Postman app.

We've started rolling out these starting `6.2` version of Postman. These updates will soon be available to everyone.

Hope that improves the overall experience.

**Comment by thoslin** [comment]
Still seeing this issue in 6.5.2 and 6.5.3. I used a new computer running Linux version postman, and tried to sync from my collections from Mac OS version postman. It just keeps spinning. And the manual sync button is not clickable.

**Comment by achaiah** [comment]
Hi,

I'm also experiencing syncing issues. Nothing is syncing between my computer and my team. I'm on Mac OS with Postman v6.6.1. It works fine on Windows but the mac version refuses to sync.

**Comment by ButchAnton** [comment]
Same issue here on my Mac running Mojave.  Postman 6.6.1 spins the sync indicator forever, and changes do not show up on Windows machines.

**Comment by normdoow** [comment]
I'm having this issue on Mac running Mojave. Im on the newest Postman 6.7.3. had the issue of not syncing after I moved to a new computer and tried to get all my old collections/requests from my account. It actually shows the name of each request inside the collection. But when clicking on the request all the params and url is blank. When I click the sync button, it just flashes blue for a second. doesn't seem to do anything.

**Comment by mo-nz** [comment]
I am having the same issue also. I cannot sync the application. I am running Postman v 6.7.3  on windows 10. 
Please help!!

**Comment by dboyadzhiev** [comment]
I'm having it too:

Postman for Mac
Version 7.0.6
OS X 18.0.0 / x64

**Comment by sujayvenaik** [comment]
Hey @dboyadzhiev 
Can you send us the logs?
You can find the logs from View -> Developer -> View logs in Finder and send the files in it.

**Comment by dboyadzhiev** [comment]
Hi @sujayvenaik,

Where should I send the files? They contain sensitive data! 

In additional: Now the sync works. (after the N-th restart)

**Comment by sujayvenaik** [comment]
@dboyadzhiev 
Can you email the logs at help@getpostman.com? [Redact any sensitive information]
Put this as the email subject -> Github 4401: Sync Issue

**Comment by mira-thakkar** [comment]
I'm having the same issue on:

Postman for Mac
Version 7.0.7

**Comment by tsantor** [comment]
Same issue.  I just worked at home this weekend and added new requests and collections and nothing is syncing to my work computer...still looking at what it was before the weekend. 

Postman for Mac
Version 7.0.7

**Update:** I just updated to 7.0.7 on both computers and it synced.

**Comment by lvnar** [comment]
Same issue here. I haven't sync in two days and didn't figure out till now.I changed between sessions and now I can't see  any collection.

@tsantor  solved with the update. I have the notification to update, but there no Settings > Update tab. Re-sync button inactive too. :confused: 

![Captura de pantalla de 2019-04-04 12-00-33](https://user-images.githubusercontent.com/7190801/55577979-0c3dac00-56d2-11e9-8347-019a16cec1fd.png)
![Captura de pantalla de 2019-04-04 11-51-10](https://user-images.githubusercontent.com/7190801/55578001-1eb7e580-56d2-11e9-9c62-35ba32c2bf6a.png)

**Comment by sujayvenaik** [comment]
Hey @Ivnar
Hi! Seems like you are using Postman for Linux installed via Snap or Ubuntu Software Center. Please switch your release channel via the following commands to get access to Postman 7.0

sudo snap switch --channel=candidate postman
sudo snap refresh postman

**Comment by robert-swail** [comment]
> Hey @Ivnar
> Hi! Seems like you are using Postman for Linux installed via Snap or Ubuntu Software Center. Please switch your release channel via the following commands to get access to Postman 7.0
> 
> sudo snap switch --channel=candidate postman
> sudo snap refresh postman

Thank you @sujayvenaik that got the sync working for me.

I had also installed postman via snap

Cheers!
Bob

**Comment by puntodamar** [comment]
close your postman properly. 
for me that was the culprit.

**Comment by ShivaniSain28** [comment]
Hi, 
I am also facing the same issue. Not syncing on my device and some missing requests. Please help. I have updated my postman as well.

**Comment by sujayvenaik** [comment]
Hey @ShivaniSain28 
What version and platform are you currently on?
Also, can you elaborate on the issue? You are not able to get the requests created by others or your data is not syncing?

Also, attach the logs from View -> Developer -> View Logs in Finder.

**Comment by ShivaniSain28** [comment]
Hello Sujay Venaik,
 ,
I am using Postman version V 7.1.0 on windows platform. (win32 10.0.17134 /
x64).

I was login on my mac system (V 7.0) and on my windows system as well. I
have moved requests using drag and drop in between collections. Now a
request is not showing on my windows system postman. I have tried re-login
and syncing many times but still my request is missing. If on windos system
I make new request, it shows 2 requests on mac system. So i can not create
same new request (which is missing).


*Best Regards,*
*Shivani Sain*
Team Lead






*415/ 416, Tower-2, World Trade Center, Kharadi,
Pune-411014, Maharashtra.[image: ranosys]
<http://ranosys.com/esign/>[image: facebook]
<https://www.facebook.com/ranosys>[image: twitter]
<https://twitter.com/ranosys>[image: linkedin]
<https://www.linkedin.com/company/741079?trk=prof-exp-company-name>[image:
googleplus] <https://plus.google.com/+Ranosys> Head Office:Oxley Bizhub,
#06-48 | 73 Ubi Road 1 | Singapore - 408733Tel: +65 66331556Global
Offices:San Francisco, USA | London, UK | Pune, India | Jaipur, India |
Bikaner, IndiaWarning: Privileged/Confidential information may be contained
in this communication (which includes any attachment). If you are not an
intended recipient, you must not use, copy, disclose, distribute or retain
this communication or any part of it. Instead, please delete all copies of
this communication from your computer system and notify the sender
immediately by reply mail. Thank you.*

**Comment by cesc1989** [comment]
Updating Postman installed via Snap as @sujayvenaik suggested solved the thing for me:

```bash
$ sudo snap switch --channel=candidate postman
$ sudo snap refresh postman
```

**Comment by ebabel-eu** [comment]
Postman stopped syncing for me too.

![Screenshot 2019-06-07 at 06 55 57](https://user-images.githubusercontent.com/4309770/59082027-5d943280-88f1-11e9-8429-a5fd2065567b.png)

**Comment by juanpablo-delgado-tierconnect-com** [comment]
> Updating Postman installed via Snap as @sujayvenaik suggested solved the thing for me:
> 
> ```shell
> $ sudo snap switch --channel=candidate postman
> $ sudo snap refresh postman
> ```

Also this works for me too. Environment: Ubuntu 18.04

**Comment by hosamhemaily** [comment]
remove it and setup it again it will work fine

**Comment by akaczinski** [comment]
I'm having very large collections that are not saving to the cloud. They will save locally, but if I wipe my Postman installation, some large things will not be saved on the cloud, even though they appeared to be before.

**Comment by preethammavin** [comment]
@akaczinski can you write to us at help@getpostman.com with the collection id, and what does the size of the collection look like locally so that we can take a closer look?

**Comment by akaczinski** [comment]
> @akaczinski can you write to us at [help@getpostman.com](mailto:help@getpostman.com) with the collection id, and what does the size of the collection look like locally so that we can take a closer look?

I went ahead and sent an email, thanks for taking a look!

**Comment by emereyd** [comment]
> > @akaczinski can you write to us at [help@getpostman.com](mailto:help@getpostman.com) with the collection id, and what does the size of the collection look like locally so that we can take a closer look?
> 
> I went ahead and sent an email, thanks for taking a look!

Hi @akaczinski, did you get a response or a resolution?
I think i'm in the same situation you have described. 
> very large collections that are not saving to the cloud.

**Comment by akaczinski** [comment]
> Hi @akaczinski, did you get a response or a resolution?
> I think i'm in the same situation you have described.

Hello @emereyd, I haven't received a response yet, but I did submit the email. Have you found any workarounds that guarantee saving collections to the cloud? It's a fairly frustrating bug.

I'll tag you once I hear back. Good luck!

**Comment by emereyd** [comment]
@akaczinski yes pls to tagging me.
Workaround: I created a new collection and migrated the old one over using the Postman API. I followed these steps:

1. Exported my collection from Postman app.
2. Using the [Postman API](https://docs.api.getpostman.com/?_ga=2.141458416.39102523.1565347887-1831388330.1532599713&version=latest#99810ef3-3cc0-a6cc-06f5-d8e2ae9d84e4) I added to body what i exported + tidy up (removed collection id and added `collection` object)

This seems to have done the trick, however i've had to change the collection id in our CD jobs.

Hope this helps!

**Comment by Toretu** [comment]
Seem to have similar problem, fresh install on windows 10. New account with a some team stuff i whant to get local.
13828][1581675489798][requester][warn]["Failed to refresh API List",{"error":{"message":"SyncRequestService\\x7erequestListener: Could not fetch from sync. Socket not connected."}}]

**Comment by gadelkareem** [comment]
Is that a premium feature because I cannot get it to work after downgrading

**Comment by rafael-asaph** [comment]
I'm having this issue right now. Is there anything i can do?

**Comment by JosebaMerino** [comment]
I was having the same problem. I uninstalled it and downloaded it from the official page: https://www.postman.com/downloads/ . It syncs fine

**Comment by preethammavin** [comment]
@rafael-asaph can you mention the app version you are using. Also would be great if you could write to help@postman.com so that we can take a deeper look.

@gadelkareem its available to all users. If you are still facing the issue can you drop a note at the above mentioned email?

**Comment by gadelkareem** [comment]
@preethammavin thanks, I sent an email.

**Comment by rafael-asaph** [comment]
> I was having the same problem. I uninstalled it and downloaded it from the official page: https://www.postman.com/downloads/ . It syncs fine

Ok, that solved my problem.

**Comment by rafael-asaph** [comment]
> @rafael-asaph can you mention the app version you are using. Also would be great if you could write to [help@postman.com](mailto:help@postman.com) so that we can take a deeper look.
> 
> @gadelkareem its available to all users. If you are still facing the issue can you drop a note at the above mentioned email?

I was using 6.7.6, but as JosebaMerino said, i'd got the application from the official site and it worked.

**Comment by arthurkushman** [comment]
Hi, can't sync postman today, from `renderer-requester.log`:
```
[46198][1586937289355][requester][warn]["CloudProxyHandler: Error while reading proxy configuration from user data - ",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/amkushmantsev/Library/Application Support/Postman/Postman_Config/proxy","name":"Error","message":"ENOENT: no such file or directory, open '/Users/amkushmantsev/Library/Application Support/Postman/Postman_Config/proxy'","stack":"Error: ENOENT: no such file or directory, open '/Users/amkushmantsev/Library/Application Support/Postman/Postman_Config/proxy'"}]
[46198][1586937289566][requester][warn]["Failed to subscribe to workspace for all APIs",{"name":"Error","message":"","stack":"Error\n    at SafeSubscriber.realtimeRequest$.pipe.subscribe.event [as _next] (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:474527:24)\n    at SafeSubscriber.__tryOrUnsub (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41935:16)\n    at SafeSubscriber.next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41873:22)\n    at Subscriber._next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41816:26)\n    at Subscriber.next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41793:18)\n    at FilterSubscriber._next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:156391:30)\n    at FilterSubscriber.Subscriber.next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41793:18)\n    at RefCountSubscriber.Subscriber._next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41816:26)\n    at RefCountSubscriber.Subscriber.next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41793:18)\n    at Subject.next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:77802:25)\n    at ConnectableSubscriber.Subscriber._next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41816:26)\n    at ConnectableSubscriber.Subscriber.next (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:41793:18)\n    at EventEmitter.realtimeRequestBus.subscribe.event (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:474474:14)\n    at EventEmitter.emit (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:48184:5)\n    at _dispatch (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:154453:14)\n    at EventEmitter.<anonymous> (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:154463:9)\n    at EventEmitter.emit (events.js:182:13)"}]
[46198][1586937289754][requester][warn]["APIDevService~getAPIs: Failed to get APIs.",{"error":{"message":"SyncRequestService\\x7erequestListener: Could not fetch from sync. Socket not connected."}}]
[46198][1586937289755][requester][warn]["Failed to refresh API List",{"error":{"message":"SyncRequestService\\x7erequestListener: Could not fetch from sync. Socket not connected."}}]
[46198][1586937290676][requester][info]["SessionValidation - Registering listener"]
[46198][1586937290724][requester][warn]["FeatureFlagsStore~updateFlags: Could not find feature flags",{"error":{"message":"SyncRequestService\\x7erequestListener: Could not fetch from sync. Socket not connected."}}]
[46198][1586937451087][requester][warn]["APIDevService~getAPIs: Failed to get APIs.",{"error":{"type":"Request Timeout"}}]
[46198][1586937451088][requester][warn]["Failed to refresh API List",{"error":{"type":"Request Timeout"}}]
```
`main.log`
```
[46198][1586937284882][main][info]["Booting Postman 7.22.1, darwin-19.4.0 on x64"]
[46198][1586937284885][main][info]["EventBus~initialize - Success"]
[46198][1586937284888][main][warn]["CloudProxyManager~init: Error while reading proxy configuration from user data - ",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/amkushmantsev/Library/Application Support/Postman/Postman_Config/proxy","name":"Error","message":"ENOENT: no such file or directory, open '/Users/amkushmantsev/Library/Application Support/Postman/Postman_Config/proxy'","stack":"Error: ENOENT: no such file or directory, open '/Users/amkushmantsev/Library/Application Support/Postman/Postman_Config/proxy'"}]
[46198][1586937284889][main][info]["CloudProxyManager~init - Success"]
[46198][1586937284890][main][info]["UpdateHandler~init - Success"]
[46198][1586937284891][main][info]["RuntimeExecutionService~initialized: Success"]
[46198][1586937285191][main][info]["Bootstrap-models~bootstrap - Success"]
[46198][1586937285389][main][info]["window-manager~newSharedWindow: Shell loaded"]
[46198][1586937287138][main][info]["Main~AppEvents - Received booted event for process shared"]
[46198][1586937289326][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[46198][1586937289341][main][info]["Main~AppEvents - Received booted event for process requester"]
```
As u can see this is the latest version of Postman 7.22.1

**Comment by marcopierac** [comment]
As you can clearly see from the fact that i am uploading this screenshot, it looks like i **do** have an active internet connection...
![image](https://user-images.githubusercontent.com/57956836/79323115-1530a280-7f0e-11ea-833d-0737a64f1087.png)

Since an hour ago I am having the same problem as @arthurkushman , with v7.22.1. The log reports `Could not fetch from sync. Socket not connected`.
I had just logged out because the app told me my login was expired, then i logged in again (google auth) but my collections **aren't** syncing. Also, if i tried to see my active sessions or account settings, the website shows a 401 http error page.

I had the EXACT same problems some months ago when my login expired and i had to login again. That time the problems resolved by themselves after a few hours.

### Update
Now even `ping identity.getpostman.com` gives no response:
```
Pinging identity.getpostman.com [54.152.119.129] with 32 bytes of data:
Request timed out.
```

And the log reports multiple errors:
```
[22544][1586943832736][requester][info]["SessionValidation - Validation starting (https://identity-api.getpostman.com)"]
[22544][1586943832741][requester][info]["SessionValidation - Intent received"]
[22544][1586943832741][requester][info]["SessionValidation - Validation already in progress"]
[22544][1586943832746][requester][warn]["FeatureFlagsStore~updateFlags: Could not find feature flags",{"error":{"message":"You are not authenticated by the server.","name":"authenticationError"},"headers":{"Access-Control-Allow-Credentials":"","Access-Control-Allow-Headers":"","Access-Control-Allow-Methods":"","Access-Control-Allow-Origin":"","Access-Control-Expose-Headers":""},"status":403}]
[22544][1586943832759][requester][info]["SessionValidation - Intent received"]
[22544][1586943832760][requester][info]["SessionValidation - Validation already in progress"]
[22544][1586943832760][requester][info]["SessionValidation - Intent received"]
[22544][1586943832760][requester][info]["SessionValidation - Validation already in progress"]
[22544][1586943832761][requester][info]["SessionValidation - Intent received"]
[22544][1586943832762][requester][info]["SessionValidation - Validation already in progress"]
[22544][1586943833946][requester][info]["SessionValidation - Response received (200)"]
[22544][1586943833948][requester][error]["SessionValidation - Session expiry hint validated as incorrect, disconnecting socket for ~53 seconds"]
[22544][1586943887330][requester][info]["SessionValidation - Waited ~53 seconds. Reconnecting socket."]
[22544][1586943961620][requester][info]["SessionValidation - Intent received"]
[22544][1586943961621][requester][info]["SessionValidation - Validation starting (https://identity-api.getpostman.com)"]
[22544][1586944022064][requester][info]["SessionValidation - Request error (1)"]
[22544][1586944022066][requester][error]["SessionValidation - Session expiry hint validated as incorrect, disconnecting socket for ~18 seconds"]
[22544][1586944040734][requester][info]["SessionValidation - Waited ~18 seconds. Reconnecting socket."]
```

**Comment by nikolamajmunovic** [comment]
same problem, not syncing anymore, when upgraded to the latest version. Mac Book

**Comment by denz404** [comment]
same problem, not syncing anymore, when upgraded to the latest version. Windows

**Comment by denz404** [comment]
> same problem, not syncing anymore, when upgraded to the latest version. Mac Book

you fixed it ?

**Comment by teddis** [comment]
Same problem today after upgrading from Chrome to native app on Mac Catalina 10.15.4. Syncing never ends, my collections never show up locally. :-(

**Comment by kamalaknn** [comment]
Hey @teddis Could you forward the logs from `View -> Developer -> View logs in Finder` to `help@postman.com` so we can take a closer look?

**Comment by teddis** [comment]
Hi Kamalakannan, I apologize, apparently the upgrade process did not
install the Postman native "app", and I was still using the Chrome app, but
all my collections disappeared in my local Chrome app. When I finally
realized and manually downloaded the latest app, it synced and my
collections appeared. This was a combination of user error and confusion by
Postman upgrade process.

Ted

From: Kamalakannan <notifications@github.com> <notifications@github.com>
Reply: postmanlabs/postman-app-support
<reply@reply.github.com>
<reply@reply.github.com>
Date: May 9, 2020 at 10:43:54 AM
To: postmanlabs/postman-app-support <postman-app-support@noreply.github.com>
<postman-app-support@noreply.github.com>
Cc: Ted Cohn <tedcohn2@gmail.com> <tedcohn2@gmail.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [postmanlabs/postman-app-support] Postman is not syncing
(#4401)

Hey @teddis <https://github.com/teddis> Could you forward the logs from View
-> Developer -> View logs in Finder to help@postman.com so we can take a
closer look?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/postmanlabs/postman-app-support/issues/4401#issuecomment-626211535>,
or unsubscribe

**Comment by seanonthenet** [comment]
Also. Cannot sync.

**Comment by El-Glory** [comment]
Same here. Been acting this way for a while now

**Comment by numaanashraf** [comment]
@El-Glory Could you let us know the following details?
1. Your Postman version
2. Your OS and its version
3. Are you using any proxies or behind any corporate firewall or VPN?

**Comment by El-Glory** [comment]
Version 6.7.6
OS - Ubuntu, Linux 18.04.4 LTS

**Comment by numaanashraf** [comment]
@El-Glory Could you try installing the latest version via Snap? https://snapcraft.io/postman

**Comment by ghost** [comment]
1. Version 7.36.5
2. linux 5.8.0-53-generic / x64
3. I am not using any proxies or VPN

**Comment by monkeychew-ico** [comment]
I had a problem with collections not syncing between web and app. I chose not to create a team initially, once I'd created a team it started syncing, hope that helps.
