### ISSUE TITLE
Import of swagger 1.2 API fails with TypeError: process.exit is not a function

### ISSUE THREAD

**Issue by asmod3us** [a85/POSTMan-Chrome-Extension#4498]
## App Details:

```
Postman for Mac
Version 6.0.10
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Don't know, attempted for the first time now.
 2. Expected behaviour: Successfully import a Swagger 1.2 API def.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Error while importing Swagger 1.2: TypeError: process.exit is not a function
 4. Screenshots (if applicable): 

- Attempt to import an AppD API definition from https://achim.saas.appdynamics.com/api-docs/service.json.

- Observe error: Error while importing Swagger 1.2: TypeError: process.exit is not a function

- The top level API spec contains links to separate API defs:

https://achim.saas.appdynamics.com/api-docs/accounts.json
https://achim.saas.appdynamics.com/api-docs/rca.json
https://achim.saas.appdynamics.com/api-docs/controllerflags.json
https://achim.saas.appdynamics.com/api-docs/rbac_v1.json
https://achim.saas.appdynamics.com/api-docs/controllermds.json
https://achim.saas.appdynamics.com/api-docs/ecl.json

All of which import just fine individually.

**Comment by sdnts** [comment]
Hi @asmod3us, thanks for reporting this, I was able to see this as well, we will get this fixed in an upcoming version.

**Comment by ig0rsky** [comment]
any news on this bug?

**Comment by APIwithjepp** [comment]
Still experiencing this 
Postman for Windows
Version 7.0.7
win32 10.0.17763 / x64
Same as asmond3us, higher level spec non-importable, individual folders successful with Swagger 1.2

**Comment by dleesalestreamsoft** [comment]
I am also having this problem

**Comment by derekkddj** [comment]
I am having the same problem

**Comment by VShingala** [comment]
@asmod3us @ig0rsky @APIwithjepp @dleesalestreamsoft @dhd0004 

Fix for this was released in App and [Module](https://github.com/postmanlabs/swagger1-to-postman/commit/dc22cd283e932478579819392acd30eb00b6e7fe). Can you check latest Postman App to see if fix is working for you and let me know.

**Comment by mccannt** [comment]
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.
