### ISSUE TITLE
Secure Cookies No Longer Set

### ISSUE THREAD

**Issue by MLG-ANolan** [a85/POSTMan-Chrome-Extension#4581]
**Describe the bug**
Secure cookies are no longer set.

**To Reproduce**
1. Perform any HTTP request that will return and set secure cookies.

**Expected behavior**
All cookies that are to be set and visible in the Manage Cookies of Postman.

**Screenshots**
First Image: Cookies to be Set
![image](https://user-images.githubusercontent.com/20689093/40326253-b0f66978-5d0c-11e8-8a35-a0f87b415303.png)
Second Image: Cookies that were Set
![image](https://user-images.githubusercontent.com/20689093/40326268-c126e566-5d0c-11e8-85b8-c84d3a8ccc9d.png)

**App information:**
Postman for Mac
Version 6.1.2
OS X 16.7.0 / x64

**Comment by sanvipy** [comment]
Ive been stuck with the same issue.
None of the secure cookies are being added to cookie manager, and which means postman is no longer able to maintain sessions

Do note that it seems to work fine if using collection runner

![image](https://user-images.githubusercontent.com/18203625/40339441-0ffa367a-5dad-11e8-86eb-21b71d30be6a.png)
![image](https://user-images.githubusercontent.com/18203625/40339449-1baa1a94-5dad-11e8-87f8-c3b16bad8e2a.png)

Console view
![image](https://user-images.githubusercontent.com/18203625/40339725-4ca57836-5dae-11e8-9d31-ed01aaff55e4.png)


Running
Postman for Windows
Version 6.1.2
win32 6.1.7601 / x64

**Comment by terrencewei** [comment]
Same issue with:
Postman for Linux
Version 6.1.2
linux 4.15.0-20-generic / x64

All 'Secure' Cookies not set.
And the most importtant JSESSIONID is no longer persistance

**Comment by terrencewei** [comment]
It is really a CRITICAL BUG for v6.1.2
After revert back to:
Postman for Linux
Version 6.0.10
linux 4.15.0-20-generic / x64

The cookie is set.

**Comment by harryi3t** [comment]
@MLG-ANolan @terrencewei Thanks for reporting this bug. We are fixing it.

**Comment by battestiacole** [comment]
I have the same issue. Any ideas on the ETA of the fix ?

**Comment by ghost** [comment]
I can verify the bug exists in Postman for Linux v6.1.2 running linux 4.15.0-22-generic / x64 (Ubuntu 18.04). I started with a complete new install (removed all data from ~/config/Postman). A clean install of v6.0.10 stores secure cookies as expected).

**Comment by archana-acharya** [comment]
I have the same issue in windows 64 bit. I have to make a clean install of v 6.0.10. Any update on the issue?

**Comment by terrencewei** [comment]
I had noticed postman release version 6.1.3, but seems not fixing this bug yet?

**Comment by harryi3t** [comment]
Sorry for the delay. We have figured out the issue and are fixing it.
This should be available in the next release.

This happened because of an undocumented behaviour change in the latest version of the electron. An additional check was added for adding secure cookies.

**Comment by dotnetallday** [comment]
@harryi3t Is this supposed to be fixed in 6.1.3 (Win x64)? If so, it does not appear to be fixed when the app updates itself. This bug is still present in my current build.
![image 001](https://user-images.githubusercontent.com/4284351/40694157-086eb8b8-6370-11e8-9a59-9207999eda7e.png)

**Comment by harryi3t** [comment]
@dotnetallday No, the next release will be most probably 6.2.0
Also, we will be releasing the canary build with the fix soon.

**Comment by whyvrafvr** [comment]
So, I assume this is probably why my `JSESSIONID` cookies are not stored ;)
BTW, it works on newman 3.9.4 and Collection Runner on Postman 6.1.3.

**Comment by harryi3t** [comment]
We have released the canary version with the fix. Can you guys try it out?
https://www.getpostman.com/canary

**Comment by terrencewei** [comment]
@harryi3t Thanks and good news, I had test and it works on my Linux for version:
Postman for Linux
Version 6.2.0-canary01
linux 4.15.0-22-generic / x64

**Comment by FreeWillaert** [comment]
Thanks! Works on macOS, version 6.2.0-canary01

**Comment by MLG-ANolan** [comment]
Looks good to me! Side by side comparison with 6.1.3 on the left and 6.2.0 on the right. Checked on mac and windows.
![image](https://user-images.githubusercontent.com/20689093/40783803-97458624-64b1-11e8-91f3-ae008a69a2f0.png)

Mac | Windows
------------ | -------------
Version 6.2.0-canary01 | Version 6.2.0-canary-01
OS X 16.7.0 / x64 | win32 10.0.14393 / x64

**Comment by whyvrafvr** [comment]
It works. Thanks a lot 👍

**Comment by terrencewei** [comment]
Hey guys, any update about release plan for fixing this bug?

**Comment by harryi3t** [comment]
Right now, the fix is only available in our [canary build](https://www.getpostman.com/canary).
In production, it will be available as part of 6.2.0 release.

**Comment by donnfelker** [comment]
This is an unfortunate bug. I've spent a couple hours debugging why cookies are not being set in postman (thinking it was an PEBCAK error) and finally I came here to see if there is an open issue. Sad to see I wasted some time due to a bug, but happy to see that there is a bug for this and that it has been fixed in Canary. Just tested this and it looks good, works on Canary for me. Thanks team. 👍

**Comment by donnfelker** [comment]
I think I've identified another possible issue with cookies. The Expires property is not saving in the `Expires` column of the Cookies tab of Postman Canary. 

Version 6.2.0-canary02 (6.2.0-canary02)

If I issue a request the cookie is returned and it is set in the cookie manager (with the expires property showing). However, the Expires property is not showing in the cookie tab. See screenshots: 

![cookie-tab-2](https://user-images.githubusercontent.com/91827/41465478-4707291c-706c-11e8-96cc-d44b76ba5e05.png)

![cookie-manager-2](https://user-images.githubusercontent.com/91827/41465482-49f86a00-706c-11e8-8a25-b9596079408b.png)

**Comment by harryi3t** [comment]
@donnfelker I have reproduced this bug. Once the fix is available, will update the same thread.

**Comment by ma-schmidt-de** [comment]
> In production, it will be available as part of 6.2.0 release.

@harryi3t 
Can you give a hint when release 6.2.0 will be available?

**Comment by visweshwar** [comment]
@donnfelker  is right, the expiry date is still an issue which is preventing the cookie from being chained into the next request.

@harryi3t  is there a way we can get our hands on a previous stable build?

**Comment by harryi3t** [comment]
Postman 6.1.4 is out with the fix for this bug 🎉

**Comment by tmldsousa** [comment]
@harryi3t can you please check if pm.cookies in the Tests scripts is fixed too? I'm having this issue but, while the cookie is set in cookie manager, pm.cookies is empty in my test script.

To be clear:
1 - I make a request that returns a Set-Cookie header with a secure cookie
2 - The cookie is added to the Cookie Manager (which is OK)
3 - In the post-script (Tests) of this request, pm.cookies is empty (which is not OK)

**Comment by kingb** [comment]
Food for thought: I was getting this error with Postman v6.2.4 on Linux...

I renamed ~/.config/Postman to ~/.config/Postman.old and restarted the app, and now cookies are sticking.

**Comment by ne0c0de** [comment]
I'm using 6.3.0 native Mac version and still have the same problem.

I'm using this way to add cookie:

Click on Cookies
add the proper domain name of the site.
Click on Add Cookie and append the proper cookie value into the new cookie field. 
Click save

and nothing happens. whenever i open the cookies tab i can't see the cookie that i entered before.

**Comment by ne0c0de** [comment]
I'm using 6.3.0 native Mac version and still have the same problem.

I'm using this way to add cookie:

Click on Cookies
add the proper domain name of the site.
Click on Add Cookie and append the proper cookie value into the new cookie field. 
Click save

and nothing happens. whenever i open the cookies tab i can't see the cookie that i entered before.

**Comment by harryi3t** [comment]
@ne0c0de can you post a screenshot/screen-recording of the steps?

**Comment by dan-cooke** [comment]
> @ne0c0de can you post a screenshot/screen-recording of the steps?

https://github.com/postmanlabs/postman-app-support/issues/5323

**Comment by ne0c0de** [comment]
here it's: http://recordit.co/8hRGOY7ywJ

**Comment by harryi3t** [comment]
@ne0c0de Apologies for the delayed response
I saw the screen-recording, you are adding the `key=value` in the end instead of in the beginning 
<img width="718" alt="recordit__record_screencasts_fast___free__with_gif_support_" src="https://user-images.githubusercontent.com/5207331/47267063-22104800-d55c-11e8-8520-df7c1a519551.png">

I have made a recording to help you
![kapture 2018-10-21 at 18 10 51](https://user-images.githubusercontent.com/5207331/47267106-b8446e00-d55c-11e8-8053-ddcdcc1d366c.gif)

**Comment by danielo515** [comment]
This is still a problem, and I'm using the latest postman app.
You just make a call to google and you will see that it returns back 3 cookies, but only 1 is recogniced

**Comment by ryekerjh** [comment]
I also am having this issue again. I have latest (Version 7.25.0). The cookie is returned from the server, but then it doesn't get sent to the server upon subsequent requests.

**Comment by varun508** [comment]
I'm having the same issue.
Postman for Linux
Version 7.25.2
linux 5.3.0-53-generic / x64

**Comment by arlemi** [comment]
If you're having issues keeping/sending cookies with your requests, make sure that the "disable cookie jar" setting is set to off.

![Annotation 2020-06-08 092654](https://user-images.githubusercontent.com/5029719/84009116-b9612380-a96a-11ea-8684-7380c13844f7.png)

We're also tracking an issue where cookies are not being added when the url is set using a variable in #8348.

If your issue isn't any of these two, please open a new one and provide as many details as possible.

**Comment by tominflux** [comment]
I am having this issue currently. (Ver 7.31.10). Cookie is set when secure is set to false, but no cookie appears to be set when secure is set to true, even though in both cases the "Set-Cookie" header is present in the HTTP response.

**Comment by Seifozzakerini** [comment]
Hi all
In the latest version of the Postman for Mac (7.34.0), I removed automatic Cookie from the header to test something. Now I can not add it again to the requests anymore. Seems there is no way, very strange!
I appreciate your advice

**Comment by Seifozzakerini** [comment]
Meaning that the session token is not added automatically and the session is not maintained by Postman again

**Comment by arlemi** [comment]
@Seifozzakerini Have you tried turning the setting I mentioned above back on? 
https://github.com/postmanlabs/postman-app-support/issues/4581#issuecomment-640453915

**Comment by WilfredH** [comment]
Hello,
I also have this (or a closely related) issue with v7.34.0

As this issue is closed I opened a new bug: #9264

**UPDATE**: It was a user error, I was using secure cookies over a http connection...

**Comment by ronenmagid** [comment]
This error still occurs, making Postman unusable for software development. 

- I'm on Mac
- Postman desktop version: `7.35.0 (7.35.0)`
- my server is running under `https`, and I make sure I call it under `https`. 
- I'm using environment parmaters for server url. (e.g. `{{base_url}}/v1/login` All secure cookies communicated with the /login response, however, the cookie manager doesn't get them and subsequent `https` calls to the same domain do not include the secure cookies given by the `/login`.

It seems this bug has been around for years without a fix. Does anyone know anything about a timeline to fix?

**Comment by Warlock-9000** [comment]
The error is still present. Windows 10, Postman v8.6.2
Because of this, I had to use crutches and bicycles. Here it is
Add this to the test section where you plan to receive cookies in the request
`let headers = []
for (const [key, value] of Object.entries(pm.response.headers.all())) {
  if (value.key == 'Set-Cookie') headers.push(value.value)
}
let cookieString = ''
for (i in headers){
    cookieString += headers[i].split(';')[0]+'; '
}
cookieString = cookieString.slice(0,-2)
pm.environment.set('cookieString', cookieString);`

than add the variable cookieString to the headers section in every request where cookies should be

**Comment by pchatzou** [comment]
Having the issue for Linux:

Postman for Linux
Version 7.36.5
linux 5.4.0-77-generic / x64

Disable cookie jar setting is set to off as advised and still secure cookies are not being saved.

**Comment by walidklai** [comment]
Hello, if the httpOnly cookie is secure postman will not set it again after deleting it manually, i'm facing this issue when working locally .

i have to set it to not secure in order to get this fixed .

_npm package used for cookie management in node server : coockie-session v2
postman v 9.18_

**Comment by dgallego58** [comment]
> Hello, if the httpOnly cookie is secure postman will not set it again after deleting it manually, i'm facing this issue when working locally .
> 
> i have to set it to not secure in order to get this fixed .
> 
> _npm package used for cookie management in node server : coockie-session v2 postman v 9.18_

this happened to me when i set on my app Secure to false (like the top comment in this issue), the cookies tab does not grab them from the response.

i did reproduce this in a Spring Boot Application i was just creating.

![licecap-test](https://user-images.githubusercontent.com/42015175/168503110-cde47ef3-0ae1-4fb4-9f51-2bdc323a9180.gif)

**Comment by cgcostume** [comment]
> The error is still present. Windows 10, Postman v8.6.2 Because of this, I had to use crutches and bicycles. Here it is Add this to the test section where you plan to receive cookies in the request `let headers = [] for (const [key, value] of Object.entries(pm.response.headers.all())) { if (value.key == 'Set-Cookie') headers.push(value.value) } let cookieString = '' for (i in headers){ cookieString += headers[i].split(';')[0]+'; ' } cookieString = cookieString.slice(0,-2) pm.environment.set('cookieString', cookieString);`
> 
> than add the variable cookieString to the headers section in every request where cookies should be

Just had the same issue (Windows: Enterprise 10, 21H2, 19044.2006; Postman: 9.29.0) and modified the code to directly set the cookie from the response headers and make subsequent requests work:
```
// Set Cookies from Set-Cookies Headers

const cookieJar = pm.cookies.jar();
for (const [key, header] of Object.entries(pm.response.headers.all())) {
    if (String(header.key).toLowerCase() !== 'set-cookie') {
        continue;
    }
    const values = String(header.value).split(';');
    const domain = values.find((value, index) => value.toLowerCase().trim().startsWith('domain'))?.split('=')[1];

    cookieJar.set(domain, header.value);
}
```
For this to work, the domain must be on the Cookie whitelist.

**Comment by Vansh-Baghel** [comment]
Cookies are not getting saved in postman when the secure is **true**. It is saved when we set secure to **false**

**Comment by Vansh-Baghel** [comment]
1. Cookies are not getting saved in postman when the secure is true. 
2. It is saved when we set secure to false.

**Comment by Vansh-Baghel** [comment]
1, Cookies are not getting saved in postman when the secure is **true**.
2. It is saved when we set secure to **false**.
3. It is getting saved on the website but Postman is **unable to show it**.
![Comment](https://user-images.githubusercontent.com/103327712/211142041-e2de5bb7-01f2-456c-8c2c-9bf1e7010e87.jpg)

**Comment by Vansh-Baghel** [comment]
1, Cookies are not getting saved in postman when the secure is true.
2. It is saved when we set secure to false.
3. It is getting saved on the website but Postman is unable to show it.
![Uploading Comment (1).jpg…]()

**Comment by Vansh-Baghel** [comment]
1, Cookies are not getting saved in postman when the secure is true.
2. It is saved when we set secure to false.
3. It is getting saved on the website but Postman is unable to show it.
![Comment (1)](https://user-images.githubusercontent.com/103327712/211142111-0a267eb9-3b32-4917-b15d-1d161a02f9bc.jpg)

**Comment by CreativeWarlock** [comment]
This bug still occurs in  v10.11.1. 
For us this is a K.O. criterium since development cannot work properly (the requested endpoints are not in our hands).

**Comment by coditva** [comment]
@CreativeWarlock Can you share a screenshot or screen-recording of the issue? I would like to know the value of `set-cookie` header and the request URL. `Secure` cookies are only set for `https://` urls.

Also, can you see the cookie in the ["Cookies" modal](https://learning.postman.com/docs/sending-requests/cookies/#using-the-cookie-manager) in Postman?

**Comment by CreativeWarlock** [comment]
It's hard to reproduce. Right now Postman does behave nicely and fills the received cookie into the cookie tab.
And yes, all requests are sent over https. 

![image](https://user-images.githubusercontent.com/4894323/223293082-9d72556a-9b67-4bbc-92ba-c7aaa78abe5b.png)

**Comment by coditva** [comment]
@CreativeWarlock It could be that the cookie had expired when you replicated the issue. Expired cookies are not shown in the Cookies tab. Feel free to create a new issue if you are able to replicate this again. We'll continue there. 🙂

**Comment by CreativeWarlock** [comment]
Yes, we can confirm that. Cookies that we received were already expired, but it has been fixed by now.

Interestingly though, Postmand sometimes took the cookie over to the Cookies Tab, and sometimes not.
Fact is, as soon as it stopped doing that PostMan was not able to take over the cookie any longer, also not after restarting Postman.
Unfortunately, we cannot replicate the issue here as the developer of the REST API has fixed the expiration date.

**Comment by kbublitz** [comment]
I have a similar issue with requests to http://localhost URL. It's not https://, but according to the standards, localhost should be an exception.
The cookie does show up in the cookies dialog:
![grafik](https://user-images.githubusercontent.com/118510778/227522547-20f7947c-b751-4060-a224-84936fb5235b.png)

But when I try to access it in a test or send it with another request, the cookie is not available.
```
pm.test("Has authentication cookie", function() {
    pm.expect(pm.cookies.has('DownloadToken')).to.be.true; // Test fails
}
```
