### ISSUE TITLE
Link handling in tables in docs' description is weird

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5180]
**Describe the bug**
When you publish a document that has a long table, the longer table becomes clickable with ‘click to expand’ overlay. With links in longer table, the ‘expand’ action then overrides the link action. So, when a user clicks a link expecting to navigate, instead they are shown the full-screen table view. 

**To Reproduce**
1. Publish a documentation that has a table of more than 10 rows with few clickable links in it.
2. Click on a 'link' inside the table.

**Comment by bt-dd** [comment]
I believe this could be solved by looking at the click target and checking if it is an <a> tag, with a non-blank href value? Then if that is the case, don't open the expanded view?

Alternatively, could also make only the hoverable "Click to Expand" button clickable, instead of the whole table?

**Comment by JP-from-Postman** [comment]
Comments on desired behavior from user (via Support):
- If the user clicks the hyperlink then open the link
- If the user clicks elsewhere in the table, expand table

It looks like linking to anchor tags in the doc does actually work, but when the table is expanded you can't tell until minimizing the view again:

https://documenter.getpostman.com/view/5293839/S1LvV8KL
1) At page above, expand table
2) Click link for Example Section
3) See URL change to: https://documenter.getpostman.com/view/5293839/S1LvV8KL#example-section
4) Minimize table view (press ESC), and see that the page is at the correct heading

This happens whether or not you click Expand first and then click the link for Example Section.

Might be good to just go straight to the indicated anchor tag when clicked without expanding, and also automatically minimize the table view when a link to an anchor tag is clicked.

**Comment by ghost** [comment]
> It looks like linking to anchor tags in the doc does actually work, but when the table is expanded you can't tell until minimizing the view again

that's another way to define "does not work".

> Comments on desired behavior from user (via Support):
> If the user clicks the hyperlink then open the link
> If the user clicks elsewhere in the table, expand table

"If the user clicks the hyperlink then open the link", thereby allowing my user to completely miss the data below the cutoff.
don't forget to include the link to the instructional video explaining how this "feature" works so my clients won't be confused.

**better ideas:** 
1) my favorite!! **provide an option to disable this feature**
2) provide options to control the cutoff height of the table and to add a permanent "click to expand" button on long tables if desired.

**Comment by ghost** [comment]
also, what genius decided it was better to open a whole other page to show the expanded table instead of just expanding the table in place?
**VERY bad design!**

**Comment by Cazaimi** [comment]
@elrod-johnson , we've fixed this in production. Please find the GIF below:

![Mar-20-2020 19-17-53](https://user-images.githubusercontent.com/13660453/77169689-f215fd00-6adf-11ea-9452-451a9b7a6deb.gif)

Hope this solves it 🙂.

**Comment by rostykzub** [comment]
@Raja-Simha Hello.
I am still experiencing this issue when opening a link that is an anchor to some part of my documentation

My documentation is stored on `https://developers.recman.no/` domain
And if I paste `https://developers.recman.no/#e1695b17-6b58-4207-9975-dfd01760a844` link into the table and try to open it while this table is expanded - nothing is happening.

You are actually navigated to the appropriate anchor but the problem is that the expanded table view is not closed after you pressed the link and it becomes an overlay for the content of the page...

This is really annoying issue and makes it difficult for users to navigate over the documentation..

![bug postman](https://user-images.githubusercontent.com/51949386/174078601-c2c752a1-47da-41ea-af7d-8e6338dbaef0.gif)
