### ISSUE TITLE
Collection variables not resolved while previewing auth

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#5452]
_internally reported_

**Comment by sujayvenaik** [comment]
This is fixed in v6.5.2

**Comment by broom9** [comment]
Has this been fixed? I'm using v6.6.0 and still seeing this issue.

1. Adding a collection variable named "myKey"
2. In Collection Authorization tab, choose "Basic Auth", then input `{{myKey}}` in the username field.
3. It shows "unresolved variable", although if I create a request and choose "inherit auth from parent" it works.

**Comment by re-jim** [comment]
I'm using v6.6.1 and I'm still seeing this issue
