### ISSUE TITLE
Closing runner mid-run, causes native app to crash

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5848]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Cancelling a request while it is pending, or closing the Collection Runner window before the active run completes, causes the native app to crash.

**To Reproduce**

Import attached Collection into Postman app:
[Cancel Bug.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/2809172/Cancel.Bug.postman_collection.json.zip)

_Single request:_
1. Select the request `echo` from the imported Collection, and send it (uses .setTimeout() to delay request)
2. In the response pane, click `Cancel Request` while the response is pending
3. App will crash

_Collection Runner:_
1. Open the Collection Runner, and run the imported Collection
2. Close the Runner window before the run has completed
3. App will Crash

**Expected behavior**
Cancelling an individual request or Collection run while it is pending does not cause the app to crash

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 6.7.2
 - OS: MacOS High Sierra 10.13.6, Windows

**Comment by sujayvenaik** [comment]
Duplicate of #5799

**Comment by saswatds** [comment]
This issue has been fixed in the latest version of the app `7.18.0`. Closing this issue for now

**Comment by simonschllng** [comment]
In v7.36.1 Postman still crashes in runner. Now it's not crashing on close of the runner but when opening it again afterwards.
