### ISSUE TITLE
Migrate Your Team to Postman 7.0 not closing

### ISSUE THREAD

**Issue by jlavelle-uk** [a85/POSTMan-Chrome-Extension#6008]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

On opening Postman 7.0 on Linux the message ` Migrate Your Team to Postman 7.0 ` is displayed.

I migrated my team successfully but the message won't go away! And I cannot use Postman

**To Reproduce**
1. Start Postman
2. See Message

**Expected behavior**

the Message to go away!

**Screenshots**

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 7.0 ? don't know exactly as it won't start]
 - OS: [e.g. Linux Mint]

**Additional context**
Web App works fine
![screenshot from 2019-03-02 18-30-56](https://user-images.githubusercontent.com/43206573/53685984-b4e69d80-3d19-11e9-9fb3-e91a92a209f6.png)

**Comment by prashantagarwal** [comment]
@jlavelle-uk Can you try closing and reopening the app once.

**Comment by JQL** [comment]
Thanks for getting back to me so quickly.

#### Things I've tried:
* Closing and reopening the App - 6 times
* Clicking Sign out (and signing out) - twice
* Restarting Linux then starting the App - twice 
* Doing various activites on the Web version
* Trying to do the tutorial (didn't get far as I couldn't click on any buttons)
* Trying to click on the ` New ` button before the message was displayed
* Trying to click on the ` New ` button then clicking on ` Request ` before the message was displayed

The last one worked! _Trying to click on the ` New ` button then clicking on ` Request ` before the message was displayed_

May I suggest a Close button is added to the Message Window...

**Comment by numaanashraf** [comment]
@JQL Thanks for clarifying. We had an issue at our end which was causing us to erroneously send you a migrate your team message after your team has  already migrated. We had identified and resolved the issue at our end and you should no longer receive that message.

**Comment by preethammavin** [comment]
@JQL @jlavelle-uk can you confirm if the issue is solved.

**Comment by jlavelle-uk** [comment]
Yes it is.

Sorry about the delay but my hosting service has gone under and I'm having
to migrate a lot of sites.

Best regards,
John Lavelle
john@jql.co.uk

Sent via awful Android

**Comment by preethammavin** [comment]
Thank you for letting us know, closing the thread now.

**Comment by Anyoks** [comment]
I still have the same issue. and @JQL 's solution didn't work for me.

**Comment by Anyoks** [comment]
> I still have the same issue. and @JQL 's solution didn't work for me.

I had to migrate from the web dashboard for this to for away. But I lost some unsaved changes.

**Comment by ro6** [comment]
I just experienced this as well. Trying fixes now.

**Comment by AllPDFfillersGoToHeaven** [comment]
experiencing this now...

**Comment by abdurrahman** [comment]
> experiencing this now...

I've recommend you to remove manually modal with following direction. Its a short term advise 😃 
View > Developer > Show Dev Tools and inspect modal for selection and delete.

Its also happening when you have team workspace, if you don't use then remove your account via browser. After that, It'll work on desktop app once you sign out and sign in again. For that purpose you have to follow 1st hacking step above to able to sign out.

My case when I having same issue: Postman v9.2.0

**Comment by q45** [comment]
im experiencing this as well
<img width="1010" alt="Screen Shot 2022-01-05 at 11 18 04 AM" src="https://user-images.githubusercontent.com/1934271/148268250-daca9cf8-41ff-413b-ae62-1be90d0c5f78.png">

**Comment by akshay-kulkarni-03** [comment]
@q45 we have fixed this issue from our end. Can you please verify from your end?

**Comment by q45** [comment]
@akshay-kulkarni-03 thanks for the note. I am still getting this when I open postman
<img width="1410" alt="Screen Shot 2022-01-07 at 10 41 17 AM" src="https://user-images.githubusercontent.com/1934271/148584436-861cb8cf-6054-49b8-a391-e65c61ff2fb1.png">
.

**Comment by akshay-kulkarni-03** [comment]
Hi @q45 can you try click on `Migrate my team` post which the modal should not longer pop up.
