### ISSUE TITLE
Environment variables not updated correctly

### ISSUE THREAD

**Issue by emilgodsk** [a85/POSTMan-Chrome-Extension#6144]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When I send a request to my server, I have set up a Test script to run after the response has been received, which takes a variable from the response header and assigns it to an environment variable. When I then send the request again, it use that variable as my Authentication variable using {{variable}}. However if I send a request too quickly after each other, Postman still thinks the variable is the old variable before the last request, even though I can see with console.log that it should already have been set to the new variable.

If I wait a little while, there is no problem at all, but sending it right away fails, since my server expects to receive the new {{variable}} variable as the authorization token.

I can reproduce this behavior without the use of my server backend, and just using a random URL, but still running the attached Test script and Pre-request script on the requests.

The Test-script and Pre-request scripts has been attached in the "Additional context" section of this Bug-report.

**To Reproduce**
1. Set an environment variable "variable" to a random value 
2. Open the Postman console
3. Send a request, to a random URL, where the attached Test script and Pre-request will run.
4. Once the first request finishes, quickly send a the same request, where the attached Test script and Pre-request script will run again.
5. See in the Postman console that the "Before:" value on the second request is the same as the previous "Before:" value on the first request, and not the "After:" value from the first request as expected.

(You can see on the time stamps on the screenshots, that these requests are called after each other)

**Expected behavior**
I expect the environment variable to be the one that has been set in the Test script, which the console.log spits out, and not the previous value. 

I use the pm.environment.get("variable")) and pm.environment.set("variable")), to get the variable saved by Postman and not a local variable that could have been cached.

See the attached screenshots. Screenshot 1 shows the expected behavior. Screenshot 2 shows the actual happenings.

**Screenshots**
Screenshot 1 (right):
<img width="990" alt="right" src="https://user-images.githubusercontent.com/18194629/54885573-eae0f280-4e7d-11e9-9767-2fe20c2072b3.png">

Screenshot 2 (wrong):
<img width="991" alt="wrong" src="https://user-images.githubusercontent.com/18194629/54885572-eae0f280-4e7d-11e9-9dec-9ee140149351.png">

**App information (please complete the following information):**
 - App Type: Postman for Mac
 - Postman Version: Version 7.0.6 - OS X 18.2.0 / x64
 - OS: macOS Mojave 10.14.3

**Additional context**
Test script:
```
var authToken = Math.random().toString(36).substring(2);
pm.environment.set("variable", authToken);
console.log("After:" + pm.environment.get("variable"));
```

Pre-request script:
```
console.log("Before:" + pm.environment.get("variable"));
```

**Comment by kamalaknn** [comment]
Hi @egodsk 

Thanks for writing in. We batch updates to environments for a maximum of 1 second to improve the performance of writing those updates. This could have led to you seeing an outdated value of the environment.

We will work to  make sure this optimization does not affect workflows in a noticeable way.

Could you confirm that when you say 'quickly' you are sending the second request in under a second after receiving the first response?

**Comment by emilgodsk** [comment]
Hi.

Yes. I’m sending the next request within 1 second of receiving the response from the first request.

However why it confuses me a lot, is that in my Test script i use `pm.environment.set("variable", string);` to set the enviroment variable and then use `pm.environment.get("variable");` to console log the value, which shows that the environment should have been updated to the new value.

But when I run the next request and I in the Per-request script do a console log of `pm.environment.get("variable");` the value is not the same, even though it is the exact same command.

So yes, it seems that after the 1 second delay you are talking about it is correctly saved to the environment, but using the console.log shows that it should already have been updated.

**Comment by kamalaknn** [comment]
Thanks @egodsk for the clarification. It helped us validate our fix.

Let me clarify why the console log of the original request showed the correct environment value.

1. When a request is executed Postman app creates a copy of the request and current environment and sends it to the execution engine - [postman-runtime](https://github.com/postmanlabs/postman-runtime)
2. Postman runtime executes the request using the copy of environment. 
3. Any updates made during the execution are on the copy of the environment (This is why during execution the values are accurate)
4. After the execution the updated environment is sent to the Postman app which replaces the original environment (This is where the update was throttled. So the next request created a copy of the original environment before the first request updated it)

I hope this clarifies the behavior. We understand that this could be annoying and we are working on a fix for this.

**Comment by ckanibal** [comment]
I am experiencing the same problem, when I try to fetch and set a CSRF-token asynchronically in a pre-request script like this:
```
function getToken() {
    return new Promise(function(resolve, reject) {
        pm.sendRequest({
            url: `${pm.environment.get('ip')}/xml/getter.xml`,
            method: 'POST',
            header: {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            body: {
                mode: 'urlencoded',
                urlencoded: [
                    { key: "fun", value: "3", disabled: false }
                ]
            }
        }, function (err, res) {
            if (!err) {
                const {multilang: {Lang, MsoId, Token, WebCapPor, lang_support}} = xml2Json(res.text());
                resolve(Token);
            } else {
                reject(err);
            }
        });
    });
}

getToken()
    .then(token => pm.environment.set("token", token) )
    .catch(console.error);
```
It works, however, when I set the token directly in the response-callback. So, as a workaround:
```
pm.sendRequest({
    url: `${pm.environment.get('ip')}/xml/getter.xml`,
    method: 'POST',
    header: {
        'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: {
        mode: 'urlencoded',
        urlencoded: [
            { key: "fun", value: "3", disabled: false }
        ]
    }
}, function (err, res) {
    if (err === null) {
        const {multilang: {Lang, MsoId, Token, WebCapPor, lang_support}} = xml2Json(res.text());
        pm.environment.set("token", Token);
    } else {
        console.error(err);
    }
});
```
Any fix is highly appreciated!

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0.8

**Comment by orShapira** [comment]
the same issue of @ckanibal is happening to me at v7.19.1

**Comment by haroldiedema** [comment]
The issue described by @ckanibal still happens in version 9.1.3 (latest at time of writing).
