### ISSUE TITLE
App doesn't receive sync changes after clicking the sync icon

### ISSUE THREAD

**Issue by kamalaknn** [a85/POSTMan-Chrome-Extension#6239]
**Describe the bug**
If the Sync indicator icon is clicked when it is in the connected state, the app stops listening to changes coming from Sync.

So any further changes made from the app are synced, but any changes made outside the app don't come to this app.

**To Reproduce**
1. Wait for sync to finish. Sync indicator will turn to orange
2. Click the Sync icon
3. Make some changes from another app/web dashboard
4. Observe that these changes don't come to this app

**Expected behavior**
App should be listening to changes after clicking the sync icon

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.0
 - OS: N/A

**Comment by VaporFan** [comment]
Same. My changes from app (mac osx) are not syncing to published collections.

**Comment by sujayvenaik** [comment]
Hey @VaporFan 
We have fixed this in the latest canary version 7.1.0-canary02 and would be pushing out to the stable release later this week.

**Comment by labifrancis** [comment]
A user reports that this issue sometimes happens with Postman Canary but more reliable than the main app.

**Comment by jperucello** [comment]
I did some tests on Postman Canary with my team and the sync pressing the button is still not working.
But, if I don't press the button and I just save the tab, then it seems to be working very well.

**Comment by sujayvenaik** [comment]
Hey, @jperucello On which canary version are you on?
Can you tell whether your changes are not going out or you are not receiving any changes from your team?

**Comment by jperucello** [comment]
@sujayvenaik version: v7.1.0-canary02
After we click on sync, the button keeps with loading animation and the sync is stuck for both scenarios: send new updates and receive updates.
It goes back to sync when I close the files and open again and not click on sync anymore.

**Comment by sujayvenaik** [comment]
@jperucello Can you help us with the logs?
View -> Developer -> View Logs in Finder. You will find all the log files here.

**Comment by jperucello** [comment]
[canary-logs.zip](https://github.com/postmanlabs/postman-app-support/files/3084809/canary-logs.zip)

**Comment by webcoder-eu** [comment]
I've come across the same sync'in problem. We share a collection and changes made by one of my develoipers come throgh late or usually don't come through at all. A temp workaround was to completely close the app and reopen then we see changes straight away. This isn't a proper solution though. We're worried that our changes will go missing if more than one person is editing collections hence only one user can do it for the time being. This is a serious bug.

**Comment by sujayvenaik** [comment]
Hey, we have pushed out a fix for this in the latest v7.0.9. Update to the latest app and notify if you find any other issues.

**Comment by masouddarvishi** [comment]
hello i have postman v7.13.0 still syncing is problem.

**Comment by vkondratiuk** [comment]
v7.14.0 the same problem.
`[5140][1576746974904][shared][warn]["TimelineHelpers~syncAndSubscribeTimeline: Could not subscribe to timeline",{"name":"Error","message":"BaseSyncTimeline~getPendingServerChanges: Could not make /sync call. Exceeded maximum retry count for environment:<redacted>","stack":"Error: BaseSyncTimeline~getPendingServerChanges: Could not make /sync call. Exceeded maximum retry count for environment:<redacted>\n    at EnvironmentTimeline.getPendingServerChanges (file:///C:/Users/Admin/AppData/Local/Postman/app-7.14.0/resources/app.asar/js/shared.js:5386:13)\n    at EnvironmentTimeline._sync (file:///C:/Users/Admin/AppData/Local/Postman/app-7.14.0/resources/app.asar/js/shared.js:4959:36)"}]`

**Comment by zarpio** [comment]
From April 15, 2020, getting this issue not able to sync :-(

**Comment by denz404** [comment]
> From April 15, 2020, getting this issue not able to sync :-(

@zarpio  you got a solution?

**Comment by arlemi** [comment]
@denz404 Some users are experiencing degraded performance with the app, including sync. You can follow the issue on our status page: https://status.postman.com/

**Comment by imtrobin** [comment]
7.29.1, I'm also seeing syncing issues. My routes are synced, but they are not in correct folders after syncing

**Comment by firemaples** [comment]
Same issue on 7.30.1 (mac osx)

**Comment by AhmadVatani** [comment]
Same issue on 7.34.0 (Mac OS X 19.6.0 / x64)

**Comment by nasouhmr** [comment]
same issue on 23-02-2021 (Win 10 /  x64)
