### ISSUE TITLE
empty request body after importing raw text in cURL format when there's backslash, apostroph and bracket opening

### ISSUE THREAD

**Issue by oprogramador** [a85/POSTMan-Chrome-Extension#6289]
**To Reproduce**
1) Click `Import` (top left corner)
2) Select `Paste Raw Text` tab
3) Paste this text:
```
curl 'http://localhost:3014/auctions' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36' -H 'Content-Type: application/json' --data-binary $'{"foo":"bar\'s ("}' --compressed
```
4) In the `Body` tab there's an empty body though a body was provided in the imported request
5) In fact, no request body is sent

**Expected behavior**
4) `Body` tab should show this request body:
```
{"foo":"bar's ("}
```
5) The request body from the previous point should be sent.

**Screenshots**
<img width="985" alt="Screenshot 2019-04-13 at 01 13 43" src="https://user-images.githubusercontent.com/8701039/56070706-c182fa80-5d89-11e9-9d3a-b236d9bf76b1.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.7.4
 - OS: Mac OS X 10.14.4

**Additional context**
- It occurs when there's `\'` and next `(`.
- When I paste `curl 'http://localhost:3002/auctions' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36' -H 'Content-Type: application/json' --data-binary $'{"foo":"bar\'s a"}' --compressed`, it shows a request body but incorrect one (`{"foo":"bar\s a}'`).
- The original `curl 'http://localhost:3014/auctions' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36' -H 'Content-Type: application/json' --data-binary $'{"foo":"bar\'s ("}' --compressed` works well when using cURL directly from bash CLI (the server obtains correctly `{"foo":"bar's ("}` request body.

**Comment by abhijitkane** [comment]
@oprogramador Can you confirm this fixed in the latest version of Postman Canary (https://getpostman.com/canary)?

**Comment by oprogramador** [comment]
@abhijitkane 

It's still broken:
<img width="1197" alt="Screenshot 2019-06-05 at 01 46 43" src="https://user-images.githubusercontent.com/8701039/58920742-d9e11700-8733-11e9-9eac-765598852270.png">

**Comment by abhijitkane** [comment]
@oprogramador Can you confirm you're on 7.1.1-canary05? I'm getting the expected output: 
<img width="938" alt="Screen Shot 2019-06-05 at 10 23 51" src="https://user-images.githubusercontent.com/681190/58931130-16386580-877c-11e9-9b95-64fafa712582.png">

The version can be checked at Settings > About (Settings > Update to update)

**Comment by abhijitkane** [comment]
@oprogramador Feel free to add a comment if you're still seeing this in the latest build.

**Comment by oprogramador** [comment]
It's fixed in 7.36.5:

![image](https://user-images.githubusercontent.com/8701039/121812889-f5a81d80-cc69-11eb-8e05-26b3ffd5650e.png)
