### ISSUE TITLE
Example's response preview not working

### ISSUE THREAD

**Issue by lauxjpn** [a85/POSTMan-Chrome-Extension#6292]
**Describe the bug**
After saving an example of a request/response, the example's response preview does not show anything, despite the fact, that the response preview did work before saving it as an example and despite the "Pretty" and "Raw" tabs containing valid HTML code.

**To Reproduce**
1. Retrieve an HTML page as a response of a request.
2. Save that request/response pair as an example.
3. Click the "Preview" tab of the example's response.
4. See an empty preview.

**Expected behavior**
The preview should be displayed as it is for the response of a request.

**App information (please complete the following information):**
 - Postman Version v7.0.7
 - OS: Windows 10 (1809)

**Comment by numaanashraf** [comment]
@lauxjpn Is there a publicly accessible endpoint we can try to replicate this?

**Comment by lauxjpn** [comment]
@numaanashraf This issue can be replicated with *any* endpoint that responds with valid HTML.
I just tried it again against multiple sites including https://google.com

**Comment by numaanashraf** [comment]
@lauxjpn Thanks. I was able to replicate this.

**Comment by sujayvenaik** [comment]
Hey @lauxjpn  We pushed out a fix for this in the latest v7.0.9.

**Comment by hillsydev** [comment]
Hey @saswatds, this problem still exists in 7.13.0.  I can issue a GET to an API, result appears in the 'Pretty' and 'Raw' tab, but clicking in the 'Preview' tab shows nothing.  Loaded the same URL in Chrome and FF, and content displays as expected.  Content is a swagger/index.html response from a .net core 2.2 app.

However, if i try issuing a GET to an endpoint which produces a plain JSON result, it does get rendered in the 'Preview' tab as expected.

**Comment by rgarrett1127** [comment]
@saswatds, I am also seeing this issue in v7.13 when trying to authenticate with OpenId connect and Azure using POST. The HTML response from Azure is visible in the 'Pretty' and 'Raw' tabs but not the 'Preview' tab.   Standard JSON results from GET requests seem to work as expected.
