### ISSUE TITLE
Global Proxy Configuration not working when request url has port

### ISSUE THREAD

**Issue by darrelldraney** [a85/POSTMan-Chrome-Extension#6364]
When I upgraded postman to Version 7.0.9 on Mac OS (10.14.2 (18C54)) my global proxy configuration in postman is no longer used when a request url contains a port

Proxy configs in postman
```
Global Proxy Configuration:     ON
Proxy Type:                     http, https
Proxy Server:                   127.0.0.1:9090
Proxy Auth:                     OFF
Use System Proxy:               OFF
```

Example requests expressed as curl statements

Ignores proxy configs:
```
curl -X GET \
  http://example.host.com:8081/request/path
```

Uses proxy configs:
```
curl -X GET \
  http://example.host.com/request/path
```

Prior to upgrading both of these types of requests would use the proxy config

**Comment by dgriswo** [comment]
I am experiencing the same behavior using v7.0.9 on Windows 7.

If a request specifies a port other than :80 or :443, the global proxy setting is ignored.

**Comment by codenirvana** [comment]
@darrelldraney @dgriswo Thanks for reporting this.

Is this happening after the upgrade (v7.0.9)? I see similar behavior with older versions as well 😕

**Comment by darrelldraney** [comment]
@codenirvana, I downloaded  v7.0.7 and requests with ports are going to the proxy (as long as I include the protocol in the url). That being said, I do recall at some point in the past I had to start remembering to always add the protocol to the request url to get it to go to the proxy, so I just did a test in 7.0.7 where I left off the protocol so just 
```
curl -X GET example.host.com/request/path
``` 
and 
```
curl -X GET example.host.com:8081/request/path
```

 and the one with out a port did go to the proxy while the one with the port did not.

I'd prefer that all requests both with a protocol and without a protocol or with a port and without a port go to the proxy when the global proxy is configured, but I'm ok with having to include the protocol if that's the way it's intended to work.

**Comment by arnolde** [comment]
I have a similar issue with v7.0.9 on Windows 10, when configuring a proxy on port 8080 and then trying to access a destination with ip address like https://1.2.3.4:12345/deep/path (ssl cert checking is turned off) I am getting a timeout. I assume it's the same issue. Looking forward to a fixed release :-)

**Comment by avvari-da** [comment]
@codenirvana Same is the issue for me. Not working after upgrading to 7.0.9

**Comment by ppoojachd** [comment]
Same is the issue for me. Not working after upgrading to 7.0.9

**Comment by codenirvana** [comment]
We've fixed the issue in our internal library. Will update here once the fix is released in our stable or canary channel.

**Comment by Kapcash** [comment]
I'm still facing this issue in v7.0.10 :/

**Comment by codenirvana** [comment]
@darrelldraney @arnolde @dheeraj2dj This is fixed in the latest version of the Postman App (v7.1.1).

**Comment by arnolde** [comment]
@codenirvana Still doesnt work in 7.1.1 on Win10 v. 1803
Global Proxy configured: internal.host.name:8080 (also tried ipaddress of proxy)
Posting to URL: https://ip-address:port/sub/dir returns timeout, using hostname results in name resolve error (the workstation has no direct internet connection and no external DNS)
Both work fine if I use curl in a command prompt (on Win10):
curl -kx proxy-ip-address:8080 https://destination-FQDN:10111/sub/dir

**Comment by GreenLightt** [comment]
@codenirvana it's not ok in 7.1.1 on Mac 10.14.4

**Comment by GreenLightt** [comment]
@codenirvana it's not ok in 7.1.1 on Mac 10.14.4

**Comment by codenirvana** [comment]
@arnolde @GreenLightt Is this the first time you setup proxy configurations in Postman?
Can you try restarting the Postman app and check if the issue persists?

We made a temporary fix in 7.1.1 which patches the misconfigured proxy on the app boot, for new setup the patch is not effective until app restarts. We already made the stable fix for this which will be out soon.

**Comment by arnolde** [comment]
@codenirvana The proxy config was already in place, app was restarted upon update, and again manually after negative test result. I also changed the proxy config several times (hostname, ip address, https on/off, etc.) but nothing helps.

**Comment by arnolde** [comment]
Works now with 7.2.0. Thank you!
