### ISSUE TITLE
Deleting history group crashes the app

### ISSUE THREAD

**Issue by kingfer30** [a85/POSTMan-Chrome-Extension#6378]
**Describe the bug**
When I delete some group of history record , reported somethings went wrong. I can't continue to operate only when restart, but when it restart , that group I delete was went away

**To Reproduce**
1. Click on delete history(group)

**Expected behavior**

**Screenshots**
1.
![image](https://user-images.githubusercontent.com/34082198/56858030-ada0e080-69a6-11e9-8bc2-b67b814a9a18.png)
2.
![image](https://user-images.githubusercontent.com/34082198/56858033-bf828380-69a6-11e9-8635-407e7e98c2fe.png)
3.
![image](https://user-images.githubusercontent.com/34082198/56858036-cc06dc00-69a6-11e9-9fe8-9c250871fa4c.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [v7.0.9]
 - OS: [windows 10 professional edition]

**Additional context**

**Comment by numaanashraf** [comment]
@kingfer30 Thanks for reporting this. We are able to replicate this and will include the fix in the upcoming release.

**Comment by numaanashraf** [comment]
We've fixed this in Postman v7.1.0

**Comment by lavixu** [comment]
I am using 7.24.0 on Mac 10.13.6 and still see this issue. I had turned on the interceptor and did not channel the noise into a collection, that started filling my history. Deleting it just crashes the app and on rebooting the app,

**Comment by tostinni** [comment]
Similar problem with 7.26 on Windows, no crash but the history is not deleting, later I upgraded to 7.27.0 and after various retries I was able to delete the history.

However I guess the main problem is the fact that interceptor can be enabled with no filter and thus start catching all traffic and one might not find out until it has pilled up.

**Comment by davidlstanton** [comment]
@numaanashraf please re-open.  This is definitely not fixed!  Postman Mac 7.36.5
