### ISSUE TITLE
Windows ARM64 builds

### ISSUE THREAD

**Issue by Googulator** [a85/POSTMan-Chrome-Extension#6583]
Windows 10 has recently gained support for ARM64-based platforms, and multiple vendors
are now shipping such laptops. While 32-bit x86 code can run on these machines with emulation,
it would be nice to have a recompiled version available for native ARM64.

**Comment by Sourtoast** [comment]
Yes I'm looking forward to arm64 build

**Comment by dennisameling** [comment]
+1 for this! Would love to have improved performance by having a native arm64 version of Postman on the Surface Pro X 😊

**Comment by aarsan** [comment]
Would love to have this!

**Comment by siggipop** [comment]
Is this happening?

**Comment by sunyiming** [comment]
Apple M1 (#9346) and Linux ARM64 (#5816) is available. So what about Windows?

**Comment by Tirmisee** [comment]
One more voice from a Windows Dev Kit user

**Comment by RoLYroLLs** [comment]
Our company just moved from Win on x64 to Win on ARM64. I'm another advocate for windows ARM support. Thank you!

**Comment by DanielGoehler** [comment]
+1

**Comment by Austin3dPrinting** [comment]
+1

**Comment by siggipop** [comment]
+1

**Comment by erikburman** [comment]
+1

**Comment by siggipop** [comment]
While we are waiting for ARM version of Postman client for windows, you can utilize web version of Postman using browser like MS Edge/Chrome (arm version). Since postman client is based on Electron (Chromium and Node.js) which is basically a browser based app, the difference should me minimal. This way you get Postman on windows ARM64 without emulation.

**Comment by andriysavin** [comment]
It's hard to believe that no progress or communication has occured here for 5 years of this issue existence! So many software vendors now support ARM64 and Windows on ARM, and ARM was the second topic after AI at MS Build 2024, but Postman looks to be ignoring this demand, even though the effort to support ARM64 is minimal for such an app. Fortnunately, there are many alternatives, as well as API testing [built into Visual Studio](https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0).

**Comment by falle1234** [comment]
+1

**Comment by TeddMcAdams** [comment]
+1 
New Surface Pro is shipping with ARM chips.  
Most programs I am re-installing have ARM64 installers.  Not Postman? :(

**Comment by vanUbor** [comment]
same, want to try the new surface laptop with arm, currently checking the apps I need, please add arm support

**Comment by manningli** [comment]
+1 for considering the Surface Laptop and I can't believe we still don't have Postman for Windows arm64

**Comment by airtaxi** [comment]
+1

**Comment by PsyChonek** [comment]
+1

**Comment by buvinghausen** [comment]
With the viability and looming popularity of Snapdragon X chips it's time to support ARM64 on Windows officially.  Thankfully the emulation layer seems to be working fine but would still be nice to have a native app.

**Comment by andriysavin** [comment]
> Thankfully the emulation layer seems to be working fine

Maybe on Snapdragon X it works fine (MS claims it optimized the emulation for these chips), but on Apple Silicon chips (in Parallels VM) emulated Postman is very slow and laggish. Painful to use :(

**Comment by joe-mills** [comment]
> > Thankfully the emulation layer seems to be working fine
> 
> Maybe on Snapdragon X it works fine (MS claims it optimized the emulation for these chips), but on Apple Silicon chips (in Parallels VM) emulated Postman is very slow and laggish. Painful to use :(

For me also its very sluggish on the new Surface 7 laptop.  Emulation 'works' but only as a short term solution.

**Comment by buvinghausen** [comment]
> For me also its very sluggish on the new Surface 7 laptop. Emulation 'works' but only as a short term solution.

To be fair I have the 64 gigs of ram model so it probably does cover up some emulation sins...

**Comment by talynone** [comment]
+1 vote for this

**Comment by Shiiiwa** [comment]
+1 vote

**Comment by Painkiller995** [comment]
+1 vote

**Comment by lexcyn** [comment]
+1 let's get ARM support added!

**Comment by sXe79** [comment]
+1 ARM support

**Comment by danforero** [comment]
September 2024, more than 5 years after this issue was opened and still nothing, not even in the canary releases, it's fair to assume this is not happening and the project was abandoned, I'll be looking for open source alternatives.

**Comment by airtaxi** [comment]
For anyone finding alternative, use [Hoppscotch](https://hoppscotch.io/) with this [Extension (both for Chrome and Edge)](https://chromewebstore.google.com/detail/hoppscotch-browser-extens/amknoiejhlmhancpahfcfcfhllgkpbld) or [Extension (for Firefox)](https://addons.mozilla.org/en-US/firefox/addon/hoppscotch)

**Comment by anton-makarenko** [comment]
+1
I support the common vote to get Postman for ARM

**Comment by buvinghausen** [comment]
You can use the Postman extension in VS Code and it seems to run in arm64 mode inside the Code.exe executable.

**Comment by Sir-Rain** [comment]
+1
I really need this.

**Comment by qKOMAPp** [comment]
+1

**Comment by Molier** [comment]
any update on this topic with the new batch of windows on Arm pcs that came out and the industry push towards snapdragon chips? seems relevant enough to include in the windows installer?

**Comment by betancd** [comment]
Anyone try it with a Snapdragon X machine yet? Just curious if the emulation is any good compared to old ARM chips.

**Comment by danforero** [comment]
> Anyone try it with a Snapdragon X machine yet? Just curious if the emulation is any good compared to old ARM chips. 

The emulation is good. These are very good machines, but it's always better to have the native application, especially if you are running multiple applications at the same time. I can run multiple instances of Visual Studio with no issues, but I can tell some drop-in performance when running Postman x64 emulated.

**Comment by krisalcordo** [comment]
Additional request for ARM64 support

**Comment by tseanf** [comment]
+1 ARM64 Support

**Comment by Molier** [comment]
> Anyone try it with a Snapdragon X machine yet? Just curious if the emulation is any good compared to old ARM chips.

for some reason the postman emulated instance is extremely resource hungry on my x-elite surface pro11 , laggy and doesnt like existing on it. The machine has to also turn on the fans, which I have only seen when building giant python modules from source, using 100cpu... so not well.

But if you are comparing, from what I have read from the older machines (which I did not use), the emulation is night and day. It will emulate almost anything, even though the gaps in performance. So for stuff you don`t have to use all day/daily, it works. They did very well bringing the emulation into the future.

**Comment by technobrat-us** [comment]
> > Anyone try it with a Snapdragon X machine yet? Just curious if the emulation is any good compared to old ARM chips.
> 
> for some reason the postman emulated instance is extremely resource hungry on my x-elite surface pro11 , laggy and doesnt like existing on it. The machine has to also turn on the fans, which I have only seen when building giant python modules from source, using 100cpu... so not well.
> 
> But if you are comparing, from what I have read from the older machines (which I did not use), the emulation is night and day. It will emulate almost anything, even though the gaps in performance. So for stuff you don`t have to use all day/daily, it works. They did very well bringing the emulation into the future.

+1 for getting an ARM for windows version of POSTMAN -- but emulator works just fine in my experience.

I currently use the new T14s with the Snapdragon X Elite chip, I also own a powerful workstation with Threadripper 3960x and 256GB ram and previously to the T14s I was running the X13s with the 1st gen Snapdragon 8x which worked just fine. The previous generation was LESS power efficient and capable than this newer generation of Snapdragon X Elite chips, this new chip is VERY good for 98% of windows users and 95% of software engineers that are NOT dependent on these light machines for compiling projects but scripting, db navigation/ management, etc... You can still compile things on this X Elite machine, I just haven't had the need to do so for large projects as I have the resources to do it elsewhere. 

I easily get 16h of work coding, browsing, db querying, not much compiling unless it is a small project. Large projects it is just easier for me to save the work I've done on the laptop and use the workstation for compiling larger projects, just more efficient that way in general as I can do something else while the workstation or server compiles what is needed.

I have had ZERO issues of latency @Molier has mentioned - I have right now RStudio open with a reasonable volume of data loaded to it as well as Postman open and I'm sitting at 16-25% CPU usage and 21% (of 64GB) I have. All applications I need work just fine and had zero issues with compatibility. When I had the x13s in 2022/3 as an early adopter there were more applications that didn't work well or at all like Dropbox (which literally made me swap to OneDrive -- but apparently now Dropbox has native application for ARM) but I've had no issues other than that to be quite honest and have been using Windows Arm chips for the second generation with no complaints... it just got a lot better as the new snapdragon X Elite chip is quite "snappy" and the "umph"/ power I lacked from the first generation has greatly surpassed on this new chip with even better battery life!! So if you wanted a green light to purchase a laptop with X Elite Chip, this is your sign!

**Comment by inha18minseokkim** [comment]
+1 vote since i've been using SPX..

**Comment by brunohoff** [comment]
+1, emulated x64 is so slow :(

**Comment by talynone** [comment]
From [Mike Bell](https://community.postman.com/u/also-mike-bell) on 12/18/2024:

> Hold tight! Windows ARM support is something we’re exploring right now and I hope to be able to share more soon.

Source: https://community.postman.com/t/the-postman-drop-december-edition/72615/8

**Comment by horros** [comment]
Just to bump and add to the interest; a native Windows Arm64 build would be the bee's knees.

**Comment by Sebbiv** [comment]
+1 any updates on this ?

**Comment by talynone** [comment]
GitHub Actions now supports Windows on Arm runners for all public repos:

https://blogs.windows.com/windowsdeveloper/2025/04/14/github-actions-now-supports-windows-on-arm-runners-for-all-public-repos/

Hopefully that should push this request forward.

**Comment by ktoksoz** [comment]
+1

**Comment by bartowski1182** [comment]
postman EATS my CPU and battery while open doing nothing, really hope an ARM64 build might fix it, please consider

**Comment by Sebbiv** [comment]
@postman-staff
please could you provide any information about the Windows ARM64 Postman client plans? The x64 version is unusable in the current state and we have to use the web version or extensions in vs code which aren't ideal for me and my team

**Comment by ravero** [comment]
Its a shame that @postman-staff doesn't provide any update **on a thread that is open for more than 6 years**, on a demand that is very high at this moment. From Microsoft to JetBrains, to lots of small toolings are providing ARM64 versions of their products on Windows. There's no excuses for Postman to not have such an option.

Everyone on my team (myself included) started migrating to other solutions that has proper support. I hope you don't get late to this trend...

**Comment by sXe79** [comment]
Yep, it's a shame @postman-staff, had plenty of time to deal with this. And no comunications at all is not professional.
Looking for alternatives.

**Comment by chaba11** [comment]
Same over here. I think what makes this so dissapointing it's that Postman it's an electron based app. So, we're not asking to rewrite the entire app. It's just to add another build target. Such a shame.

**Comment by gabriel-werzner** [comment]
+1 for this, every app I have except postman has this option

**Comment by tseanf** [comment]
This and GitKraken are my only 2 holdouts.:.


*Sean Fuhrmann*
Systems Architect

*Sail POS Solutions*
d:  (855) Sail-POS x700
e:  ***@***.***

**Comment by Sebbiv** [comment]
@postman-staff 
Could you at least provide information if this is something that is being worked on ?

**Comment by martin131** [comment]
The emulated version of Postman is extremely slow. However, I just tried the web version of Postman (https://web.postman.co/home)
) in Chrome, and it works much better. If you install the Postman web version in Chrome as an app, you’ll get an experience very close to a native application. 

You’ll also need to install the Postman Agent app on your computer so that your requests don’t go through the cloud - https://learning.postman.com/docs/getting-started/basics/about-postman-agent/

**Comment by a85** [comment]
This is being worked on. We will ship this next month. Agree that it shouldn't have taken this long. We will do better.

**Comment by Sebbiv** [comment]
@a85 Glad to hear that, thanks for the update.

**Comment by gabriel-werzner** [comment]
> This is being worked on. We will ship this next month. Agree that it shouldn't have taken this long. We will do better.

thanks a lot, this is appreciated

**Comment by simpleetech** [comment]
looking forward to this!

**Comment by cjohnsto-nz** [comment]
Very exciting news!

**Comment by talynone** [comment]
Would have been good to release this during/before Qualcomm's Snapdragon 2025 Summit event, you could have been part of their announcements of more native app adoptions.

**Comment by AlsoMikeBell** [comment]
Hi all, I lead Client Platform engineering for Postman.  We’re planning on having a canary/preview build available next week, with official release later this month. 

There may still be a few bugs and rough edges in the preview build, but I’d love to provide it to some of you to get early feedback.  If you’re interested, can you email me at mike.bell@postman.com and i’ll reach out when we’re ready.

Thanks!

**Comment by saecurrry** [comment]
Any news on the Arm64 release?

**Comment by AlsoMikeBell** [comment]
Happy Friday everyone. I'm excited to let you know you can download our native Windows ARM64 build now.

You can find the latest version at https://dl.pstmn.io/download/latest/windows_arm64
(We'll have our download pages updated soon at postman.com as well)

Thank you all for your patience, looking forward to hearing your feedback!

**Comment by talynone** [comment]
> Happy Friday everyone. I'm excited to let you know you can download our native Windows ARM64 build now.

Awesome! Probably want to update that link to be https instead of http.

**Comment by talynone** [comment]
@AlsoMikeBell The link seems to be broken now, returns 500 error. 

Edit: working now

**Comment by buvinghausen** [comment]
Only issue so far is the check for update link spins forever seemingly

**Comment by talynone** [comment]
Just wanted to say running great so far, enjoying the increased performance on heavy tasks such as GraphQL query prototyping on endpoints with large GraphQL schemas.

**Comment by AlsoMikeBell** [comment]
Thanks to our early testers and everyone who has tried it since!

Downloads are now available at https://www.postman.com/downloads/

**Comment by JdAlofa** [comment]
@AlsoMikeBell, Shoutout to the team, there is a decent performance improvement with the arm version.

There is just one small hiccup remaining that seems to plague quite a few windows on arm software in transition as well.
While upgrading the app viw winget (the windows package manager) the manifest seems to not be precisely wired to upgrade to the  arm version and instead overrides the arm version with the x64 version.

It would be perfect if you guys could look into it

**Comment by AlsoMikeBell** [comment]
@JdAlofa will have the team look at this.

**Comment by buvinghausen** [comment]
@AlsoMikeBell my guess is this is probably why the ARM version of the postman app never finds new updates it just sits at 11.69.6 and says I'm using the latest version when my x64 machine is on 11.76.3

**Comment by JdAlofa** [comment]
Precisely, the arm version did not receive the new updates the last time i checked

**Comment by sXe79** [comment]
Same here, my arm version is overriden by a x64 via "winget update"

**Comment by sXe79** [comment]
@AlsoMikeBell just gave another shot. Downloaded the arm64 version from the website, ugraded via winget and got an override of x64 version :(

**Comment by AlsoMikeBell** [comment]
It's a two-fold issue:

1. Our ARM64 releases are currently behind x64 releases while we get the necessary support in our testing infrastructure to fully automate the process.
2. winget doesn't handle architecture filtering the best. You can try adding '--architecture arm64' on the command line, but it doesn't seem to want to install the latest arm64 package(even from an earlier version than 'latest'). It just recognizes that the latest version available doesn't have an arm64 package and skips installation. 

We did correct one issue while debugging this, checking for updates within the app should find 11.77.0 now and properly install it.

**Comment by sXe79** [comment]
@AlsoMikeBell  winget issue is still there, I've been able to install the arm version with "--architecture arm64" flag, but then winget update keep suggest me the x64 version:

winget update:
Postman arm64 11.77.0 Postman.Postman 11.77.0  11.80.4     
winget update --id Postman.Postman
https://dl.pstmn.io/download/version/11.80.4/windows_64

It's the only app that has such issue... may you investigate further?

**Comment by sXe79** [comment]
@AlsoMikeBell 
It seems this issue isn't considered at all. Too bad, it force me to look for alternatives because I use winget almost every day and this issue will prevent me to update with "winget update --all"

**Comment by TeddMcAdams** [comment]
> For anyone finding alternative, use [Hoppscotch](https://hoppscotch.io/) with this [Extension (both for Chrome and Edge)](https://chromewebstore.google.com/detail/hoppscotch-browser-extens/amknoiejhlmhancpahfcfcfhllgkpbld) or [Extension (for Firefox)](https://addons.mozilla.org/en-US/firefox/addon/hoppscotch)

+1 for this

I have moved on to Hoppscotch and it does everything I need.  Is not as laggy and bloated as Postman which is a nice benefit.

**Comment by cjohnsto-nz** [comment]
@AlsoMikeBell When is ARM64 windows getting the v12 update? I am locked to v11 and the site download does not make it clear that you're not getting any of the new features if you click download for ARM64

**Comment by talynone** [comment]
> [@AlsoMikeBell](https://github.com/AlsoMikeBell) When is ARM64 windows getting the v12 update? I am locked to v11 and the site download does not make it clear that you're not getting any of the new features if you click download for ARM64

@AlsoMikeBell Even the general download is broken, going to https://dl.pstmn.io/download/latest/windows_arm64

Will download a file without an extension. I had to rename it and give it a .exe extension to get it to run. Looks like Q/A needs a bit of a kick in the butt. 

Edit: looks like the .exe file download issue was fixed.

**Comment by JdAlofa** [comment]
The winget update appears to have been fixed on my end. I just upgraded all my winget packages and Postman got upgraded to v12.1.3 (arm64). @sXe79 @TeddMcAdams give it a try.
Thanks to the team @AlsoMikeBell

**Comment by sXe79** [comment]
> The winget update appears to have been fixed on my end. I just upgraded all my winget packages and Postman got upgraded to v12.1.3 (arm64). [@sXe79](https://github.com/sXe79) [@TeddMcAdams](https://github.com/TeddMcAdams) give it a try. Thanks to the team [@AlsoMikeBell](https://github.com/AlsoMikeBell)

Still not working for me:

(1/2) Trovato Postman [Postman.Postman] Versione 12.2.3
Questa applicazione viene concessa in licenza dal proprietario.
Microsoft non è responsabile né concede alcuna licenza a pacchetti di terze parti.
Download in corso https://dl.pstmn.io/download/version/12.2.3/windows_64
  █▋                              8.00 MB /  142 MB
Annullato

Also, I downloaded the last version from the website, the result of winget update:
Postman arm64 12.1.3  Postman.Postman 12.1.3   12.2.3      winget

**Comment by talynone** [comment]
> > The winget update appears to have been fixed on my end. I just upgraded all my winget packages and Postman got upgraded to v12.1.3 (arm64). [@sXe79](https://github.com/sXe79) [@TeddMcAdams](https://github.com/TeddMcAdams) give it a try. Thanks to the team [@AlsoMikeBell](https://github.com/AlsoMikeBell)
> 
> Still not working for me:


Looks like it's a different Winget package for the ARM64 version:

<img width="520" height="92" alt="Image" src="https://github.com/user-attachments/assets/ef297999-2fe1-465b-a62d-9bb5702879a4" />

**Comment by ShahinKohan** [comment]
This is a total bug in their deployment. It still happens. The only solution is to pin postman in Winget so it doesn't upgrade it.
