### ISSUE TITLE
Postman v7.1.1 数据返回格式显示出现不对齐,越位问题

### ISSUE THREAD

**Issue by ylanhds** [a85/POSTMan-Chrome-Extension#6650]
**Describe the bug**
![image](https://user-images.githubusercontent.com/24424233/58854326-8937d280-86cf-11e9-8af1-c9f3c55a8926.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [Postman v7.1.1]
 - OS: [18.04.1-Ubuntu]

**Additional context**

**Comment by shamasis** [comment]
Ah. Thank you for bringing this to notice. Looks like an issue with our text editor component. We are working to fix this and will post update in Postman Canary within the week: https://www.getpostman.com/downloads/canary

cc @kamalaknn @saswatds @codenirvana @numaanashraf

**Comment by saswatds** [comment]
Hi @zhangbaosheng this has been fixed in the latest version of Postman App.

Closing this issue now.

**Comment by ylanhds** [comment]
The problem still remains unresolved
To Reproduce
Steps to reproduce the behavior:

![image](https://user-images.githubusercontent.com/24424233/66538113-9a00c500-eb55-11e9-9c31-c08ee10bb450.png)
![image](https://user-images.githubusercontent.com/24424233/66538136-b270df80-eb55-11e9-88a7-537907d992da.png)
