### ISSUE TITLE
Collection disappeared suddenly and not found in trash

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#6669]
**Describe the bug**
A collection got disappeared suddenly from all the workspace. However, the collection owner can see the collection being present at https://go.postman.co/me/collections but he can neither access the collection nor share it with any workspace 

**To Reproduce**
1. Go to 'https://go.postman.co/me/collections'
2. Search for collection in question .'
3. Click on the collection & see the below error

**Expected behavior**
While the collection owner is still being a part of the team he should have EDITOR role for all the collections including the orphan collections.

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/59021863-4ceca980-886a-11e9-8443-f62f49e98307.png)

![image](https://user-images.githubusercontent.com/40994626/59021936-6ee62c00-886a-11e9-94f0-f6fe388c0842.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.1.1]
 - OS: macOS High Sierra 10.13.2

**Comment by preethammavin** [comment]
@Ramya-From-Postman we have pushed a fix for the same, closing the issue for now. Feel free to reopen it if it isn't so.

**Comment by Ramya-From-Postman** [comment]
@preethammavin,

The issue is still happening, collection owner doesn't have edit permission on the collection in a team workspace.
![image](https://user-images.githubusercontent.com/40994626/59342383-4c9b5500-8d27-11e9-9a0e-57f976d355d8.png)

**Comment by preethammavin** [comment]
@Ramya-From-Postman I see the confusion, the copy for the tool tip will be updated

But as of RBAC, a collection owner is just a creator and has no special role on the element in general

The user with the editor role on the collection can assign the said role the user. Will keep the issue open till we update the copy and enable it.

**Comment by ghost** [comment]
Hi, there!

This serious problem has just happened to one of my collections. My username: [renato.milan@latam.com](mailto:renato.milan@latam.com).

**Bug description**
The collection _iPOS_ got suddenly disappeared from _Cappta_ team workspace.

**To reproduce**
1. Go to https://go.postman.co/me/collections;
2. Search for collection in question.

**Expected behavior**
Collection available to be used.

**Screenshots**
Collection hidden from my collections list
![2019-11-19 13_50_02-Your Collections](https://user-images.githubusercontent.com/57957465/69167873-6447e800-0ad4-11ea-9433-3463a8573b70.png)

No activity related to collection deletion
![2019-11-19 13_50_15-Your Activity](https://user-images.githubusercontent.com/57957465/69167885-6b6ef600-0ad4-11ea-8d6d-3a39619a88c6.png)

**App information**
- App Type: Native App
- Postman Version: 7.11.0
- OS: Windows 10 Pro 64 bits

**Comment by Ramya-From-Postman** [comment]
Hi @renato-milan-latam-com,

I see the collection "**iPOS**" has been deleted from your team workspace. 
It could be possible that the other members of the team might have deleted it by mistake. Could you ask them to look for this collection in their Trash?

**Comment by ghost** [comment]
Hi, @Ramya-From-Postman! Thanks for your reply!

As you can probably also see, there is anybody else being part of my team workspace.
Where can I find my Trash? So I could also check if perhaps I deleted it by mistake.
Anyway, is there a way to restore it from Trash?

Looking forward to hear from you again. Regards,

Renato

**Comment by ghost** [comment]
Hi, there! Any news? Regards, Renato

**Comment by ghost** [comment]
Hi, there!

Could you please help me having back my collection _iPOS_ from _Cappta_ team workspace? 

Regards,

Renato

**Comment by qubiack** [comment]
The same for me. Collections are visible on Linux and online, but not on MacOS ;/

**Comment by Ramya-From-Postman** [comment]
@renato-milan-latam-com and @qubiack Could you raise a ticket at help@getpostman.com for this issue?

**Comment by qubiack** [comment]
To be honest I lose my trust for your software and I never again confined to it. One collection is disappeared. Four other collection doesn't have any items so I don't need to use this software anymore. I remove it.

**Comment by sankalp0o** [comment]
Hey @qubiack we're very sorry you lost your work! Can you raise a ticket at help@getpostman.com and we will try to recover them if possible. 

We're working hard in making sure no one runs into this problem and as you probably noticed on this thread, we've patched bugs which can cause this. I understand this has been a frustrating experience for you and therefore I request you to help us diagnose and fix this for everyone.

**Comment by sankalp0o** [comment]
We've fixed the copy in the tooltip as well as solved the original issue. I'm closing this issue but feel free to reopen this if you face more problems.

We're also making improvements to the Workspace activity feed which will now show events for collection deletions, as well as who deleted them, this should be out this month!

**Comment by qubiack** [comment]
It's happen again....
