### ISSUE TITLE
Error while installing Windows app: Failed to extract installer

### ISSUE THREAD

**Issue by rudrajeet03** [a85/POSTMan-Chrome-Extension#6707]
**Describe the bug**
Downloaded the version 7.1.1 for windows x64 from https://www.getpostman.com/products.
Installation fails with the error: _Failed to extract installer_
Issue persists with the same package downloaded on a different system as well.

**To Reproduce**
1. Go to 'Downloaded package Postman-win64-7.1.1-Setup.exe'
2. Double Click on package to install
4. See error (screenshot attached)

**Expected behavior**
Installation is successfull

**Screenshots**

![PostmanIssue](https://user-images.githubusercontent.com/40350564/59420228-6b9bf480-8dc4-11e9-9a87-eb3c99a7a3d4.PNG)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.1.1]
 - OS: [Windows 10 x64 operating system ]

**Comment by Raj-postman** [comment]
- App Type: Native App
- Postman version: 7.20 (stable) and 7.1.1 (Canary)
- OS: Windows 7
Same error message while installing the application with Stable and Canary version.

**Comment by rudrajeet03** [comment]
Hello @Kurmavathar 
 The issue I was facing is resolved. It seems there was a conflict with the security policy of my organisation regarding installation of non-standard applications from the internet.

Once I had the necessary exemptions from my IT dept, it installed just fine.

**Comment by rudrajeet03** [comment]
issue resolved as per above steps

**Comment by Raj-postman** [comment]
@numaanashraf The issue persists with the latest version of the application on both Stable and Canary version (v7.9 -Windows 10 x64). Hence, reopening this issue.

**Comment by harryi3t** [comment]
@Raj-postman Could you share some screenshots/screen-recording to help us identify the issue.
Also, please share the `SquirrelSetup.log` which is present at `%LOCALAPPDATA%\Postman`
![image](https://user-images.githubusercontent.com/5207331/68088864-24082900-fe89-11e9-9a06-34721f30bc07.png)

**Comment by thealiraza** [comment]
I am also facing the same issue and could not find postman folder in local app data
![hgh](https://user-images.githubusercontent.com/37246697/71621938-608ba300-2bf4-11ea-9f0e-d1a195578e27.PNG)

**Comment by thealiraza** [comment]
I have found a solution.
1. Install 7zip software.
2. Extract Postman.exe.
3. There will be a folder with unpkg extension. Extract that as well with 7zip.
4. Open the extracted folder, goto lib folder and then net45 folder. You will find Postman app there.

**Comment by ankurdengla** [comment]
@thealiraza From the screenshot it seems that you are in `SquirrelTemp` directory. Could you try typing `%LOCALAPPDATA%\Postman` in the explorer and check if there is the `SquirrelSetup.log` file. Alternatively you can try going to the path `C:\Users\{username}\AppData\Local\Postman`.

![Postman](https://user-images.githubusercontent.com/26045713/71667172-e7be4f80-2d89-11ea-83b5-be8172539671.gif)

**Comment by asi-postman** [comment]
@ankurdengla We have a user that is experiencing a similar issue with their install. They have tried the latest stable & canary version as an administrator. 

Below is a screen recording of the behavior when trying to locate the log files. 

https://www.loom.com/share/6ca80e777e7f4b53811e7f4c68e13e35

![image](https://user-images.githubusercontent.com/52974659/84176339-ecfc8600-aa1c-11ea-8a23-ed76254b2c7a.png)
![image](https://user-images.githubusercontent.com/52974659/84176367-fab20b80-aa1c-11ea-9118-0160c870f461.png)

**Comment by DannyDainton** [comment]
Hey @asi-postman,

Is this still and issue for that use / any other users trying to install the latest version of the app?

**Comment by gjd6640** [comment]
This just affected me. I have a group policy in place that disallows execution of files that are located under c:\ProgramData\. The installer was able to extract its files but when it tried to run update.exe it was blocked. The windows event logs showed this when I ran the installer:

`Access to C:\ProgramData\<myuserid>\SquirrelTemp\Update.exe has been restricted by your Administrator by location with policy rule {540fccd0-3cd0-4dcb-825d-e1a99cab5ef0} placed on path C:\ProgramData.`

Potential solutions so that others won't encounter this:
- Have the installer create a temporary subdirectory next to wherever the installation file was run (under its working directory). Remove that when the install completes.
- Improve the error message to describe what specifically failed (running the executable). Have the error message also instruct the user on how to re-run the installer with a user-supplied working path.

**Comment by mccannt** [comment]
Thanks for reporting this @gjd6640

**Comment by zhouyingge1104** [comment]
> I have found a solution.
> 
> 1. Install 7zip software.
> 2. Extract Postman.exe.
> 3. There will be a folder with unpkg extension. Extract that as well with 7zip.
> 4. Open the extracted folder, goto lib folder and then net45 folder. You will find Postman app there.

It works for me!

**Comment by ShokhrukhDeveloper** [comment]
HI every one I can't fix that problem  but you can use postman poratbale version on your windows and it works as installer

**Comment by icemons** [comment]
You're amazing guys still happening in 2024 and even the 7Zip solution used since 2019 no longer works

**Comment by faketw** [comment]
I'm facing the same problem here when I executing file 'GitHubDesktopSetup-x64.exe', but the problem is resolved when I executing 'GitHubDesktopSetup-x64 (1).exe'. I don't know why.

**Comment by serotoninN01** [comment]
Now 2025 still facing the same problem.
