### ISSUE TITLE
Exported CSV file from different applications is not working with collection runner

### ISSUE THREAD

**Issue by vikiCoder** [a85/POSTMan-Chrome-Extension#6784]
Exported CSV file gives the following error while using it in collection runner.
```
Error while parsing data file: Error: Invalid Closing Quote: got """ at line 2 instead of delimiter, row delimiter, trimmable character (if activated) or comment
```

CSV file that I am using:
```
id,name
1,"""Foo Bar"""
```

The same file was working in collection runner before updating to Postman App version 7.2.1 but it is giving above error after update.

**Steps to reproduce the behaviour**
1. Create a CSV file with above-given content
2. Select that CSV file in collection runner
3. Press run collection button
4. See error (shown in a toast)

 - App Type: Native App
 - Postman Version: 7.2.1
 - OS: any

**Additional context**
This is happening because when exported a CSV it uses `"` as the escape character to escape double quotes inside quoted fields. But latest Postman App needs the quotes inside a quoted field to be escaped by backslash `\`.

[Created by Postman internal]

**Comment by vikiCoder** [comment]
Fix for this is out in the latest canary of Postman App (version 7.3.0-canary05).

We have changed the escape character from `\` to `"` for CSV file. So now you can use exported CSV file from Google Sheets directly without preprocessing it.

**Comment by vikiCoder** [comment]
This is fixed in the latest version of Postman app (v7.3.4).

**Comment by cyrielle-hada** [comment]
@vikiCoder Windows Users exporting a .CSV file from a Microsoft Excel spreadsheet are still experiencing the issue. 

Steps to reproduce the behavior on **Windows** and **Microsoft Excel**. 
1 - Have a .xlsx file containing leading zero values.
<img width="438" alt="Screen Shot 2019-07-29 at 16 19 21" src="https://user-images.githubusercontent.com/47351631/62060242-aa72f600-b21c-11e9-87dc-ad556f8c5fd3.png">
2 - Export the file in CSV.
3 - Go to the Postman app and make sure it is updated it to v7.3.4 
4 - Open the Collection Runner for a collection. 
5 - Click `Select File` and upload the CSV exported in step 2. 
6 - Click `Preview` 

The value `0` and `+` are missing. 
![inline-1343085218](https://user-images.githubusercontent.com/47351631/62060136-80b9cf00-b21c-11e9-8512-3b8ef544ca50.png)

**Comment by AdrianTP** [comment]
I just had a similar issue to @cyrielle-hada helping a coworker troubleshoot why he couldn't run a collection with a CSV as input. The CSV in question was exported from Excel as UTF-8 CSV. The computer in question is a Mac, which was running both the Excel instance and the Postman instance. I examined the CSV and it looks like a normal CSV. It was just three columns, comma-delimited -- the first column contains only alphabetic characters and spaces (full names), the second column contains only alphanumeric characters (no spaces), and the third column contains email addresses. We even tried manually editing the file to quote each field, just in case, and that had no notable effect.

The workaround we decided on for now is to convert the CSV to JSON because that seemed to work in our testing.

![image](https://user-images.githubusercontent.com/1585276/62657913-2102a880-b92d-11e9-81fa-e2233001e643.png)

Example of the CSV data (just made it up as an example, not a direct copy-paste):
```csv
name,provider,email_address
Dafydd ab Hugh,Test1,dahugh@example.com
Alexander Abasheli,Test2,alexander.abasheli@example.com
Edwin Abbott Abbott,Test3,edwin.a.abbott@example.com
Kobo Abe,Test4,kobo.abe@example.com
Robert Abernathy,Test1,robert.abernathy@example.com
Dan Abnett,Test2,dan.abnett@example.com
Daniel Abraham,Test3,dabraham@example.com
Forrest J Ackerman,Test4,fjackerman@example.com
Douglas Adams,Test1,dnadams@example.com
```

The difference from the main issue is perhaps that the data appears appropriate in the preview, but something prevents it from populating correctly in the request body variables (`{{name}}` and `{{email_address}}`). The Collection Runner sent as many requests as there were lines in the CSV, but the Console (in Postman) showed the same values for each request (the first row of the CSV repeated every time), and the receiving API reported a `400 Bad Request` for each one. Manually replacing the variables with equivalent strings worked just fine, so it's not the API's problem, but seems to be Postman's. No error messages were displayed by Postman at any step in the process.

It's especially odd to me that the Preview functionality seems to work fine and the Console shows values filling in the proper format, but the Console *also* shows it repeating the first row each time, and the request fails each time.

Unfortunately I do not have access to the logs of the receiving API in order to verify what headers and request body were actually sent.

**Comment by fadhil0305** [comment]
Hi everyone, it seems that I also have the same problem when exporting data from excell to CSV ectension cannot be read from Postman. I have tried to find solutions from several sources, but the results are still not as expected.
The solution I can do is **export files to CSV via Google Sheets**, this is very helpful and the data can be read as expected in Postman. I think this is a problem from the Office itself. Hope this can help




![Screenshot 2024-08-09 181231](https://github.com/user-attachments/assets/bfa022f3-c045-455a-8652-35a1807c38a2)
