### ISSUE TITLE
Cookies disappearing after 1 request

### ISSUE THREAD

**Issue by akaczinski** [a85/POSTMan-Chrome-Extension#6807]
**Describe the bug**
If a site sends me a "set-cookie" header, the cookie will save for only one more request. After that request, if another "set-cookie" header is not sent to replace the prior, it will be wiped from Postman.

**To Reproduce**
1. Login to site with a x-www-form-urlencoded body to send in username/pass
2. Confirm the server responded with a 'set-cookie : sessionToken' header to confirm login
3. Go to another page on that domain's server
4. Verify in the "Cookies" button that after visiting this second site, the session cookie from before is now gone.

**Expected behavior**
Cookies persist until removed manually or by logging out

**App information (please complete the following information):**
 - PostmanCanary
 - v7.3.0-canary05 (pretty sure this started in v7.3.0-canary03)
 - Windows 10

**Comment by harryi3t** [comment]
@akaczinski 
Thanks for reporting this issue.
We have found the root cause of this issue and are working on the fix.
Will update here once the fix is released.

Thanks again 👍

**Comment by codenirvana** [comment]
@akaczinski Thanks for using Postman Canary and reporting this issue.
But, We are not able to reproduce this at our end, can you provide more information or steps to reproduce?

Here's how I tried:
1. Clear all cookies for `postman-echo.com`
2. Request `http://postman-echo.com/cookies/set?foo=bar`
    > set-cookie `foo=bar; Path=/`
3. Request `http://postman-echo.com/cookies/set?bar=baz`
    > set-cookie `bar=baz; Path=/`
4. Request `http://postman-echo.com/cookies`
    > response body has both `foo` and `bar`
5. Verified the same in Cookie Manager

Note: I also disable "Automatically follow redirects" setting to check `set-cookie` response header because `cookies/set` redirects to `/cookies`.

Please follow the steps given above and let us know if it works fine with `postman-echo.com`.

**Comment by akaczinski** [comment]
Hi,
I received a message from @harryi3t but I don't see it in the comments here so I am a little confused. However, I tried the latest PostmanCanary today and the problem still exists. I am assuming the bug fixes in canary07 "Fixed a bug where setting cookies on URLs with port number was not working" is meant to address this. Although, in my instance I was not using ports.

In the example you show, @codenirvana, I can confirm that Postman is saving the cookie in this instance as you expect. I don't believe this is the correct way to test this, though. Here's the problem step:

4. Request http://postman-echo.com/cookies
The response needs to NOT have a set-cookie header. The issue is when a site returns a response with no set-cookie header at all, but even if it sends one single set-cookie, it will save the priors. After receiving no set-cookie header, we would need to send another request to the same URL.

**Comment by codenirvana** [comment]
@akaczinski Can you confirm if you can reproduce the issue using the following steps:

1. Request `http://httpbin.org/cookies/set?foo=bar`
2. Request `http://httpbin.org/cookies`
3. Check Cookie Manager

httpbin's `/cookies` endpoint doesn't respond with `set-cookie` header as you expected.

**Comment by akaczinski** [comment]
> @akaczinski Can you confirm if you can reproduce the issue using the following steps:
> 
> 1. Request `http://httpbin.org/cookies/set?foo=bar`
> 2. Request `http://httpbin.org/cookies`
> 3. Check Cookie Manager
> 
> httpbin's `/cookies` endpoint doesn't respond with `set-cookie` header as you expected.

I think, what it requires, is the endpoint to still respond with a set-cookie header, but with a different cookie. Then, for whatever reason, PostmanCanary tosses the old cookies after this, except for the ones that were still in a set-cookie header in the last response.

e.g.
request 1 (login):
POST /loginPage/
body: loginCredentials

response 1:
set-cookie: loginCookie=thisGuy; pointlessCookie=overHere

request 2:
GET api/coolInfo/
cookies: loginCookie=thisGuy; pointlessCookie=overHere

response 2:
body: someCoolInfo
set-cookie: pointlessCookie=overHere; someOtherPointlessCookie=yay

and at this point, my loginCookie=thisGuy gets deleted from Postman.

Our website only returns a set-cookie for our front end, but the front end APIs we use don't, which is where the problem lies. I request my login credentials, using those cookies I authenticate ot the API, the API responds with just some tracking cookies in the set-cookie response. Then, PostmanCanary drops the old session cookies.

**Comment by codenirvana** [comment]
@akaczinski I am on Canary version `7.3.0-canary07` and the following NodeJS server behaves exactly what you mentioned above.

```js
require('net').createServer(function (socket) {
  socket.on('data', function (chunk) {
    chunk = chunk.toString();
    socket.write('HTTP/1.1 200 OK\r\n');
    if (chunk.indexOf(' /login') !== -1) {
      socket.write('set-cookie: loginCookie=thisGuy\r\n');
      socket.write("set-cookie: pointlessCookie=overHere\r\n");
    } else if (chunk.indexOf(' /info') !== -1) {
      socket.write("set-cookie: pointlessCookie=overHere\r\n");
      socket.write("set-cookie: someOtherPointlessCookie=yay\r\n");
    }
    socket.write('\r\n');
    socket.write('ok');
    socket.end();
  });
}).listen(3000);
```

* `localhost:3000/login` -> 2 cookies
* `localhost:3000/info` -> 2 cookies
* `localhost:3000/anything` -> no cookies

I am still not able to reproduce the issue, try/change the local server accordingly and let me know if it works for you.

**Comment by akaczinski** [comment]
I didn't even think of trying to make a server like that! Great idea. I was able to reproduce it, and I believe you should be able to now as well:

```js
require('net').createServer(function (socket) {
  socket.on('data', function (chunk) {
    chunk = chunk.toString();
    socket.write('HTTP/1.1 200 OK\r\n');
    if (chunk.indexOf(' /login') !== -1) {
      socket.write('set-cookie: LOGIN_COOKIE=yummy; Version=1; Path=/somePath; HttpOnly\r\n');
      socket.write("set-cookie: Locale=en; Expires=Sun, 01-Sep-2019 16:47:39 GMT; Path=/\r\n");
      socket.write("set-cookie: someOtherPointlessCookie=yay; AWSALB=Loooooong; Expires=Tue, 09 Jul 2019 20:47:39 GMT; Path=/\r\n");
      socket.write("set-cookie: pointlessCookie=overHere; X-SID=117466745; Path=/; \r\n");
    } else if (chunk.indexOf(' /info') !== -1) {
      socket.write("set-cookie: pointlessCookie=overHere; X-SID=117466745; Path=/; \r\n");
      socket.write("set-cookie: someOtherPointlessCookie=yay; AWSALB=Looooooong; Expires=Tue, 09 Jul 2019 20:47:39 GMT; Path=/\r\n");
    } 
    socket.write('\r\n');
    socket.write('ok');
    socket.end();
  });
}).listen(3000);
```
After calling /login, LOGIN_COOKIE is saved to Postman.
After the call is made to /info, LOGIN_COOKIE disappears.

**Comment by codenirvana** [comment]
@akaczinski We've pushed a fix for this on `7.3.0-canary08`. Can you update your app and confirm if this fixes your issue?

**Comment by akaczinski** [comment]
> @akaczinski We've pushed a fix for this on `7.3.0-canary08`. Can you update your app and confirm if this fixes your issue?

It works great! Thank you very much. Tested on Postman v7.3.2-canary01

**Comment by harryi3t** [comment]
The fix is now available on our stable channel (Postman v7.3.4) also.
