### ISSUE TITLE
Response "Pretty" view encodes strings containing \201 

### ISSUE THREAD

**Issue by crowcoder** [a85/POSTMan-Chrome-Extension#6947]
A JSON response with a character sequence of "\201" is encoded in "Pretty" view but the "Raw" view is not.

Example Raw response snippet:

...,SourceFolder: \"\\\\someshare\\shares\\somefolder\\anotherfolder\\anotherfolder\\etc\\etc\\2018\\2018-08\\ForTest\",...

Example Pretty response snippet:

...,SourceFolder: \"\\\\someshare\\shares\\somefolder\\anotherfolder\\anotherfolder\\etc\\etc\�8\�8-08\\ForTest\",...

**Comment by shamasis** [comment]
Are these texts you posted in issue exact representation as you see? It is best to share encoding inconsistency as screenshots to avoid any confusion ... it renders with a lot of (?) marks at my end.

@kamalaknn the escape sequence `\2018` should not be encoded IMHO.

Also @crowcoder ... again to be sure, can you post your app version. We did some decoding changes in 7.3.x versions.

**Comment by crowcoder** [comment]
@shamasis 

Version is Postman for Windows 7.3.3.

Screenshot is for "Pretty" view:
![image](https://user-images.githubusercontent.com/4210624/61490279-93a9e500-a97a-11e9-8825-8d5849ef29ae.png)

for "Raw":
![image](https://user-images.githubusercontent.com/4210624/61490416-e1265200-a97a-11e9-920c-e3390d8c5997.png)

**Comment by ankurdengla** [comment]
@crowcoder The fix for this issue is out on our Canary build (PostmanCanary 7.3.5-canary04) which can be downloaded here - https://www.getpostman.com/downloads/canary .
Do let us know if the issue persists.

**Comment by kamalaknn** [comment]
We have pushed this fix to the stable channel in Postman 7.3.6. Please update to the latest version and give it a try.

**Comment by castillojuan1000** [comment]
I'm having a similar problem to this. The issue still persist in postman version 9.2.0 and in postmanCanary as well
