### ISSUE TITLE
Issue viewing monitors in Web - "Something went wrong"

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#7239]
**Describe the bug**
Unable to check monitors from the Monitors Tab

**To Reproduce**
1. Click on the specific monitor from Monitor Tab
2. Error: "Something went wrong" + redirection to the "Choose an account to continue"
3. Successful login + redirection to Workspaces
4. Go to the Monitors tab and go back to 1.

**Expected behavior**
Be able to check monitors

**Screenshots**
<img width="833" alt="Screen Shot 2019-08-31 at 9 15 53 AM" src="https://user-images.githubusercontent.com/47771757/64058917-d55fb980-cbcf-11e9-9b07-b91fe2804a0e.png">

**App information (please complete the following information):**
 - App Type: Chrome app
 - Postman Version: v5.5.3
 - OS: Windows / Ubuntu 18.04.3

**Comment by vicker** [comment]
We got the same issue starting today

**Comment by zincsoda** [comment]
We have the issue too. Any hope of a fix soon?

**Comment by godfrzero** [comment]
@vicker @zincsoda Are you see this issue with a session that was recently created, or with one older than  2 days ago? In addition, does the issue persist if you clear all cookies on the domains getpostman.com & postman.co and log in again?

**Comment by pierscin** [comment]
> In addition, does the issue persist if you clear all cookies on the domains getpostman.com & postman.co and log in again?

@godfrzero I tried to access monitors in incognito mode - no success. I also checked this on other computer with which I didn't ever signed in to the postman account (browser was also different - safari).

**Comment by vicker** [comment]
@godfrzero 
This issue appears just recently, I believe they are within 2 days.

Tries Chrome incognito and clear all cookies. The issue still reproducible.

**Comment by AnkitMasand** [comment]
@Raj-postman @vicker @zincsoda @pierscin Thanks for reporting this issue.
We are looking into this and would like you all to help us with some additional information around this scenario. Can you share logs from the Networks tab (inside your browser's developer tool options)? I am sharing a web link that demonstrates how to go about executing this. 
Also, please note that the dump file can contain sensitive information related to your organization. So make sure that you have cleaned the file of all such information before sharing the logs with us.
Thanks!
https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-Network-Captures-for-Troubleshooting/ta-p/366

**Comment by godfrzero** [comment]
@vicker @zincsoda @pierscin Please send the files to help@getpostman.com instead of posting here. We'll update this thread once we've identified the problem and have an ETA for the fix.

**Comment by asockett** [comment]
To confirm, I am also experiencing this issue. Thanks

**Comment by pierscin** [comment]
@godfrzero I already did that a few days ago before this issue was created, but I will send it again with this issue's number...

**Comment by pierscin** [comment]
@ArjunSingh-PM you attached only `product/monitoring` label, but I also mentioned it in the mail (which resulted in this issue creation), that we were not able to submit a support ticket from browser (same issue - "endless login").

**Comment by vicker** [comment]
@AnkitMasand @godfrzero Done

**Comment by ash007-postman** [comment]
@AnkitMasand I have forwarded you the requested files from the users

**Comment by mathoosh** [comment]
@AnkitMasand 
Here you go: *.har file from devtools.
[identity.getpostman.com.zip](https://github.com/postmanlabs/postman-app-support/files/3573329/identity.getpostman.com.zip)

**Comment by godfrzero** [comment]
We've isolated the source of this issue and we're working on pushing out a fix within the next 24 hours. I'll post an update here once it's in production.

**Comment by godfrzero** [comment]
We've pushed out a fix to address the issue where attempting to view monitor(s) on the Dashboard would lead to an error page. Please let us know if any of you are still running into this problem.

**Comment by vicker** [comment]
@godfrzero Awesome. It is working great now. Thank you.

**Comment by pierscin** [comment]
@godfrzero It works like a charm now, but I still can't go to the account specific support page :/

**Comment by godfrzero** [comment]
Closing this issue now that we have confirmation.

@pierscin Could you follow up on the support request regarding the support page issue?
