### ISSUE TITLE
Disable Auto-complete/Typing suggestions in postman - getting unneeded/unrelated suggestions

### ISSUE THREAD

**Issue by jonsworkalias** [a85/POSTMan-Chrome-Extension#7481]
**Describe the bug**
(not new, been happening for a while)
Frequently when editing code in postman I will mouse in to a section of code and delete a letter, or otherwise edit the code, and postman tries to suggest variables to replace the partially edited text. If I use the arrows to navigate it will often replace things I never intended. I have to hit esc or use the mouse to click away to get rid of the suggestion dialog box.

Can this suggestion feature be disabled?  Seems like a bug that it makes suggestions unrealted to the code.

in the below I removed the ‘t’ from a ‘let’ statement and it wants me to replace it with an unrelated variable.

![image](https://user-images.githubusercontent.com/56596696/66839999-559a6e00-ef35-11e9-8ace-92b7f0f341c3.png)

Thanks.
**To Reproduce**
Steps to reproduce the behavior (see above but also):
1. In an workspace with some call w/ scripts, and env variables
2. Edit a line of code such as **let hm = 'something';**
3. Delete the t from the first word let, and see that postman wants to suggest environment variable names to insert as auto-complete/suggested text.
4. The suggestion is not needed, and is further not related to anything in the line of code.  There is no partial string match.  IE - there is no variable named "le"

**Expected behavior**
Would hope that auto-complete suggestions are related to the strings near the mouse-cursor, and if nothing is a near match, nothing is suggested.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version 7.9.010
 - OS: Ubuntu 18.04.3 LTS

**Additional context**
![image](https://user-images.githubusercontent.com/56596696/66839999-559a6e00-ef35-11e9-8ace-92b7f0f341c3.png)

**Comment by jonsworkalias** [comment]
If helpful, here is an even easier way to reproduce and shows how simply it can happen when not needed.  In blank API call, create this line in Pre-request Script.  The place cursor at the start of the line and hit enter.

![image](https://user-images.githubusercontent.com/56596696/67409403-88bdac80-f588-11e9-8bf1-0afac80831bf.png)

**Comment by ankurdengla** [comment]
@jonsworkalias You can disable autocomplete in the `Settings -> Variable Autocomplete` 

![image](https://user-images.githubusercontent.com/26045713/70787524-db5f5c00-1db4-11ea-846a-986bb9bb0316.png)

The reason for these suggestions appearing in your case are that `le` in the first case matches the substring `le` for the variable `cycle_awsinstanceTy` and similarly `let` matches substring in `hideReportingDeleted`.

Having said this, thank you for reaching out and expressing your concerns. You are right and the context should be taken into account when showing suggestions. Since `let` is a reserved word, the suggestions are unrelated in this case. While we are working on improving the quality of the suggestions we show, you can disable the autocomplete as mentioned above.

**Comment by pankajk07** [comment]
Fixed as part of v7.24

**Comment by cafedood** [comment]
I'm using `Version 7.24.0 (7.24.0)` still happening even I've turned it off.

**Comment by pankajk07** [comment]
@cafedood Can you please shed more light on the issue that you are facing now or some screenshots?

**Comment by NelemaniA** [comment]
using v11.23.3 and i am experiencing the same problem.
the setting 'Variable autocomplete' is turned off.
![image](https://github.com/user-attachments/assets/ec77dfda-462a-4596-91a8-ab81c5a1b5a6)

when editing the Pre-request tab on a Scripts tab for a folder there is a pop-up when editing which I don't need because I am editing testvalues and not variables. Since I am translating everything from Dutch to English I have to hit escape with every item I translate, because the down arrow key (to go to next line I need to edit) will select a value I dont need. Very very annoying!
![image](https://github.com/user-attachments/assets/189da171-b775-4269-b8a8-505a8e7cc26a)

**Comment by aap-jmedema** [comment]
Still a problem.  What's it going to take in order to get autocomplete fully disabled?

**Comment by DableUTeeF** [comment]
> Still a problem. What's it going to take in order to get autocomplete fully disabled?

It's the AI slop they force us to use. Thank fully we can disable that, for now. I have to upgrade it to the newest version for the option to disable it to appear though.
