### ISSUE TITLE
Cannot log in via Google Account on Postman Desktop 7.10.0

### ISSUE THREAD

**Issue by rgmembreno** [a85/POSTMan-Chrome-Extension#7569]
**Describe the bug**
I started up Postman today after not using it for a few weeks, and I was prompted to sign out and sign back in.  My account is tied to my GSuite account, and when I click the "Sign in with Google" button the screen hangs and does not take me to a screen to authorize access to my Google account.

**To Reproduce**
1. Log out of Postman, and then click the "Sign in" button
2. Click the "Sign in with Google" button
3. The screen will hang on the "loading" screen.  It will not take me to a screen to log in via my Google account

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type Postman for Windows
 - Postman Version 7.10.0
 - OS: Windows 10.0.18362

**Additional context**
I can log in with GSuite account on the web portal web.postman.co with no issues.

**Comment by JavierPDev** [comment]
The same exact thing is happening to me on Ubuntu 19.10 with the same version of Postman (7.10.0), except I last used Postman a couple days ago.

**Comment by Mentioum** [comment]
Happening for me too on latest version of PopOS.

Just installed from snap

**Comment by jamiecarl** [comment]
Exact same thing happened to me this morning.  Windows 10.  I've signed out.  I've also revoked access from the Google Account settings, in the hope that it will force a re-auth.  Nope.  Postman just sits there chewing up some CPU while doing nothing.

**Comment by vadim-kovalyov** [comment]
+1. The same problem on Windows 10. I also tried removing `C:\Users\<user>\AppData\Roaming\Postman` but still no luck.

**Comment by ablyeom** [comment]
I have same issue on MacOS 10.15.1.
I deleted Postman with all of files about application, and reinstalled but not working.
I stuck like below attachment.

![image](https://user-images.githubusercontent.com/2979043/68004225-fc139c80-fcb3-11e9-888d-bd97e9214a88.png)

**Comment by aborilov** [comment]
same here

**Comment by kepikoi** [comment]
Sign In via google not working on `Postman 7.10.0, win32-10.0.18362 on x64`.
As a workaround I was able to reset the password in the app prompt and login via a regular Postman account.

Here some hopefully relevant logs:

`render-requester.log`
```
[33832][1572595073534][requester][info]["VerifyUserSessionService~verifyUserSession: Locking current session. Forcing user to login again."]
```

`render-auth.log`
```
[33832][1572595141525][auth][info]["Authentication~will-navigate:","https://accounts.google.com"]
[33832][1572595141728][auth][info]["Authentication~did-navigate:","https://accounts.google.com"]
[33832][1572595141763][auth][info]["Authentication~will-navigate:","https://accounts.google.com"]
[33832][1572595141967][auth][info]["Authentication~did-navigate:","https://accounts.google.com"]
[33832][1572595142016][auth][info]["Authentication~will-navigate:","https://accounts.google.com"]
[33832][1572595142245][auth][info]["Authentication~did-navigate:","https://accounts.google.com"]
[33832][1572595142291][auth][info]["Authentication~will-navigate:","https://accounts.google.com"]
[33832][1572595142497][auth][info]["Authentication~did-navigate:","https://accounts.google.com"]
[33832][1572595142550][auth][info]["Authentication~will-navigate:","https://accounts.google.com"]
[33832][1572595142744][auth][info]["Authentication~did-navigate:","https://accounts.google.com"]
[33832][1572595142772][auth][info]["Authentication~will-navigate:","https://accounts.google.com"]
[33832][1572595142986][auth][info]["Authentication~did-navigate:","https://accounts.google.com"]
[33832][1572595143033][auth][info]["Authentication~will-navigate:","https://accounts.google.com"]
[33832][1572595143236][auth][info]["Authentication~did-navigate:","https://accounts.google.com"]
[33832][1572595143267][auth][info]["Authentication~will-navigate:","https://accounts.google.com"]
[33832][1572595143501][auth][info]["Authentication~did-navigate:","https://accounts.google.com"]
[33832][1572595143540][auth][info]["Authentication~will-navigate:","https://accounts.google.com"]
[33832][1572595143730][auth][info]["Authentication~did-navigate:","https://accounts.google.com"]
[33832][1572595143772][auth][info]["Authentication~will-navigate:","https://accounts.google.com"]
[33832][1572595144018][auth][info]["Authentication~did-navigate:","https://accounts.google.com"]
[33832][1572595144058][auth][info]["Authentication~will-navigate:","https://accounts.google.com"]
[33832][1572595144286][auth][info]["Authentication~did-navigate:","https://accounts.google.com"]
[33832][1572595144337][auth][info]["Authentication~will-navigate:","https://accounts.google.com"]
[33832][1572595144518][auth][info]["Authentication~did-navigate:","https://accounts.google.com"]
```

`renderer-shared.log`
```
[33832][1572595073342][shared][info]["UI pulled the session locked information on init"]
[33832][1572595131460][shared][warn]["UserService~fetchGateKeeperInfo: Error in fetching gatekeeper info",{"error":{"name":"paramMissingError","message":"Parameter is missing in the request.","details":{"param":"user_id"}}}]
[33832][1572595131461][shared][warn]["GateKeeperService~handleGateKeeperRefresh error",{"error":{"name":"paramMissingError","message":"Parameter is missing in the request.","details":{"param":"user_id"}}}]
[33832][1572595252237][shared][warn]["UserService~fetchGateKeeperInfo: Error in fetching gatekeeper info",{"error":{"name":"paramMissingError","message":"Parameter is missing in the request.","details":{"param":"user_id"}}}]
[33832][1572595252239][shared][warn]["GateKeeperService~handleGateKeeperRefresh error",{"error":{"name":"paramMissingError","message":"Parameter is missing in the request.","details":{"param":"user_id"}}}]
```

**Comment by cybd** [comment]
I have the same issue on Linux MInt 19.
Try to use "Trouble signing in?" to reset password. Then login using email/newPassword instead of Google SignIn

**Comment by jbauerrfid** [comment]
Same issue on WIndows 10.
I tried to downgrade to Postman 7.9.0, but this did not solve the issue.

**Comment by prositen** [comment]
> I have the same issue on Linux MInt 19.
> Try to use "Trouble signing in?" to reset password. Then login using email/newPassword instead of Google SignIn

Thank you! This helped me out.

**Comment by JesseLabruyere** [comment]
Same issue on Ubuntu 18.04

**Comment by optimique** [comment]
Same issue on Mac 10.15 Catalina

**Comment by mgeissen** [comment]
Same issue on Mac 10.14.4 with Postman 7.10 - @cybd solution works! Thx!

**Comment by jcbinet** [comment]
Same issue on Windows 10 / Postman 7.10. I tried reinstalling the app and resetting the config but it did not solve the issue.

**Comment by rgmembreno** [comment]
Great news!  I tried logging in today with my Google account and it seems to be working.  It seems the problem is fixed in v7.11.0

**Comment by CundyTech** [comment]
I've got a different but related issue. So I click to sign in with google, sign in using my google credentials, and then I get this screen. 

![image](https://user-images.githubusercontent.com/19817493/69802551-b1614380-11d1-11ea-8c65-703c86c4b898.png)

So I cannot sign in using Google on Version 7.12.0.

**Comment by mschubi72** [comment]
I've the same problem. 32 & 64 Bit postman :-(
Also tested on differend computers....

**Comment by yaimag** [comment]
I am experiencing the same problem ....

**Comment by JosueNicholson** [comment]
> I have the same issue on Linux MInt 19.
> Try to use "Trouble signing in?" to reset password. Then login using email/newPassword instead of Google SignIn

nice! it works in my case (ubuntu 18.04)

**Comment by krzysztof-kalinowski** [comment]
Same problem with google credentials

**Comment by stevelobach** [comment]
I had the same problem, clicked on the login with google, and it would sit an spin for a very long time. Then I got the idea to open the app without logging in, then after I was in, I logged in to my google account with no issue..  It was a bit frustrating until I finally got in correctly..

**Comment by shonidan** [comment]
Same problem

**Comment by arzakmiftakhul** [comment]
> I've got a different but related issue. So I click to sign in with google, sign in using my google credentials, and then I get this screen.
> 
> ![image](https://user-images.githubusercontent.com/19817493/69802551-b1614380-11d1-11ea-8c65-703c86c4b898.png)
> 
> So I cannot sign in using Google on Version 7.12.0.

Same issue, I got that response when I try to get new access token (Google oAuth)

**Comment by ArjunSingh-PM** [comment]
Thank you everyone for reporting this issue. We are working on a solution to bypass the same. 

Meanwhile, try to use "Trouble signing in?" option to reset your password. Then login using email/newPassword instead of Google SignIn.

**Comment by elssar** [comment]
We’ve enabled a new auth option which will allow you to sign in via your browser. Could you try this out and let us know if it works for you?

![browser-based-login-link](https://user-images.githubusercontent.com/1042301/70425365-1c92fb80-1a97-11ea-9bb4-92d356635c23.png)

**Comment by arzakmiftakhul** [comment]
> We’ve enabled a new auth option which will allow you to sign in via your browser. Could you try this out and let us know if it works for you?
> 
> ![browser-based-login-link](https://user-images.githubusercontent.com/1042301/70425365-1c92fb80-1a97-11ea-9bb4-92d356635c23.png)

Yes, I can sign in using my browser to postman. But my case is little different,
I need access token to authorize my request to [Google Play Developer API](https://developers.google.com/android-publisher/api-ref/purchases/products/get). I configured by following  [authorization instructions.](https://developers.google.com/android-publisher/authorization). Then I tried it using postman by following [DimaTx's answer](https://stackoverflow.com/a/53529534/11445944) in stackoverflow.


![postman](https://user-images.githubusercontent.com/29246238/70436372-b8366300-1abb-11ea-8fe4-eee4a89ab210.PNG)
![google](https://user-images.githubusercontent.com/29246238/70436462-eddb4c00-1abb-11ea-86ee-23830c18d0b7.PNG)
![google2](https://user-images.githubusercontent.com/29246238/70436468-f2a00000-1abb-11ea-8141-ad9fdd06b606.PNG)


No "Try on a web browser" for this case, so I cant sign in.
Thanks for attention, and sorry if this case is not related.

**Comment by CundyTech** [comment]
> We’ve enabled a new auth option which will allow you to sign in via your browser. Could you try this out and let us know if it works for you?
> 
> ![browser-based-login-link](https://user-images.githubusercontent.com/1042301/70425365-1c92fb80-1a97-11ea-9bb4-92d356635c23.png)

This works perfectly for me, I'm back in.

**Comment by vasiliyb** [comment]
I've been able to get around this bug.  Click Enterprise login, then Try on a web browser.  Logging in via your regular browser works just fine.  Nuisance, but worked

**Comment by gtxistxgao** [comment]
> I've been able to get around this bug. Click Enterprise login, then Try on a web browser. Logging in via your regular browser works just fine. Nuisance, but worked

Thanks! Works for me. I clicked "Try on a web browser", which is Chrome and which has already login with my Google account. Without any further typing, the pops out windows shows I am logged in.

**Comment by rgmembreno** [comment]
@CundyTech 
My session expired and I can't log back in via Google; the "Sign in via web browser" link only works if your default browser is already logged in to this Google account.  When I copy the URL and try to open it in my sync'ed Chrome browser I get 400/403 errors saying the link is either invalid or already expired.  Can you increase the time that the link is valid, or give us an option to open our browser of choice?

**Comment by ArjunSingh-PM** [comment]
@rgmembreno Thank you for writing to us. We are working on resolving this issue. 

Meanwhile, you can either login at the sign-in page that opens on your default browser or directly use your Postman accounts credentials at the Postman app.

**Comment by Vegeta86** [comment]
> I have the same issue on Linux MInt 19.
> Try to use "Trouble signing in?" to reset password. Then login using email/newPassword instead of Google SignIn

Thaaaaaanks!!! <3

**Comment by Hack-N-Coded** [comment]
> I have the same issue on Linux MInt 19.
> Try to use "Trouble signing in?" to reset password. Then login using email/newPassword instead of Google SignIn

THanks

**Comment by ArjunSingh-PM** [comment]
Closing the issue for now, as we have deployed stability fixes for the same. Please do let us know if the issue continues to persist.

**Comment by jecaestevez** [comment]
I still have the same issue, am I missing something?
![image](https://user-images.githubusercontent.com/1833176/76140284-fb6f8600-6058-11ea-9684-cb0f21a89346.png)

**Comment by AlyAzeemi** [comment]
> I still have the same issue, am I missing something?
> ![image](https://user-images.githubusercontent.com/1833176/76140284-fb6f8600-6058-11ea-9684-cb0f21a89346.png)

Same.

**Comment by salmanwahed** [comment]
Occurred to me for windows 10 and postman version 7.21.1. I reset my password and after trying multiple times could sign in.

**Comment by bjornvdakker** [comment]
Same issue here, I don't see any option to workaround on this on another browser or something....
Using Version 7.23.0 (7.23.0) on MacOS Mojave 10.14.6

**Comment by AjayChoudary** [comment]
![image](https://user-images.githubusercontent.com/12094764/88465698-6c1d1f00-cee2-11ea-9c6d-8d4142d635eb.png)
Unable to login with Google SSO in Postman v7.29.1 in Ubuntu 20.04 

Tried changing default browser chrome/Firefox but didn't helped

**Comment by arlemi** [comment]
@AjayChoudary Can you check if your browser is blocking a pop-up at that moment in time?

**Comment by Wirone** [comment]
I also can't sign with Google on Postman 7.30.1 using Chrome 84.0.4147.105 as default web browser. I could log in with Firefox.

**Comment by SwaroopKumarDasari** [comment]
Use this link guys, it worked for me. Just follow the steps properly. Delete whatever is there now and follow the procedure in the doc.
https://learning.postman.com/docs/getting-started/installation-and-updates/#installing-postman-on-linux
