### ISSUE TITLE
Request looped many times lags, hangs, crashes app

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7742]
**Describe the bug**
When using `postman.setNextRequest()` to loop a request many times (i.e. 300+), the app slows down, hangs, and ultimately crashes when trying to close the Collection Runner window.

**To Reproduce**
(note: see attached Collection below, which just needs to be run to reproduce issue)
1. Create a Collection containing a single request, that uses `postman.setNextRequest()` to loop at least 500 times.
2. Run Collection via the Collection Runner
3. Notice that at 200 - 300 iterations, the rate of requests being sent slows down
4. Notice that at ~350 iterations, requests are no longer being sent. `Stop run` button in Collection Runner does not respond.
5. Close Collection Runner window, see app crash.

**Expected behavior**
Requests continue to send, even at large numbers of iterations.

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.12.0
 - OS: MacOS Catalina 10.15.1 (19B88)

**Additional context**
Example collection:
[large_loop_test.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/3924453/large_loop_test.postman_collection.json.zip)

App logs attached:
[Archive.zip](https://github.com/postmanlabs/postman-app-support/files/3924253/Archive.zip)

**Comment by saswatds** [comment]
We have pushed all of our performance fixed to the stable version `7.18.0`. The runner should more snappier and not crash.  
I am closing this issue and tracking all the performance issue on https://github.com/postmanlabs/postman-app-support/issues/6525 as master issue

**Comment by k-anuradha** [comment]
This issue still exists even with latest version v8.5.1.  All execution logs until before the crash are lost too.
