### ISSUE TITLE
GET works fine but POSTs return 403 Forbidden Invalid Origin

### ISSUE THREAD

**Issue by seandcoleman** [a85/POSTMan-Chrome-Extension#7764]
**I can GET an object but the POST fails with a 403 forbidden**
Using the Mac App, version 4.3.2 I am able to GET with my API credentials but I am no longer able to POST.  Using cURL I can POST the exact same message and it works fine.  What am I missing?  My Creds are good, there is no ip checking, it is a live API on a server (not local).  I can successfully POST this change with JavaScript, cURL, etc.  It just fails on my Postman app. 

**To Reproduce**
1. Create a valid POST JSON Body
2. Enter in Basic Auth credentials 
3. Enter https route
4. Click send
5. returns 403 forbidden

**Expected behavior**
If I have the correct credentials and can GET, I should be able to POST changes. 

**Screenshots**
In/a

**App information (please complete the following information):**
 - App Type : Mac App
 - Postman Version 4.3.2
 - OS: macOS High Sierra 10.13.6

**Additional context**
I seem to be the only one using this api experiencing this and it used to work fine. Is there some sort of setting I am missing?

**Comment by preethammavin** [comment]
@seandcoleman do you have any check on the origin of the request on the server-side for the POST request?

**Comment by seandcoleman** [comment]
@preethammavin No, the api doesn't have any origin checking.  So long as you have valid API keys it should work. 

Note: the API uses Basic Auth and there is no user-level permissions issues as the api only has no permission granularity.

**Comment by seandcoleman** [comment]
I talked with a co-worker who had a similar issue and they found that a postman app cookie was being added when they removed it the issue went away.  I too was getting that cookie added but the issue remains when I remove the cookie.

**Comment by saswatds** [comment]
@seandcoleman The app version `4.3.2` seems to be a really old version of the app. At this moment the latest version of app is `7.18.0`. There have been a lot of bug fixes during these release and most probably this issue should be fixed in the latest version. Could you upgrade to the latest version and check if the issue still persists?

**Comment by seandcoleman** [comment]
@saswatds Thank you, I noticed that as well but when I click check for updates it tells me:
<img width="481" alt="Screen Shot 2020-02-14 at 9 48 30 AM" src="https://user-images.githubusercontent.com/5331287/74554827-46d9bd00-4f0f-11ea-8415-22df585977b6.png">

I'll see about just removing the app and re-installing it.  Thank you

**Comment by codenirvana** [comment]
@seandcoleman is this issue persists after upgrading to the latest version?

**Comment by codenirvana** [comment]
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Comment by Pavandollar** [comment]
And even though I am facing the issue here as when I post request an login it works fine with postman ..
As I request post post with another with authenticate token it shows invalid or expired token 
I took 3 days but didn't solve it
