### ISSUE TITLE
Import > Paste Raw Text cURL --data-raw not import to bodyraw

### ISSUE THREAD

**Issue by wrssmi** [a85/POSTMan-Chrome-Extension#7895]
Body - raw not filled with data after import

**To Reproduce**
1. Go to 'Import > Paste Raw Text cURL'
2. Use following curl
`curl --location --request POST "https://sample.com" --header "Content-Type: application/json" --data-raw "{ \"details\": { \"id\": \"11\", \"sample\": { \"name\": \"ankit\" } } }"`
3. Body is not filled (see Screenshot)

**Expected behavior**
Should be the same as with that curl (see Screenshot)
`curl --location --request POST "https://sample.com" --header "Content-Type: application/json" --data "{ \"details\": { \"id\": \"11\", \"sample\": { \"name\": \"ankit\" } } }"`

**Screenshots**
Successfull with -data
![image](https://user-images.githubusercontent.com/1664017/72058407-5478a300-32d0-11ea-802d-414b6bc1c327.png)

Not Successfull with -data-raw
![image](https://user-images.githubusercontent.com/1664017/72058516-838f1480-32d0-11ea-89b6-b90d331a4eec.png)

**App information (please complete the following information):**
 - Postman Version 7.14.0
 - OS: Windows 10

**Context**
Generate Code Snippet creats --data-raw

![image](https://user-images.githubusercontent.com/1664017/72058756-ef717d00-32d0-11ea-8041-931280e007be.png)

**Comment by ivliskot** [comment]
Yeah, we have noticed that as well :(

**Comment by atallon** [comment]
Seeing the same on Version 7.15.0 w/ OS X 18.7.0 / x64

**Comment by swuppio** [comment]
any suggestions?

**Comment by pavelsaman** [comment]
I see the same issue in version 7.16.0, app for Windows OS x64

**Comment by garrucho** [comment]
It's really sad that the code generator, since their big update, changed to use `--data-raw`, and so we couldn't import these cURL anymore in a while.

**Comment by tiaraju** [comment]
Same problem happening to me. 
Any news about it?

Same problem reported in #7983

**Comment by kevinding0218** [comment]
Same issue happening to me on OS 10.15.3

**Comment by shreys7** [comment]
Duplicate of #8126

**Comment by shreys7** [comment]
Duplicate of #7983

**Comment by shreys7** [comment]
@wrssmi Thanks for reporting this issue. We are soon going to release a fix for this. Will keep you updated here.

**Comment by anirudhavpavashe** [comment]
Remove -raw which is after --data [--data ~~-raw~~ ]
just keep it as --data in the cURL

**Comment by anirudhavpavashe** [comment]
> any suggestions?

Remove -raw which is after --data [--data ~~-raw~~ ]
just keep it as --data in the cURL

**Comment by siddharth5797** [comment]
@shreys7 On which version is this issue fixed? I am still facing this issue in version v7.21.0.

**Postman for Linux
Version 7.21.0
linux 4.15.0-88-generic / x64**

**Comment by shreys7** [comment]
Hello everyone, we have added the fix for this issue and it will be released with the next Postman App version - **7.22**, planned on 8th April.
Thank you for your patience.

**Comment by RajatBanerjee** [comment]
Is this fixed ? i did a code generate and it still does --data-raw

**Comment by mccannt** [comment]
@RajatBanerjee Did you get the 7.22 version of the app yet? It is currently being rolled out to users. 

If you haven't, please wait until you get the update and then try again. If you have received it and it's still not working, please let us know.

**Comment by shreys7** [comment]
Hey @RajatBanerjee , the issue wasn't the code generator generating a `--data-raw` in the snippet. It was about not able to import the cURL request body when using `--data-raw` argument. This has been fixed with the latest release. Do let us know if you have any other queries :)

**Comment by RajatBanerjee** [comment]
Got it @shreys7 . So the issue i am talking about is that considered a bug?

**Comment by shreys7** [comment]
@RajatBanerjee The unsuccessful import of body in cURL request with --data-raw flag was the only bug, which has been fixed with the latest release of App, 7.22

**Comment by vbothra** [comment]
I tried with v7.22. And the issue is not fixed yet. I am unable to import. Please see the attached video below:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/61234122/79987848-88688480-84cb-11ea-9054-adbd1fcb5c34.png">

[Screen Recording 2020-04-22 at 6.58.23 PM.mov.zip](https://github.com/postmanlabs/postman-app-support/files/4516355/Screen.Recording.2020-04-22.at.6.58.23.PM.mov.zip)

**Comment by JaswantBB** [comment]
instead of --data-row use --data-binary will work

**Comment by kasumiru** [comment]
the bug is stiil here in chrome Version 88.0.4324.190 (Official Build) (64-bit)

**Comment by umeshp7** [comment]
Hey @kasumiru!
Are you using the Chrome App? We have actually deprecated the Chrome app version of Postman.
Although we have recently launched Postman on the Web - Here you can experience the latest Postman app with all the recent features directly on any web browser.

You can download the latest version of the native Postman apps or try out the Web version here: https://www.postman.com/downloads

Do try this out in one of the latest apps and let us know if you are still facing this.

**Comment by rxluz** [comment]
Hey folks, I updated my Postman to the last version and it seems that this problem remains, I tried to change the params like suggested in the post but also didn't work

I'm using Version 8.0.7 (8.0.7) (Mac)

**Comment by temamagic** [comment]
Same problem on newest version

![image](https://user-images.githubusercontent.com/15264697/116050683-6fffec80-a680-11eb-8457-7f3ce88aa9d0.png)

**Comment by gregtuc** [comment]
Issue is still occurring for me, Postman for Windows version 8.3.0.

**Comment by arlemi** [comment]
@temamagic @gregtuc  Can you provide more information on what you're seeing? I've just given it a try on the latest version on Windows and the import works fine. 

![import-curl](https://user-images.githubusercontent.com/5029719/117120381-2a7fa580-ad8b-11eb-8179-8ede781c0fda.gif)

**Comment by temamagic** [comment]
@arlemi Hi, sure!

In my case, I'll take request from Chrome and expect to see Form Data values

![image](https://user-images.githubusercontent.com/15264697/117245017-c0c2d280-ae42-11eb-9e4f-5833db7f0e57.png)

Chrome copy as curl return like this:

```
curl 'http://example' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7oJTsSWYoA2LdaPx' \
  --data-raw $'------WebKitFormBoundary7oJTsSWYoA2LdaPx\r\nContent-Disposition: form-data; name="source"\r\n\r\ns\r\n------WebKitFormBoundary7oJTsSWYoA2LdaPx\r\nContent-Disposition: form-data; name="destination"\r\n\r\nt\r\n------WebKitFormBoundary7oJTsSWYoA2LdaPx--\r\n' \
  --compressed \
  --insecure
```

I think that problem is in content-Type: multipart/form-data, cuz my request is a simple post with form data values and expect to see form data parsed, not raw json body

**Comment by temamagic** [comment]
Just checked, curl request copied from Charles proxy doesn't parsed properly too

Maybe I was wrong with issue? Anyway, Postman should learn how to parse multipart form data values from curl :)

**Comment by tsundara** [comment]
For the generated curl command, how to get rid of the string `--data-raw` and just set it to `--data`? 
Is there some built in setting to deal with this? 

It is annoying as everytime I have to copy paste command to another editor and change text from `data-raw` to `data`

**Comment by Spaum145** [comment]
Still have problems, version 9.0.2.
Trying to import curl for post request with multipart/form-data request

```
curl -X POST '...' 
-H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryDvazaXbGrGcqqTAA' \
...
--data-raw $'------WebKitFormBoundaryDvazaXbGrGcqqTAA\r\nContent-Disposition: form-data; name="contacts[][email]"\r\n\r\n\r\n------WebKitFormBoundaryDvazaXbGrGcqqTAA\r\nContent-Disposition: form-data;
name="contacts[][phone]"\r\n\r\n\r\n------WebKitFormBoundaryDvazaXbGrGcqqTAA\r\nContent-Disposition: form-data; 
...
name="country"\r\n\r\n0\r\n------WebKitFormBoundaryDvazaXbGrGcqqTAA--\r\n'
```
and got no body parsed

**Comment by VShingala** [comment]
@tsundara Issue related to code snippet generation having `--data-raw` has been [fixed](https://github.com/postmanlabs/postman-code-generators/pull/663) now with latest postman app. Behavior now is `--data` should be present instead of `--data-raw` for almost all cases.

@Spaum145 We've identified the issue with formdata request you shared and will be working on a fix. I'll update here once fix is out.

**Comment by VShingala** [comment]
@Spaum145 @temamagic 

We've fixed the issues with cURL not able to import Multipart / formdata bodies correctly with the latest Postman App v10.13. Do let us know if you're facing further issues with it.
