### ISSUE TITLE
Postman fails to encode ampersands within query parameters

### ISSUE THREAD

**Issue by adamkelm** [a85/POSTMan-Chrome-Extension#8106]
**Describe the bug**
When an ampersand is input into the query parameters, it fails to encode correctly, leading to erroneous results. Instead, the ampersand is retained and creates an additional unwanted query parameter.

**To Reproduce**
1. In Postman GUI, create a new GET request for https://postman-echo.com/get
2. Set query parameter key "foo1" to value "bar1 & bar2"
3. Send request
4. The ampersand fails to encode correctly, leading to the this erroneous response:
{
    "args": {
        "foo1": "bar1 ",
        " bar2": ""
    },
    "headers": {
        "x-forwarded-proto": "https",
        "host": "postman-echo.com",
        "accept": "*/*",
        "accept-encoding": "gzip, deflate, br",
        "cache-control": "no-cache",
        "cookie": "sails.sid=s%3AXPNQ8tMSTqGnTnvBpR-CjnBllxkMssl4.IOdRvN9skWJIJyKKWK8UmBT2mkeiQHzoit5RNiuzlMM",
        "postman-token": "b5b95f8c-bde4-4ba3-85ce-c884a35435b2",
        "user-agent": "PostmanRuntime/7.22.0",
        "x-forwarded-port": "443"
    },
    "url": "https://postman-echo.com/get?foo1=bar1%20&%20bar2"
}

In the request builder, the following is correctly displayed:
`https://postman-echo.com/get?foo1=bar1 %26 bar2`

In code generator, the following is incorrectly displayed:
`curl --location --request GET 'https://postman-echo.com/get?foo1=bar1%20&%20bar2'`

In Postman console, the following request is shown:
`GET https://postman-echo.com/get?foo1=bar1%20&%20bar2`

**Expected behavior**
Ampersands entered into query parameters should be encoded correctly and consistently throughout the application.

**Screenshots**
<img width="914" alt="Screen Shot 2020-02-25 at 7 41 46 PM" src="https://user-images.githubusercontent.com/42389795/75301472-e6008d80-5808-11ea-8abb-742793ad5d95.png">

<img width="788" alt="Screen Shot 2020-02-25 at 7 42 05 PM" src="https://user-images.githubusercontent.com/42389795/75301490-ef89f580-5808-11ea-9c94-54a31db6b72d.png">

**App information:**
 - Native app
 - 7.18.1
 - OS: macOS 10.15.3

**Comment by vikiCoder** [comment]
@adamkelm, this is fixed in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). You can see more details about the fix at #8154

**Comment by adamkelm** [comment]
@vikiCoder using Canary, I see that the encoding/decoding is fixed. Thanks! One thing I still notice is spaces in the url in the request builder. That is to say, the space isn't showing as an encoded character in the url when presented here. Is this an intentional decision to make more readable or is this considered unexpected behavior:
<img width="672" alt="Screen Shot 2020-03-09 at 10 54 58 AM" src="https://user-images.githubusercontent.com/42389795/76226716-a10b2c80-61f4-11ea-819b-e853640a72e7.png">

**Comment by codenirvana** [comment]
@adamkelm That's the expected behavior as the actual URL encoding happens before sending the request. User entered data is not encoded automatically.

This, in particular, is a special case where `#` and `&` are the two characters that come in the way of parsing the query parameters if not encoded.

Check #8154 for more details on which characters get encoded before sending the request.
Also, consider enabling the "Use next generation URL processing" setting as mentioned in #8154 which fixes all these encoded related issues.

Closing as this is fixed in the latest version of the Postman app (v7.20.0).
Feel free to leave your feedback at #8154 or reopen this thread if the issue persists.

**Comment by keyboarder** [comment]
This problem still occurs in version 7.34.0 for Mac.  Aside from different parameter names and values, I'm getting identical buggy results, the resulting URL having e.g. `%20&%20`.
