### ISSUE TITLE
Code can be overlapped by a hint on hover

### ISSUE THREAD

**Issue by andrewVolodko** [a85/POSTMan-Chrome-Extension#8829]
**Steps to reproduce the behavior:**
1. Go to **Tests** section.
2. Enter e.g. `pm.response.json()` **on the 2nd line**.
3. Hover over any of the words entered (e.g. **response**).
4. Note the hint appeared.

**Actual behavior**:
The **response** is overlapped by the hint.

**Expected behavior**:
The hint should NOT overlap the code. 

**Screenshots**:
![image](https://user-images.githubusercontent.com/54236817/88416128-4e6b8f00-cde8-11ea-9c98-09c3125dccd2.png)

**App information**:
- App Type - Native App
- Postman Version - Version 7.29.1
- OS - OS X 19.6.0 / x64, Mac OS Catalina (10.15.6)

**Comment by pankajk07** [comment]
Hey @andrewVolodko, this issue is fixed as part of `v7.35`. Please update your app and do give it a try.

**Comment by andrewVolodko** [comment]
@pankajk07 sorry, but I still don't have an update to v7.35.

**Comment by pankajk07** [comment]
@andrewVolodko Apologies for the delay. We have rolled out the `v7.35` release. Please update the app and give it a try.

**Comment by andrewVolodko** [comment]
Not reproduced.
