### ISSUE TITLE
Empty scope when using OAuth 2.0

### ISSUE THREAD

**Issue by jvitrifork** [a85/POSTMan-Chrome-Extension#8837]
Using Postman v7.29.1:

When using the Authorization tab using OAuth 2 and requesting a new access token, the 'scope' is sent with an empty string instead of being omitted when not used.
![image](https://user-images.githubusercontent.com/46567685/88544056-21ea8980-d019-11ea-94f1-0415d6473a9a.png)

**Comment by dpoetzsch** [comment]
Still happens with 7.36.1.

Very annoying for us because we cannot use this feature as an empty string results in "Invalid scope" error for newer versions of keycloak.

**Comment by bodograumann** [comment]
In the current version 8.0.6 of postman you can define a scope to use. So I think this issue is fixed.

**Comment by lordldx** [comment]
@bodograumann I have to disagree.
OAuth2 states that a scope is optional, which means it's ok to not specify any scope. It is not ok to specify an empty scope.

So if you don't define a scope in the authorization tab, then the authorization request being sent should completely omit the scope field, instead including it with an empty value.

**Comment by dpoetzsch** [comment]
I can confirm what @lordldx said, it is still the same problem in version 8.0.7.

**Comment by meden** [comment]
Still valid with Postman 8.2.2

**Comment by AlexVigogne** [comment]
Hello,

Sadly still valid in 8.3.0 version.
I have to hack it with pre-req part for Keycloak..

So i have the only choice between :
- Use it on folder, and every request, even not necessary ones call Keycloak
- Use copy/paste on every request, and it pollutes every request pre-req parts.

**Comment by AdVetter** [comment]
Just updated to v9.0.7 and it seems to work now with an empty scope field.
