### ISSUE TITLE
Error Message - Could not open Postman

### ISSUE THREAD

**Issue by AliciaLITP** [a85/POSTMan-Chrome-Extension#8962]
**Describe the bug**
Adapter Error: Marformed error from adapter. Should always be an Error instance, but instead, got.

[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing.

**To Reproduce**
Nil, can't open the app

**Expected behavior**
As per error message which pops up when i attempt to run the app.

**Screenshots**
![Postman - error message](https://user-images.githubusercontent.com/70120841/90997025-ea103b00-e5f2-11ea-88b4-c926c0cc6056.JPG)

**App information (please complete the following information):**
 - App Type [Downloaded from Chrome https://www.postman.com/downloads/ on 20 Aug]
 - Postman Version [Postman-win64-7.30.1]
 - OS: [Windows 10 Pro; vers 2004; Build: 19041.450; Windows Feature Exp Pack 120.2212.31.0; 64x; Windows updated on 19 Aug 2020 - latest updates]

**Additional context**
- I downloaded both 32-bit and 64-bit to check if one of the versions work, but still can’t work. 
- Uninstall & re-install – done, same error message.
- Restart the computer and app – done, same error message.
- I have another older version of Postman exe. file. Works the first time, but not the second time, as I received the same error message.

**Comment by xk0der** [comment]
Hey @AliciaLITP  did you attempt the steps at the article shown in the error message? https://go.pstmn.io/troubleshoot-could-not-open

Since you are on Windows, follow the steps listed for Windows platform.
And **make sure to rename/clear both the Postman folders** before you re-install the app
* `C:\Users\<user>\AppData\Local\Postman` and
* `C:\Users\<user>\AppData\Roaming\Postman`

**Comment by AliciaLITP** [comment]
Dear Amit,

Thanks for your advice.

I still face the same issue, same error message.
[cid:image001.png@01D67A09.7997BC90]

**Comment by xk0der** [comment]
@AliciaLITP - That doesn't good!
Do submit a ticket with us from this page: https://www.postman.com/support so that we may assist you!
Provide the Postman app logs from this location "`C:\Users\<username>\AppData\Postman\logs`" when you create a ticket.
Read here if you need help collecting logs: https://support.postman.com/hc/en-us/articles/360033270134

And in the meanwhile, try out the Canary build to see if that works fine: https://postman.com/downloads/canary

**Comment by AliciaLITP** [comment]
Hi, my laptop is issued by my organisation. Is that the reason why I cannot see AppData\Postman\logs under my user account ID?

On a separate note, can i use the web edition to run my API? Will i miss out any features if i use a web-based version?

**Comment by xk0der** [comment]
Hi @AliciaLITP you would need to enable viewing of hidden files first.

Refer to these articles to make the hidden/system folder visible:
* https://support.microsoft.com/en-us/help/14201/windows-show-hidden-files
* https://support.microsoft.com/en-us/help/4028316/windows-view-hidden-files-and-folders-in-windows-10

If you were unable to rename/delete the Postman folders earlier, do give it a try after you enable hidden/system folders visibility.

Our Web edition may be used, but you would need to install the Postman Agent to run requests to execute cross-origin requests :)
Do note that It's still in beta, but I would encourage you to give it a spin 👍 

Read up here for more details: 
* https://community.postman.com/t/announcing-postman-for-the-web-now-in-open-beta/14192
* https://blog.postman.com/announcing-postman-for-the-web-now-in-open-beta/

**Comment by AliciaLITP** [comment]
Dear Amit,

I was wondering if I do see postman logs in my roaming folder, will it help in the checking?

C:\Users\AppData\Roaming\Postman
[cid:image001.png@01D67BBA.6D6530D0]

Thank you.

Regards,

Alicia Lee
Executive  l  Online Learning (OLE)

**Comment by xk0der** [comment]
@AliciaLITP 
Yes, the logs under `C:\Users\<username>\AppData\Roaming\Postman` is what we are looking at
The folder may also be opened from the Postman app by navigating to: `View > Developer > View Logs in ...`

Now that these folders are accessible for you, do try renaming both the Postman folders and then re-install the Postman app, that should fix it!
- `C:\Users\<user>\AppData\Local\Postman` and
- `C:\Users\<user>\AppData\Roaming\Postman`

Do reach out to us if you continue to face issues, if you haven't already: https://www.postman.com/support

**Comment by AliciaLITP** [comment]
Dear Amit,

I think I managed to figure out the problems. There were 2 issues. It should be fixed already as I was able to test run 1 time without any problem.

Thanks for your help. ☺

Thank you.

Regards,

Alicia Lee

**Comment by xk0der** [comment]
That's great news! 🎉  Thanks for letting us know 🙌 

Enjoy using Postman and feel free to reach out to us via https://www.postman.com/support if you face any issues!

**Comment by KrausLove** [comment]
I have the same problem,but following your advice, but i still face the same issue

**Comment by irfanahmadhidayat** [comment]
> Hey @AliciaLITP did you attempt the steps at the article shown in the error message? https://go.pstmn.io/troubleshoot-could-not-open
> 
> Since you are on Windows, follow the steps listed for Windows platform. And **make sure to rename/clear both the Postman folders** before you re-install the app
> 
> * `C:\Users\<user>\AppData\Local\Postman` and
> * `C:\Users\<user>\AppData\Roaming\Postman`

thanks, its work
