### ISSUE TITLE
Generated code snippet does not url-encode correctly

### ISSUE THREAD

**Issue by odmjuk** [a85/POSTMan-Chrome-Extension#9321]
Generated code snippets for x-www-form-urlencoded does not url-encode the body parameters correctly in the generated code snippets.

The forward slash "/" character does not get url-encoded. Maybe other characters also?

In the body section of a new POST request select "x-www-form-urlencoded". Add a new key with a value containing "/". Click "Code --> Python"

**Environment Information**

 - Platform Type: Desktop App
 - Postman Version: 7.34.0
 - Operating System: macOS Catalina

**Comment by webholik** [comment]
@odmjuk  The forward slash `/` character seems to be encoded in Postman 7.36.0.
<img width="655" alt="Screenshot 2020-12-21 at 4 34 12 PM" src="https://user-images.githubusercontent.com/360759/102770560-5e44ca80-43aa-11eb-95da-e1faa9105a81.png">
<img width="655" alt="Screenshot 2020-12-21 at 4 34 37 PM" src="https://user-images.githubusercontent.com/360759/102770602-6c92e680-43aa-11eb-8b57-02b60cc58022.png">

Can you try again if the issue is still there? If it is, can you please share a screenshot or copy/paste the problematic snippet.

**Comment by umeshp7** [comment]
@odmjuk This was fixed here> https://github.com/postmanlabs/postman-code-generators/pull/394

Do try out the latest version of Postman and let us know if you are facing any issues.

**Comment by robross0606** [comment]
This is still not working on even the latest current version.  Both spaces and slashes in parameters are not encoded in code snippets. 
![image](https://user-images.githubusercontent.com/2965467/205924863-a78b2569-b34a-432d-98e9-d71de988e874.png)
