### ISSUE TITLE
Schema Validation not working when Path Templating and Fixed Paths overlap

### ISSUE THREAD

**Issue by darrencapner** [a85/POSTMan-Chrome-Extension#9396]
**Describe the Issue**

I am trying to define an Openapi spec where I have the following paths:

/{id}
/lookups
When I perform a validation on the collection within the API Designer the API Designer Collection validator does not understand a fixed path where there exists a path with a wildcard. The merge window evaluates both paths as one and the suggested merge is nonsensical.

**Steps to Reproduce**

Definition used below that is causing issues:

```
/lookups:
    get:
      summary: Lookup Job Values
      description: Lookup values for job fields
      operationId: lookupJobValues
      security:
        - authorizer: []
      parameters:
        - in: path
          name: include
          schema:
            type: string
          required: true
          description: Unique value to return list of possible job field values.
          example: "cancellationReasons"
/{jobid}:
    get:
      summary: Get Job by ID
      description: |
        Retrieve a job by the identifier provided.
        Query Parameters supported are:
        * 'include' will return related entities to a Job. Can ask for 'quote' at this time.
      operationId: getJobById
      security:
        - authorizer: []
      parameters:
        - in: path
          name: jobid
          schema:
            type: string
          required: true
          description: Unique identifier for a job to retrieve.
          example: "{{jobid}}"
        - in: query
          name: include
          schema:
            type: string
            example: quote
          required: false
          description: Include related entities to a Job to be returned in request. Can ask for 'quote' at this time.
```

**Screenshots or Videos**
![Postman_conflict_merge_screen](https://user-images.githubusercontent.com/30915037/103546566-d01c1a00-4e68-11eb-967b-bd99fe328ffc.png)

**Environment Information**

 - Platform Type: [e.g. Postman On The Web]
 - Postman Version: December 28th, 2020
 - Operating System: Windows / Chrome Browser

**Additional Context**

[Postman Community Post](https://community.postman.com/t/schema-validation-not-working-when-path-templating-and-fixed-paths-overlap/18725)

**Comment by abhinaba-ghosh** [comment]
Hi @darrencapner, this is fixed in current postman version. Feel free to re-open the ticket if you face any diffuculties.

**Comment by darrencapner** [comment]
I still see the error. I have created an API Spec to verify this scenario using the pre-generated one in the API Designer.

I am using the Web Version of Postman.

```
openapi: 3.0.0
info:
  version: 0.0.1
  title: test
servers:
  - url: 'http://localhost:3000'
paths:
  /{userid}:
    get:
      summary: 'Sample endpoint: Returns details about a particular user'
      operationId: getUserid
      parameters:
        - name: id
          in: query
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user:
    get:
      summary: 'Sample endpoint: get details about a particular user'
      operationId: listUser
      tags:
        - user
      parameters:
        - name: id
          in: query
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

1. I generate a collection using spec. 
2. Then go to the 'test' tab of the API Designer, and click the 'Validate Again' button of the collection listed (attached). 
3. I click the 'Review Issues' button

I see the following comparison that doesn't look to work as it says can't find path variables in schema.

![image](https://user-images.githubusercontent.com/30915037/111830804-78644b00-88bc-11eb-9a8c-aaea6dada55e.png)

**Comment by VShingala** [comment]
@darrencapner Given specification doesn't adhere to OpenAPI specification as it's required to define al path parameters defined in path under `parameters` of that operation. Here for operation `GET /{userid}`, no definition of `userid` is present under parameters so the validator is suggesting mismatch for it.

**Comment by darrencapner** [comment]
Yes sorry, my mistake
