### ISSUE TITLE
Recursive Variables (variables defined in another variable in Global and Environment) do not resolve properly

### ISSUE THREAD

**Issue by kfehribach** [a85/POSTMan-Chrome-Extension#964]
I am having problems with variable replacements when I want to define a default at the Global level and then optionally overwrite those at the environment level and using those values inside of a global value.

In my situation I am trying to create some api URLs that differ between environments that build up the components of the request.

I want a global that is the overall address that I can use in defining a URL such as this:

{{myUrl}}/api/action?param=1

{{myUrl}} is a combination of the server and the route, each environment defines the server and the route is to be defaulted at Global and optionally overridden at the environment.

For example:
Globals -
	{{myUrl}} = {{serverUrl}}{{route}}
	{{route}} = /route
Environment A -
	{{serverUrl}} = http://serverA
	{{route}} = :7566
	
	When processed this should replace myUrl with http://serverA:7566

Environment B -
	{{serverUrl}} = http://serverB
	
	When processed this should replace myUrl with http://serverB/route
	
When trying this in PostMan I get the result that it does not do the replacement (I think that is if the replacement tokens are not ordered correctly) or that it will only use the Globals and the Environment values do not override the Globals.

Thanks,
Kent

**Comment by abhijitkane** [comment]
Thanks for reporting this. We'll fix it in a coming release.

**Comment by abhijitkane** [comment]
This has been fixed in the latest version. @kfehribach Can you confirm?

**Comment by kfehribach** [comment]
Hello, thanks for the quick response to this bug!  Unfortunately, it still
does not seem to work properly.  I'll attempt to articulate the issues that
I am still seeing. If needed I could do a WebEx/JoinMe session to walk
through these.

Let's assume that I have the following set up:

Requests
{{shouldShowServerAndRoute}}
{{shouldNotShowDisabledUrl}}

Globals
shouldShowEnvironmentUrlNotGlobal = {{serverUrl}}{{route}}
route = /GlobalRoute

Environment 1
serverUrl = http:// <http://myQAserver>qa.postmanbug.com

Expected result: http://qa.postmanbug.com/GlobalRoute
Actual result: http://qa.postmanbug.com/GlobalRoute

Environment 2
serverUrl = http://p <http://localhost/>ostmanbug.com
route = :1234

Expected result: http://p <http://localhost/>ostmanbug.com:1234
Actual result: http://p <http://localhost/>ostmanbug.com/globalroute

Additionally, if the global variable is disabled it still gets used when it
is resolving the variables. The example is that if I disable route in the
globals above and I preview the request for Environment 2 I still see the
/globalroute which is unexpected.

Thanks,
Kent Fehribach

**Comment by abhijitkane** [comment]
Got it. To summarize - you're facing two issues - 
1. Globals are not being overriden by environment variables of the same name
2. Disabling global/environment variables is not working
We'll fix both in a coming release. Earlier, I only focussed on the recursive resolution of variables.

**Comment by kfehribach** [comment]
Exactly.  Thanks.

**Comment by kfehribach** [comment]
Is there a bug to track progress on this? I'd like to be able to test is
once the changes come through.

Thanks,
Kent

**Comment by abhijitkane** [comment]
The latest version of Postman - v2.0.19 has both these bugs fixed - https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

**Comment by kfehribach** [comment]
Awesome. Confirmed to be working. Makes my configurations MUCH DRY'er.  Thanks!!!
