### ISSUE TITLE
Native Wayland Support

### ISSUE THREAD

**Issue by matthew-jones-uk** [a85/POSTMan-Chrome-Extension#9746]
**Is your feature request related to a problem? Please describe.**
There's no native Wayland support with Postman, XWayland has to be used.

**Describe the solution you'd like**
Support for Wayland as XWayland isn't great, especially with mixed DPI environments.

**Describe alternatives you've considered**
N/A.

**Additional context**
Electron 12 introduced (nearly) full Wayland support, would it be possible to enable this? Possibly a duplicate of #6252 but that issue was closed and seemed to intend to enable compatibility with Wayland, not support.

**Comment by mamantoha** [comment]
It's starts under native Wayland with `/opt/Postman/Postman --enable-features=UseOzonePlatform --ozone-platform=wayland`
But fails "Segmentation fault" when the cursor moves to the window.

**Comment by matthew-jones-uk** [comment]
I can confirm that I experience similar behaviour.

**Comment by mamantoha** [comment]
@matthew-jones-uk  as far as I understand, the latest stable build is still on 11.1.1, thus it doesn't have the Ozone code path properly enabled.

![image](https://user-images.githubusercontent.com/61285/143489702-7c7bec18-3f8c-4044-95dd-73e7a32d2b13.png)

We need to wait while developers update it to  Electron 12.

**Comment by sepehr** [comment]
Eagerly looking forward to this. Many other Electron-based apps, including [Insomnia](https://github.com/Kong/insomnia/issues/4131) which I just have switched to, have considered this for their Linux users. Hope postman will join.

**Comment by nik-kashi** [comment]
Any update after two years, please?
High-resolution monitors are trending now and supporting the mixed DPI is crucial for dev tools.
Postman is the only tool(from my stack) that does not support this feature.
Is there any plan for supporting Wayland or is this neglected?

**Comment by eEQK** [comment]
this should be working, in your application shortcut (in my case `/usr/share/applications/postman.desktop`) edit this:
```
Exec=/opt/postman/Postman %U
```
to this:
```
Exec=/opt/postman/Postman --enable-features=UseOzonePlatform --ozone-platform=wayland %U
```

**Comment by simepy** [comment]
@eEQK I tried, and at least it not segfault anymore.
I tried your solution and `--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations` but is not working I still have a blurry text on my HDPI screen.
I'm on arch / Gnome with Postman 10.22

**Comment by andreaippo** [comment]
> this should be working, in your application shortcut (in my case `/usr/share/applications/postman.desktop`) edit this:
> 
> ```
> Exec=/opt/postman/Postman %U
> ```
> 
> to this:
> 
> ```
> Exec=/opt/postman/Postman --enable-features=UseOzonePlatform --ozone-platform=wayland %U
> ```

I'm happy to report that this one worked for me.
I'm running opensuse Tumbleweed snapshot 20240311 with KDE Plasma 6.0.1 and postman downloaded from the official website:

Postman for Linux
Version
10.23.8
UI version
10.23.8-ui-240226-0504

Desktop platform version
10.23.5

Architecture
x64

OS platform
linux 6.7.7-1-default


Here's my full .desktop file, placed under:

~/.local/share/applications/

The postman archive was un-tar'd under my home/bin folder

```
[Desktop Entry]
Encoding=UTF-8
Name=Postman
Exec=/home/andrea/bin/Postman/app/Postman --enable-features=UseOzonePlatform --ozone-platform=wayland %U
Icon=/home/andrea/bin/Postman/app/resources/app/assets/icon.png
Terminal=false
Type=Application
Categories=Development;
```

Hope this is useful to someone.

That's it, now go out there and enjoy those super-crispy fonts! :)

**Comment by 1Jo1** [comment]
I have tried both `postman --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations` or 
`postman -enable-features=UseOzonePlatform --ozone-platform=wayland` etc. 
none of them working...

(Fedora 38 arm64)
```
The disableGPU setting is set to undefined
Not disabling GPU
[52746:0410/143433.668274:ERROR:wayland_connection.cc(214)] Failed to connect to Wayland display
[52746:0410/143433.668289:ERROR:ozone_platform_wayland.cc(227)] Failed to initialize Wayland platform
[52746:0410/143433.668292:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.zsh: IOT instruction (core dumped)  postman -enable-features=UseOzonePlatform --ozone-platform=wayland
```

**Comment by andreaippo** [comment]
> I have tried both `postman --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations` or `postman -enable-features=UseOzonePlatform --ozone-platform=wayland` etc. none of them working...
> 
> (Fedora 38 arm64)
> 
> ```
> The disableGPU setting is set to undefined
> Not disabling GPU
> [52746:0410/143433.668274:ERROR:wayland_connection.cc(214)] Failed to connect to Wayland display
> [52746:0410/143433.668289:ERROR:ozone_platform_wayland.cc(227)] Failed to initialize Wayland platform
> [52746:0410/143433.668292:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
> The futex facility returned an unexpected error code.zsh: IOT instruction (core dumped)  postman -enable-features=UseOzonePlatform --ozone-platform=wayland
> ```

Are you running it as a flatpak? If so, maybe try overriding the following flags via flatseal:

![image](https://github.com/postmanlabs/postman-app-support/assets/801070/ab5518ac-00d0-4ca3-88ec-2651531448ee)

Otherwise try with the RPM package

**Comment by romanstingler** [comment]
`postman --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations` This works for me on arch out of the box. 
But is there a way to use a `~/.config/?-flags.conf` file? 
`electron-flags.conf` doesn't work
`export ELECTRON_OZONE_PLATFORM_HINT=wayland` 
doesn't work

**Comment by andreaippo** [comment]
Hello,
I'd like to report an issue when running postman in Wayland mode inside a KDE Plasma 6.0 (Wayland) session

Postman info:
```
Version
11.1.13
UI version
11.1.13-ui-240520-0433

Desktop platform version
11.1.0

Architecture
x64

OS platform
linux 6.9.1-1-default
```

System info:
```
Operating System: openSUSE Tumbleweed 20240520
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.9.1-1-default (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 7840U w/ Radeon 780M Graphics
Memory: 30,7 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: Framework
Product Name: Laptop 13 (AMD Ryzen 7040Series)
System Version: A7
```

App installed via tar.gz.

.desktop file looks like this to run it as a Wayland app:

```
[Desktop Entry]
Encoding=UTF-8
Name=Postman RPM
Comment=Postman RPM
Exec=/home/andrea/bin/Postman/app/Postman --enable-features=UseOzonePlatform --ozone-platform=wayland %U
Icon=/home/andrea/bin/Postman/app/resources/app/assets/icon.png
Terminal=false
Type=Application
Categories=Development;
```

The problem consists in a coordinate offset between the pointer position and the location at which the effects of mouse actions (hovering, clicking) are produced.

As an example, here I was hovering over some request tabs and clicked on one. Instead of selecting/opening it, the URL bar for the current tab was focused/clicked instead, i.e. my mouse click produced its effects a bunch of pixels away from the pointer position. Notice also how the pointer turned into a caret:

![image](https://github.com/postmanlabs/postman-app-support/assets/801070/3fdab82b-079b-48d9-9693-ce678eb9e781)


I can reproduce this when only when my laptop is connected to an external monitor && the app is on the external monitor.
As soon as I move the postman window to the internal display, or disconnect the external monitor and operate the internal one only, the issue disappears.
Important: it seems that the issue does not happen on the first start of the app (even if it opens on the external monitor). In this case it's enough to move the app window to the internal display, and then back to the external one, and the coordinate offset will become apparent.

For information, my laptop display scaling is set to 120%, while the external one is unscaled (100%).

I will try to run the app under gnome

Thanks!

**Comment by andreaippo** [comment]
> Hello, I'd like to report an issue when running postman in Wayland mode inside a KDE Plasma 6.0 (Wayland) session
> 
> Postman info:
> 
> ```
> Version
> 11.1.13
> UI version
> 11.1.13-ui-240520-0433
> 
> Desktop platform version
> 11.1.0
> 
> Architecture
> x64
> 
> OS platform
> linux 6.9.1-1-default
> ```
> 
> System info:
> 
> ```
> Operating System: openSUSE Tumbleweed 20240520
> KDE Plasma Version: 6.0.4
> KDE Frameworks Version: 6.2.0
> Qt Version: 6.7.0
> Kernel Version: 6.9.1-1-default (64-bit)
> Graphics Platform: Wayland
> Processors: 16 × AMD Ryzen 7 7840U w/ Radeon 780M Graphics
> Memory: 30,7 GiB of RAM
> Graphics Processor: AMD Radeon Graphics
> Manufacturer: Framework
> Product Name: Laptop 13 (AMD Ryzen 7040Series)
> System Version: A7
> ```
> 
> App installed via tar.gz.
> 
> .desktop file looks like this to run it as a Wayland app:
> 
> ```
> [Desktop Entry]
> Encoding=UTF-8
> Name=Postman RPM
> Comment=Postman RPM
> Exec=/home/andrea/bin/Postman/app/Postman --enable-features=UseOzonePlatform --ozone-platform=wayland %U
> Icon=/home/andrea/bin/Postman/app/resources/app/assets/icon.png
> Terminal=false
> Type=Application
> Categories=Development;
> ```
> 
> The problem consists in a coordinate offset between the pointer position and the location at which the effects of mouse actions (hovering, clicking) are produced.
> 
> As an example, here I was hovering over some request tabs and clicked on one. Instead of selecting/opening it, the URL bar for the current tab was focused/clicked instead, i.e. my mouse click produced its effects a bunch of pixels away from the pointer position. Notice also how the pointer turned into a caret:
> 
> ![image](https://private-user-images.githubusercontent.com/801070/332702676-3fdab82b-079b-48d9-9693-ce678eb9e781.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjM3ODQsIm5iZiI6MTcxNjM2MzQ4NCwicGF0aCI6Ii84MDEwNzAvMzMyNzAyNjc2LTNmZGFiODJiLTA3OWItNDhkOS05NjkzLWNlNjc4ZWI5ZTc4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwNzM4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDE0YjQ4NDIyZTAzNzU2YmFmZWY4NGIzYzcxZjVlMGNmZjY2MWU0NTNlMDcyZmZiMmRlNzIyNmRiOWE3YWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y5XQTSbyQoIAuCxxJLX8PyuR91KVbH3c8t8oPxk5eNo)
> 
> I can reproduce this when only when my laptop is connected to an external monitor && the app is on the external monitor. As soon as I move the postman window to the internal display, or disconnect the external monitor and operate the internal one only, the issue disappears.
> 
> For information, my laptop display scaling is set to 120%, while the external one is unscaled (100%).
> 
> I will try to run the app under gnome
> 
> Thanks!

Note to self:

flatpak app is also affected. To run it as a Wayland app:

Configure it as follows via flatseal:
![image](https://github.com/postmanlabs/postman-app-support/assets/801070/08a41f86-b585-47de-9d7d-f9bf867612e2)

Change the Exec directive inside the .desktop file to:

```
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=Postman --file-forwarding com.getpostman.Postman --enable-features=UseOzonePlatform --ozone-platform=wayland @@u %U @@
```

**Comment by andreaippo** [comment]
> I will try to run the app under gnome

Same result, tested with the fedora 40 live medium and the archive I downloaded from https://www.getpostman.com/

You really need to move the window to the internal display (scaled) and back to the external (unscaled) one, only then you will reproduce the issue.

**Comment by romanstingler** [comment]
yes absolutely true they f*** up something terrible, I tested like 8 electron apps with various Electron versions, all are at least usable. But here I can start it and as soon as you resize it, it just dies. And other stuff like, doesn't rescale when resized.
Element interactions are not recognized .....

**Comment by andreaippo** [comment]
@DannyDainton is this ticket being checked/considered by the Postman DEV team?
Is Wayland on your roadmap?

Thanks :)

**Comment by 4kz** [comment]
.

**Comment by andreaippo** [comment]
> Hello, I'd like to report an issue when running postman in Wayland mode inside a KDE Plasma 6.0 (Wayland) session
> 
> Postman info:
> 
> ```
> Version
> 11.1.13
> UI version
> 11.1.13-ui-240520-0433
> 
> Desktop platform version
> 11.1.0
> 
> Architecture
> x64
> 
> OS platform
> linux 6.9.1-1-default
> ```
> 
> System info:
> 
> ```
> Operating System: openSUSE Tumbleweed 20240520
> KDE Plasma Version: 6.0.4
> KDE Frameworks Version: 6.2.0
> Qt Version: 6.7.0
> Kernel Version: 6.9.1-1-default (64-bit)
> Graphics Platform: Wayland
> Processors: 16 × AMD Ryzen 7 7840U w/ Radeon 780M Graphics
> Memory: 30,7 GiB of RAM
> Graphics Processor: AMD Radeon Graphics
> Manufacturer: Framework
> Product Name: Laptop 13 (AMD Ryzen 7040Series)
> System Version: A7
> ```
> 
> App installed via tar.gz.
> 
> .desktop file looks like this to run it as a Wayland app:
> 
> ```
> [Desktop Entry]
> Encoding=UTF-8
> Name=Postman RPM
> Comment=Postman RPM
> Exec=/home/andrea/bin/Postman/app/Postman --enable-features=UseOzonePlatform --ozone-platform=wayland %U
> Icon=/home/andrea/bin/Postman/app/resources/app/assets/icon.png
> Terminal=false
> Type=Application
> Categories=Development;
> ```
> 
> The problem consists in a coordinate offset between the pointer position and the location at which the effects of mouse actions (hovering, clicking) are produced.
> 
> As an example, here I was hovering over some request tabs and clicked on one. Instead of selecting/opening it, the URL bar for the current tab was focused/clicked instead, i.e. my mouse click produced its effects a bunch of pixels away from the pointer position. Notice also how the pointer turned into a caret:
> 
> ![image](https://private-user-images.githubusercontent.com/801070/332702676-3fdab82b-079b-48d9-9693-ce678eb9e781.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTY3ODEsIm5iZiI6MTcyNTQ1NjQ4MSwicGF0aCI6Ii84MDEwNzAvMzMyNzAyNjc2LTNmZGFiODJiLTA3OWItNDhkOS05NjkzLWNlNjc4ZWI5ZTc4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMzI4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGZjZWRhNGJkNDg4ZDE1ZTNjMmM4MDYxYjcwZWQxYzdlMjIwNjBiMTUyZTY5ZmM4ZjY1MWI5ZjczZWMwZGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UZC3GvA4JtdMoVxi3cb5uCmIiDZzhMt5RGRDnVtcfyY)
> 
> I can reproduce this when only when my laptop is connected to an external monitor && the app is on the external monitor. As soon as I move the postman window to the internal display, or disconnect the external monitor and operate the internal one only, the issue disappears. Important: it seems that the issue does not happen on the first start of the app (even if it opens on the external monitor). In this case it's enough to move the app window to the internal display, and then back to the external one, and the coordinate offset will become apparent.
> 
> For information, my laptop display scaling is set to 120%, while the external one is unscaled (100%).
> 
> I will try to run the app under gnome
> 
> Thanks!

I can't reproduce this issue anymore (11.11.1)

Here are the contents of the `.desktop` file that launches Postman:

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Encoding=UTF-8
Name=Postman RPM
Comment=Postman RPM
# Causes offset coordinates issue
# Exec=/home/andrea/bin/Postman/app/Postman --enable-features=UseOzonePlatform --ozone-platform=wayland %U
Exec=/home/andrea/.local/bin/Postman/app/Postman %U
Icon=/home/andrea/.local/bin/Postman/app/resources/app/assets/icon.png
Terminal=false
Type=Application
Categories=Development;
```

I had commented the line with `--enable-features=UseOzonePlatform --ozone-platform=wayland` at the time of reporting this issue, because it was so annoying that I'd rather go back to X11 than keeping using Wayland with the unpredictable coordinate offset.

However I've noticed that for whatever reason, even with that line commented, my Postman is still running in Wayland mode now, AND the coordinate offset issue is gone. That's a double win in my book, not sure what caused it, though.

**Comment by hholst80** [comment]
I got working by just adding the switches described above.
Sure there are some warnings but nothing that seems to be critical to launching Postman.

There is issues with the Flatpak (that I am using) that it has disabled Wayland support, but that's the point here right- it does actually work, with these two switches.


```
root@xps ~# flatpak run com.getpostman.Postman --enable-features=UseOzonePlatform --ozone-platform=wayland
F: Can't find a11y bus: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.a11y.Bus received signal 5
[8:1022/215625.011608:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
The disableGPU setting is set to undefined
Not disabling GPU

(postman:8): Gdk-WARNING **: 21:56:25.331: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
[8:1022/215625.428291:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[8:1022/215625.428322:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Main: Starting cleanup of stale files
Main: Cleanup of stale files completed
ProtocolHandler~setDefaultProtocolClient: Command failed: xdg-mime default Postman.desktop x-scheme-handler/postman
/bin/sh: line 1: xdg-mime: command not found

LaunchProcess: failed to execvp:
xdg-settings
```

![image](https://github.com/user-attachments/assets/a866d947-e5fc-4936-8008-1b0655b7da85)

**Comment by MC-sanderv** [comment]
I’ve been running Postman testing on Ubuntu in a Wayland for a year npw and haven’t run into Wayland-specific problems. Native Wayland support appears to be working in current Postman/Electron versions.

Given that this is an older feature request and it seems effectively implemented now, I’m closing this.
If anyone still sees issues on a recent Postman version and a Wayland desktop, please re-open the  issue with new information
