### ISSUE TITLE
Mock servers feature of Postman not working

### ISSUE THREAD

**Issue by DevappaSrinivasanManoj** [a85/POSTMan-Chrome-Extension#9909]
**Describe the Issue**
Mock server returning the below error, in spite of example being added to it.

{
    "error": {
        "name": "mockRequestNotFoundError",
        "message": "To mock this request add an example response for the mock server to return.",
        "header": "You need an example"
    }
}
 

**Steps to Reproduce**

Create a new mock server in Postman version 8.3.1.
Select Create new collection option.
Give the request URL and response body.
Click on Next and give a name to the mock server and create it.
Now open the created collection and submit the request. You get the above error

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/80568617/117244022-ec9b8380-ae55-11eb-8e43-c2f3a439b5a4.png)
![image](https://user-images.githubusercontent.com/80568617/117244049-fa510900-ae55-11eb-9f44-a0329589f799.png)
![image](https://user-images.githubusercontent.com/80568617/117244074-050b9e00-ae56-11eb-955a-fe9a1647cdff.png)
![image](https://user-images.githubusercontent.com/80568617/117244092-105ec980-ae56-11eb-87f6-43f087fcb108.png)
![image](https://user-images.githubusercontent.com/80568617/117244111-16ed4100-ae56-11eb-8792-974513a5cd1a.png)

**Environment Information**

 - Platform Type: Sorry, not sure what this means.
 - Postman Version: 8.3.1
 - Operating System: Windows 10

**Additional Context**

**Comment by vvs11** [comment]
@DevappaSrinivasanManoj Thanks for reporting this. This is a bug in our system caused by recent changes. We are aware of it and are working towards resolving this. Will keep you posted on this thread

**Comment by WatanabeThiago** [comment]
up

**Comment by DevappaSrinivasanManoj** [comment]
@vvs11 Thanks for the acknowledgement.

**Comment by asheinz** [comment]
@vvs11 Thanks for acknowledging. ~Is the bug being tracked somewhere?~ EDIT: I just discovered the projects page and how to track the work. Thanks to you and your team for integrating with that!

**Comment by vvs11** [comment]
This is fixed in the latest release. Please upgrade and test it out. Also, please feel free to share your feedback about the product and mock servers. It really helps us build a quality product :)

**Comment by IriaMsTechy** [comment]
Sorry, I am still getting it and I just updated (not upgraded) postman
